mongodb/mongo-go-driver

.evergreen/config.yml, Makefile, README.md, docs/CONTRIBUTING.md, go.mod
GODRIVER-2174
Bumps the minimum Go version from 1.10 to 1.13. 
The followup ticket GODRIVER-2603 will refactor old code that was built before we had access to 1.13.
=> GODRIVER-2174 Bump minimum Go version to 1.13.

testdata/crud/unified/findOneAndUpdate-errorResponse.json, testdata/crud/unified/findOneAndUpdate-errorResponse.yml
GODRIVER-2487
Removes the `useMultipleMongoses: false` from the `findOneAndUpdate-errorResponse` test.
I mistakenly added the field in this [spec commit](https://github.com/mongodb/specifications/commit/9fec9df099d132df047650315411bc0a532f0cef). It's actually not needed as the test does not configure a failpoint
=> GODRIVER-2487 No useMultipleMongoses false in findOneAndUpdate errorResponse test.

x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/topology/topology.go
[GODRIVER-2620](https://jira.mongodb.org/browse/GODRIVER-2620)
Fix hostname parsing for SRV polling.
The original code parses the SRV hostname incorrectly for any URI with a username and password. This PR extracts the hostname from a URI using the `net/url` package instead of manual parsing and finishes all sanity checks before passing the hostname.
However, I couldn't find a decent way to pass the errors from inside the polling out.
=> GODRIVER-2620 Fix hostname parsing for SRV polling.

mongo/session.go, mongo/with_transactions_test.go
GODRIVER-2565
If the context has errored right before the `CommitLoop` in `WithTransaction`, run `AbortTransaction` and return the context error.
This behavior is not specified in the convenient transactions API, as it has to do with contexts (see [DRIVERS-2471](https://jira.mongodb.org/browse/DRIVERS-2471)). If the context has errored after the callback but before `CommitLoop`, there is no chance the transaction commit will succeed, and resources will be left open server-side. We should run `AbortTransaction` in this case as a best effort to clean up server-side.
=> GODRIVER-2565 Abort transaction before CommitLoop if context errored.

.evergreen/config.yml
GODRIVER-2621
Run the fuzz tests on PR CI at most once per 24 hours, instead of periodically.
Periodic Builds  for fuzzing feed into the waterfall every night, which can be noisy. This solution resolves that noise. The periodic build will be removed after this PR is merged.
=> GODRIVER-2621 use batchtime for fuzz tests

mongo/client.go, mongo/integration/client_side_encryption_prose_test.go, mongo/mongocryptd.go
GODRIVER-2559
- Do not connect to mongocryptd if shared library is loaded
- Add prose test from https://github.com/mongodb/specifications/commit/09f1d51d549c141c310055e6d6802bc9e297258d
mongocryptd and the [crypt shared library](https://www.mongodb.com/docs/manual/core/queryable-encryption/reference/shared-library/) share the same functionality. Creating a `mongo.Client` to mongocryptd is unnecessary if using the shared library. mongocryptd will not be used if the shared library is used.
=> GODRIVER-2559 Do not connect to mongocryptd if shared library is loaded

mongo/description/selector_test.go, mongo/description/server_selector.go
Optimize allocations in latency server selector.
Similar to #1107 i try to optimize allocations in latency server selector. Benchmark provided without changes:
```
BenchmarkLatencySelector
BenchmarkLatencySelector/AllFit
BenchmarkLatencySelector/AllFit-10         	   64196	     17866 ns/op	  111273 B/op	       9 allocs/op
BenchmarkLatencySelector/AllButOneFit
BenchmarkLatencySelector/AllButOneFit-10   	   71056	     17038 ns/op	  111273 B/op	       9 allocs/op
BenchmarkLatencySelector/HalfFit
BenchmarkLatencySelector/HalfFit-10        	  124551	      9748 ns/op	   53928 B/op	       8 allocs/op
BenchmarkLatencySelector/OneFit
BenchmarkLatencySelector/OneFit-10         	 1471053	       825.6 ns/op	    1320 B/op	       3 allocs/op
PASS
```
And with proposed optimization:
``` …
```
=> GODRIVER-2627 optimize latency selector

mongo/crud_examples_test.go, mongo/integration/load_balancer_prose_test.go, mongo/integration/sessions_test.go, mongo/integration/unified/session_operation_execution.go, mongo/session.go, mongo/with_transactions_test.go
[GODRIVER-2630](https://jira.mongodb.org/browse/GODRIVER-2630)
Rename all instances of `sessCtx mongo.SessionContext` to `ctx mongo.SessionContext`.
We currently document in the [Go Driver Code Example Reference](https://docs.google.com/document/d/1FtUKxOaEmdFf4d3HcXAVIGed2awuwIWdkWc0YQIwPvk/edit#) that examples should always use variable name `ctx` for the callback function signatures when using the `mongo.WithSession` and `Session.WithTransaction` functions.
The reason for that guideline is that it helps prevent a common error of using the outer context (i.e. the one from outside the callback func that doesn't contain the session/transaction information) instead of the inner context from the callback func. Naming the variable `ctx` shadows the context from outside the callback func, …
=> GODRIVER-2630 Rename all instances of sessCtx to ctx and reformat Session documentation.

docs/common-issues.md
A common issue that Go Driver users encounter is an "Authentication Failed" message. Add a section to the common issues doc for troubleshooting "Authentication Failed" errors.
Also add an overview paragraph at the beginning with a description of what's in the common issues doc and a link to create a GODRIVER Jira ticket in case users still need more help.
The error message returned by an authentication failure intentionally omits the exact authentication failure reason (see the [OWASP Authentication and Error Messages guidelines](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-and-error-messages) for an explanation). Because of that, authentication failures can be non-intuitive to troubleshoot. Add a section to the common issues doc to help …
=> Add a common issues section for 'authentication failed' errors.

x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
GODRIVER-2628 
Optimize allocations in selectServerFromDescription
Same way as in #1108 and #1107 I want to reduce allocations in selectServerFromDescription func which flat allocations in my case are > 100GB and which possess the very first place by flat allocations in my long running job.
Benchmark attached without changes to the code:
```
BenchmarkSelectServerFromDescription
BenchmarkSelectServerFromDescription/AllFit
BenchmarkSelectServerFromDescription/AllFit-10         	   63248	     17195 ns/op	  111265 B/op	       8 allocs/op
BenchmarkSelectServerFromDescription/AllButOneFit
BenchmarkSelectServerFromDescription/AllButOneFit-10   	   65990	     18173 ns/op	  111265 B/op	       8 allocs/op
BenchmarkSelectServerFromDescription/HalfFit
BenchmarkSelectServerFromDescription/HalfFit-10 …
```
=> GODRIVER-2628 optimize allocations in selectServerFromDescription

mongo/database.go, x/mongo/driver/operation/command.go
GODRIVER-2649
Adds a TODO to reference backward-breaking change GODRIVER-2649.
`readConcern` is not being passed from `command.go` down to the underlying `driver.Operation`. This means calling `ReadConcern` on a `Command` as we do in `database.go` [here](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/database.go#L178) is a noop.
=> GODRIVER-2649 Add TODOs for passing readConcern correctly for RunCommand.

mongo/integration/csot_prose_test.go
[GODRIVER-2653](https://jira.mongodb.org/browse/GODRIVER-2653)
Increase the timeouts and expected operation durations used in the CSOT server selection prose tests by 10x.
The [CSOT server selection prose tests](https://github.com/mongodb/specifications/blob/02c6e3fa7dbc3a64e5312ef820e0f1779069cadb/source/client-side-operations-timeout/tests/README.rst#server-selection) implemented in the Go Driver frequently fail on macOS due to too strict timing requirements. Increase the timeouts to increase the reliability of the tests.
=> GODRIVER-2653 Improve reliability of the CSOT server selection prose tests by increasing timeouts.

bson/primitive/objectid.go, bson/primitive/objectid_test.go
Similar to #1062 use Decode instead of DecodeString to reduce work done just a bit.
Benchmark attached for current and new implementations gives the following results on my machine
```
BenchmarkObjectIDFromHex
BenchmarkObjectIDFromHex-10       	61378326	        19.35 ns/op
BenchmarkObjectIDFromHexNew
BenchmarkObjectIDFromHexNew-10    	66876584	        17.97 ns/op
```
It seems that string allocation is not happening in the current implementation as well, but there is a small improvement (not sure wether worth it to bother with the change at all)
=> GODRIVER-2655 optimize ObjectIDFromHex a bit

.golangci.yml
GODRIVER-2642
Enables the `exportloopref` linter in `.golangci.yml`
Go has an ["issue"](https://github.com/golang/go/discussions/56010) with for loop variable semantics that allows easy, accidental errors when dereferencing or passing around values. This linter combined with the `paralleltest` should help catch more (not all) of these types of errors.
=> GODRIVER-2642 Enable the exportloopref linter.

.evergreen/config.yml, Makefile, etc/check_fmt.sh, mongo/crud_examples_test.go
GODRIVER-2661
Changes the `fmt` and `check-fmt` make targets to use `go fmt` instead of `gofmt` and avoid usage of the now non-existent `PKGS` variable (removed in GODRIVER-2093). Installs linters for `sa-fmt` task that was [not actually running](https://evergreen.mongodb.com/lobster/evergreen/task/mongo_go_driver_static_analysis_sa_fmt_eff5307d71ecbc763735076f3e2f63b5d77ead2a_22_11_28_17_04_17/0/task#bookmarks=0%2C1987&l=1&shareLine=1955) the `lll` linter. Fixes an unwrapped comment in `crud_examples_test.go`.
`make fmt` and `make check-fmt` will currently fail and hang indefinitely, respectively. Since we encourage users to run `make fmt` for contributions and run `check-fmt` ourselves in the `sa-fmt` task, we should fix these targets.
=> GODRIVER-2661 Fix make targets that still refer to PKGS.

x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
GODRIVER-2577
This fix retries heartbeat on timeout errors to delay pool cleanup by one event loop.
Pausing behavior in FAAS environment, e.g. AWS Lambda, causes connection timeout in heartbeat, which then clears the pool.
This fix retries heartbeats on timeout so only two continuous timeout errors will trigger a pool cleanup.
Its test case uses a proxy `net.Conn` to mimic timeout errors.
=> GODRIVER-2577 Retry heartbeat on timeout to prevent pool cleanup in FAAS pause.

.evergreen/config.yml, .evergreen/run-tests.sh
GODRIVER-2643
replace use of [activate_venv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/e276a93e6477149362ca85881006a1fae99a9095/.evergreen/csfle/activate_venv.sh) with [activate-kmstlsvenv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/e276a93e6477149362ca85881006a1fae99a9095/.evergreen/csfle/activate-kmstlsvenv.sh).
The activate-kmstlsvenv.sh is a hygienic alternatives to activate_venv.sh that does not leak variables into the environment and does not depend on environment variables for its behavior.
=> GODRIVER-2643 update virtual environment source

bson/bsoncodec/string_codec.go
This PR seeks to fix a typo in `bsoncodec.StringCodec` comment.
=> Fix typo in `bsoncodec.StringCodec` comment

testdata/command-monitoring/redacted-commands.json, testdata/command-monitoring/redacted-commands.yml, testdata/unified-test-format/valid-pass/observeSensitiveCommands.json, testdata/unified-test-format/valid-pass/observeSensitiveCommands.yml
GODRIVER-2657
Syncs spec tests with [this commit](https://github.com/mongodb/specifications/commit/735a667672c758617821e3c5dda99c551e007375). 
Support for the `getNonce` command will be removed in server version 6.2. This updates spec tests that send `getNonce` to the server to only run on 6.1.99 and below. The only usage of `getNonce` we have otherwise is in the MongoDBCR authentication system, which we've ["deprecated"](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/auth/mongodbcr.go#L41-L42). The [mongdbcr_test.go](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/auth/mongodbcr_test.go) mocks connections for writing and reading messages, so `getNonce` is never actually sent to a server.
=> GODRIVER-2657 Restrict getNonce spec tests to < 6.2.

mongo/options/clientoptions.go, mongo/options/clientoptions_test.go
GODRIVER-2650
Extract the subject from the first certificate instead of the last.
The Subject of the last certificate was returned as the username for X509 auth after [GODRIVER-2263](https://jira.mongodb.org/browse/GODRIVER-2263), which did not match the order of loading a PEM file with multiple certs.
As the ticket suggests, this change updates the certificate subject string if the `certDecodeBlock` is never set.
=> GODRIVER-2650 Fix incorrect X509 certificate being used as username for authentication.

x/bsonx/bsoncore/value.go, x/bsonx/bsoncore/value_test.go
GODRIVER-2702
Update the "bsoncore.Value#String" method to preserve timestamp int/uint type during string conversion. This method is intended to express BSON as extended JSON and converting the timestamp (I,U) values is in antithesis to [specifications](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#conversion-table).
The "CommandStartedMessage" for command logging and monitoring has a field called "command" which is the "relaxed extJSON representation of the command." To accomplish this in the Go Driver, we use the "[bsoncore.Value#String](https://github.com/mongodb/mongo-go-driver/blob/master/x/bsonx/bsoncore/value.go#L228)" method to convert `cmdCopy` in the operation executor to a string before logging. However, "bsoncore.Value#String" does not preserve …
=> GODRIVER-2702 update bsoncore value string to preserve timestamp type

.evergreen/config.yml, mongo/client_encryption.go, mongo/doc.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/client_side_encryption_test.go, mongo/options/encryptoptions.go, testdata/client-side-encryption-prose/range-encryptedFields-Date.json, testdata/client-side-encryption-prose/range-encryptedFields-DoubleNoPrecision.json, testdata/client-side-encryption-prose/range-encryptedFields-DoublePrecision.json, testdata/client-side-encryption-prose/range-encryptedFields-Int.json, testdata/client-side-encryption-prose/range-encryptedFields-Long.json, x/mongo/driver/crypt.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/mongocrypt_not_enabled.go, x/mongo/driver/mongocrypt/options/mongocrypt_context_options.go
GODRIVER-2433
- Add `RangeOptions`.
- Add `ClientEncryption.EncryptExpression()`.
- Add prose test for explicit encryption with range.
- Document requirement of libmongocrypt 1.7.0.
See https://github.com/mongodb/specifications/pull/1355.
The API is marked experimental due to [this comment](https://jira.mongodb.org/browse/DRIVERS-2286?focusedCommentId=4975162&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4975162).
The libmongocrypt API is also described in [mongocrypt.h](https://github.com/mongodb/libmongocrypt/blob/master/src/mongocrypt.h#L949)
=> GODRIVER-2433 Support explicit encryption for Range Index

mongo/client_encryption.go, mongo/integration/client_side_encryption_prose_test.go
GODRIVER-2493
- Add a new `CreateEncryptedCollection` method which automatically generates new encryption data keys for nil `keyIds`;
- Add test cases.
https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/client-side-encryption.rst#create-encrypted-collection-helper
https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/tests/README.rst#automatic-data-encryption-keys
=> GODRIVER-2493 Automatically create Queryable Encryption keys.

mongo/doc.go, x/mongo/driver/dns/dns.go
GODRIVER-2679
Elaborates on the ["Potential DNS Issues"](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#hdr-Potential_DNS_Issues) section of our documentation with more explicit workarounds. Wraps the ambiguous `cannot unmarshal DNS message` error from `LookupSRV` with a link to that documentation.
Go driver users connecting to their clusters with SRV-schemed connection strings are still running into the infamous `cannot unmarshal DNS message` error due to non-compliant SRV servers and resolvers in the wild (i.e. Ubuntu 18.04's native DNS resolver `systemd`). This is not an issue we can fix in the Go driver, but we should elaborate on our documentation internally and wrap the error to point to our documentation.
=> GODRIVER-2679 Elaborate on DNS issues docs and confusing DNS error.

bson/raw_test.go, x/bsonx/bsoncore/array.go, x/bsonx/bsoncore/document.go, x/bsonx/bsoncore/element.go
[GODRIVER-2734](https://jira.mongodb.org/browse/GODRIVER-2734)
* Replace all uses of `bytes.Buffer` with `strings.Builder` in `bsoncore` where the function output is a string.
* Remove all uses of `fmt.Fprintf` and `fmt.Sprintf` where there is little or no string formatting added.
* Add a benchmark that exercises `bson.Raw.String` for various inputs.
There are a number of simple optimizations we can make to [bsoncore.Document.String](https://github.com/mongodb/mongo-go-driver/blob/60cfd91eb66c2646de5034327c50208d13c05db3/x/bsonx/bsoncore/document.go#L265), [bsoncore.Array.String](https://github.com/mongodb/mongo-go-driver/blob/60cfd91eb66c2646de5034327c50208d13c05db3/x/bsonx/bsoncore/array.go#L84), and [bsoncore.Element.String](https://github.com/mongodb/mongo-go-driver/blob/60cfd91eb66c26 …
=> GODRIVER-2734 Benchmark and reduce allocations in bson.Raw.String

testdata/client-side-encryption/unified/rewrapManyDataKey.json, testdata/client-side-encryption/unified/rewrapManyDataKey.yml
GODRIVER-2739
Add "insertedIds" matching for bulk write response "insertedIds". The Go Driver does not implement this optional feature, so this PR is just to keep the specs up-to-date.
The rewrap many data key CSFLE unified spec tests omit the optional insertIds property on the BulkWriteResult. This causes failures for drivers that have the optional field and assert exact equality of the result object in the unified tests.
=> GODRIVER-2739 Support Optional Inserted Ids in CSFLE Unified Tests

mongo/integration/client_side_encryption_spec_test.go
GODRIVER-2433
- skip `fle2-Range-*-Correctness` tests on macOS
See https://github.com/mongodb/specifications/pull/1371
=> GODRIVER-2433 skip `fle2-Range-*-Correctness` tests on macOS

mongo/client_encryption.go
GODRIVER-2493
- do not check encryptedFieldsMap in CreateEncryptedCollection
Implements https://github.com/mongodb/specifications/pull/1376
=> GODRIVER-2493 do not check encryptedFieldsMap in CreateEncryptedCollection

mongo/client_encryption.go, mongo/integration/client_side_encryption_prose_test.go
GODRIVER-2746
- replace CreateEncryptedCollection DataKeyOpts with masterKey
Implements change proposed in https://github.com/mongodb/specifications/pull/1377
=> GODRIVER-2746 replace CreateEncryptedCollection DataKeyOpts with masterKey

testdata/command-monitoring/logging/unacknowledged-write.json, testdata/command-monitoring/logging/unacknowledged-write.yml
GODRIVER-2732
Sync the unified spec tests for logging unacknowledged write behavior.
Add a test case ensuring drivers follow the spec-defined behavior for command logging and unacknowledged writes, which is to emit a "command succeeded" log message with a reply of ok: 1.
=> GODRIVER-2732 CLAM Unacknowledged Write Behavior

mongo/client_encryption.go, mongo/options/autoencryptionoptions.go, mongo/options/encryptoptions.go
GODRIVER-2748
- Add "Public Technical Preview" note to CreateEncryptedCollection
- Note that CreateEncryptedCollection is specific to Queryable Encryption
The API for ClientEncryption.CreateEncryptedCollection is specific to Queryable Encryption. Queryable Encryption API was determined to be marked as "Public Technical Preview" in DRIVERS-2349.
The "Public Technical Preview" note is copied from [encryptoptions.go](https://github.com/mongodb/mongo-go-driver/blob/c5146995ca4dcf539ac0d687c5f2d313b2b84f9b/mongo/options/encryptoptions.go#L16) for consistency.
=> GODRIVER-2748 Add "Public Technical Preview" note to CreateEncryptedCollection

mongo/change_stream.go, mongo/client.go, mongo/collection.go, mongo/cursor.go, mongo/database.go, mongo/index_view.go, testdata/sessions/README.rst, testdata/sessions/implicit-sessions-default-causal-consistency.json, testdata/sessions/implicit-sessions-default-causal-consistency.yml, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/session/client_session.go, x/mongo/driver/session/client_session_test.go
[GODRIVER-2497](https://jira.mongodb.org/browse/GODRIVER-2497)
Create a new function `session.NewImplicitClientSession` for creating implicit client-side sessions that always sets `causalConsistency=false`. Simplify the existing `session.NewClientSession` function to always create explicit client-side sessions.
The goal of [GODRIVER-2497](https://jira.mongodb.org/browse/GODRIVER-2497) is to always create implicit sessions with causal consistency disabled to fix a bug that can cause errors when operations are retried. Instead of adding additional conditional logic to the existing `session.NewClientSession` function, a safer and significantly simpler approach is to completely separate the logic for creating implicit and explicit client-side sessions.
Changes:
* Add a new …
=> GODRIVER-2497 Always set causalConsistency=false for implicit sessions.

bson/example_test.go, bson/marshal.go, bson/raw.go, bson/raw_element.go, bson/raw_value.go, bson/unmarshal.go, mongo/single_result.go
* Improve documentation on `SingleResult.Err`.
* Clarify difference between `bson.Marshaler`/`bson.Unmarshaler and `bson.ValueMarshaler`/`bson.ValueUnmarshaler`
* Improve documentation of the functionality of `bson.Raw` and `bson.RawValue` types.
* Add examples for using `bson.Raw` and `bson.RawValue` to delay decoding using `bson.Unmarshal` or precompute BSON values using `bson.Marshal`.
Documentation improvements are inspired by providing feedback on best practices when using the `SingleResult` API and when defining custom BSON marshal/unmarshal behavior.
Also, while investigating feature parity between the `bson.Raw`/`bson.RawValue` types and the Go `json.RawMessage` type, I realized that the BSON types can be used for basically identical purposes. However, none of that functionality …
=> Improve various documentation, add examples for using `bson.Raw` and `bson.RawValue` when encoding/decoding BSON.

bson/primitive/primitive.go, bson/primitive/primitive_test.go
[GODRIVER-2681](https://jira.mongodb.org/browse/GODRIVER-2681)
* Add `primitive.Timestamp` methods `Before`, `After`, and `Compare`.
* Deprecate the `primitive.CompareTimestamp` function.
The [primitive.CompareTimestamp](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.10.3/bson/primitive#CompareTimestamp) function is not a Go idiomatic API. Replace it with `primitive.Timestamp` methods `Before`, `After`, and `Compare` (inspired by Go's [time.Time](https://pkg.go.dev/time#Time) API). Deprecate `primitive.CompareTimestamp` and suggest using the new methods.
=> GODRIVER-2681 Replace CompareTimestamp with Before, After and Compare methods.

event/examples_test.go
I use the CommandMonitor feature in my project and refer to the ExampleCommandMonitor example. However, there was a memory surge during the long run, and the problem was checked for a while because the closure did not clear the element in time, resulting in a memory surge leak. Specifically to complete an example, remind the user to clear in time.
=> fix: fixed a memory leak caused by the commandMonitor example closure.

cmd/build-oss-fuzz-corpus/main.go
Use `"crypto/sha256"` instead of `"crypto/sha1"` to generate filenames for the oss-fuzz integration.
The gosec linter currently warns about using the `"crypto/sha1"` package:
> G505: Blocklisted import crypto/sha1: weak cryptographic primitive
The oss-fuzz integration doesn't rely on the filenames being SHA1 hashes, so use SHA256 instead to resolve the gosec linter warnings. Updates the integration added in https://github.com/mongodb/mongo-go-driver/pull/1170.
=> Use SHA256 instead of SHA1 in oss-fuzz to resolve gosec warning.

event/monitoring.go, mongo/integration/unified/client_entity.go, x/mongo/driver/operation.go, x/mongo/driver/topology/server.go
[GODRIVER-2674](https://jira.mongodb.org/browse/GODRIVER-2674)
* Deprecate field `event.CommandFinishedEvent.DurationNanos`. Suggest using `time.Duration` field `Duration` instead.
* Deprecate field `event.ServerHeartbeatFailedEvent.DurationNanos`. Suggest using `time.Duration` field `Duration` instead.
* Deprecate field `event.ServerHeartbeatSucceededEvent.DurationNanos`. Suggest using `time.Duration` field `Duration` instead.
A Go `time.Duration` is much easier to work with than an `int64` that represents a duration in nanoseconds because `time.Duration` units are implicit and the Go `time` package provides lots of functions for inspecting and manipulating the duration values. In Go Driver 2.0, we plan to replace the `DurationNanos int64` fields with `Duration time.Duration` fields. …
=> GODRIVER-2674 Add Duration and deprecate DurationNanos

mongo/integration/client_side_encryption_test.go, testdata/client-side-encryption/legacy/fle2-CreateCollection.json, testdata/client-side-encryption/legacy/fle2-CreateCollection.yml, testdata/client-side-encryption/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json, testdata/client-side-encryption/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
GODRIVER-2764
- Update fle2-CreateCollection and fle2-EncryptedFields-vs-EncryptedFieldsMap with state collection names meeting requirements of SERVER-74069
- Update `TestFLE2CreateCollection` with state collection names meeting requirements of SERVER-74069
See https://github.com/mongodb/specifications/pull/1382. These tests are expected to fail against latest server builds until this update is applied.
=> GODRIVER-2764 update fle2 tests

etc/add_license.sh
Ignore third-party files when adding licenses to files in the Go Driver.
The etc/add-license.sh script will try to add the copyright notice to third-party imports, which is not necessary.
=> Ignore third-party files on adding licenses

x/mongo/driver/topology/server.go
GODRIVER-2730
Remove the channel reading in the `recover` block of the `Server.update()`.
The channel reading exists from commit [94ae2dc](https://github.com/mongodb/mongo-go-driver/commit/94ae2dc59114fbf6dd39707929068adfa20a92e8#diff-f1adee6cee5a6c64fac82d534ca26f6565e80fb5c288ba7768bfb29463fd6c77R251-R254). The shortcut if-condition was added shortly after the initial commit to fix a deadlock in [550660b](https://github.com/mongodb/mongo-go-driver/commit/550660bb2a7f750c43524c0d2b9816b2e863bddd).
I can neither practically reproduce a deadlock by a panic as the ticket implies nor logically figure out any reason that may cause a deadlock if the `Server.Disconnect()`, where the `done` channel [is closed](https://github.com/mongodb/mongo-go-driver/blame/master/x/mongo/driver/topology/server. …
=> GODRIVER-2730 Remove blocking channel in update recovering.

go.mod
[GODRIVER-2773](https://jira.mongodb.org/browse/GODRIVER-2773)
Retracts Go driver v1.11.0 through v1.11.2 releases due to a data race bug described in [GODRIVER-2768](https://jira.mongodb.org/browse/GODRIVER-2768).
There is a data race bug in all current Go driver v1.11.x releases that that may cause undefined behavior when reading raw BSON responses from error documents (e.g. `CommandError.Raw`). The issue is resolved by [GODRIVER-2677](https://jira.mongodb.org/browse/GODRIVER-2677), which will be released in GO driver v1.11.3.
=> GODRIVER-2773 Retract v1.11.0 through v1.11.2.

mongo/collection.go, mongo/database.go, mongo/single_result.go
GODRIVER-2769
This PR adds a context.Context field to mongo.SingleResult to safeguard user expectations when setting timeout logic on contexts passed to operations that return a single result.
The motivation for this proposal is to avoid indefinitely blocking the mongo.SingleResult cursor on operations that set timeout logic.
=> GODRIVER-2769 add context to SingleResult

bson/bsoncodec/struct_codec.go, bson/decoder_test.go
GODRIVER-2766
The DecodeValue method in the struct codec creates its own DecodeContext to decode the underlying value. This approach can cause issues with ancestor selection, as the defaultDocumentType constraints on empty interfaces are not enforced.
In addition to updating the struct.DecodeValue's DecodeContext, this PR parallelized a subset of the decoder tests.
GODRIVER-2407 defined a bug wherein the empty interface codec (EIC) will interpret embedded data to be the same type as the parent (or "ancestor") data. In the case of 2766:
```go
item := &struct {
A map[primitive.ObjectID]interface{} `json:"foo" bson:"foo"`
}{}
 
jsonData := "{ \"foo\" : {\"63ea2082b1ce23422a8bf9ca\" : { \"bar\" : \"\" } } }"
 
err = json.Unmarshal([]byte(jsonData), item)
fmt.Println("json …
```
=> GODRIVER-2766 Support inherited defaultDocumentType

mongo/cursor.go
=> Fixed comment of Cursor.Next() and Cursor.TryNext() functions.

mongo/integration/mtest/opmsg_deployment.go, mongo/integration/mtest/wiremessage_helpers.go, x/mongo/driver/compression.go, x/mongo/driver/driver.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
GODRIVER-2778
1. Modified around `Operation.decompressWireMessage` to eliminate duplicate memory allocation;
2. Reused `zlib.Writer`;
3. Removed unused parameter of `ReadWireMessage` in the interface of `driver.Connection`.
```
name                          old time/op    new time/op    delta
ClientRead/not_compressed-10    33.5µs ±17%    29.6µs ± 7%  -11.61%  (p=0.000 n=10+10)
ClientRead/snappy-10            37.2µs ±12%    34.9µs ± 8%     ~     (p=0.095 n=10+9)
ClientRead/zlib-10               130µs ± 1%      57µs ± 6%  -55.78%  (p=0.000 n=9+9)
ClientRead/zstd-10              46.3µs ±16%    48.5µs ±22%     ~     (p=0.436 n=10+10)
name                          old alloc/op   new alloc/op   delta
ClientRead/not_compressed-10    17.4kB ± 0%    17.4kB ± 0%     ~     (p=0.900 n=10+10) …
```
=> GODRIVER-2778 Reduce memory usage on compressed loads.

mongo/batch_cursor.go, mongo/cursor.go, mongo/cursor_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/batch_cursor_test.go, x/mongo/driver/list_collections_batch_cursor.go
GODRIVER-1605
The "SetBatchSize" method can be used to override the batch size of a mongo.Cursor instance. This allows users to customize the batch size according to their needs.
The cursor's "Next" method executes a [getMore](https://www.mongodb.com/docs/v6.0/reference/command/getMore/) operation with a specific batch size. However, there may be cases where it is necessary to override the default batch size in order to prevent cursor operations from timing out. The Go Driver supports this use case by allowing the batch size to be overridden.
=> GODRIVER-1605 Add SetBatchSize to mongo.Cursor

.evergreen/config.yml
Update the evergreen config file to pin golangci-lint v1.51.2 to avoid the static analysis lint failures that were introduced in the latest version.
=> pin golangci-lint v1.51.2

mongo/database_test.go, mongo/errors.go, x/mongo/driver/operation.go, x/mongo/driver/topology/errors.go
GODRIVER-2672
Return `mongo.ServerError` with the "TransientTransactionError" label for server selection timeouts.
As per the request of a "TransientTransactionError" label described in [the spec](https://github.com/mongodb/specifications/blob/master/source/transactions/transactions.rst#transienttransactionerror), add a `mongo.ServerSelectionError` type, which wraps `topology.ServerSelectionError`, to implement the `mongo.ServerError` interface.
I don't think this is a breaking change because, originally, we return a `topology.ServerSelectionError`, a type under the "x" API, which is not encouraged to be used by driver users.
=> GODRIVER-2672 Return ServerError with "TransientTransactionError" label for server selection timeouts.

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_encoders.go, bson/primitive_codecs.go
[GODRIVER-2709](https://jira.mongodb.org/browse/GODRIVER-2709)
Deprecate `DefaultValueEncoders`, `DefaultValueDecoders`, and `PrimitiveCodecs` and all exported methods of those types. Recommend that users call `bson.NewRegistry` to get a default registry instead.
The only known use cases for using of the `DefaultValueEncoders`, `DefaultValueDecoders`, and `PrimitiveCodecs` types and methods is to create a default `Registry` of value encoders/decoders. That can already be accomplished by calling `bson.NewRegistry`, so the `DefaultValueEncoders`, `DefaultValueDecoders`, and `PrimitiveCodecs` types and methods are redundant and create confusion with users.
=> GODRIVER-2709 Deprecate DefaultValueEncoders, DefaultValueDecoders, and PrimitiveCodecs.

bson/primitive/primitive.go
[GODRIVER-2684](https://jira.mongodb.org/browse/GODRIVER-2684)
Deprecate `bson.D.Map`. Recommend that users marshal a `bson.D` as BSON and unmarshal it as a `bson.M` to achieve the same `D`-to-`M` conversion.
Using the `bson.D.Map` method often results in unexpected output because the method only shallow-converts the `D` to an `M`. Updating the method to recursively convert a `D` to an `M` requires a lot of reflection logic and would be a backward-breaking change in Go Driver 1.x. The only use case for converting a `D` to an `M` that we have observed is to marshal the D to an intuitive JSON representation (i.e. key-value instead of an array of tuples). In Go Driver 2.0, encoding to the intuitive JSON representation will be supported natively (see …
=> GODRIVER-2684 Deprecate D.Map.

bson/raw_value.go
[GODRIVER-2167](https://jira.mongodb.org/browse/GODRIVER-2167)
Deprecate frequently lossy `AsInt32` and `AsInt32OK` functions.
The BSON library currently includes 4 BSON-to-Go numeric value conversion functions that can cause silent data loss:
* `AsInt32`, `AsInt32OK`
* `AsInt64`, `AsInt64OK`
While converting BSON numeric types to a Go `int64` can cause data loss in some cases, it's generally only a problem for extremely large or extremely small values that most users never encounter (values >`9.2e+18` or <`-9.2e+18`). However, converting BSON numeric types to a Go `int32` can cause data loss for values that users may commonly encounter (values >`2,147,483,647` or <`-2,147,483,648`). As a result, using `AsInt32` or `AsInt32OK` is practically much less safe than `AsInt64` or `AsInt64OK`. …
=> GODRIVER-2167 Deprecate frequently lossy AsInt32 and AsInt32OK functions

bson/raw.go, bson/raw_test.go
[GODRIVER-2682](https://jira.mongodb.org/browse/GODRIVER-2682)
Add a new function `bson.ReadDocument` that does exactly the same thing as `bson.NewFromIOReader`. Deprecate `bson.NewFromIOReader` in preparation to remove it in Go Driver 2.0.
The function `bson.NewFromIOReader` is not intuitively named. Replace it with a new, more intuitive function `bson.ReadDocument` that behaves exactly the same and deprecate `bson.NewFromIOReader`.
=> GODRIVER-2682 Prepare to rename bson.NewFromIOReader to bson.ReadDocument.

etc/check_fmt.sh
Ignore testable example `// Output: ` comments in line-length linter.
Go [testable examples](https://go.dev/blog/examples) use a comment that starts with `// Output: ` to indicate the expected example output. Those lines are required to match the expected output exactly and are not included in the example code rendered on the pkg.go.dev docs site, so they should be ignored by the `lll` line-length linter.
=> Ignore testable example 'Output' comments in line-length linter.

bson/bsoncodec/bsoncodec.go, bson/bsonrw/extjson_reader.go, bson/bsonrw/extjson_writer.go, bson/bsonrw/value_reader.go, bson/bsonrw/value_writer.go, bson/bsonrw/writer.go, bson/bsontype/bsontype.go, bson/primitive/objectid.go, bson/types.go, mongo/gridfs/download_stream.go, mongo/mongo.go, mongo/options/mongooptions.go, mongo/results.go, mongo/writeconcern/writeconcern.go
[GODRIVER-2606](https://jira.mongodb.org/browse/GODRIVER-2606)
Deprecate unused code in preparation to remove it in Go Driver 2.0. Suggest replacements if there is one.
There is a lot of functionality that appears totally unused in the Go Driver API. We've kept it around to maintain backward compatibility. Mark all of the seemingly unused types and functions as deprecated so we can reduce the negative impact of removing them in Go Driver 2.0.
Totally unused:
* `mongo.BSONAppender`
* `mongo.BSONAppenderFunc`
* `options.MarshalError`
No known use case:
* `options.Collation.ToDocument`
* `options.ArrayFilters.ToArray`
* `options.ArrayFilters.ToArrayDocument`
* `options.ArrayFilters.Registry`
* `bsonrw.SliceWriter`
* `writeconcern.AcknowledgedValue`
Used internally but no known use case …
=> GODRIVER-2606 Deprecate unused code in preparation to remove it in Go Driver 2.0

.evergreen/config.yml
GODRIVER-2802
- Remove the no longer used `ENABLE_featureFlagFLE2ProtocolVersion2=ON`
The `ENABLE_featureFlagFLE2ProtocolVersion2=ON` was part of a temporary workaround to opt in to enabling the feature flag `featureFlagFLE2ProtocolVersion2` on the server. The workaround was removed in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/289. Setting `ENABLE_featureFlagFLE2ProtocolVersion2=ON` no longer has any effect.
=> GODRIVER-2802 remove ENABLE_featureFlagFLE2ProtocolVersion2=ON

bson/decoder.go, bson/encoder.go
[GODRIVER-2712](https://jira.mongodb.org/browse/GODRIVER-2712)
* Deprecate the bson.NewEncoderWithContext and Encoder.SetContext functions. Recommend using the Encoder configuration methods set the desired behavior of the encoder instead.
* Deprecate the bson.NewDecoderWithContext and Decoder.SetContext functions. Recommend using the Decoder configuration methods set the desired behavior of the decoder instead.
There are too many ways to configure a `bson.Encoder` and `bson.Decoder` to get the exact same behavior. We're planning to remove all usages of the `EncodeContext` and `DecodeContext` from the standard user configuration of the `bson.Encoder` and `bson.Decoder` types. All configuration will be done via the configuration methods on the `bson.Encoder` and `bson.Decoder` types.
=> GODRIVER-2712 Deprecate BSON Encoder and Decoder 'Context' methods.

mongo/change_stream.go, mongo/options/changestreamoptions.go, mongo/options/changestreamoptions_test.go
[GODRIVER-2804](https://jira.mongodb.org/browse/GODRIVER-2804)
Fix bug that can squash the `FullDocument` configuration value when merging multiple `ChangeStreamOptions` structs.
The `options.ChangeStream` options constructor currently sets a default `FullDocument` configuration of `Default`. That can lead to the `FullDocument` configuration value in some `ChangeStreamOptions` structs being squashed because `Default` appears to be a user-configured option in the default struct constructed via `options.ChangeStream`.
=> GODRIVER-2804 Fix bug that can squash FullDocument when merging ChangeStreamOptions.

mongo/readconcern/readconcern.go
[GODRIVER-2686](https://jira.mongodb.org/browse/GODRIVER-2686)
Simplify the `readconcern` package API by deprecating the "functional options" setters and exporting all fields in a `ReadConcern`. Also improve the documentation and add links to the corresponding MongoDB manual pages.
The `readconcern` package unnecessarily uses the "functional options" pattern which is not used on any other public API. Remove the functional options pattern and just export all fields in the `ReadConcern` struct so users can set them directly.
Also, some exported values or functions do not need to be exported:
* `ReadConcern.MarshalBSONValue` - There is no known use case for this outside of the Go driver.
=> GODRIVER-2686 Simplify the readconcern API.

bson/primitive/primitive.go, bson/primitive/primitive_test.go
[GODRIVER-2811](https://jira.mongodb.org/browse/GODRIVER-2811)
Make the JSON format of `primitive.DateTime` use UTC, consistent with the relaxed extJSON format.
Marshalling in relaxed extJSON already uses UTC, which makes sense since the type has no timezone information.
Using local time in JSON does not appear to have been intentional, as there is no comment or test for this behavior.
Using UTC allows the JSON to be deterministic with respect to the BSON, rather than depend on the environment.
=> GODRIVER-2811 Use UTC when marshalling primitive.DateTime as JSON.

bson/example_test.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go
addressing this ticket https://jira.mongodb.org/browse/GODRIVER-1668 
improving error message when the database name is empty.
after spending a quiet amount of time debugging the misleading error message, which could have been detected immediately if there where better error messages.
=> GODRIVER-1668: specify database name empty error

mongo/readpref/readpref.go
[GODRIVER-2689](https://jira.mongodb.org/browse/GODRIVER-2689)
Always return a distinct `ReadPreference` value from the `Primary` read preference helper function.
The `readpref.Primary` helper function currently returns a pointer to the same value for every call. It's technically possible to modify the `*ReadPreference` value returned, which would modify the value for all callers of `readpref.Primary`.
=> GODRIVER-2689 Always return a distinct Primary read preference.

mongo/client.go
[GODRIVER-2683](https://jira.mongodb.org/browse/GODRIVER-2683)
Deprecate `mongo.NewClient` and `Client.Connect`.
There are no known use cases for the `mongo.NewClient` API that aren't followed by an immediate call to `Client.Connect`. Since `mongo.Connect` already combines those two behaviors, there's no known use case for `mongo.NewClient`, so deprecate it for removal in Go Driver 2.0.
=> GODRIVER-2683 Deprecate NewClient and Client.Connect

mongo/readpref/options.go, mongo/readpref/options_example_test.go, tag/tag.go
Improve tag sets documentation and add testable examples.
While investigating [GODRIVER-2687](https://jira.mongodb.org/browse/GODRIVER-2687), I realized that the documentation in the `tag` and `readpref` package concerning read preference tag sets could be improved. There is not much information about tag set matching behavior, and there are also no links to relevant documentation.
=> Improve tag sets documentation and add testable examples.

bson/bsoncodec/slice_codec.go, bson/bsoncodec/slice_codec_test.go
Memory allocations in the bson slice codec has been reduced.
```
name                       old time/op    new time/op    delta
SliceCodec_EncodeValue-10    56.9µs ± 0%     0.5µs ± 1%  -99.15%  (p=0.008 n=5+5)
SliceCodec_DecodeValue-10     185µs ± 0%       0µs ± 1%  -99.92%  (p=0.008 n=5+5)
name                       old alloc/op   new alloc/op   delta
SliceCodec_EncodeValue-10    16.6kB ± 0%     4.1kB ± 0%  -75.23%  (p=0.008 n=5+5)
SliceCodec_DecodeValue-10    98.3kB ± 0%     0.1kB ± 0%  -99.93%  (p=0.008 n=5+5)
name                       old allocs/op  new allocs/op  delta
SliceCodec_EncodeValue-10     4.11k ± 0%     0.00k ± 0%  -99.95%  (p=0.008 n=5+5)
SliceCodec_DecodeValue-10     4.10k ± 0%     0.00k ± 0%  -99.93%  (p=0.008 n=5+5)
```
There is a problem with using …
=> GODRIVER-2779 Reduce memory allocations in bson slice codec

.evergreen/config.yml, x/mongo/driver/mongocrypt/mongocrypt.go
GODRIVER-2761
- use libmongocrypt 1.8.0-alpha1
- remove use of `mongocrypt_setopt_fle2v2`
This PR is a follow-up to https://github.com/mongodb/mongo-go-driver/pull/1213
Queryable Encryption v2 is enabled by default in libmongocrypt 1.8.0-alpha1. libmongocrypt 1.8.0-alpha1 removes the symbol `mongocrypt_setopt_fle2v2` from the public API. `mongocrypt_setopt_fle2v2` was added in libmongocrypt 1.8.0-alpha0.
=> GODRIVER-2761 use libmongocrypt 1.8.0-alpha1

README.md
Remove the team-maintained table of contents from the README.md file in favor of the GitHub-generated ToC: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/
The linting CI failures are fixed in PR https://github.com/mongodb/mongo-go-driver/pull/1246
=> remove toc from README.md

mongo/options/changestreamoptions_test.go
Fix the import failure of `assert` in changestreamoptions_test.go.
=> Fix assert import.

bson/bsoncodec/array_codec.go, bson/bsoncodec/bsoncodec.go, bson/bsoncodec/bsoncodec_test.go, bson/bsoncodec/byte_slice_codec.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/empty_interface_codec.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/pointer_codec.go, bson/bsoncodec/slice_codec.go, bson/bsoncodec/string_codec.go, bson/bsoncodec/struct_codec.go, bson/bsoncodec/struct_codec_test.go, bson/bsoncodec/struct_tag_parser.go, bson/bsoncodec/time_codec.go, bson/bsoncodec/uint_codec.go, bson/decoder.go, bson/decoder_example_test.go, bson/decoder_test.go, bson/encoder.go, bson/encoder_example_test.go, bson/encoder_test.go
[GODRIVER-2716](https://jira.mongodb.org/browse/GODRIVER-2716)
Introduce a new way to customize BSON marshaling and unmarshaling by configuring a BSON `Encoder` or `Decoder`. Deprecate all existing codec types and configurations in the `bsoncodec` package (to be removed in Go Driver 2.0).
Add tests for all of the new configuration functions and add testable examples for some of them.
Currently, users have to go through the complex process of creating codecs to apply any custom marshal/unmarshal behavior and registering them in a registry. We want to provide a new, simpler API to configure BSON and Extended JSON marshaling/unmarshaling behavior via the `bson.Encoder` and `bson.Decoder` types.
The new API for configuring a `bson.Encoder` is:
```go
func (*Encoder).ErrorOnInlineDuplicates() …
```
=> GODRIVER-2716 Introduce a new BSON Encoder and Decoder configuration API to replace the bsoncodec configurations.

internal/logger/logger_test.go
Don't call `t.Parallel` in tests that use `t.Setenv`.
[t.Setenv](https://pkg.go.dev/testing#T.Setenv) documents:
> Because Setenv affects the whole process, it cannot be used in parallel tests or tests with parallel ancestors.
Some of the logger tests do call `t.Parallel` in tests that use `t.Setenv`, resulting in a panic:
```
❯ go test -run ^TestSelectLogSink$ go.mongodb.org/mongo-driver/internal/logger
--- FAIL: TestSelectLogSink (0.00s)
--- FAIL: TestSelectLogSink/stdout (0.00s)
panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests [recovered]
panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests
```
These tests confusingly don't panic in the Evergreen CI.
=> Don't call t.Parallel in tests that use t.Setenv.

.evergreen/config.yml, Makefile, etc/add_license.sh
[GODRIVER-2837](https://jira.mongodb.org/browse/GODRIVER-2837)
* Don't use `for` loops in the Makefile.
* Remove redundant `make build-examples` Makefile target.
* Don't limit package parallelism on `make test-short` because it's not necessary.
* Install `lll` and `golangci-lint` as part of Makefile targets to make commands repeatable.
I attempted to combine the `build` and `build-tests` Makefile targets, but there are many build CI tasks that are unable to run test code (e.g. Go 1.13 build, S390X build, etc).
A recent release that failed to build on customers' workstations highlighted cases where the Makefile targets can silently swallow errors (see [GODRIVER-2831](https://jira.mongodb.org/browse/GODRIVER-2831)). The main culprit is `for` loops in Makefiles, which only return the error …
=> GODRIVER-2837 Don't use for loops in the Makefile and always build test packages.

mongo/integration/server_selection_prose_test.go, mongo/integration/sessions_test.go, mongo/integration/unified/unified_spec_runner.go
Skip frequently failing test cases with follow-up GODRIVER tickets to resolve the failures:
* [GODRIVER-2842](https://jira.mongodb.org/browse/GODRIVER-2842)
* [GODRIVER-2843](https://jira.mongodb.org/browse/GODRIVER-2843)
* [GODRIVER-2844](https://jira.mongodb.org/browse/GODRIVER-2844)
To prevent known intermittent test failures from hiding new real test failures, skip frequently failing test cases and create GODRIVER tickets to follow up with fixes.
=> Skip frequently failing test cases with follow-up GODRIVER tickets.

mongo/integration/mtest/opmsg_deployment.go, x/mongo/driver/driver.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/operation.go, x/mongo/driver/operation/hello.go, x/mongo/driver/operation_test.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go
GODRIVER-2737
Backport changes from #1239 to release/1.11
- FLE tests failing due to 1.11 not having the changes made in #1213 
- Static analysis tasks failing due to 1.11 not having the changes made in #1177
[CDRIVER-4502](https://jira.mongodb.org/browse/CDRIVER-4502) reports that mongohoused (used for Atlas Data Federation) always returns int64.
=> GODRIVER-2737 ConnectionId returned in heartbeats may be int64

bson/doc.go
[GODRIVER-2568](https://jira.mongodb.org/browse/GODRIVER-2568)
Add a link to the [Work with BSON](https://www.mongodb.com/docs/drivers/go/current/fundamentals/bson/) page in the `bson` package docs.
There is additional useful information in the Go Driver docs site. We should regularly link to it from the Go package docs.
=> GODRIVER-2568 Add link to BSON fundamentals page in bson package docs.

mongo/integration/client_side_encryption_prose_test.go, x/mongo/driver/mongocrypt/mongocrypt.go
GODRIVER-2584
- return error if `masterKey` is set, but `provider` is not set for `rewrapManyDataKey`
- add prose test specified in DRIVERS-2441
The specified API for `rewrapManyDataKey` does not permit calling with a set `masterKey` without a `provider`.
```typescript
class ClientEncryption {
rewrapManyDataKey(filter: Document, opts: RewrapManyDataKeyOpts | null): RewrapManyDataKeyResult;
}
class RewrapManyDataKeyOpts {
provider: String
masterKey: Optional<Document>
}
```
Some driver implementations do not represent `RewrapManyDataKeyOpts` as a separate type. Instead, the `provider` and `masterKey` are both optional arguments to `RewrapManyDataKey`.
The current behavior of `ClientEncryption#RewrapManyDataKey` silently ignores the `MasterKey` option if `Provider` is nil.
This may result …
=> GODRIVER-2584 Error if RewrapManyDataKey is called with MasterKey and without Provider

bson/bsonrw/extjson_writer.go, bson/bsonrw/extjson_writer_test.go, bson/decoder.go, bson/decoder_example_test.go, bson/encoder.go, bson/encoder_example_test.go, bson/marshal.go, bson/unmarshal.go
[GODRIVER-2711](https://jira.mongodb.org/browse/GODRIVER-2711)
* Deprecate all `bson` package `Marshal`/`Unmarshal` functions that append data to an existing byte slice. Recommend people use the `Encoder` or `Decoder` types instead.
* Deprecate all `bson` package `Marshal`/`Unmarshal` functions that accept a `Registry`. Recommend people use the `Encoder` or `Decoder` types instead.
* Deprecate all functions that use an `EncodeContext` or `DecodeContext` during marshaling or unmarshaling. Recommend people use the `Encoder` or `Decoder` configuration functions instead.
* Add testable examples of how to use `Encoder` and `Decoder` to achieve most deprecated behaviors.
The `bson` package is cluttered with permutations of `*WithRegistry`, `*WithContext` and `*Append` functions for `Marshal` …
=> GODRIVER-2711 Deprecate BSON *Append and *With functions.

mongo/integration/handshake_test.go, x/mongo/driver/operation/hello.go, x/mongo/driver/operation/hello_test.go
GODRIVER-2833
Update handshake FaaS logic to skip AWS_EXECUTION_ENV data that is not prefixed with "AWS_Lambda_".
[DRIVERS-2209](https://jira.mongodb.org/browse/DRIVERS-2209) outlined that if the AWS_EXECUTION_ENV env var is present, the app is running on AWS Lambda. This turns out to be too permissive because AWS_EXECUTION_ENV is used in other non-Lambda envs. For example the Windows evergreen machines have AWS_EXECUTION_ENV=EC2.
=> GODRIVER-2833 restrict aws lambda metadata detection logic

bson/bsoncodec/bsoncodec.go, bson/bsoncodec/string_codec.go, bson/bsoncodec/struct_codec.go, bson/bsoncodec/time_codec.go, bson/bsonoptions/byte_slice_codec_options.go, bson/bsonoptions/empty_interface_codec_options.go, bson/bsonoptions/map_codec_options.go, bson/bsonoptions/slice_codec_options.go, bson/bsonoptions/string_codec_options.go, bson/bsonoptions/struct_codec_options.go, bson/bsonoptions/time_codec_options.go, bson/bsonoptions/uint_codec_options.go, bson/decoder.go, bson/decoder_test.go
[GODRIVER-2706](https://jira.mongodb.org/browse/GODRIVER-2706)
* Deprecate all types and methods in the `bsonoptions` package with suggested alternatives.
* Add the `Decoder.UseLocalTimeZone` option and deprecate `TimeCodec.UseLocalTimeZone` and the corresponding `bsonoptions` options. Note this should have been done with [#1229](https://github.com/mongodb/mongo-go-driver/pull/1229), but I missed it.
* Deprecate `StringCodec.DecodeObjectIDAsHex`. Note this should have been done with [#1229](https://github.com/mongodb/mongo-go-driver/pull/1229), but I missed it.
Currently the `bsonoptions` package is used exclusively to define configuration options for types and functions in the `bsoncodec` package. Those options structs are almost exact duplicates of most of the `*Codec` structs, which …
=> GODRIVER-2706 Deprecate all code in the bsonoptions package.

.evergreen/config.yml
- Hide libmongocrypt output by default
- Clone libmongocrypt with depth=1
- Use "bash" in every `shell.exec`
This is intended to reduce the logs in Evergreen that are not helpful to Go driver development.
Before this change, a [sample task](https://parsley.mongodb.com/evergreen/mongo_go_driver_tests_42_plus_zlib_zstd_support__version~latest_os_ssl_40~ubuntu1804_64_go_1_19_test_sharded_noauth_nossl_zlib_compression_54a3206c25f4b625c43aedbed95d83123d8bb7f7_23_05_05_18_58_58/0/task?bookmarks=0,1773,2277) includes 1716 lines of log output are from compiling libmongocrypt. After this change, there is 7 lines of output. The full logs of libmongocrypt compile are still printed on error to aid debugging a failed libmongocrypt build. [This …
=> Silence libmongocrypt build

bson/bsonrw/copier.go, bson/bsonrw/reader.go, bson/bsonrw/writer.go
[GODRIVER-2713](https://jira.mongodb.org/browse/GODRIVER-2713)
- Deprecate `bsonrw.Copier` and all associated methods.
- Deprecate the `bsonrw.BytesReader` and `bsonrw.BytesWriter` interfaces, which are only used by `bsonrw.Copier`.
The `bsonrw.Copier` type exposes a collection of methods related to copying BSON or Extended JSON documents using the `ValueReader` and `ValueWriter` interfaces. There is no known use case for `bsonrw.Copier` outside of the BSON library, so deprecate it because it will not be supported in Go Driver 2.0.
=> GODRIVER-2713 Deprecate bsonrw.Copier and related functions and types.

bson/bsoncodec/registry.go
[GODRIVER-2818](https://jira.mongodb.org/browse/GODRIVER-2818)
Deprecate bsoncodec errors that will be removed in Go Driver 2.0.
There are a number of exported error values and types in the `bsoncodec` package that do not need to be exported.
Errors that indicate an implementation error typically do not need to support comparison at runtime because we expect users will fix the implementation error rather than write error handling logic. There are a number of exported error values and types in the `bsoncodec` package that are only used to signal an implementation error and don't need to be exported:
Error values:
* `ErrNilType`
* `ErrNotPointer`
* `ErrNotInterface`
Error types:
* `ErrNoEncoder`
* `ErrNoDecoder`
* `ErrNoTypeMapEntry`
We still need to return errors in most of those cases, …
=> GODRIVER-2818 Deprecate bsoncodec errors that will be removed in Go Driver 2.0

x/mongo/driver/driver.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
[GODRIVER-2828](https://jira.mongodb.org/browse/GODRIVER-2828)
* Use the latest topology version from either the server or connection when processing errors in `ProcessError`.
* Refactor the `ProcessError` test to express the expected initial and resulting state changes more clearly.
* Add test cases for when the connection topology version is newer than the server topology version and when the topology process ID has changed.
While processing errors, the SDAM error handling function `ProcessError` attempts to compare the topology version on the error to the current topology version known by the Go driver, ignoring errors where the topology version is not newer than the known topology version. However, the Go driver currently uses the connection's topology version as the "known" topology …
=> GODRIVER-2828 Use topology version from Server instead of Connection in ProcessError.

bson/primitive/decimal_test.go
Use `testify/assert` in decimal_test.go for v1.11.7
The `release/1.11` branch still uses the `testify/assert` package and does not contain the new unified internal assertion library. Update decimal_test.go to use `testify/assert`.
=> Use testify/assert in decimal_test.go for v1.11.7

.evergreen/config.yml, .evergreen/run-tests.sh
GODRIVER-2481
Wait for the KMIP server to start after initializing it.
Avoid a long traceback that occurs when the server is stopped before fully starting.
=> GODRIVER-2481 Fix MacOS kmip python failures

mongo/integration/client_test.go
GODRIVER-2266
Stop paralleling in the client stress test.
"Client recovers from traffic spike" fails frequently on the CI of MacOS due to context timeout. Trying to reduce paralleling to release the pressure on the server because the RTT used to set the deadline is not from a paralleled condition either.
=> GODRIVER-2266 Stop paralleling in client stress test.

mongo/client_encryption.go, mongo/options/autoencryptionoptions.go, mongo/options/encryptoptions.go
[GODRIVER-2836](https://jira.mongodb.org/browse/GODRIVER-2836)
Remove the Beta notices for Queryable Encryption Equality APIs.
The feature will be stable in MongoDB Server 7.0.
=> GODRIVER-2836 Preview from Queryable Encryption Equality API

x/mongo/driver/topology/fsm.go
GODRIVER-2791
Bumps the max supported wire version to 21, which correlates with MongoDB server version 7.0.
=> GODRIVER-2791 Bump maxWireVersion for MongoDB 7.0

mongo/integration/unified/logger_verification.go
[GODRIVER-2855](https://jira.mongodb.org/browse/GODRIVER-2855)
Add the pool clear log event to the unordered list with the condition that closing a connection does not occur before clearing the pool.
The existing unified [spec test](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/tests/logging/connection-logging.yml#L199-L220) for connection logging has a specific order required for the following three events: ConnectionPoolCleared, ConnectionPoolClosed, ConnectionCheckOutFailed. There is an acceptable race condition in the connection pool's workflow where it is non-deterministic whether the connection pool will fail a checkout or close a connection first. Because of this, either ConnectionPoolClosed or ConnectionCheckOutFailed may be …
=> GODRIVER-2855 Relax closed, cleared, checkout conditions on logger verification

mongo/writeconcern/writeconcern.go, mongo/writeconcern/writeconcern_example_test.go, mongo/writeconcern/writeconcern_test.go
[GODRIVER-2685](https://jira.mongodb.org/browse/GODRIVER-2685)
Remove the functional options pattern, export all fields in the `WriteConcern` struct so users can set them directly, and add package functions for quickly specifying common write concerns `w: "majority"`, `w: 0`, and `w: 1`. Since users can now set any value to the exported `W` field, add type validation logic in the `MarshalBSONValue` function that returns an error if `W` is not a supported type, and add tests for the new error logic.
The `writeconcern` package and types use a lot of unnecessary APIs that can confuse users. Additionally, there are no helper functions for specifying common write concerns like there are for the `readconcern` and `readpref` packages. Remove the functional options pattern, export all fields in …
=> GODRIVER-2685 Simplify the writeconcern API.

mongo/integration/client_side_encryption_prose_test.go
Skip a frequently failing `TestClientSideEncryptionProse` test case with a follow-up ticket to resolve the failure:
* [GODRIVER-2872](https://jira.mongodb.org/browse/GODRIVER-2872)
=> Skip frequently failing TestClientSideEncryptionProse test case.

examples/_logger/logrus/go.mod, examples/_logger/zap/go.mod, examples/_logger/zerolog/go.mod, internal/test/compilecheck/go.mod, internal/test/faas/awslambda/mongodb/go.mod
[GODRIVER-2860](https://jira.mongodb.org/browse/GODRIVER-2860)
Update Go driver module version to `latest` in all submodules and add a note about the version being mostly irrelevant because of the replace directive.
This should resolve Github Dependabot alert https://github.com/mongodb/mongo-go-driver/security/dependabot/7
=> GODRIVER-2860 Update Go driver module version in all submodules.

x/mongo/driver/topology/server.go
GODRIVER-2874
Directly reference the connection existence when performing a server check where it is possible that the connection does not exist. The existing pattern used a variable "iNilConn" which is not reset after initialization, the reality is that the state of the connection can change via "createConnection" through "setupHeartbeatConnection". 
This PR proposes scrapping checking through "iNilConn" in favor of directly checking the state of the connection.
This bug prevents the initial connection from publishing a heartbeat event.
=> GODRIVER-2874 Directly reference conn existence

x/mongo/driver/topology/server_options.go, x/mongo/driver/topology/topology_options.go
GODRIVER-2871
This PR unexports the WithLogger server configuration setter. This function sets an internal-package object to the server configuration, which is useless to an external user. 
The configuration of the topology server includes a functional setter that allows for the export of the Logger struct from the internal/logger package. However, since this setter is not intended for use by external users who cannot import data from the internal package, it is recommended to unexport the WithLogger function to prevent confusion.
This setter was added as a part of the work for GODRIVER-2586 , adding log messages to CMAP. WithLogger is not currently exported as part of the experimental API in an existing release.
=> GODRIVER-2871 Unexport optional setter for internal-package logger

.evergreen/config.yml
[GODRIVER-2792](https://jira.mongodb.org/browse/GODRIVER-2792)
Only use Ubuntu 20.04 for Serverless tasks.
https://github.com/mongodb/mongo-go-driver/pull/1301 unintentionally added Ubuntu 20.04 builds for all MongoDB >4.0 tasks. Fix that issue so only Serverless uses Ubuntu 20.04.
=> GODRIVER-2792 Separate Serverless OS into new axis.

x/bsonx/bsoncore/bsoncore.go, x/bsonx/bsoncore/bsoncore_test.go, x/mongo/driver/compression.go, x/mongo/driver/compression_test.go
GODRIVER-2869
This PR is to fix two possible conditions which could result in a potential denial of service of a client connected to a malicious MongoDB server.
* Commit 1 - `readLengthBytes` requires the 4 bytes for the length to be included. Previously when reading a document from the wire this could result in a tight loop where an empty struct is appended to a slice repeatedly until the service runs out of memory (both CPU and memory consumption).
* Commit 2 - Fix a large memory allocation condition with Snappy decompression if a large size is encoded in the Snappy compressed / encoded portion of the bytes.
Let me know if you have additional questions or if there is anything more I can do to help.  Thank you!
=> GODRIVER-2869 Two protocol validations to reduce client denial of service risks

x/bsonx/bsoncore/bsoncore_test.go, x/mongo/driver/compression_test.go, x/mongo/driver/operation_test.go
GODRIVER-2869
- Parallelize new tests
- Add a test to reproduce the infinite loop
A test touchup following https://github.com/mongodb/mongo-go-driver/commit/a888dc6678b7a91301018a6e1bf04bdd3d22a63b
=> GODRIVER-2869 Test touchup

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/mgocompat/setter_getter.go
[GODRIVER-2887](https://jira.mongodb.org/browse/GODRIVER-2887)
Remove all uses of reflect.Value.MethodByName since it prevents dead code elimination. This causes binaries built with the mongodb/mongo-go-driver library to be larger than they need to be. 
All occurrences of reflect.Value.MethodByName are replaced with type assertions.
Source: https://go.dev/src/cmd/link/internal/ld/deadcode.go#L293
Reduce the size of binaries built with mongodb/mongo-go-driver.
=> GODRIVER-2887 bson: remove use of reflect.Value.MethodByName

x/mongo/driver/auth/plain_test.go, x/mongo/driver/errors.go
GODRIVER-2883
Handle boolean "ok" messages in command responses, and add text.
While the specification says that [Command Responses](https://www.mongodb.com/docs/manual/reference/method/db.runCommand/#std-label-command-response) have an "ok" field that "A number that indicates whether the command has succeeded (1) or failed (0).", there are some cases where the returned command can have a boolean value.   Update the Go driver to handle boolean "ok" responses and treat "ok": true as a success. 
We do not handle the case of a "hello" command returning a boolean value, since it has not been observed and we do not have a direct way to test the handling of hello responses without creating a new unified spec test.
=> GODRIVER-2883 Handle boolean 'ok' responses

mongo/integration/change_stream_test.go
GODRIVER-2827
The Go Driver does not have strongly typed change stream events, this PR adds the specification-defined prose test to ensure this behavior.
MongoDB 7.0 is adding a new aggregation stage $changeStreamSplitLargeEvent, which will split large events (>16MB) into smaller fragments.
=> GODRIVER-2827 Add prose test for change stream splitting

.evergreen/run-tests.sh
GODRIVER-2858
Limit the amount of tests we run on MacOS to a subset, prioritizing the unified spec tests.
With this change, the longest task that had previously timed out finishes in 46m 31s.
We often see timeouts when testing on MacOS on Evergreen, due to resource contention on the hosts.
=> GODRIVER-2858 Run a subset of tests on MacOS

mongo/database.go, mongo/integration/database_test.go, x/mongo/driver/batch_cursor.go
[GODRIVER-2847](https://jira.mongodb.org/browse/GODRIVER-2847)
Currently when you run a command that does not return a cursor (e.g. an "explain" command) with `RunCommandCursor`, you get a cryptic error message:
```go
"cursor should be an embedded document but is of BSON type invalid"
```
Improve the error message that is returned so that it more clearly expresses what went wrong and guides users to use `RunCommand` instead of `RunCommandCursor`:
```go
"database response does not contain a cursor; try using RunCommand instead"
```
The existing error message is confusing for users (see [GODRIVER-2847](https://jira.mongodb.org/browse/GODRIVER-2847)). When a user runs a command that does not return a cursor with `RunCommandCursor`, the error should give them enough information to switch to …
=> GODRIVER-2847 Improve error message if RunCommandCursor command doesn't return a cursor.

x/mongo/driver/topology/pool.go
Always add relevant errors to pool events.
The `Error` field was added to [PoolEvent](https://pkg.go.dev/go.mongodb.org/mongo-driver/event#PoolEvent) in v1.12.0, but is currently only used for errors that cause a connection to be closed. There are other events, like `ConnectionPoolCleared` and `ConnectionCheckOutFailed` that frequently have an error associated with them. Add the associated error to those events as well to make the events more useful for understanding what's going on.
=> Always add relevant errors to pool events.

.evergreen/config.yml
GODRIVER-2900
Ensures that the AWS EC2 Instance Profile is restored after the test runs: "Assigned authtest_instance_profile_role".
AWS Instance Profiles are now assigned for each of the EG hosts.  The "run-aws-auth-test-with-aws-web-identity-credentials" removes that instance profile to ensure that `AssumeRoleWithWebIdentity` is used.    We add a `post:` task to ensure that it is restored.
=> GODRIVER-2900 Fix handling of EC2 Instance Profile in EG Tests

.evergreen/config.yml
GODRIVER-2916
Ensure that the Atlas cluster created for FaaS test is properly cleaned up.
A new set  of scripts was added to drivers-evergreen-tools to ensure the Atlas cluster is shut down cleanly.
=> GODRIVER-2916 Clean up Lambda Test Script

mongo/options/loggeroptions.go
GODRIVER-2891
Add documentation for the level mappings propagated by the internal library to the user-defined LogSink. Clarify that the level returned is not intended to be 1-1 with the optional level enumeration used to construct a logger on a client.
The documentation team ran into an issue when attempting to compare the optional log levels to those returned by the "Info" method in a custom log sink. See [here](https://gist.github.com/prestonvasquez/faa1626b117a1cde12cfe02fb21a3107) for a detailed example.
=> GODRIVER-2891 Add documentation for log levels

event/monitoring.go, internal/logger/component.go, internal/logger/component_test.go, mongo/integration/unified/event_verification.go, mongo/integration/unified/schema_version.go, testdata/command-monitoring/find.json, testdata/command-monitoring/find.yml, testdata/command-monitoring/logging/command.json, testdata/command-monitoring/logging/command.yml, x/mongo/driver/operation.go
GODRIVER-2752
Add databaseName field to Command Events.
- Sync changes from commit https://github.com/mongodb/specifications/blob/6b267ddc7cca303a722d2893106fad4810709f06/source/command-logging-and-monitoring/command-logging-and-monitoring.rst
- add the `databaseName` field to `expectedCommandEvent.CommandFailedEvent` and `expectedCommandEvent.CommandSucceededEvent`
- add "database name" to the "command failed" and "command succeeded" log messages
- Sync changes from commit https://github.com/mongodb/specifications/blob/e7ee829329400786e01279b4f37d4e440d1e9cfa/source/unified-test-format/unified-test-format.rst#expectedcommandevent
- update mongo/integration/unified/event_verification.go
- update unified tests
=> GODRIVER-2752 Add databaseName field to Command Events

x/mongo/driver/topology/cmap_prose_test.go
GODRIVER-2851
Fix failing "TestCMAPProse" test.
Resume `TestCMAPProse` test cases.
=> GODRIVER-2851 Fix failing "TestCMAPProse" test.

mongo/integration/load_balancer_prose_test.go, x/mongo/driver/session/client_session.go
[GODRIVER-2867](https://jira.mongodb.org/browse/GODRIVER-2867)
* Unpin connections when ending a session.
* Add a test that asserts that running transactions when connected to a load balancer does not leak connections.
Currently the Go driver leaks connections if a user runs a transaction while connected to a load balancer. When a user explicitly ends a session, we should unpin any pinned connection so it can be reused.
=> GODRIVER-2867 Unpin connections when ending a session.

mongo/readconcern/readconcern.go, mongo/readconcern/readconcern_test.go
GODRIVER-2822
Add an `ErrEmptyReadConcern` following the convention in the marshaler of `WriteConcern`.
The marshaler of `WriteConcern` has been protected at [writeconcern.go#L285](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/writeconcern/writeconcern.go#L284-L286), and test-covered at [writeconcern_test.go#L127-L131](https://github.com/mongodb/mongo-go-driver/blame/master/mongo/writeconcern/writeconcern_test.go#L127-L131).
=> GODRIVER-2822 Add error on empty for ReadConcern marshaler.

bson/bsontype/bsontype.go, bson/primitive_codecs.go, bson/primitive_codecs_test.go, bson/raw_value.go, bson/raw_value_test.go
GODRIVER-2896
This PR proposes an "IsZero" method for the BSON "RawValue" type, which will be used by the EncodeValue-implementing types to "skip" encoding when the "omitempty" tag is present. Otherwise, this PR proposes that the PrimitiveCodecs' "RawValueEncodeValue" method should return an error when the RawValue's type is "invalid".
For clarity, after these changes the use case in the "Background & Motivation" section WILL NOT result in  a runtime error. However, if the user removes the "omitempty" tag from the "Likes" field, like this:
```go
type P struct {
Name  string        `bson:"name,omitempty"`
Likes bson.RawValue `bson:"likes"`
}
```
then the following error will be thrown:
```
the RawValue Type specifies an invalid BSON type: 0x0
```
A user has reported an issue where the …
=> GODRIVER-2896 Add IsZero to BSON RawValue

testdata/bson-corpus/top.json
GODRIVER-2139
Sync BSON corpus spec tests to [mongodb/specifications@5fad277](https://github.com/mongodb/specifications/commit/5fad2773960d63d46b7738dde8d7b1aca0ceaac9).
Two decodeErrors tests in top.json incorrectly use $options as a field within $regularExpression.
=> GODRIVER-2139 Fix invalid field name in regex parse error test.

testdata/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_integer.json, testdata/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_integer.yml, testdata/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_type.json, testdata/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_type.yml, testdata/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_integer.json, testdata/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_integer.yml, testdata/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_type.json, testdata/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_type.yml
GODRIVER-2253
Remove the incorrect (and redundant) tests.
We don't have warnings in Go, so we return warnings as errors though the spec states that a warning should be logged and the parsed value ignored. The behavior is commented at [connstring_spec_test.go#L123-L128](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/connstring/connstring_spec_test.go#L123-L128).
=> GODRIVER-2253 Remove srvMaxHosts tests expecting an error for invalid values.

internal/logger/logger.go, internal/logger/logger_test.go
GODRIVER-2881
Update the considerations for enabling a log to 
1. Disable with any case where the level if "off"
2. Disable when ComponentLevels are undefined
3. Enable if the component "ComponentAll" is defined and it bounds the level passed to the function
There is a logging design oversight in which enabling logging with "options.LogComponentAll" does not result in the publication of logs. This issue arises because the "LevelComponentEnabled" method on the internal logger object fails to account for this specific use case.
=> GODRIVER-2881 Enable logging for ComponentAll

mongo/options/clientoptions.go, x/mongo/driver/topology/connection_options.go
GODRIVER-2846
Update the out-of-date comments on `SetDialer`.
The Go driver now uses the default `net.Dialer` when nothing is specified. `connectTimeoutMS` no longer impacts the dialer timeout.
=> GODRIVER-2846 Update comments on ClientOptions.SetDialer().

mongo/change_stream.go
[GODRIVER-2930](https://jira.mongodb.org/browse/GODRIVER-2930)
Allow setting batch size for subsequent `getMore`s on a `ChangeStream`.
Currently you can set batch size on a `ChangeStream` using `ChangeStreamOptions.SetBatchSize`. However, that applies to both the initial "aggregate" command as well as the subsequent "getMore" commands run while iterating the change stream. That can cause a problem when starting a change stream on low- or bursty-traffic collections because the initial aggregate won't return a cursor until the batch size is filled. The tailable cursor used by a change stream is intended to wait indefinitely for updates, but the initial "aggregate" command isn't, so will time out if there aren't enough changes to fill a batch, leading to an unexpected error.
=> GODRIVER-2930 Allow setting batch size for subsequent getMore's on a ChangeStream.

bson/bsontype/bsontype.go, bson/types.go, testdata/bson-corpus/binary.json
GODRIVER-2926
Adds support for BSON Binary Data subtype 8: Sensitive
Query stats users who wish to supply their own HMAC key will do so via this subtype.
=> GODRIVER-2926 Add BSON Binary Data subtype Sensitive

x/mongo/driver/batch_cursor.go, x/mongo/driver/operation.go
GODRIVER-2209
Add an "OmitReadPreference" field to the Operation struct with the goal of excluding the readPreference from the command, regardless of state (nil or not nil) on an instance of Operation.
Currently, the default read preference of primaryPreferred is included in the getMore and killCursors. This can be surprising to users logging CommandStarted events.
=> GODRIVER-2209 Omit readPreference on BatchCursor commands

.github/workflows/comment.yml
[GODRIVER-2923](https://jira.mongodb.org/browse/GODRIVER-2923)
Fix handling of the API Report for PRs made from a fork.
The previous PR was tested using PRs from the same repo (my own fork).
=> GODRIVER-2923 Fix remote handling

.evergreen/config.yml
GODRIVER-2942
Updates the host to fix the failing MongoDB Download.
Ubuntu 20.04 does not support MongoDB 7.0.
=> GODRIVER-2942 Fix Failing Serverless MongoDB Download

mongo/integration/unified/unified_spec_runner.go, mongo/integration/unified_spec_test.go
GODRIVER-2943
Skip failing logging test for now, to be picked up in Green Build.
Get builds green in PRs to avoid masking other errors.
=> GODRIVER-2943 Skip failing logging tests

mongo/integration/change_stream_test.go
GODRIVER-2912
Run the split large changes change stream prose test on server versions 6.0.9 or higher.
The feature was backported to 6.0.9.
=> GODRIVER-2912 Backport: Avoiding Errors if Change Stream Events Exceed 16MB

x/mongo/driver/errors.go
[GODRIVER-2929](https://jira.mongodb.org/browse/GODRIVER-2929)
Make `driver.ErrDeadlineWouldBeExceeded` wrap `context.DeadlineExceeded`.
`context.DeadlineExceeded` and `driver.ErrDeadlineWouldBeExceeded` are logically the same error condition, but either can be returned depending on the timing an operation. Make it easier to check for either by updating `driver.ErrDeadlineWouldBeExceeded` to wrap `context.DeadlineExceeded`. That way, no matter which error timing scenario happened, the following will return true:
```
errors.Is(err, context.DeadlineExceeded)
```
=> GODRIVER-2929 Make driver.ErrDeadlineWouldBeExceeded wrap context.DeadlineExceeded

.evergreen/config.yml
GODRIVER-2951
Explicitly set the env variables used in `run-load-balancer-tests`.
Variables were not being explicitly set.
=> GODRIVER-2951 Improper handling of env vars in Load Balancer Test

x/mongo/driver/topology/CMAP_spec_test.go
[GODRIVER-2852](https://jira.mongodb.org/browse/GODRIVER-2852)
Use a mock connection for all CMAP spec tests.
Some CMAP spec tests currently use a TCP listener, but does not accept any connections or read or write data. As a result, the behavior of the tests depends on how the "zombie" TCP listener behaves, which may be inconsistent. Use a mock connection in all cases to make the tests more reliable.
=> GODRIVER-2852 Use a mock connection for all CMAP spec tests.

x/mongo/driver/topology/errors.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/server.go
GODRIVER-2423
Include "connections in use by cursors" and "connections in use by transactions" in `WaitQueueTimeoutError` only for load balanced clusters.
When connected to Load Balancers, drivers are required to pin connections to cursors and transactions. However, The Go driver always reports pinned connections in WaitQueueTimeoutError, even if no connection pinning occurs.
This PR proposes the pinned connections in the `WaitQueueTimeoutError` to be optional. The pool includes the pinned connections in `WaitQueueTimeoutError` only when the topology is load-balanced.
=> GODRIVER-2423 Include pinned connections in WaitQueueTimeoutError only for load balanced clusters.

.evergreen/config.yml, cmd/testkms/main.go
GODRIVER-2963
- Use environment variables for the `keyName` and `keyVaultVndpoint` in the Azure KMS test.
Changes were verified with this patch: https://spruce.mongodb.com/version/64ee53e7c9ec449533606004
The `test-azure-kms` task currently uses credentials and data from a personal MongoDB account.
DRIVERS-2709 gives MongoDB managed credentials for the Azure KMS tests.
`AZUREKMS_KEY_NAME` and `AZUREKMS_KEY_VAULT_ENDPOINT` were added as Variables to the Evergreen Projects:
- `mongo-go-driver-cloud`
- `mongo-go-driver`
- `mongo-go-driver-release`
- `mongo-go-driver-previous`
The old values were used. After this PR is merged, the Variables can be migrated to the new MongoDB managed values.
=> GODRIVER-2963 Use more environment variables in Azure KMS test

mongo/integration/client_side_encryption_prose_test.go, x/mongo/driver/mongocrypt/binary.go
GODRIVER-2872
Fix the failing "TestClientSideEncryptionProse" test by duplicating the memory passed to the C side.
The original comment was not accurate. The C side [mongocrypt_binary_new_from_data()](https://github.com/kevinAlbs/libmongocrypt/blob/master/src/mongocrypt-binary.c#L30-L41) does a shallow copy of the passed array only, while the Golang slice which holds the memory may be freed or moved by GC.
Once a GC happens, for example, between [C.mongocrypt_binary_new_from_data()](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/mongocrypt/mongocrypt.go#L122) and [C.mongocrypt_ctx_encrypt_init()](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/mongocrypt/mongocrypt.go#L127), the memory block pointed by `C.mongocrypt_binary_t` gets corrupted and …
=> GODRIVER-2872 Fix failing "TestClientSideEncryptionProse" test.

.evergreen/config.yml, .gitignore, Makefile, cmd/testatlas/main.go, etc/get_aws_secrets.sh, etc/run-atlas-test.sh
[GODRIVER-2958](https://jira.mongodb.org/browse/GODRIVER-2958)
Use AWS Secrets for variables instead of Evergreen project variables for Atlas tests.
Centralizes location of secrets and allows them to be accessed for local development.
=> GODRIVER-2958 Use AWS Secrets for Atlas tests

x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/wiremessage/wiremessage.go
GODRIVER-2972
The usage of "wiremessage.CurrentRequestID()" in the operation.Execute method will cause a race condition where concurrent calls to Execute will result in wire messages from different operations sending the same RequestID to the server.
NA
=> GODRIVER-2972 Fix wiremessage RequestID race in operation.Execute

mongo/integration/client_test.go, mongo/integration/mtest/sent_message.go, x/mongo/driver/auth/speculative_scram_test.go, x/mongo/driver/auth/speculative_x509_test.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/legacy.go, x/mongo/driver/operation.go, x/mongo/driver/operation/hello.go, x/mongo/driver/topology/server_test.go
GODRIVER-2935
Add OP_QUERY back to to operation execute's construction of wire messages, but specifically for handshake requests.
[GODRIVER-2892](https://jira.mongodb.org/browse/GODRIVER-2892) deprecated 3.4. server support and removed the usage of OP_QUERY from the code. Incidentally, removing the "createQueryWireMessage" operation method also prevents handshakes from using OP_QUERY , which is a spec requirement: https://github.com/mongodb/specifications/blob/master/source/mongodb-handshake/handshake.rst#connection-handshake
=> GODRIVER-2935 Use OP_QUERY in connection handshakes

mongo/errors.go, mongo/integration/client_test.go, x/mongo/driver/errors.go
[GODRIVER-2603](https://jira.mongodb.org/browse/GODRIVER-2603)
Use `errors.Is`/`As` in `mongo.IsTimeout` and `mongo.IsDuplicateKeyError`.
As we add more error wrapping inside the Go driver, error checking code that doesn't unwrap errors will start breaking. This came up as I was implementing [GODRIVER-2579](https://jira.mongodb.org/browse/GODRIVER-2579). Subsequent PRs will handle wrapped errors in additional Go driver code.
=> GODRIVER-2603 Use errors.Is/As for IsTimeout and IsDuplicateKeyError.

x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
GODRIVER-2904
Log informational message client-side based on detected environment (DocumentDB or CosmosDB)
Log informational messages by examining host names added to a topology.
SRV connection strings are not tested, since initial lookup responses cannot be easily mocked.
=> GODRIVER-2904 Add environment log.

bson/bsoncodec/slice_codec.go, bson/bsoncodec/struct_codec.go, bson/bsoncodec/struct_codec_test.go, bson/bsoncodec/types.go, bson/bsonrw/copier.go, bson/bsonrw/value_reader.go, bson/bsonrw/value_writer.go, bson/marshal.go
[GODRIVER-2914](https://jira.mongodb.org/browse/GODRIVER-2914)
This commit eliminates all allocations during marshalling (except for
the final []byte slice allocation, which is unavoidable). This matches
the behavior of encoding/json. It also prevents the vwPool from leaking
writers and includes a few small optimizations to the value_writer.
Other Changes:
* bsoncodec: reduce use of reflect.Value.Interface()
* bson: use a buffer pool instead of SliceWriter to eliminate 2 allocs
* bsonrw: use references to slice indexes
This work builds off of https://github.com/mongodb/mongo-go-driver/pull/1313
and uses the BenchmarkCode* suite added by that PR.
The combined performance improvement is below:
```
goos: darwin
goarch: arm64
pkg: go.mongodb.org/mongo-driver/bson
│ base.20.txt  │ …
```
=> GODRIVER-2914 bsoncodec/bsonrw: eliminate encoding allocations

.evergreen/config.yml, .evergreen/run-tests.sh, mongo/integration/client_side_encryption_prose_test.go
GODRIVER-2792
Migrate CI to RHEL 8.7 for long-term support.
The build team is winding down support for OSes that are either unsupported or in extended security maintenance (ESM) as part of PM-3193. This includes Ubuntu 18.04, which is in ESM in Apr 2023, and any of the RHEL 7.x build variants less than 7.6. RHEL 7.6 enters ESM in Jun 2024.
=> GODRIVER-2792 Migrate CI to RHEL 8.7

etc/api_report.sh
GODRIVER-2985
This is a quick update for the API changes report to make it work for new branches such as `v1`.
Maybe we need to merge to v1 as well.
=> GODRIVER-2985 Enable api changes report on all branches.

mongo/integration/change_stream_test.go, mongo/integration/unified/client_entity.go, mongo/integration/unified/context.go, mongo/integration/unified/logger.go, mongo/integration/unified/unified_spec_runner.go
GODRIVER-2986
- Extend the change stream timeout in the "split large changes" change stream prose test added in GODRIVER-2827 
- Guard read / write to the UST logger's lastOrder field, which is incremented every time the "info" method is called
=> GODRIVER-2986 Resolve failures in Race Detector Test

mongo/integration/change_stream_test.go, mongo/integration/unified/client_entity.go, mongo/integration/unified/logger.go, mongo/integration/unified/unified_spec_runner.go
Cherry-pick of #1380 from v1 to master
=> GODRIVER-2986 [master] Resolve failures in Race Detector Test

x/mongo/driver/operation/hello.go, x/mongo/driver/operation/hello_test.go
GODRIVER-2906
- Update the metadata handshake `client.env.name` field to optional.
- Add `client.env.container`.
The values for `client.env.container` are sourced from the environment, see [here](https://github.com/mongodb/specifications/blob/611ecb5d624708b81a4d96a16f98aa8f71fcc189/source/mongodb-handshake/handshake.rst#container).
`client.env.container.runtime` is untested since it requires "/.dockerenv", which exists in the root directory.
=> GODRIVER-2906 Add container Env to Handshake.

.evergreen/config.yml
GODRIVER-2982
Add PR build tags ("pullrequest") for easier Evergreen config.
A tag, "pullrequest", has been added to current variants as well as the "race detector" tasks so the Go driver Evergreen project can use tags instead of regexes.
Go driver Evergreen project configs will be updated later after the PR merging.
I think it would be better if we could manage the Evergreen project settings under the version control for tracking purpose. But it can be in a separate PR/ticket.
=> GODRIVER-2982 Add PR build tags.

.evergreen/config.yml
GODRIVER-2996
Fix search index matrix "config.yml".
The issue was caused by: [https://github.com/mongodb/mongo-go-driver/commit/f192906799a33a2c777e74b4153481ef99ee1c45#diff-2bc841e86ce96b7b422ae2[…]ecbe0e096420656fc3fb12R2827](https://github.com/mongodb/mongo-go-driver/commit/f192906799a33a2c777e74b4153481ef99ee1c45#diff-2bc841e86ce96b7b422ae203fd8315d0b2a461956cecbe0e096420656fc3fb12R2827)
=> GODRIVER-2996 Fix search index matrix config.yml.

x/mongo/driver/operation/hello.go, x/mongo/driver/operation/hello_test.go
Cherry-pick of #1382 from v1 to master
=> GODRIVER-2906 [master] Add container Env to Handshake.

mongo/errors.go, x/mongo/driver/errors.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/eSKOAOz0K0M
=> Remove redundant nil check in `HasErrorLabel`

README.md, mongo/options/clientoptions.go
GODRIVER-2955
Add top-level documentation for network compression.
Once the team agrees on the documentation, I will create a DOCSP ticket to add a "Network Compression" to the connection section of the Go Driver documentation , in the style of Java: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/network-compression/
> Network compression info should be clearly documented and easy to find by our users via a top-level section/tutorial in the docs.
=> GODRIVER-2955 Add user-facing network compression documentation

.evergreen/config.yml, .github/workflows/sync.yml
GODRIVER-2978
Fix the branch synching workflow.
The synch run [failed](https://github.com/mongodb/mongo-go-driver/actions/runs/6299987566) due to not configuring the github user globally.
=> GODRIVER-2978 Fix branch synching workflow

mongo/integration/mtest/mongotest.go
[GODRIVER-2075](https://jira.mongodb.org/browse/GODRIVER-2075)
Updated documentation for `GetStartedEvent()`, `GetSucceededEvent()`, and `GetFailedEvent()` helpers on the `mtest.T`.
The documentation for these helpers states that they return the "most recent" event, however the implementation actually returns the least recent event.
Existing tests depend on this behavior (see `mongo/integration/database_test.go`), therefore it is easier to change the documentation to reflect the same.
=> GODRIVER-2075 Update "mtest.T.Get*Event()" documentation

x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
GODRIVER-2966
Remove the heartbeat events when checking on the server after a connection is closed / a check is canceled.
=> GODRIVER-2966 Remove the heartbeat events after a connection is closed / a check is canceled.

.evergreen/config.yml
GODRIVER-3002
Use Azure KMS credentials from the vault, and ensure the Azure role is removed.
Credentials can be centrally managed, and we stop orphaning Azure roles.
=> GODRIVER-3002 Azure KMS Clean up

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/server.go
[GODRIVER-2952](https://jira.mongodb.org/browse/GODRIVER-2952)
Updated instances of `ctx.Err() == context.Cancelled || ctx.Err() == context.DeadlineExceeded` with calls to `errors.Is()`
This is a more idiomatic way of checking error types.
=> GODRIVER-2952 Update context.Canceled equality comparisons to errors.Is

mongo/client_side_encryption_examples_test.go, mongo/gridfs/bucket.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/client_side_encryption_test.go, mongo/integration/client_test.go, mongo/integration/collection_test.go, mongo/integration/crud_helpers_test.go, mongo/integration/database_test.go, mongo/integration/gridfs_test.go, mongo/integration/mtest/setup.go, mongo/integration/retryable_writes_prose_test.go, mongo/integration/unified/client_encryption_operation_execution.go, mongo/integration/unified/collection_operation_execution.go, mongo/integration/unified/database_operation_execution.go, mongo/mongocryptd.go, mongo/single_result.go, mongo/single_result_test.go, mongo/with_transactions_test.go
GODRIVER-2979
Cherry-pick https://github.com/mongodb/mongo-go-driver/commit/da5f54a90326fa5c90796b1a0fffc8429c644f70 and remove SingleResult.DecodeBytes .
The method SingleResult.DecodeBytes is a misnomer because it does not decode the result, but returns the raw bytes. It would be better to rename it SingleResult.Raw instead.
=> GODRIVER-2979 Rename SingleResult DecodeBytes to Raw

mongo/session.go
GODRIVER-2997
Use a background context when committing a transaction.
The Go Driver documentation for Session.WithTransaction notes that you should not use the method with a cancelable context:
> Because this method must succeed to ensure that server-side resources are properly cleaned up, context deadlines and cancellations will not be respected during this call.
Therefore, we should not response user-defined contexts in the commit loop.
=> GODRIVER-2997 Prevent cancelable context in txn commit loop

mongo/index_view.go, mongo/integration/index_view_test.go, mongo/integration/unified/collection_operation_execution.go
GODRIVER-961
Remove server response from IndexView.DropAll.
Dropping an index replies with a superset of the following message: `{nIndexesWas: n}`, where `n`  indicates the number of indexes there were prior to removing whichever index(es) were dropped. In the case of DropAll this number is always `m - 1`, where m is the total number of indexes. We can simplify the DropAll method by removing the server response.
=> GODRIVER-961 Change IndexView.DropAll to not return bson.Raw

README.md
Added keyword `go` to highlight Go syntax in code examples.
Observed this while going through the documentation.
=> Updated README.md for highlighting Go syntax

.evergreen/config.yml
GODRIVER-3010
Update our Ubuntu AWS tests to use Ubuntu 20.04.
Move to a supported Ubuntu distribution.
=> GODRIVER-3010 Update ECS Test to use Ubuntu 20.04

mongo/integration/unified/logger.go
GODRIVER-3013
Lock the entire test runner logger.Info method.
=> GODRIVER-3013 Resolve race test failures

.evergreen/config.yml, .evergreen/run-tests.sh, .gitignore, Dockerfile, docs/CONTRIBUTING.md, etc/docker_entry.sh, etc/install-libmongocrypt.sh, etc/run_docker.sh, mongo/client_test.go, mongo/integration/handshake_test.go, mongo/integration/sdam_prose_test.go
Cherry-pick of #1381 from v1 to master
=> GODRIVER-2989 [master] A Dockerfile for local development

examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go
[GODRIVER-2005]( https://jira.mongodb.org/browse/GODRIVER-2005)
- Removed usages of `require` library in documentation examples with
`assert` library.
=> GODRIVER-2005 - Replace "require" library with "assert" in documentation examples

mongo/collection.go, mongo/collection_test.go, mongo/errors.go
[GODRIVER-2582](https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-2582)
Update `collection.InsertMany()` to accept `interface{}` instead of `[]interface{}`. Use reflection to convert to `[]interface{}` internally.
Accepting `[]interface{}` forces the users to do this every time.
=> GODRIVER-2582 Accept any value for "documents" in InsertMany

bson/bsoncodec/default_value_decoders.go
GODRIVER-2046
Update error text.
Just ran into this today and it caused me a little friction. It seems like a simple enough fix.
=> GODRIVER-2046 Return clearer error when truncating a float64 to float32 without the truncate tag

bson/bsoncodec/default_value_decoders.go
Cherry-pick of #1448 from v1 to master
=> GODRIVER-2046 [master] Return clearer error when truncating a float64 to float32 without the truncate tag

mongo/index_view.go
GODRIVER-3038
Add TODO comments for this ticket. There are still open questions.
=> GODRIVER-3038 Add todo comments

internal/driverutil/hello.go, internal/test/faas/awslambda/mongodb/main.go, mongo/integration/unified/testrunner_operation.go, x/mongo/driver/topology/rtt_monitor.go
Cherry-pick of #1451 from v1 to master
=> Fix spelling issues (#1451) [master] Fix spelling issues (#1451)

internal/errutil/join.go, internal/errutil/join_go1.19.go, internal/errutil/join_go1.20.go, internal/errutil/join_test.go
[GODRIVER-2929](https://jira.mongodb.org/browse/GODRIVER-2929)
Add `errutil.Join`, which provides the ability to join multiple errors into one.
Go 1.20 adds the [errors.Join](https://pkg.go.dev/errors#Join) function that can join multiple "sibling" errors into one (e.g. multiple errors that happen when retrying an operation). Add a similar method to the "internal/errutil" package that works similarly both Go 1.20+ and for earlier Go versions.
=> GODRIVER-2929 Add the ability to join multiple errors into one.

event/doc.go, event/monitoring.go, mongo/gridfs/gridfs_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/retryable_reads_prose_test.go, mongo/integration/retryable_writes_prose_test.go, mongo/integration/server_selection_prose_test.go, mongo/integration/unified/client_entity.go, mongo/integration/unified/event.go, mongo/integration/unified/event_verification.go, mongo/with_transactions_test.go, x/mongo/driver/topology/pool.go
[GODRIVER-2693](https://jira.mongodb.org/browse/GODRIVER-2693)
Renamed event constants in `event/monitoring.go` and all references.
The changed event constants did not match their string values.
=> GODRIVER-2693 Rename event constants to match event names

event/monitoring.go, internal/logger/component.go, internal/logger/component_test.go, mongo/integration/mtest/opmsg_deployment.go, mongo/integration/server_selection_prose_test.go, mongo/integration/unified/event_verification.go, x/mongo/driver/driver.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/server.go
GODRIVER-2824
- Change PoolEvent.ConnectionID to an int64.
- Rename the deprecated ServerConnectionID64 to ServerConnectionID on CommandStartedEvent and CommandFinishedEvent.
- Update the internal representation of the connection pool's connection ID to int64 (from uint64).
[GODRIVER-2737](https://jira.mongodb.org/browse/GODRIVER-2737) changes the connection ID types on events to int64. To avoid breaking changes in the v1 driver, we deprecated the old ServerConnectionID fields in favor of ServerConnectionID64.
=> GODRIVER-2824 Remove non-int64 Exported Connection IDs

mongo/integration/unified_spec_test.go
[GODRIVER-2117](https://jira.mongodb.org/browse/GODRIVER-2117)
- In method `executeTestRunnerOperation`, check `clientSession` for nullability
where `clientSession` is required.
- Return errors to the caller - this makes error handling consistent
across `executeTestRunnerOperation`.
=> GODRIVER-2117 - Check clientSession is not nil inside executeTestRunnerOperation

mongo/integration/unified_spec_test.go
GODRIVER-2117
Cherry-pick fd1ca35845e24ad667abfedecbe175bdb1b95883
The ticket improves error handling in the executeTestRunnerOperation, cherry-picking will improve the waterfall for 1.12.
=> GODRIVER-2117 Cherry-pick legacy test runner error handling

mongo/writeconcern/writeconcern.go
GODRIVER-2954
Add WCMajority constant to the writeconcern package.
Add a convenience constant to help user's of the writeconcern package avoid using magic strings.
=> GODRIVER-2954 Add WCMajority const to wc package

event/monitoring.go, mongo/client_test.go, mongo/integration/unified/client_entity.go, x/mongo/driver/operation.go
GODRIVER-2616
Change CommadFailedEvent.Failure type from string to error. 
The original proposal for the command monitoring event api was given in ecbcd69 . It is unclear why a string type was chosen for failure. The [specifications](https://github.com/mongodb/specifications/blob/master/source/command-logging-and-monitoring/command-logging-and-monitoring.rst#events-api) concerning a failed event states the following about the failure type:
> Returns the failure. Based on the language, this SHOULD be a message string, exception object, or error document.
Since a [Go error](https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/builtin/builtin.go;l=307) is a wrapper for a function that returns a string, I think it is reasonable to assume that a Go error falls under the "string" type. …
=> GODRIVER-2616 Change CommandFailedEvent.Failure type to error

benchmark/harness_case.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/struct_codec.go, bson/decoder_example_test.go, bson/encoder_example_test.go, bson/primitive/objectid.go, cmd/testatlas/main.go, cmd/testaws/main.go, internal/aws/awserr/types.go, internal/csfle/csfle.go, mongo/cursor.go, mongo/integration/errors_test.go, mongo/integration/mtest/global_state.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/with_transactions_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/ocsp/config.go
[GODRIVER-2603](https://jira.mongodb.org/browse/GODRIVER-2603)
- Used the new formatting directive `%w` for wrapping errors
- Removed usage of `WrappedError` struct for wrapping errors
- Used the error APIs `errors.Is` and `errors.As` for examining wrapped errors
As a requirement for the related ticket [GODRIVER-2646](https://jira.mongodb.org/browse/GODRIVER-2646), all errors are required to
be addressed to enable [errorlint linter](https://github.com/mongodb/mongo-go-driver/blob/0a826e6efd4b362d59be309e2cd9e6f70ddcc5c0/.golangci.yml#L16). Enabling the linter gave a significant
number of errors that would require revision.
From code review aspect, to keep the volume of changes in a single PR manageable,
I chose to address only a fraction of linter errors here. Would submit subsequent …
=> GODRIVER-2603 - Revised error handling using Go 1.13 error APIs

x/mongo/driver/topology/server.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
GODRIVER-2432
Add a defer-recover function that logs unexpected failures encountered during topology maintenance.
Runtime fatals occurring in server maintenance methods are silently ignored. The rationale behind this is to prevent server maintenance, like updating a server, from disrupting a client's application. While there is currently no identified source for these fatals, it is presumed they may arise from the intricate locking system designed to facilitate concurrent updates. This pull request suggests the addition of a logging solution for these defer/recover blocks to learn more form clients, our unified spec test, and perhaps future telemetry.
=> GODRIVER-2432 Improve panic handling in background processes

benchmark/harness_case.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/struct_codec.go, bson/decoder_example_test.go, bson/encoder_example_test.go, bson/primitive/objectid.go, cmd/testatlas/main.go, cmd/testaws/main.go, internal/aws/awserr/types.go, internal/csfle/csfle.go, mongo/cursor.go, mongo/integration/errors_test.go, mongo/integration/mtest/global_state.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/with_transactions_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/ocsp/config.go
Cherry-pick of #1470 from v1 to master
=> GODRIVER-2603 [master] - Revised error handling using Go 1.13 error APIs

.evergreen/config.yml, .evergreen/run-mongodb-aws-test.sh, Makefile, etc/run-atlas-test.sh
GODRIVER-2960
- Make Evergreen output less verbose.
- Attach `test_suite.tgz` file even in failure so we see the reason.
- Only start CSE servers when we need to.
- Clean up CSE startup code.
Improve Evergreen Runtime and Usability.
=> GODRIVER-2960 Improve Evergreen Runtime and Usability

bson/bsoncodec/registry.go, bson/bsoncodec/registry_test.go, bson/bsoncodec/struct_codec.go, bson/marshal_test.go, bson/unmarshal_test.go
GODRIVER-3009
Remove the unnecessary nil cache, so nil encoder/decoder will not be stored.
The original panic was:
> interface conversion: interface is nil, not bsoncodec.ValueEncoder
from bson/bsoncodec/codec_cache.go:45
The root cause is at https://github.com/mongodb/mongo-go-driver/blob/master/bson/bsoncodec/struct_codec.go#L481
=> GODRIVER-3009 Fix concurrent panic in struct codec.

Makefile, mongo/integration/client_test.go, mongo/integration/handshake_test.go, testdata/load-balancers/sdam-error-handling.json, testdata/load-balancers/sdam-error-handling.yml, x/mongo/driver/operation/hello.go
Cherry-pick of #1482 from v1 to master
=> GODRIVER-3054 [master] Handshake connection should not use legacy for LB

mongo/options/collectionoptions.go, mongo/options/dboptions.go
GODRIVER-2937
Copy BSONOptions when merging coll or db opts.
The copy logic was missed when implementing BSONOptions.
=> GODRIVER-2937 Copy BSONOptions when merging coll or db opts

bson/primitive/objectid_test.go, mongo/bulk_write.go, mongo/collection.go, mongo/mongo.go, mongo/mongo_test.go
any insert operation preemptively generates new ObjectID to check/ensure if `_id` exists in doc or not - but chances are that goes to waste. this waste is more pronounced in scenarios where _id is a mix of custom userland id and system generated one across collections of a db or even across documents of same collection
```go
type IDO struct {
ID primitive.ObjectID `bson:"_id,omitempty"`
}
dsn := os.Getenv("MONGO_DSN")
client, _ := mongo.Connect(context.Background(), options.Client().ApplyURI(dsn))
coll := client.Database("db_name").Collection("id_test")
fmt.Println(coll.InsertOne(context.Background(), IDO{primitive.NewObjectID()}))
fmt.Println(coll.InsertOne(context.Background(), IDO{}))
fmt.Println(coll.InsertOne(context.Background(), IDO{primitive.NewObjectID()})) …
```
=> Generate new ObjectID only when required

event/monitoring.go, internal/benchmark/harness.go, mongo/address/addr.go, mongo/description/description.go, mongo/gridfs/bucket.go, mongo/mongo.go, mongo/options/clientoptions.go, mongo/readconcern/readconcern.go, mongo/readpref/readpref.go, mongo/writeconcern/writeconcern.go, tag/tag.go, version/version.go, x/bsonx/bsoncore/bsoncore.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/driver.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/topology.go
GODRIVER-2392
Remove all vestigial "import comments" from the Go Driver. See [GODRIVER-2977](https://jira.mongodb.org/browse/GODRIVER-2977) for the ticket for removing import comments from the BSON library.
=> GODRIVER-2392 Remove all "import comments" on Go Driver packages

mongo/integration/unified/unified_spec_runner.go, testdata/index-management/createSearchIndex.json, testdata/index-management/createSearchIndex.yml, testdata/index-management/createSearchIndexes.json, testdata/index-management/createSearchIndexes.yml, testdata/index-management/dropSearchIndex.json, testdata/index-management/dropSearchIndex.yml, testdata/index-management/listSearchIndexes.json, testdata/index-management/listSearchIndexes.yml, testdata/index-management/searchIndexIgnoresReadWriteConcern.json, testdata/index-management/searchIndexIgnoresReadWriteConcern.yml, testdata/index-management/updateSearchIndex.json, testdata/index-management/updateSearchIndex.yml
GODRIVER-3074
Sync Index Management tests to this commit to resolve test failures on MongoDB server 7.3.0 latest builds:
https://github.com/mongodb/specifications/commit/6943ba1ac430753f90340b042f0022b61bc0b041
=> GODRIVER-3074 Sync index management tests

.evergreen/config.yml
GODRIVER-3088
Remove redundant code that interfered with serverless startup.
crypt_shared is already downloaded in the drivers-tools script, so we don't need to do it here.
=> GODRIVER-3088 Fix serverless binary handling

bson/doc.go, bson/encoder_example_test.go
GODRIVER-3071
Update documentation for when the Go Driver will marshal Go integer values (int, int8, int16, int32, int64, uint, uint8, uint16, uint32, or uint64) as the minimum BSON int size (either 32 or 64 bits) that can represent the integer value.
A user submitted [this](https://www.mongodb.com/community/forums/t/mongo-go-driver-uint-always-marshals-to-bson-int64/257633) community issue describing how the Go Driver does not work as described in the following documentation:
> uint, uint32, and uint64 marshal to a BSON int32 if the value is between math.MinInt32 and math.MaxInt32, inclusive, and BSON int64 otherwise.
The logic for this, added in [GODRIVER-1358](https://jira.mongodb.org/browse/GODRIVER-1358), is contradictory. The default case for the "min int" condition in the UintCodec …
=> GODRIVER-3071 Correct uint Encoding BSON Documentation

bson/encoder_example_test.go
Fix the build failure:
```
bson/encoder_example_test.go:251:14: assignment mismatch: 2 variables but bson.NewEncoder returns 1 value
```
Code introduced in https://github.com/mongodb/mongo-go-driver/pull/1516 does not build with the updated `bson.Encoder` API.
=> Fix encoder_example_test.go build.

.pre-commit-config.yaml, docs/CONTRIBUTING.md
[GODRIVER-3089](https://jira.mongodb.org/browse/GODRIVER-3089)
Adds link checks for our Markdown representation.
Ensure we aren't pointing to dead links.
=> GODRIVER-3089 Add link checkers for repository

mongo/description/selector_test.go, mongo/description/server_selector.go
Optimize allocations of Server slices during writes.
On one of my services this function allocates 295 GBs over several days.
This is very similar to #1107 #1108 #1111. NB: one of these optimizations was reverted for correctness - 26e6c8ac9da113e7e4398588bd9ffa42cdc4e2ea I used similar here, but cannot judge wether it may be used here.
=> GODRIVER-3108 Optimize writeServerSelector

mongo/integration/client_side_encryption_prose_test.go
GODRIVER-2934
Add list of possible OS and Go dependent errors that can occur when timing out an HTTP client. Further investigation as to why there are suddenly noticeable differences needs to be done as part of the continuing work for 2934.
`TestClientSideEncryptionProse/18._Azure_IMDS_Credentials/Case_6:_Slow_Response` started failing as of https://github.com/mongodb-labs/drivers-evergreen-tools/commit/4393c2873d25dceaacd9ec27278d3b795e82c933 . These failures are independent of the Go implementation https://github.com/mongodb/mongo-go-driver/commit/a5a237e07ac14b2e75337bbb9be5b4fc5b97056c as they are also occurring on master, which does not yet have this change.
=> GDORIVER-2934 Add list of possible OS and Go dep errors to case 6

bson/primitive/decimal.go
In bson/primitive/decimal.go around line 167, the following if-else branches contain the same logic, and should be combined:
```go
if high == 0 && low == 0 && exp == 0 {
if posSign {
return new(big.Int), 0, nil
}
return new(big.Int), 0, nil
```
 ## Background & Motivation
Make the code more readable and robust
=> GODRIVER-3111 Combine the identical if-else branches in bson/primitive/decimal.go

.evergreen/config.yml
GODRIVER-3117
Ensure secrets are not logged in Evergreen
Ensure we do not accidentally print secrets in Evergreen logs.
=> GODRIVER-3117 Ensure secrets are not logged in Evergreen #1542

internal/integration/gridfs_test.go, internal/integration/unified/entity.go, internal/integration/unified_spec_test.go, mongo/database.go, mongo/gridfs_bucket_test.go, mongo/gridfs_test.go
Remove the unused error returned by `Database.GridFSBucket`.
The `Database.GridFSBucket` method currently returns an error that is never used. That error is also unconventional based on the existing pattern of the chainabe `Database` and `Collection` methods, which don't return errors. Similar to the way users can write
```go
coll := client.Database().Collection()
```
they should also be able to write
```go
bucket := client.Database().GridFSBucket()
```
=> Remove unnecessary error from GridFSBucket method.

.evergreen/config.yml
GODRIVER-3116 
Ensure secrets are not logged in Evergreen
Ensure we do not accidentally print secrets in Evergreen logs.
=> GODRIVER-3116 Ensure secrets are not logged in Evergreen

internal/integration/sdam_prose_test.go
GODRIVER-3036
This RP adds a prose test to ensure that `ServerHeartbeatStartedEvent` is emitted before the monitoring connection is established.
Heartbeat Tests: https://github.com/mongodb/specifications/tree/master/source/server-discovery-and-monitoring/tests#heartbeat-tests
=> GODRIVER-3036 Add prose test for ServerHeartbeatStartedEvent.

.evergreen/config.yml
GODRIVER-3114
Ensure secrets are not logged in Evergreen
Ensure we do not accidentally print secrets in Evergreen logs.
=> GODRIVER-3114 Ensure secrets are not logged in Evergreen

internal/integtest/integtest.go, mongo/integration/initial_dns_seedlist_discovery_test.go, mongo/integration/mtest/global_state.go, mongo/integration/mtest/setup.go, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/connstring/connstring_spec_test.go, x/mongo/driver/integration/main_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
Cherry-pick of https://github.com/mongodb/mongo-go-driver/pull/1521 to v1.
=> GODRIVER-3092 Fix UNIX socket in URL parsing.

internal/test/compilecheck/go.mod, internal/test/compilecheck/go.sum
GODRIVER-3082
The dependabot PRs to resolve the Terrapin CVE issue threw the go.mod file for the compilecheck package off.
=> GODRIVER-3082 go mod tidy compilecheck package

bson/bsoncodec/array_codec.go, bson/bsoncodec/byte_slice_codec.go, bson/bsoncodec/empty_interface_codec.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/pointer_codec.go, bson/bsoncodec/slice_codec.go, bson/bsoncodec/string_codec.go, bson/bsoncodec/struct_codec.go, bson/bsoncodec/time_codec.go, bson/bsoncodec/uint_codec.go
[GODRIVER-2886](https://jira.mongodb.org/browse/GODRIVER-2886)
Provide more detailed deprecation notes with references to replacement functionality and code examples for the deprecated BSON codecs.
Based on feedback on https://github.com/mongodb/mongo-go-driver/pull/1269, some users are confused about what to use to configure BSON encode/decode behavior instead of the deprecated BSON codec types. We should rewrite and expand the deprecation notes to reference specific replacement types or fields and provide some example code.
=> GODRIVER-2886 Provide more detailed deprecation notes for BSON codecs.

event/monitoring.go, internal/eventtest/eventtest.go, mongo/integration/unified/client_entity.go, mongo/integration/unified/entity.go, mongo/integration/unified/event_verification.go, mongo/integration/unified/testrunner_operation.go, mongo/integration/unified/unified_spec_runner.go, testdata/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.json, testdata/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.yml, testdata/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.json, testdata/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.yml, testdata/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.json, testdata/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.yml, testdata/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.json, testdata/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.yml, x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_generation_counter.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
Cherry-pick of https://github.com/mongodb/mongo-go-driver/pull/1423 to v1.
=> GODRIVER-2335 Preemptively cancel in progress operations when SDAM heartbeats timeout.

.evergreen/config.yml
DEVPROD-3871
Use `teardown_task` when there is one function/command.
The `teardown_group` is currently not run if there is only one function/command.
=> DEVPROD-3871 Use teardown_task when there is one function/command

bson/marshal.go
GODRIVER-2976
Re-add bufPool to `Marshal`.
The [PR #1410](https://github.com/mongodb/mongo-go-driver/pull/1410/files#diff-fc67ccfcf8fb7020e05412e10e0f43e715369aab368160f6255c4fdfe1a4470dL146) removed some of the buffer reuse optimizations
=> GODRIVER-2976 Re-add Marshal optimizations.

.evergreen/config.yml, .github/reviewers.txt, docs/CODEOWNERS
GODRIVER-3148
Auto-assign PR reviewer without pinging the whole team.
N/A
=> GODRIVER-3148 Use GitHub App to Auto Assign Reviewer

Dockerfile
[GODRIVER-3150](https://jira.mongodb.org/browse/GODRIVER-3150)
Make Dockerfile more robust.
Prevent intermittent connection errors to the golang PPA.
=> GODRIVER-3150 Make Docker Test More Robust

mongo/writeconcern/writeconcern.go
PR fixes typo in WriteConcern documentation.
Wrong description can be seen [here](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.14.0/mongo/writeconcern#WriteConcern:~:text=A%20WriteConcern%20defines%20a%20MongoDB%20read%20concern).
=> Fix typo within WriteConcern docs

event/monitoring.go, testdata/connection-monitoring-and-pooling/logging/connection-logging.json, testdata/connection-monitoring-and-pooling/logging/connection-logging.yml, testdata/connection-monitoring-and-pooling/logging/connection-pool-options.json, testdata/connection-monitoring-and-pooling/logging/connection-pool-options.yml, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_test.go
[GODRIVER-2910](https://jira.mongodb.org/browse/GODRIVER-2910)
* Add a `Duration` field to `event.PoolEvent`.
* Set the `Duration` on "ConnectionReady", "ConnectionCheckedOut", and "ConnectionCheckOutFailed" events.
Users have asked for the ability to measure the duration of some processes that the connection pool performs that can contribute to increased latency, increased errors, or other issues if not monitored and tuned correctly. Those requested measurements are:
* The checkout duration.
* The total amount of time a new connection took to establish (i.e. the time between requesting a new connection and the new connection being ready to send application operations on).
=> GODRIVER-2910 Add durations to connection pool events.

bson/raw_array.go, bson/raw_array_test.go, bson/raw_value.go, internal/bsonutil/bsonutil.go, internal/integration/change_stream_test.go, internal/integration/client_test.go, internal/integration/cmd_monitoring_helpers_test.go, internal/integration/crud_helpers_test.go, internal/integration/unified/bulkwrite_helpers.go, internal/integration/unified/client_operation_execution.go, internal/integration/unified/collection_operation_execution.go, internal/integration/unified/crud_helpers.go, internal/integration/unified/database_operation_execution.go, mongo/bson_helpers_test.go
GODRIVER-1639
Copy the unstable bsoncore Array methods to the stable bson library, in the style of `bson.Raw`.
Make the lookup logic less awkward for arrays in the stable lib. Consider the following example:
```
{
a: [{x: 1}, {y: 2},
}
```
Currently the lookup would be `doc.Lookup("a", "1", "y")`, now a user could use 
```
doc.Lookup("a").Array()[1].Document()["y"]`
```
=> GODRIVER-1639 Add RawArray to bson lib

mongo/integration/client_side_encryption_prose_test.go
GODRIVER-3123
Skip prose test for Range Protocol until QE Range Protocol V2 is Implemented.
The tests will fail until we implement the new feature.
=> GODRIVER-3123 Skip test until QE Range Protocol V2 is Implemented

mongo/integration/unified/unified_spec_runner.go, mongo/integration/unified_spec_test.go
GODRIVER-3137
GODRIVER-3034
Skip failing tests until we are able to implement the changes.
N/A
=> GODRIVER-3137 Skip failing transaction tests

internal/test/faas/awslambda/mongodb/bootstrap.go, mongo/database.go, mongo/integration/unified_runner_events_helper_test.go, x/mongo/driver/operation.go
=> chore: fix function names in comment

bson/raw_array_test.go, docs/common-issues.md
GODRIVER-2612
Fix the dead link caused by PR #1565. See the error at https://github.com/mongodb/mongo-go-driver/actions/runs/8729560532/job/23951727571
=> GODRIVER-2612 Docs updates.

x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/server.go
GODRIVER-3107
Fix the leaky `rttMonitor.runHellos()` routine when a disconnect occurs before a connection takes place.
There is a chance that `rttMonitor.disconnect()` is called before `rttMonitor.connect()` as [described](https://github.com/mongodb/mongo-go-driver/pull/1376/files#r1375049503) in PR #1376. In that case, the [condition](https://github.com/mongodb/mongo-go-driver/blob/d41a7cc214e8ed6c229d0a80245023300296ef4c/x/mongo/driver/topology/rtt_monitor.go#L100-L102) in `disconnect()` triggers a shortcut return which makes the `runHellos()` routine impossible to be [closed](https://github.com/mongodb/mongo-go-driver/blob/d41a7cc214e8ed6c229d0a80245023300296ef4c/x/mongo/driver/topology/rtt_monitor.go#L164).
=> GODRIVER-3107 Fix leaking rttMonitor.runHellos() routine.

docs/common-issues.md
GODRIVER-2287
An update for GODRIVER-2287 regarding the recent changes in the master branch. Also, a cherry-pick of #1607.
=> Docs updates.

.github/dependabot.yml
GODRIVER-3185
Set up dependabot config for gomod and GitHub Actions.
Better security posture for the repository.
=> GODRIVER-3185 Set up dependabot config

etc/compile_check.sh
Run `go mod tidy` before `go mod vendor` in the compile check script.
Github Dependabot PRs that update dependencies (e.g. https://github.com/mongodb/mongo-go-driver/pull/1619) fail the build check while running `etc/compile_check.sh` because of error:
```
+ GC=go
+ COMPILE_CHECK_DIR=internal/test/compilecheck
+ DEV_MIN_VERSION=1.19
+ compile_check
+ cd internal/test/compilecheck
+ go mod vendor
go: updates to go.mod needed; to update it:
go mod tidy
```
That is caused by running `go mod vendor` after changing some dependency version in the `go.mongodb.org/mongo-driver` module. We already run `go mod tidy` later in the script, but need to run it earlier to avoid the above error.
=> Run `go mod tidy` before vendoring in compilecheck.

etc/compile_check.sh, mongo/options/mongooptions.go, mongo/writeconcern/writeconcern.go, x/mongo/driver/auth/speculative_x509_test.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/wiremessage/wiremessage.go
=> chore: fix some comments and typos

mongo/collection.go
In case of context being nil, the Find method will panic.
It's a bug fix.
=> fix: check if context is nil before calling ctx.Deadline

.evergreen/config.yml
GODRIVER-3216
Run `go mod tidy` in the lambda test directory before running the test.
Keep the test in sync with the top level go mod files.
=> GODRIVER-3216 Run go mod tidy before lambda test

mongo/integration/client_side_encryption_prose_test.go
GODRIVER-3120
Add list of possible OS dependent errors that can occur when an unknown authority signs a certificate, see [here](https://cs.opensource.google/go/go/+/master:src/crypto/x509/platform_test.go;l=170?q=certificate%20signed%20by%20unknown%20authority&ss=go%2Fgo) for more details.
Example failure:
```
[2024/02/02 06:42:59.770] === RUN   TestClientSideEncryptionProse/11._kms_tls_options_tests/kmip
[2024/02/02 06:42:59.770]     client_side_encryption_prose_test.go:1631:
[2024/02/02 06:42:59.770]         	Error Trace:	/data/mci/a715128daf36f39e041d22b141c0582a/src/go.mongodb.org/mongo-driver/mongo/integration/client_side_encryption_prose_test.go:1631
[2024/02/02 06:42:59.770]         	            				/data/mci/a715128daf36f39e041d22b141c0582a/src/go.mongodb.org/mongo-driver/mongo/int …
```
=> GODRIVER-3120 Add list of possible OS errors to case 11

.evergreen/config.yml, etc/run-serverless-test.sh, mongo/integration/unified/unified_spec_runner.go, testdata/load-balancers/sdam-error-handling.json, testdata/load-balancers/sdam-error-handling.yml
[GODRIVER-3157](https://jira.mongodb.org/browse/GODRIVER-3157)
Skip the ["errors during the initial connection hello are ignored"](https://github.com/mongodb/specifications/blob/57bb0f2af7a46872f5d0457bd34032f3bdc8ab15/source/load-balancers/tests/sdam-error-handling.yml#L142) test case when running against Serverless Proxy, which doesn't support failpoints on "hello".
Also sync the latest [sdam-error-handling](https://github.com/mongodb/specifications/commits/master/source/load-balancers/tests/sdam-error-handling.yml) load balancer tests at https://github.com/mongodb/specifications/commit/008d2f5aab41dabced03e0860bab614c0f15ded5 to get the corrected test description (since the skipping logic is based on test description, so would stop skipping the test if we synced that test later). …
=> GODRIVER-3157 Skip Serverless Proxy test that requires failpoint on hello.

testdata/crud/unified/aggregate-write-readPreference.json, testdata/crud/unified/aggregate-write-readPreference.yml, testdata/crud/unified/db-aggregate-write-readPreference.json, testdata/crud/unified/db-aggregate-write-readPreference.yml
GODRIVER-3218 
Limit the two tests to server versions less than 8.0 until upstream ticket is addressed.
=> GODRIVER-3218 Skip Aggregation with  Crud Tests on 8.0+

internal/integration/client_side_encryption_test.go, internal/integration/index_view_test.go, mongo/index_view.go
GODRIVER-3038
Add FLE support to IndexView.List and IndexView.Crypt
=> GODRIVER-3038 Apply CSE to IndexView operations

internal/integration/mtest/mongotest.go, mongo/collection.go, mongo/gridfs_bucket.go
GODRIVER-3023
Remove unused error from the `collection.Clone` function signature
=> GODRIVER-3023 Remove unused error from Clone function signature

mongo/integration/search_index_prose_test.go, mongo/integration/unified/collection_operation_execution.go, mongo/options/searchindexoptions.go, mongo/search_index_view.go, testdata/index-management/createSearchIndex.json, testdata/index-management/createSearchIndex.yml, testdata/index-management/createSearchIndexes.json, testdata/index-management/createSearchIndexes.yml
GODRIVER-3125
Add the ability to pick the search index type when creating a new search index.
Drivers must support use of the type field when creating search indexes. Creating a vector search index requires specifying type=vectorSearch.
=> GODRIVER-3125 Allow to set search index type

testdata/client-side-operations-timeout/command-execution.json, testdata/client-side-operations-timeout/command-execution.yml
GODRIVER-3106
A patch to the `maxTimeMS`.
Will follow up with a change to the upstream tests.
=> GODRIVER-3106 Increase the `maxTimeMS` to temporarily fix the test failure.

x/mongo/driver/operation.go, x/mongo/driver/wiremessage/wiremessage.go, x/mongo/driver/wiremessage/wiremessage_test.go
[GODRIVER-3240](https://jira.mongodb.org/browse/GODRIVER-3240)
* Use functions from the `"encoding/binary"` package instead of custom bit-shifting logic to convert between binary and integer values in the `wiremessage` package.
* Add unit tests for the modified `wiremessage` functions.
=> GODRIVER-3240 Replace all bit-shifting in wiremessage with encoding/binary calls.

x/mongo/driver/operation.go, x/mongo/driver/wiremessage/wiremessage.go, x/mongo/driver/wiremessage/wiremessage_test.go
GODRIVER-3240
(cherry picked from commit ab38b7405916e6e9fdce6beffafb31293dfb952b)
=> GODRIVER-3240 [v1] Replace all bit-shifting in wiremessage with encoding/binary calls

mongo/integration/csot_test.go, x/mongo/driver/operation.go
[GODRIVER-3217](https://jira.mongodb.org/browse/GODRIVER-3217)
If `maxTimeMS` is specified on a `Find` or `Aggregate` operation, always use it to set `maxTimeMS` on the command, even if CSOT is enabled.
https://github.com/mongodb/mongo-go-driver/issues/1589 enabled sending an automatically calculated `maxTimeMS` with (almost) every command when CSOT is enabled. However, it doesn't send `maxTimeMS` on `Find` and `Aggregate` commands because it also sets a server-side lifetime on the cursor created by the command, which is surprising to many users. An unintended side effect of that change is that `maxTimeMS` is ignored for `Find` and `Aggregate` commands, meaning that there is no currently no way to set `maxTimeMS` on a `Find` or `Aggregate` when CSOT is enabled. We want to allow users to …
=> GODRIVER-3217 Use the manually-specified maxTimeMS on Find and Aggregate if it would be ommitted by CSOT

sbom.json
GODRIVER-3187
Add SBOM-lite file to track bundled third party dependencies (there are none).
Part of SSDLC conformance.
=> GODRIVER-3187 Add SBOM lite file

.github/workflows/codeql.yml
[GODRIVER-3245](https://jira.mongodb.org/browse/GODRIVER-3245)
Use a custom CodeQL workflow.
The current CodeQL autobuild setup reports build failures. Try using a custom workflow to fix the build failures.
=> GODRIVER-3245 Use a custom CodeQL workflow.

.github/workflows/release.yml
GODRIVER-3229
Add workflow to create a signed tag and draft release with attached SBOM file.
SSDLC Compliance.  Example run: https://github.com/blink1073/mongo-go-driver/actions/runs/9508933321
=> GODRIVER-3229 Add release workflow

.github/workflows/codeql.yml
Cherry-pick of #1674 from v1 to master
=> GODRIVER-3245 [master] Use a custom CodeQL workflow.

x/mongo/driver/compression.go
Cherry-pick of #1577 from v1 to master
=> GODRIVER-3132 [master] Use dst buf pool for zstd encoding.

bson/raw_value.go
[GODRIVER-3206](https://jira.mongodb.org/browse/GODRIVER-3206)
Deprecate `RawValue.UnmarshalWithContext`.
We want to remove the DecodeContext from all BSON unmarshal APIs (it should only be used in the ValueEncoder/ValueDecoder APIs). Deprecate them in the v1.x API.
=> GODRIVER-3206 Deprecate RawValue.UnmarshalWithContext

bson/default_value_decoders.go, bson/default_value_encoders.go, bson/default_value_encoders_test.go, bson/marshal.go, bson/marshal_value_cases_test.go, bson/primitive_codecs_test.go, bson/unmarshal.go, mongo/mongo.go, mongo/mongo_test.go
GODRIVER-2866
Update method signatures of `bson.ValueMarshaler`/`bson.ValueUnmarshaler` to only use basic types.
=> GODRIVER-2866 Update method signatures of `bson.ValueMarshaler`/`bson.ValueUnmarshaler` to only use basic types.

bson/registry.go
[GODRIVER-3227](https://jira.mongodb.org/browse/GODRIVER-3227)
Deprecate `bson.DefaultRegistry`.
Currently it's possible to change the behavior of BSON encoding and decoding by modifying [bson.DefaultRegistry](https://pkg.go.dev/go.mongodb.org/mongo-driver/bson#pkg-variables). That behavior is extremely difficult to test and is easy to break unexpectedly. There are already APIs for setting registries, both for BSON encoders/decoders and for a mongo.Client. We should direct all users to modify BSON registries using those official configurations to prevent unintended behavior regressions when modifying how BSON registries are configured.
=> GODRIVER-3227 Deprecate bson.DefaultRegistry

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/uint_codec.go, bson/bsonrw/extjson_wrappers.go, bson/bsonrw/value_reader.go, cmd/testatlas/atlas_test.go, etc/run-atlas-test.sh, internal/logger/io_sink.go, mongo/options/clientoptions.go, x/bsonx/bsoncore/bsoncore.go
GODRIVER-3240
- Use functions from the "encoding/binary" package to replace bit-shifting logic as a follow-up of #1646.
- Update size check for integer conversions.
- Add allocation size check.
- Convert atlas test to a gotest.
=> GODRIVER-3240 Code hardening.

.github/workflows/release.yml
GODRIVER-3052
Update silk project environment variable.
The Silk integration runs nightly, so we need to use the previous project.  There have been no source code changes.
=> GODRIVER-3052 Update release environment variables

bson/default_value_decoders.go, bson/extjson_wrappers.go, bson/uint_codec.go, bson/value_reader.go, etc/run-atlas-test.sh, internal/cmd/testatlas/atlas_test.go, internal/logger/io_sink.go, mongo/options/clientoptions.go, mongo/writeconcern/writeconcern.go, x/bsonx/bsoncore/bsoncore.go
GODRIVER-3260
Forward-port of all of the changes in #1684 except the ones to `default_value_decoders.go`, since it did not cherry-pick cleanly.
SSDLC compliance.
=> GODRIVER-3260 [master] Code hardening

.evergreen/config.yml
Remove 8.0 from the merge / waterfall build.
It is unnecessary to define 8.0 in both the waterfall and pullrequest build, it results in 8.0 being run twice in the waterfall:
Example: https://spruce.mongodb.com/version/mongo_go_driver_v1_ad124427ab0ffabd0f7367dcd540feb6e171df4f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Remove 8.0 from windows waterfall build

x/mongo/driver/topology/fsm.go
GODRIVER-3256 
Bump the supported max wire version.
Support for MongoDB 8.0.
=> GODRIVER-3256 Bump maxWireVersion for MongoDB 8.0

internal/integration/database_test.go, internal/integration/index_view_test.go, mongo/database.go, mongo/index_view.go, mongo/results.go
GODRIVER-3252
Update `Database.ListCollectionSpecifications` and `IndexView.ListSpecifications` to return a slice of values.
The pointers confuse users because it’s unclear whether they can be nil.
=> GODRIVER-3252 Update `Database.ListCollectionSpecifications` and `IndexView.ListSpecifications` to return slice of values.

x/mongo/driver/topology/fsm.go
Cherry-pick of #1695 from v1 to master
=> GODRIVER-3256 [master] Bump maxWireVersion for MongoDB 8.0

mongo/index_view.go, mongo/integration/index_view_test.go
[GODRIVER-3277](https://jira.mongodb.org/browse/GODRIVER-3277)
The solution for [GODRIVER-2701](https://jira.mongodb.org/browse/GODRIVER-2701) adds a new method to the IndexView API called DropWithKey. The [standard API](https://github.com/mongodb/specifications/blob/master/source/index-management/index-management.md#standard-api) for dropOne overloads the function signature to include a key option.
This PR renames DropWithKey to DropOneWithKey before releasing 1.17 to follow the spec as best as possible.
=> GODRIVER-3277 Rename DropWithKey to DropOneWithKey

internal/integration/collection_test.go
GODRIVER-2821
Remove check for result from Drop in the collection tests.
We removed the result type from DDL commands in [GODRIVER-961](https://jira.mongodb.org/browse/GODRIVER-961) and [GODRIVER-3220](https://jira.mongodb.org/browse/GODRIVER-3220).
=> GODRIVER-2821 Remove result check from Drop

.evergreen/config.yml, etc/run-serverless-test.sh, mongo/integration/unified/unified_spec_runner.go
GODRIVER-3272
Remove the tests added by [DRIVERS-2648](https://jira.mongodb.org/browse/DRIVERS-2648).
=> GODRIVER-3272 Remove Serverless Proxy Incremental Rollout Tests

mongo/collection.go
Remove debugging Println from `collection.find` accidentally added in https://github.com/mongodb/mongo-go-driver/pull/1678.
=> Remove debugging Println from collection.find

mongo/integration/mtest/mongotest.go
=> GODRIVER-3292 Pass context to custom mtest monitor

.evergreen/config.yml, internal/cmd/testoidcauth/main.go, x/mongo/driver/auth/oidc.go
GODRIVER-2806
Implements automatic gcp token acquisition machine callback function with spec tests
Needed by OIDC epic
=> GODRIVER-2806 [master] Implement automatic GCP token acquisition (#1708)

mongo/integration/mtest/mongotest.go
Cherry-pick of #1724 from v1 to release/1.16
=> GODRIVER-3292 [release/1.16] Pass context to custom mtest monitor

internal/cmd/testoidcauth/main.go, x/mongo/driver/auth/internal/gssapi/gss.go, x/mongo/driver/auth/internal/gssapi/sspi.go, x/mongo/driver/auth/mongodbaws.go, x/mongo/driver/auth/oidc.go, x/mongo/driver/auth/oidc_test.go, x/mongo/driver/auth/plain.go, x/mongo/driver/auth/sasl.go, x/mongo/driver/auth/scram.go
GODRIVER-3246
Implements OIDC Human Flow
Needed for OIDC epic
=> GODRIVER-3246 [master] Support human flow for OIDC (#1713)

bson/doc.go
[GODRIVER-3138](https://jira.mongodb.org/browse/GODRIVER-3138)
Apply suggested changes to the `omitempty` BSON struct tag documentation from Preston's comment [here](https://jira.mongodb.org/browse/GODRIVER-3138?focusedCommentId=6128581&focusedId=6128581&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6128581).
=> GODRIVER-3138 Improve omitempty tag documentation.

mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/auth/oidc.go, x/mongo/driver/connstring/connstring.go
GODRIVER-3249
Add configuration errors for all malformed configuration for the OIDC authentication mechanism. Some of these are redundant with errors thrown by the OIDC code itself, but these should occur before that point. I think double checking is fine.
OIDC epic
=> GODRIVER-3249 [master] Handle all possible OIDC configuration errors

internal/integration/sdam_prose_test.go, x/mongo/driver/topology/server.go
[GODRIVER-3255](https://jira.mongodb.org/browse/GODRIVER-3255)
Adds test from #1720 to master to ensure compliance with heartbeat specifications.
=> GODRIVER-3255 [master] Await heartbeat checks upto freq when polling

.evergreen/config.yml
[GODRIVER-3301](https://jira.mongodb.org/browse/GODRIVER-3301)
Fix Atlas Data Lake Startup Failure by avoiding changing the environment before logging in to docker.
=> GODRIVER-3301 Fix Atlas Data Lake Startup Failure

x/mongo/driver/wiremessage/wiremessage.go
GODRIVER-3303
This PR fixes out of bounds error and following unwanted panic in case of corrupted message length.
=> GODRIVER-3303 Prevent out of bounds panic with length value

docs/CONTRIBUTING.md, etc/cherry-picker.sh
GODRIVER-3300
Clean up cherry-picker script and allow setting the target branch.
=> GODRIVER-3300 Clean up cherry-picker script

internal/cmd/testoidcauth/main.go
Cherry-pick of #1747 from v1 to master
=> [master] chore: fix some comments

x/mongo/driver/operation_test.go
Remove unused function param to fix linter failure.
=> Remove unused function param to fix linter failure.

.evergreen/config.yml, cmd/testoidcauth/main.go, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/auth/oidc.go
GODRIVER-3149
This cleans up a few things that changed in the spec during implementation and adds the 3 tests that were missing from previous tickets
OIDC epic
=> GODRIVER-3149: OIDC Spec Cleanup

.evergreen/config.yml, docs/CONTRIBUTING.md
GODRIVER-3314
Make it easier to backport PRs by making the magic GitHub comment: `drivers-pr-bot please backport to {target_branch}`.
Less friction when backporting PRs to release branches.
=> GODRIVER-3314 Add PR Cherrypicker Task

internal/integration/mtest/wiremessage_helpers.go, x/mongo/driver/operation.go, x/mongo/driver/wiremessage/wiremessage.go, x/mongo/driver/wiremessage/wiremessage_test.go
Cherry-pick of #1753 to master
=> GODRIVER-3303 [master] Remove redundant code; Add test cases.

testdata/server-discovery-and-monitoring/rs/too_old.json, testdata/server-discovery-and-monitoring/rs/too_old.yml, testdata/server-discovery-and-monitoring/sharded/too_new.json, testdata/server-discovery-and-monitoring/sharded/too_new.yml
[GODRIVER-2993](https://jira.mongodb.org/browse/GODRIVER-2993)
=> GODRIVER-2993 SDAM unit test sharded/too_new needs to defined wireVersions for host b

.evergreen/config.yml
GODRIVER-3314
Fix cherry-pick script invocation.
=> GODRIVER-3314 Fix backport script invocation

testdata/client-side-encryption/legacy/fle2v2-CreateCollection-OldServer.json, testdata/client-side-encryption/legacy/fle2v2-CreateCollection-OldServer.yml, testdata/client-side-encryption/legacy/fle2v2-CreateCollection.json, testdata/client-side-encryption/legacy/fle2v2-CreateCollection.yml, testdata/client-side-encryption/legacy/fle2v2-MissingKey.json, testdata/client-side-encryption/legacy/fle2v2-MissingKey.yml, testdata/client-side-encryption/legacy/fle2v2-Rangev2-Compact.json, testdata/client-side-encryption/legacy/fle2v2-Rangev2-Compact.yml
GODRIVER-3195
Sync to updated QE 2 tests to fix failures on serverless tests.
Passing build: https://spruce.mongodb.com/version/66d8b1a11a39fb00071290fd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> GODRIVER-3195 Sync updated QE Range tests

docs/migration-2.0.md
WRITING-26459
Fix pre-commit check.
=> WRITING-26459 Fix link in migration guide

bson/extjson_parser.go, bson/extjson_reader.go, bson/unmarshal.go
[GODRIVER-963](https://jira.mongodb.org/browse/GODRIVER-963)
"The canonical parameter in UnmarshalExtJSON not forcing strictly canonical or non-canonical unmarshaling, but instead disabling unmarshaling non-canonical format when canonical=true. If canonical=false in UnmarshalExtJSON, it will unmarshal canonical or "relaxed" extended JSON."
Followed Matt's comment to rename canonical to canonicalOnly and update the documentation to describe the above behavior.
=> GODRIVER-963 canonical parameter is not respected in UnmarshalExtJSON

internal/codecutil/encoding.go, internal/codecutil/encoding_test.go, internal/integration/client_test.go, mongo/cursor.go, mongo/cursor_test.go, mongo/mongo.go, mongo/mongo_test.go, mongo/options/clientoptions.go, x/mongo/driver/batch_cursor.go
GODRIVER-3326
- Add `ObjectIDAsHexString` to `BSONOptions` and enable it to set the `bson.Decoder`.
- Set up `TestGetDecoder` and `TestGetEncoder` to guarantee:
- Each `bson.Decoder`/`bson.Encoder` config method has a corresponding field in `BSONOptions`.
- `getDecoder()`/`getEncoder()` calls the corresponding `bson.Decoder`/`bson.Encoder` config methods according to `BSONOptions` fields.
- Remove the never-used error return from `EncoderFn`.
=> GODRIVER-3326 Add `ObjectIDAsHexString` to `BSONOptions`.

mongo/client.go, mongo/client_test.go, mongo/options/clientoptions.go, x/mongo/driver/auth/auth.go, x/mongo/driver/auth/gssapi.go, x/mongo/driver/auth/mongodbaws.go, x/mongo/driver/auth/mongodbcr.go, x/mongo/driver/auth/oidc.go, x/mongo/driver/auth/plain.go, x/mongo/driver/auth/plain_test.go, x/mongo/driver/auth/scram.go, x/mongo/driver/auth/x509.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/topology/topology_options.go, x/mongo/driver/topology/topology_options_test.go
[GODRIVER-3215](https://jira.mongodb.org/browse/GODRIVER-3215)
* Move logic for creating an authenticator from `ClientOptions` to a new function `topology.NewAuthenticator`. Use it everywhere that needs to create an authenticator from `ClientOptions`.
* Requires moving `convertOIDCArgs` into the `topology` package.
* Move the logic for setting the default auth source into each individual authenticator type.
* The current logic for setting the default auth source appears to be in `topology.NewConfigWithAuthenticator`, but actually has no effect currently, so no default auth sources are being set.
* Update PLAIN authenticator to support auth sources other than "$external".
* Using the database name from the connection string as the auth source is currently supported in …
=> GODRIVER-3215 Fix default auth source for auth specified via ClientOptions [master]

.pre-commit-config.yaml, mongo/client_examples_test.go
GODRIVER-2758
Add documentation examples for OIDC using (hopefully) a style consistent with go driver's other documentation examples
OIDC epic
=> GODRIVER-2758: Add documentation examples [master]

.evergreen/config.yml, mongo/options/clientoptions_test.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/connstring/connstring_test.go
[GODRIVER-3331](https://jira.mongodb.org/browse/GODRIVER-3331)
Override the default auth source from `admin` to `$external` where appropriate.
SRV connections from Atlas contain a record of `authSource=admin`, which we need to override for the auth mechanisms that require `$external` as the auth source.
=> GODRIVER-3331 Fix default authSource for SRV connections [master]

.evergreen/config.yml
GODRIVER-3335
Prefer to use the -small variants for all static checks and bot runs, to ensure they run quickly. The large variants tend to be in contention with the server evergreen tasks.
=> GODRIVER-3335 Use small evergreen variants for static checks and bot runs

mongo/client_examples_test.go
Fix the example for OIDC custom callback to not use the gcp env
=> Remove GCP from supplied callback example

.evergreen/config.yml
GODRIVER-3312
Use temporary credentials for S3 uploads of test assets and use AWS vault secrets for Azure KMS tests.
Remove usage of evergreen variables for the master branch.
=> GODRIVER-3312 Remove remaining usage of Evergreen Secrets

.evergreen/config.yml
GODRIVER-3312 
Get Azure and GCP KMS secrets from the AWS vault.
Remove evergreen variables for the v1 branch.
=> GODRIVER-3312 Use remaining test secrets from the vault [v1]

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_test.go
(cherry picked from commit be25b9a26aff54fe27210f86d00db5d573452643)
GODRIVER-3302
=> GODRIVER-3302 Handle malformatted message length properly. (#1758) [master]

.evergreen/config.yml, etc/run-enterprise-gssapi-test.sh
[GODRIVER-3342](https://jira.mongodb.org/browse/GODRIVER-3342)
Upgrade to MacOS-14 Hosts on Evergreen.
Migrate to supported hosts.
=> GODRIVER-3342 Update MacOS Hosts for Evergreen Host Migration

mongo/client.go, mongo/client_test.go, mongo/collection_test.go, mongo/database_test.go
[GODRIVER-3332](https://jira.mongodb.org/browse/GODRIVER-3332)
=> GODRIVER-3332 Returning ErrClientDisconnected when sessionPool is null is unecessary

mongo/client_encryption_test.go
Remove repeat line from client_encryption_test.go that was left from GODRIVER-2529
=> GODRIVER-2529 Remove repeat test from client_encryption_test.go

.pre-commit-config.yaml, Taskfile.yml, bson/raw_array_test.go, internal/integration/unified/event_verification.go, mongo/client.go
`golangci-lint` versions < 1.60.1 are not 1.23 compatible. See issue #[4662](https://github.com/golangci/golangci-lint/issues/4662) for more information.
Devs should not be limited to the 1.22 minimum test version.
=> GODRIVER-3357 Bump golangci-lint for 1.23 compatibility

mongo/cursor.go, mongo/cursor_test.go
GODRIVER-2589
Clarify the `*Cursor.All()` behavior in the comment that a nil slice pointer won't be modified in the case of no results.
The current behavior is a feature rather than a bug as long as we clarify it in the documentation.
Currently, in the case of no results:
1. if the pointer is nil, it will be left as is.
2. if the pointer points to an initialized slice, the slice will be set to empty.
The caller controls the received type either way.
Also, as mentioned in the [comment](https://jira.mongodb.org/browse/GODRIVER-2589?focusedCommentId=5793934#comment-5793934), users may have depended on the behavior.
**We need to merge the update to the master branch as well.**
=> GODRIVER-2589 Clarify `*Cursor.All()` behavior in comment.

.evergreen/config.yml
DEVPROD-10453
Use assume_role for s3 uploads.
Follow up from [GODRIVER-3312](https://jira.mongodb.org/browse/GODRIVER-3312).
=> DEVPROD-10453 Use assume_role for s3 uploads [v1]

internal/integration/crud_helpers_test.go, mongo/client.go, mongo/database.go, mongo/doc.go, mongo/errors.go, mongo/options/autoencryptionoptions.go, testdata/client-side-encryption/README.rst, x/mongo/driver/operation.go
[GODRIVER-2567](https://jira.mongodb.org/browse/GODRIVER-2567)
There is a distinct difference between Queryable Encryption and Client-Side Field Level Encryption made in the Server docs. Drivers must update their docs to reflect correct terminology as-needed.
Both features CSFLE and QE are nested under "In Use Encryption" rather than "Client Side Encryption".  Please verify and rename any documents to follow this convention.
=> GODRIVER-2567 CSFLE/QE Naming

mongo/cursor.go, mongo/cursor_test.go
GODRIVER-2589
cherry picked from commit 0178864b8e0a35218ceef12089e94ae3c98f9466
=> GODRIVER-2589 Clarify `*Cursor.All()` behavior in comment. (#1804)

.evergreen/config.yml
GODRIVER-3182
Update go dist version for backport task
Task requires Go 1.22+.
=> GODRIVER-3182 Update go dist version for backport task

.evergreen/config.yml, x/mongo/driver/connstring/connstring.go
GODRIVER-3358
Defer to the TXT record unless overridden by the connection string.
This is how the spec is written.  We updated the connection strings in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/502.
=> GODRIVER-3358 Do not override authSource from TXT record

internal/failpoint/failpoint.go, internal/integration/change_stream_test.go, internal/integration/client_test.go, internal/integration/crud_prose_test.go, internal/integration/csot_prose_test.go, internal/integration/csot_test.go, internal/integration/cursor_test.go, internal/integration/database_test.go, internal/integration/errors_test.go, internal/integration/index_view_test.go, internal/integration/mtest/global_state.go, internal/integration/mtest/mongotest.go, internal/integration/primary_stepdown_test.go, internal/integration/retryable_reads_prose_test.go, internal/integration/retryable_writes_prose_test.go, internal/integration/retryable_writes_spec_test.go, internal/integration/sdam_error_handling_test.go, internal/integration/sdam_prose_test.go, internal/integration/server_selection_prose_test.go, internal/integration/unified_spec_test.go
Move the `mtest.FailPoint` struct and the associated structs to a new internal package `internal/failpoint`.
Most fail points in Go Driver integration tests are defined using the `mtest.FailPoint` type. However, some integration tests, like `TestConvenientTransactions`, cannot use `mtest` because it creates an import cycle. We can move the `FailPoint` and associated structs to a separate internal package, allowing them to be used in any test package in the driver.
Note that the `SetFailPoint` function is intentionally not moved to the `internal/failpoint` package because that would require importing the `mongo` package, causing an import cycle in some cases.
=> Move fail point structs to an internal package.

mongo/cursor.go, mongo/cursor_test.go
Cherry-pick of #1804 to release/1.17
=> GODRIVER-2589 [release/1.17] Clarify `*Cursor.All()` behavior in comment.

docs/migration-2.0.md, internal/integration/collection_test.go, internal/integration/crud_helpers_test.go, internal/integration/crud_prose_test.go, internal/integration/unified/collection_operation_execution.go, internal/integration/unified/crud_helpers.go, mongo/bulk_write.go, mongo/collection.go, mongo/crud_examples_test.go, mongo/options/deleteoptions.go, mongo/options/updateoptions.go
GODRIVER-3339
- Separate the “UpdateOptions” struct into “UpdateManyOptions” and “UpdateOneOptions”.
- Separate the “DeleteOptions” struct into “DeleteManyOptions” and “DeleteOneOptions”.
For [DRIVERS-2822](https://jira.mongodb.org/browse/DRIVERS-2822), `sort` only applies to `UpdateOne`. The server throws an error if a `sort` exists in `UpdateMany`. Therefore, this PR proposes separating the options for `UpdateOne` and `UpdateMany`.
Although there is no immediate requirement yet, the “DeleteOptions” struct is also considered to be divided for future changes as it is shared by both “DeleteOne” and “DeleteMany” now.
=> GODRIVER-3339 Separate `Many` and `One` for `UpdateOptions` and `DeleteOptions`.

mongo/search_index_view.go
GODRIVER-3268
It may be unclear to users that search index operations are asynchronous, so we should document that behavior.
=> GODRIVER-3268 Document asynchronicity of creating search indexes

.evergreen/config.yml
GODRIVER-3366 
Ensure snappy tests are run in CI.
These tests were accidentally excluded at some point.
=> GODRIVER-3366 Ensure snappy tests are run in CI

etc/golangci-lint.sh
lint version not aligned with https://github.com/mongodb/mongo-go-driver/commit/9d4146089f65d51ee93db037945250ab14383e32
=> Bump lint go version to 1.22.8

.evergreen/config.yml, .evergreen/setup-system.sh, Taskfile.yml, etc/run-azurekms-test.sh, etc/run-gcpkms-test.sh, etc/run-mongodb-aws-test.sh, etc/run-oidc-remote-test.sh, etc/run_docker.sh, etc/setup-test.sh
GODRIVER-3367
Use subprocess.exec for remaining Evergreen functions
Follow evergreen best practices.
=> GODRIVER-3367 Use subprocess.exec for remaining Evergreen functions

x/mongo/driver/wiremessage/wiremessage.go
GODRIVER-3374
Support `ReadCompressedCompressedMessage` for the v1 lifetime.
Users may rely on this low-cost helper.
=> GODRIVER-3374 Add ReadCompressedCompressedMessage back to wiremessage API

.evergreen/config.yml, Taskfile.yml, etc/compile_check.sh
* Update `compile_check.sh` to use a "local" Go installation (i.e. `go install golang.org/dl/go[ver]@latest`) for checking the Go 1.18 build.
* Update the `build` Taskfile target to run all the build steps sequentially so the output is understandable.
The `go1.18-build` task currently doesn't actually use Go 1.18 to build. The `add_to_path` instruction is ineffective because the Taskfile is configured to load environment variables from a `.env` file. Instead, we should use a "local" Go 1.18 installation so we don't have to worry about overriding PATH.
=> Use a local Go 1.18 installation to check for minimum version support.

x/mongo/driver/topology/pool_test.go
Move top-level subtests in `TestPool` into separate test functions, keeping the inner subtests the same.
Deeply-nested subtests are difficult to read, run, and maintain.
Note: This PR is based on https://github.com/mongodb/mongo-go-driver/pull/1860, which should be merged first.
=>  Break up connection pool subtests into separate test funcs.

.pre-commit-config.yaml, Makefile, mongo/client.go, mongo/integration/unified/event_verification.go
Upgrade `golangci-lint` go v1.60.1.
Cherry-pick of #1823.
`golangci-lint@v1.59.1` panics when run with Go 1.22 and Go 1.23 in some cases.
=> Bump golangci-lint for 1.23 compatibility [v1]

Makefile, x/mongo/driver/topology/pool_test.go
Based on https://github.com/mongodb/mongo-go-driver/pull/1860
* Don't share the `err` variable in the goroutine closure (pool_test.go line 893) to prevent a data race.
* Enable the race detector in the `test-short` Taskfile target.
The race detector panics because of a data race in the "discards connections closed by the server side" connection pool test:
```
WARNING: DATA RACE
Read at 0x00c0005f4aa0 by goroutine 4142:
go.mongodb.org/mongo-driver/v2/x/mongo/driver/topology.TestPool_checkOut.func10.3()
/Users/matt.dale/work/mongo-go-driver/x/mongo/driver/topology/pool_test.go:897 +0x1b0
Previous write at 0x00c0005f4aa0 by goroutine 3796:
go.mongodb.org/mongo-driver/v2/x/mongo/driver/topology.TestPool_checkOut.func10()
/Users/matt.dale/work/mongo-go-driver/x/mongo/driver/topology/pool_test.g …
```
=> Fix data race in 'discard connections' pool test. [v1]

internal/integration/unified/collection_operation_execution.go, mongo/collection.go, mongo/options/distinctoptions.go, testdata/crud/unified/distinct-hint.json, testdata/crud/unified/distinct-hint.yml, x/mongo/driver/operation/distinct.go
[GODRIVER-3412](https://jira.mongodb.org/browse/GODRIVER-3412)
Add index hint support for `Distinct`.
=> GODRIVER-3412 Add index hint support for distinct command.

docs/migration-2.0.md
Add example usage for `ValueMarshaler`
=> Add examples to the marshaling updates in the migration guide

Dockerfile
GODRIVER-3438
Use artifactory for container image.
Dockerhub downloads are now rate-limited.
=> GODRIVER-3438 Use artifactory for container image

bson/decoder.go, bson/doc.go, bson/primitive.go, docs/migration-2.0.md, mongo/gridfs_download_stream.go, mongo/options/clientoptions.go, mongo/options/encryptoptions.go
GODRIVER-3420
Clarify docs and comments.
- Explicitly call out `bson.M` unmarshaling behavior changes.
- Update package names in comments.
=> GODRIVER-3420 Clarify docs and comments.

bson/decoder_test.go, bson/string_codec.go
GODRIVER-3425
Reference ObjectIdAsHexString decoder option in exception message.
=> GODRIVER-3425 Reference ObjectIdAsHexString decoder option in exception message.

internal/integration/collection_test.go, internal/integration/unified/collection_operation_execution.go, mongo/collection.go, mongo/options/findoptions.go
GODRIVER-3433
Restore the `SetOplogReplay`, which is still needed for 4.4 support.
Removed in PR #1398
=> GODRIVER-3433 Restore SetOplogReplay.

internal/integration/client_side_encryption_prose_test.go, mongo/options/autoencryptionoptions.go, mongo/options/clientencryptionoptions.go
[GODRIVER-3321](https://jira.mongodb.org/browse/GODRIVER-3321)
Immediately make a copy of the TLS config map in `ClientEncryptionOptionsBuilder.SetTLSConfig` and `AutoEncryptionOptionsBuilder.SetTLSConfig` to prevent the map values from changing before the option function is called.
Currently, if you modify the TLS config map passed to `ClientEncryptionOptionsBuilder.SetTLSConfig` or `AutoEncryptionOptionsBuilder.SetTLSConfig` before passing the options to `NewClientEncryption`, the TLS config map passed to `NewClientEncryption` will unexpectedly change. That's because the option function is a closure over the original map. Instead, we should make a copy of the map in the setter body and pass that copy into the option function.
=> GODRIVER-3321 Fix CSE SetTLSConfig option.

bson/default_value_decoders.go, bson/unmarshaling_cases_test.go
GODRIVER-3436
If the value reader is null, prevent `DefaultValueDecoders` from initializing a pointer to the zero value.
The current behavior will lead to unexpected results:
```go
ill instantiate a pointer field decoded from null data if the user defines a UnmarshalBSONValue. For example:
package main
import (
"fmt"
"go.mongodb.org/mongo-driver/v2/bson"
"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
)
type DBInt64 int64
type Product struct {
TotalForSell *DBInt64 `json:"total_for_sell" bson:"total_for_sell,omitempty"`
}
func (i *DBInt64) UnmarshalBSONValue(t bson.Type, value []byte) error {
return nil
}
func main() {
idx, doc := bsoncore.AppendDocumentStart(nil)
doc = bsoncore.AppendNullElement(doc, "total_for_sell")
doc, err := bsoncore.AppendDocumentEnd(doc, idx) …
```
=> GODRIVER-3434 Avoid initializing null data given custom decoder

bson/bsoncodec/default_value_decoders.go, bson/unmarshaling_cases_test.go
GODRIVER-3436
If the value reader is null, prevent `DefaultValueDecoders` from initializing a pointer to the zero value.
The current behavior will lead to unexpected results:
```go
ill instantiate a pointer field decoded from null data if the user defines a UnmarshalBSONValue. For example:
package main
import (
"fmt"
"go.mongodb.org/mongo-driver/bson"
"go.mongodb.org/mongo-driver/bson/bsontype"
"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
)
type DBInt64 int64
type Product struct {
TotalForSell *DBInt64 `json:"total_for_sell" bson:"total_for_sell,omitempty"`
}
func (i *DBInt64) UnmarshalBSONValue(t bsontype.Type, value []byte) error {
return nil
}
func main() {
idx, doc := bsoncore.AppendDocumentStart(nil)
doc = bsoncore.AppendNullElement(doc, "total_for_sell")
doc, err := …
```
=> GODRIVER-3436 Avoid initializing null data given custom decoder

docs/migration-2.0.md
GODRIVER-3443
Remove examples from the migration guide concerning clientOptions builder, which was removed from v2.
NA
=> GODRIVER-3443 Remove reference to clientOptions builder

docs/migration-2.0.md
`bson.M` and `bson.D` `String()` methods using decode into canonical extended JSON for their String representation. However, the migration guide says "relaxed".
=> Update guide to reflect that bson string methods are cannonical

docs/migration-2.0.md
GODRIVER-3443
Remove internal APIs in the migration guide.
=> GODRIVER-3443 Remove internal APIs in migration guide.

testdata/retryable-writes/unified/insertOne-serverErrors.json, testdata/retryable-writes/unified/insertOne-serverErrors.yml, x/mongo/driver/errors.go, x/mongo/driver/operation.go
GODRIVER-3032
For a pre-4.4 mongos response, we can trust that mongos will have already retried the operation if necessary. Drivers should not retry to avoid "excessive retrying".
Under similar circumstances, the specifications now clarify that drivers should not consider codes within writeErrors from a mongod or mongos response. Notably, the Go Driver does not currently do this.
From the comments on the related drivers ticket:
> Pre and post 4.4 mongos will retry on retryable codes within the writeConcernError field (it chooses to retry based on the "effective status" from a command response - [4.2 code](https://github.com/mongodb/mongo/blob/54e29d8dcc/src/mongo/s/client/shard.cpp#L127-L128) and [current master](https://github.com/mongodb/mongo/blob/146311aeb40f9ac573277f4ef2c234253075512 …
=> GODRIVER-3032 Don't retry writes on pre-4.4 mongos

mongo/options/clientoptions.go, mongo/options/clientoptions_test.go
GODRIVER-3452
Currently MergeClientOptions returns `nil` when given a single `nil` argument. This is unexpected behavior, this function should always return an object to avoid a check where used.
NA
=> GODRIVER-3452 MergeClientOptions returns object when given nil arguments

mongo/collection.go
* Return a `SingleResult` with an error if building options fails in `FindOne`.
=> Fix erroneous nil error return in FindOne.

bson/marshal_value_cases_test.go, bson/marshal_value_test.go, bson/unmarshal_value_test.go
[GODRIVER-3307](https://jira.mongodb.org/browse/GODRIVER-3307)
* Use keyed structs for all `MarshalValue` test cases to make them easier to read.
* Use only struct literals instead of functions to define the `MarshalValue` test cases.
* Don't use `Marshal` when testing `MarshalValue` to prevent bugs in `Marshal` from masking bugs in `MarshalValue`.
* Remove unnecessary subtest nesting in `TestMarshalValue`.
=> GODRIVER-3307 Simplify MarshalValue and UnmarshalValue test case setup.

mongo/errors.go, mongo/session.go, mongo/with_transactions_test.go
[GODRIVER-3298](https://jira.mongodb.org/browse/GODRIVER-3298)
* Use `errors.As` to check for retryability of errors returned from the `WithTransaction` callback.
Currently `WithTransaction` uses custom error unwrapping logic to check if an error returned by the callback should be retried. That unwrapping logic was not updated when support for join-able errors was added to the Go stdlib. Instead of maintaining custom error unwrapping logic, use `errors.As` to make sure the code continues to support future stdlib updates.
=> GODRIVER-3298 Handle joined errors correctly in WithTransaction.

.evergreen/config.yml, Taskfile.yml, etc/install-libmongocrypt.sh, internal/integration/client_side_encryption_prose_test.go, x/mongo/driver/crypt.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/mongocrypt_kms_context.go, x/mongo/driver/mongocrypt/mongocrypt_kms_context_not_enabled.go
GODRIVER-3168
Retry KMS requests on transient errors.
Changes described here: https://github.com/mongodb/libmongocrypt/blob/master/integrating.md#state-mongocrypt_ctx_need_kms
New tests: https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/tests/README.md#24-kms-retry-tests
=> GODRIVER-3168 Retry KMS requests on transient errors.

mongo/bulk_write.go, mongo/collection.go, mongo/integration/collection_test.go, mongo/options/bulkwriteoptions.go, mongo/options/findoptions.go, mongo/options/insertoptions.go, mongo/options/replaceoptions.go, mongo/options/updateoptions.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/insert.go, x/mongo/driver/operation/update.go
GODRIVER-3370
Add `bypassEmptyTsReplacement` option to:
- insertOne
- insertMany
- updateOne
- updateMany
- replaceOne
- findOneAndUpdate
- findOneAndReplace
- collection.bulkWrite
Correlated server ticket: SERVER-88750
=> GODRIVER-3370 Add bypassEmptyTsReplacement option.

internal/integration/unified/client_operation_execution.go, mongo/bulk_write_models.go, mongo/client_bulk_write.go, mongo/client_bulk_write_models.go, mongo/options/findoptions.go, mongo/options/gridfsoptions.go, mongo/options/replaceoptions.go, mongo/options/updateoptions.go, testdata/crud/unified/client-bulkWrite-replaceOne-sort.json, testdata/crud/unified/client-bulkWrite-replaceOne-sort.yml, testdata/crud/unified/client-bulkWrite-updateOne-sort.json, testdata/crud/unified/client-bulkWrite-updateOne-sort.yml
GODRIVER-3285
Allow sort option in `UpdateOne` and `RepleaceOne` in client bulk write.
Collection bulk write has been done in #1797
=> GODRIVER-3285 Allow sort option in client bulk write.

etc/run-fuzz.sh
GODRIVER-3448
From a similar issue described in the Go project (https://github.com/golang/go/issues/65434):
> This limits the throughput and resource consumption of the fuzz workers in the tests, which also reduces the likelihood of running out of address space in the fuzz coordinator during the test.
Limiting the number of CPU cores means fewer OS threads are available to execute the workers deployed by Go fuzzing.
=> GODRIVER-3448 Limit GOMAXPROCS for fuzz tests

bson/bsoncodec/default_value_decoders.go, bson/unmarshal.go, bson/unmarshal_value_test.go, bson/unmarshaling_cases_test.go
GODRIVER-3470
Ensure UnmarshalBSONValue is bypassed and the Go pointer is set to nil ONLY when the Go type is a pointer and the BSON value is null.
PR #1903 introduced logic where UnmarshalBSONValue() is not called for bson.TypeNull, which breaks applications that rely on this behavior for initializing fields.
=> GODRIVER-3470 Correct BSON unmarshaling logic for null values

bson/default_value_decoders.go, bson/unmarshal.go, bson/unmarshal_value_test.go, bson/unmarshaling_cases_test.go
Cherry-pick of https://github.com/mongodb/mongo-go-driver/commit/659342c5d8d8436dcfe7863026808d14505c225d to master
=> GODRIVER-3470 Correct BSON unmarshaling logic for null values (#1924) [master]

bson/bson_binary_vector_spec_test.go, testdata/bson-binary-vector/float32.json, testdata/bson-binary-vector/int8.json, testdata/bson-binary-vector/packed_bit.json
GODRIVER-3481
Sync up with updates at https://github.com/mongodb/specifications/commit/585b797c110b6709f81def6200b946b94c8d9c55
=> GODRIVER-3481 Improve JSON tests for Binary Vector Subtype.

testdata/load-balancers/non-lb-connection-establishment.json, testdata/load-balancers/non-lb-connection-establishment.yml
GODRIVER-3485
Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
This is intended to proactively avoid tests failure once drivers start testing 8.1 builds. See DRIVERS-3108. Drivers are not-yet testing 8.1 (see [slack](https://mongodb.slack.com/archives/C72LB5RPV/p1739884710850709)).
=> GODRIVER-3485 sync `non-lb-connection-establishment`

internal/integration/csot_prose_test.go, internal/integration/sdam_prose_test.go
Use the correct `mtest.T` instance inside subtests to make assertions.
Some subtests written using `mtest` use the `testing.T` from the outer test function when making assertions. That results in confusing test failures that don't directly indicate which subtest failed. See an example:
```
=== RUN   TestCSOTProse/8._server_selection/serverSelectionTimeoutMS_honored_for_server_selection_if_it's_lower_than_timeoutMS
=== NAME  TestCSOTProse
csot_prose_test.go:153: 
Error Trace:	/go.mongodb.org/mongo-driver/internal/integration/csot_prose_test.go:153
/go.mongodb.org/mongo-driver/internal/integration/mongotest.go:232
Error:      	Condition never satisfied
Test:       	TestCSOTProse
Messages:   	expected ping to fail within 150ms
```
That also corrupts the test failure info in Evergreen CI. The …
=> Fix use of testing.T instead of mtest.T in assertions in subtests.

.github/workflows/merge-up.yml
This PR adds a new GitHub Actions workflow to automatically merge changes up into newer branches. This changes the workflow in this repository: instead of merging all pull requests into the default branch and cherry-picking into older branches, pull request must now target the lowest branch they affect. Currently, this means that bug fixes would go into `release/1.17`, and new features go into `v2`.
Once a commit is pushed to a matching branch, the automation becomes active. The following details this process, assuming we pushed into the `release/v1.17` branch.
The first step is determining the branch to merge into. The action will consider these branch names in order:
- `release/1.18` (next minor branch matching `branchNamePattern`)
- `v1` (next minor branch matching …
=> Add GitHub Actions workflow for merge ups

bson/bsoncodec.go, bson/encoder.go, bson/encoder_test.go, bson/primitive_codecs_test.go, bson/struct_codec.go, bson/struct_codec_test.go, internal/integration/client_test.go, mongo/mongo.go, mongo/options/clientoptions.go
GODRIVER-3427
Add the "OmitEmpty" to both `Encoder` and `BSONOptions` so it can be enabled globally.
The global flag can be added without impacting any encoding behavior.
=> GODRIVER-3427 Add a global "omitempty" flag.

bson/bson_test.go, bson/bsonrw/extjson_writer.go
GODRIVER-3476
Escape in Regex Options to make it a valid JSON.
=> GODRIVER-3476 Escape for Regex Options.

.evergreen/config.yml, etc/run-oidc-remote-test.sh, etc/run-oidc-test.sh, internal/cmd/testoidcauth/main.go, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, testdata/auth/connection-string.json, testdata/auth/connection-string.yml, x/mongo/driver/auth/auth_spec_test.go, x/mongo/driver/auth/oidc.go
[GODRIVER-3175](https://jira.mongodb.org/browse/GODRIVER-3175)
* Support the "k8s" OIDC environment for AKS, EKS, and GKE.
* Update connection string validation for new OIDC connection string tests.
* Add tests for the "k8s" OIDC environment.
* Use the same Evergreen task group configuration for all OIDC task groups.
* Remove unnecessary `batchtime` config for other OIDC test tasks.
* Remove accidental duplication of OIDC options subtest in `TestClientOptions`.
From [DRIVERS-2882](https://jira.mongodb.org/browse/DRIVERS-2882):
> Drivers will add a "k8s" implementation of an OIDC_CALLBACK that handles AWS EKS, GCP GKE, and Azure AKS.
=> GODRIVER-3175 Add Kubernetes support for OIDC.

docs/migration-2.0.md
GODRIVER-3499
Update the v2 migration guide on `ClientOptions.AuthenticateToAnything` and `ArrayFilters`.
=> GODRIVER-3499 Update v2 migration guide.

bson/bson_test.go, bson/registry_test.go
GODRIVER-2975
~~This PR draft is not meant to be merged. Read the [comments of #1969](https://github.com/mongodb/mongo-go-driver/pull/1969#issue-2892046587) for details.~~
This PR and #1969 replace error assertions (except those in replaceErrors() in "mongo\errors.go") with errors.Is() and errors.As().
=> GODRIVER-2975 Fully support "errors.Is" and "errors.As" in BSON APIs.

testdata/load-balancers/non-lb-connection-establishment.json, testdata/load-balancers/non-lb-connection-establishment.yml
[GODRIVER-3498](https://jira.mongodb.org/browse/GODRIVER-3498)
Sync non-lb-connection-establishment test to https://github.com/mongodb/specifications/commit/f04df7d667e20fa7f9ae067e6951662c68da85b6
Test failure resolved by [SERVER-101078](https://jira.mongodb.org/browse/SERVER-101078).
=> GODRIVER-3498 Revert skip to non-lb-connection-establishment.

bson/bson_corpus_spec_test.go, internal/integration/unified/unified_spec_runner.go, internal/integration/unified_spec_test.go, internal/serverselector/server_selector_test.go, internal/spectest/skip.go, x/mongo/driver/auth/auth_spec_test.go, x/mongo/driver/connstring/connstring_spec_test.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server_rtt_test.go
[GODRIVER-3445](https://jira.mongodb.org/browse/GODRIVER-3445)
* Move all logic for skipping spec tests by description into a new function `spectest.CheckSkip`.
* Note that many legacy spec tests are still skipped using a modified "skipReason" field in the spec test. We will address those in a separate PR.
* All spec tests should include the full JSON test filename in the test name.
* Fix a test name bug in `TestAuthSpec` introduced by https://github.com/mongodb/mongo-go-driver/pull/1976
There are multiple blocks that are responsible for skipping spec tests based on description, but the logic is always the same. Unifying the logic in one place makes it easier to maintain the list of skipped tests and add new skipped tests when necessary.
The reason we should do this now is to facilitate …
=> GODRIVER-3445 Move all logic for skipping spec tests by description into one place.

internal/integration/client_side_encryption_prose_test.go, mongo/change_stream.go, mongo/collection.go, mongo/database.go, mongo/errors.go, mongo/index_view.go, mongo/search_index_view.go, mongo/session.go, mongo/with_transactions_test.go
GODRIVER-2721
~~This PR draft is not meant to be merged.~~
This PR and #1984 replace error assertions (except those in `replaceErrors()` in "mongo\errors.go") with `errors.Is()` and `errors.As()`.
However, the error assertion checks the immediate error type. Instead, `errors.Is()`/`errors.As()` trace the error tree. ~~The difference changes the current error handling logic so they are not proper. Moreover, any further replacements in `replaceErrors()` will cause regression failures because of the logic change.~~ The difference changes the error handling logic so any further replacements in `replaceErrors()` will cause regression failures. `replaceErrors()` will be replaced in another PR.
~~In conclusion, we should not replace error assertions with `errors.Is()`/`errors.As()` in the …
=> GODRIVER-2721 Fully support "errors.Is" and "errors.As".

.evergreen/config.yml, README.md, internal/driverutil/description.go, internal/integration/causal_consistency_test.go, internal/integration/index_view_test.go, mongo/bulk_write_models.go, mongo/database.go, mongo/options/aggregateoptions.go, mongo/options/bulkwriteoptions.go, mongo/options/changestreamoptions.go, mongo/options/clientoptions.go, mongo/options/countoptions.go, mongo/options/createcollectionoptions.go, mongo/options/deleteoptions.go, mongo/options/distinctoptions.go, mongo/options/findoptions.go, mongo/options/indexoptions.go, mongo/options/insertoptions.go, mongo/options/replaceoptions.go, mongo/options/updateoptions.go, mongo/results.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/create.go, x/mongo/driver/operation/delete.go, x/mongo/driver/operation/update.go, x/mongo/driver/topology/fsm.go, x/mongo/driver/topology/topology_test.go
[GODRIVER-3098](https://jira.mongodb.org/browse/GODRIVER-3098)
Drop support for MongoDB 3.6. The minimum supported MongoDB version is now 4.0.
MongoDB 3.6 reached end-of-life in 2021.
Part of a stack of changes that must be reviewed in order:
1. https://github.com/mongodb/mongo-go-driver/pull/1985
2. https://github.com/mongodb/mongo-go-driver/pull/1986
3. https://github.com/mongodb/mongo-go-driver/pull/1988 (this PR)
=> GODRIVER-3098 Drop support for MongoDB 3.6

.evergreen/config.yml, Taskfile.yml, internal/cmd/testoidcauth/main.go
[GODRIVER-3513](https://jira.mongodb.org/browse/GODRIVER-3513)
* Mark the `gotest.parse_files` step as optional for tasks that still want to run `handle-test-artifacts` (e.g. to collect other app/server logs), but don't write any Go test output (e.g. the current OIDC tasks).
* Comment out `teardown_task_can_fail_task: true` from `testoidc_task_group` until the bug [DRIVERS-3141](https://jira.mongodb.org/browse/DRIVERS-3141), which prevents successful Atlas cluster teardown in OIDC tests, is fixed.
* Prevent Taskfile task `evg-gather-test-suites` from failing the Evergreen task if there are no `*.suite`files to archive.
Some OIDC tasks started failing after merging https://github.com/mongodb/mongo-go-driver/pull/1976. All of the failures were due to pre-existing problems in the test setup …
=> GODRIVER-3513 Fix OIDC Evergreen task failures.

internal/spectest/spectest.go
[GODRIVER-3445](https://jira.mongodb.org/browse/GODRIVER-3445)
* Use `runtime.Caller` instead of `filepath.Abs` to find the repo root directory, which works the same for any caller.
=> GODRIVER-3445 Make spectest.Path work for any caller.

bson/decode_value_fuzz_test.go, bson/fuzz_test.go, etc/run-fuzz.sh
[GODRIVER-3451](https://jira.mongodb.org/browse/GODRIVER-3451)
* Fuzz `bson.MarshalValue` and `bson.UnmarshalValue`.
* Enable the data race detector during fuzzing
=> GODRIVER-3451 Add fuzz test for BSON MarshalValue/UnmarshalValue.

internal/integration/collection_test.go, mongo/client.go, mongo/client_bulk_write.go, mongo/client_test.go, mongo/collection.go, mongo/collection_test.go, mongo/cursor.go, mongo/database_test.go, mongo/errors.go, mongo/index_view.go
GODRIVER-2704
Replace input validation error constants with "InvalidArgumentError".
=> GODRIVER-2704 Replace input validation error constants with "InvalidArgumentError".

internal/integration/unified/client_entity.go, internal/integration/unified/event.go, internal/integration/unified/event_verification.go, testdata/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.json, testdata/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.yml, testdata/server-discovery-and-monitoring/unified/logging-loadbalanced.json, testdata/server-discovery-and-monitoring/unified/logging-loadbalanced.yml, testdata/server-discovery-and-monitoring/unified/logging-replicaset.json, testdata/server-discovery-and-monitoring/unified/logging-replicaset.yml, testdata/server-discovery-and-monitoring/unified/logging-sharded.json, testdata/server-discovery-and-monitoring/unified/logging-sharded.yml, testdata/server-discovery-and-monitoring/unified/logging-standalone.json, testdata/server-discovery-and-monitoring/unified/logging-standalone.yml, testdata/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.json, testdata/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.yml, testdata/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.json, testdata/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.yml, testdata/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.json, testdata/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.yml, x/mongo/driver/topology/topology.go
GODRIVER-3035
Publish TopologyDescriptionChangedEvent on topology close.
Stacked on the top of https://github.com/mongodb/mongo-go-driver/pull/1964
Also updated spec tests for GODRIVER-2967
=> GODRIVER-3035 Publish TopologyDescriptionChangedEvent on topology close.

internal/integration/sessions_mongocryptd_prose_test.go
TestSessionsMongocryptdProse started failing with "TerminateProcess: Access is denied" on windows.
=> Skip TestSessionsMongocryptdProse on windows

bson/bson_binary_vector_spec_test.go, testdata/bson-binary-vector/float32.json
GODRIVER-3478
Use ExtJSON for BSON binary vector spec tests.
Sync https://github.com/mongodb/specifications/commit/ccd72de68cc29b68fe55a79ad44d20b20ad1b4e7
=> GODRIVER-3478 Use ExtJSON for BSON binary vector spec tests.

internal/integration/client_side_encryption_prose_test.go
GODRIVER-3546
Update Client-Side Encryption prose test 7 (Custom Endpoint) to fix possible timeouts against (intentionally) invalid URIs.
=> GODRIVER-3549 Fix timeouts in CSE custom endpoint test

.evergreen/config.yml
[DEVPROD-17319](https://jira.mongodb.org/browse/DEVPROD-17319)
The perf.send command is no longer being maintained and is actually in a maintenance state and will be decommissioned eventually. It has been replaced instead by a new end point that users are able to call from their evergreen files; [this doc](https://github.com/10gen/performance-tooling-docs/blob/main/getting_started/migrating_from_perfSend_to_sps.md) outlines a drop in solution that we apply to the existing evergreen config file in this PR.
Update the Mongo-Go-Driver project to send performance data downstream using the newest supported method.
Successful patch test with changes can be found here: https://spruce.mongodb.com/version/68124eebfead0f0007f06d23/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Updated patch without …
=> DEVPROD-17319 - update perf.send command to new results end point

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/errors.go, x/mongo/driver/topology/pool_test.go, x/mongo/driver/topology/server_test.go
GODRIVER-3361
Improve connection error message.
=> GODRIVER-3361 Improve connection error message.

x/mongo/driver/topology/connection_test.go
Currently this test can fail with the following error:
```
[2025/05/18 20:55:45.033] === RUN   TestConnection/connection/connect/context_is_not_pinned_by_connect/connect_cancelled
[2025/05/18 20:55:45.033] panic: interface conversion: interface {} is nil, not bool
[2025/05/18 20:55:45.033] goroutine 384 [running]:
[2025/05/18 20:55:45.033] go.mongodb.org/mongo-driver/v2/x/mongo/driver/topology.TestConnection.func1.2.3.2.4()
[2025/05/18 20:55:45.033] 	C:/data/mci/f9a2/src/go.mongodb.org/mongo-driver/x/mongo/driver/topology/connection_test.go:154 +0x73
[2025/05/18 20:55:45.033] go.mongodb.org/mongo-driver/v2/internal/assert.Eventually.func1()
[2025/05/18 20:55:45.033] 	C:/data/mci/f9a2/src/go.mongodb.org/mongo-driver/internal/assert/assertions.go:1053 +0x23
[2025/05/18 20:55:45.033] created …
```
=> Eventually assertion in TestConnection should check the nil condition on done value

README.md, docs/CONTRIBUTING.md, docs/migration-2.0.md, etc/compile_check.sh, go.mod, internal/cmd/benchmark/go.mod, internal/cmd/compilecheck/go.mod, internal/test/compilecheck/compile_check_test.go
GODRIVER-3515
Bump minimum supported Go version to 1.19
=> GODRIVER-3515 Bump the minimum Go Version to 1.19

mongo/integration/client_side_encryption_prose_test.go
GODRIVER-3549 
Cherry-pick of https://github.com/mongodb/mongo-go-driver/commit/029da417907833509cb8
=> GODRIVER-3549 Fix timeouts in CSE custom endpoint test (#2028) (#2031) (#2061)

.evergreen/config.yml, internal/test/faas/awslambda/template.yaml
GODRIVER-3560
Extend env variables from assuming role.
Evergreen CI for FaaS isn't tearing down the resulting Atlas cluster.
=> GODRIVER-3560 Use lambda-specific arn for FaaS

mongo/readpref/options.go, mongo/readpref/readpref.go
[GODRIVER-3494](https://jira.mongodb.org/browse/GODRIVER-3494)
Deprecate `readpref.WithHedgeEnabled` and `redpref.ReadPref.HedgeEnabled`. Note that hedged reads are deprecated in MongoDB 8.0 and may be removed in a future version.
Hedged reads are deprecated in MongoDB 8.0 and may be removed in a future version.
=> GODRIVER-3494 Deprecate hedged read preference methods.

internal/test/aws/aws_test.go
The docker CI test will fail if there is no mongodb uri for the aws test: https://parsley.mongodb.com/evergreen/mongo_go_driver_docker_runner_test_test_docker_runner_patch_5bde67f5822163e067186e151dae69af37ab954f_684c5f6361860900078cb2a6_25_06_13_17_27_02/0/task?bookmarks=0,1539&selectedLineRange=L1435
=> Skip AWS Test if no URI

x/mongo/driver/drivertest/opmsg_deployment.go
This makes it slightly easier for downstream users to check for this error specifically.
We currently have a custom implementation of MockDeployment that was more-or-less copied from the v1 Go driver. I would like to replace that with the new-in-v2 drivertest package, and having this be a named error instead of an anonymous one would make some of our downstream code a bit easier to write.
=> drivertest: name an anonymous error

internal/integtest/integtest.go, x/mongo/driver/topology/server_test.go
* Skip tests that call `integtest.ConnString` if running with `-short`.
* Skip the `TestServerHeartbeatTimeout` test if running with `-short` because it's an integration test.
This should also fix the "Docker Runner Test" task.
=> Prevent integration tests from running when testing with -short

bson/doc.go
* Remove references to removed `bsoncodec` package and types.
* Move "Raw BSON" section below main marshal/unmarshal behavior.
* Rewrite the BSON custom registry section.
=> Fix stale bson package docs.

docs/CONTRIBUTING.md
This PR adds guidance to discuss work with maintainers before starting. It also clarifies which branches to target when adding features or fixing bugs.
=> Add guidelines for contributing features to the Go Driver

internal/spectest/skip.go
[GODRIVER-2016](https://jira.mongodb.org/browse/GODRIVER-2016)
Unskip all _Transactions_ unified spec tests. Note that this PR does not unskip the _Transactions Convenient API_ unified spec tests because they do not pass yet without test runner fixes.
=> GODRIVER-2016 Unskip all Transactions unified spec tests.

x/bsonx/bsoncore/bson_arraybuilder_test.go, x/bsonx/bsoncore/bson_documentbuilder_test.go, x/bsonx/bsoncore/bsoncore_test.go, x/bsonx/bsoncore/value_test.go, x/mongo/driver/auth/auth_spec_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/compression.go, x/mongo/driver/connstring/connstring_spec_test.go, x/mongo/driver/operation.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/update.go, x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_rtt_test.go, x/mongo/driver/topology/server_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
Replace all uses of `interface{}` with `any` in the "x/" packages.
[any](https://pkg.go.dev/builtin#any) is a type alias for `interface{}`, so is semantically identical. The only change is a slightly cleaner syntax.
=> Replace all uses of 'interface{}' with 'any' in the x/ packages.

internal/bsonutil/bsonutil.go, internal/cmd/benchmark/benchmark_test.go, internal/cmd/testkms/main.go, internal/codecutil/encoding.go, internal/codecutil/encoding_test.go, internal/csot/csot_test.go, internal/docexamples/examples.go, internal/errutil/join.go, internal/errutil/join_test.go, internal/failpoint/failpoint.go, internal/logger/component.go, internal/logger/component_test.go, internal/logger/context_test.go, internal/logger/io_sink.go, internal/logger/logger.go, internal/logger/logger_test.go
Replace all uses of `interface{}` with `any` in the "internal/" packages
- Excludes the "internal/integration/" packages, which are changed in https://github.com/mongodb/mongo-go-driver/pull/2141
- Excludes any packages with code copied from other repos ("internal/assert", "internal/require", "internal/rand", and "internal/aws/credentials") because they are generally not edited except for updating from the canonical code.
[any](https://pkg.go.dev/builtin#any) is a type alias for `interface{}`, so is semantically identical. The only change is a slightly cleaner syntax.
=> Replace all uses of 'interface{}' with 'any' in the internal/ packages.

.evergreen/config.yml
[GODRIVER-3622](https://jira.mongodb.org/browse/GODRIVER-3622)
* Add the `retry_on_failure: true` config to all test tasks that use the `setup-test` task.
* Remove the `type: test` config from the `setup-test` command because those are setup steps, not test steps.
We consistently have a few flaky tests. We generally start troubleshooting failed tasks by re-running them before looking at any failures. Instead of that manual process, it would be more effective to automate the process, making consistently failing tasks much more apparent.
=> GODRIVER-3622 Automatically retry some test tasks.

.evergreen/config.yml, .github/CODEOWNERS, .github/labeler.yml, .github/release.yml, .github/reviewers.txt, .github/workflows/check-labels.yml, .github/workflows/labeler.yml
GODRIVER-3564
Targeting release/1.17 so the changes apply to future patch releases.
Adds labeler and label-checker to ensure pull requests get the necessary labels to be used for release notes.
The [labeler action](https://github.com/actions/labeler) automatically assign labels to pull requests. This was previously done through Evergreen, but using GitHub Actions makes more sense so we don't need to duplicate its code.
While working on this, I also noticed that we still use Evergreen to assign PR reviewers. Since reviewers are automatically assigned through branch rules, this task was not actually doing anything and has been removed.
The new [label checker](https://github.com/agilepathway/label-checker) workflow checks for certain label requirements. It requires that one of the following …
=> GODRIVER-3564: Add config and workflows for release note labels

internal/integration/unified/collection_operation_execution.go, internal/integration/unified/crud_helpers.go, mongo/bulk_write.go, mongo/collection.go, mongo/options/bulkwriteoptions.go, mongo/options/findoptions.go, mongo/options/replaceoptions.go, mongo/options/updateoptions.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/update.go, x/mongo/driver/xoptions/options.go, x/mongo/driver/xoptions/options_test.go
GODRIVER-3522
Add support for the `rawData` option for time-series bucket access - PR1
Stacked on the top of https://github.com/mongodb/mongo-go-driver/pull/2121
Add support for the following operations:
- find
- findAndModify
- update/replace
- collection bulkWrite
=> GODRIVER-3522 Add support for the rawData option for time-series bucket access - PR1

x/mongo/driver/operation.go, x/mongo/driver/operation_test.go
I suggest to optimize allocations in redactStartedInformationCmd function used in debug logging commands and command started events.
In one of our services 20% of allocations come from this function. We use only events for metrics. CPU consumption is not that large - only 1.5%, but I believe some part of GC CPU consumption that stands for more than 10% of total service CPU consumption also originates from these allocations.
Benchmark attached gives the following results without suggested changes:
```
cpu: Intel(R) Core(TM) i9-14900K
BenchmarkRedactStartedInformationCmd
BenchmarkRedactStartedInformationCmd/0
BenchmarkRedactStartedInformationCmd/0-32  		40476044	     70.50 ns/op	     112 B/op	       1 allocs/op
BenchmarkRedactStartedInformationCmd/1
BenchmarkRedactStartedInformationCmd/1-32 …
```
=> optimize allocations in redactStartedInformationCmd

Taskfile.yml, internal/assert/assertions.go, internal/cmd/testatlas/atlas_test.go, internal/require/require.go
GODRIVER-3548
Test MONGODB-X509 auth on cloud-dev to ensure auth will succeed using OpenSSL 3.
NA
=> GODRIVER-3548 Test MONGODB-X509 on cloud-dev

internal/integration/cursor_test.go
* Move subtests in `TestCursor` that test specific `Cursor` methods into separate test functions.
Very long test functions with deeply-nested subtests are difficult to read, maintain, and run. It's better to split up some subtests into separate test functions.
=> Split TestCursor into separate test functions.

.pre-commit-config.yaml
Retry Markdown link checks when the endpoint responds with HTTP 429.
The http://reneefrench.blogspot.com/ site returns HTTP 429 frequently, leading to failed pre-commit checks when run in the Github Actions runners. The [markdown-link-check](https://github.com/tcort/markdown-link-check) tool supports retrying after an HTTP 429, automatically waiting until the time specified by the "retry-after" HTTP header. See the [usage docs](https://github.com/tcort/markdown-link-check?tab=readme-ov-file#usage) for details.
=> Retry Markdown link checks on HTTP 429.

mongo/client.go
Rewrite `mongo.Connect` documentation to be clearer and correct some out-of-date information.
=> Rewrite mongo.Connect documentation.

internal/integration/cursor_test.go, mongo/client_bulk_write.go, mongo/collection.go, mongo/cursor.go, mongo/database.go, mongo/index_view.go
GODRIVER-3616
Apply client-level timeouts for default ITERATION_MODE for tailable/awaitData cursors. 
Detailed steps to reproduce the problem?
According to the CSOT specifications, the timeoutMS value must apply to cursor iteration methods such as `cursor.Next()`:
> When applying the timeoutMS option to next calls on cursor, drivers MUST ensure it applies to the entire call, not individual commands.
=> GODRIVER-3616 Apply client-level timeout to tailable cursors

.evergreen/config.yml, internal/integration/mongointernal_test.go, mongo/mongointernal.go
[GODRIVER-3612](https://jira.mongodb.org/browse/GODRIVER-3612)
Add an internal-only API `mongo.NewSessionWithLSID` that returns a `*Session` for the specified `Client` and session ID document.
=> GODRIVER-3612 Add an internal-only NewSessionWithLSID API (v2)

.evergreen/config.yml, mongo/integration/mongointernal_test.go, mongo/mongointernal.go
[GODRIVER-3612](https://jira.mongodb.org/browse/GODRIVER-3612)
Add an internal-only API `mongo.NewSessionWithLSID` that returns a `Session` for the specified `Client` and session ID document.
=> GODRIVER-3612 Add an internal-only NewSessionWithLSID API (v1)

.pre-commit-config.yaml
This cherry-picks changes from #2191 to the 2.x release series to avoid a lengthy process of ignoring changes in an up-merge.
=> Consider HTTP 429 a succcessful response in the Markdown link check.

.github/workflows/check-labels.yml
The label check requires one of the categorisation labels that is then used for release notes, but it does not pass when using the `ignore-for-release` label that excludes a pull request from release notes. This pull request rectifies this.
=> Allow ignore-for-release label to satisfy label checker

etc/profile-test.sh
Add a script `etc/profile-test.sh` that makes profiling and tracing Go tests and benchmarks easier.
The command syntax is identical to `go test`, but you replace `go test` with `etc/profile-test.sh`.
E.g.
```
❯ etc/profile-test.sh -timeout 30s -run ^TestRetryableReadsProse$ go.mongodb.org/mongo-driver/v2/internal/integration -v
1) cpu
2) mem
3) block
4) mutex
5) trace
Choose a profile type: 1
Writing cpu profile to /var/folders/jm/nk3y7g2d0539mxh5bhdcnhcm0000gp/T/tmp.WwVNvAewwl
=== RUN   TestRetryableReadsProse
=== RUN   TestRetryableReadsProse/PoolClearedError_retryability
=== RUN   TestRetryableReadsProse/retrying_in_sharded_cluster
mongotest.go:112: skipping due to environmental constraints: topology kind "single" does not match any of the required kinds ["sharded"]
--- PASS: …
```
=> Add a convenience wrapper for profiling and tracing Go tests.
