mongodb/mongo-go-driver

bson/element.go
Created a dirty fix just to show the reason.
Steps to reproduce:
```
package main
import (
"github.com/mongodb/mongo-go-driver/bson"
"log"
)
func main() {
log.Printf("%+v", bson.EC.Interface("test", bson.VC.ArrayFromValues(bson.VC.String("test01"), bson.VC.String("test02"))).String())
}
```
Result is:
```
panic: too small
goroutine 1 [running]:
github.com/mongodb/mongo-go-driver/bson.(*Value).MutableArray(0xc42007a720, 0x4)
/home/cold/develop/gitlab/go/src/github.com/mongodb/mongo-go-driver/bson/value.go:528 +0x2ae
github.com/mongodb/mongo-go-driver/bson.(*Value).Interface(0xc42007a720, 0xc4200182a0, 0xc4200800f0)
/home/cold/develop/gitlab/go/src/github.com/mongodb/mongo-go-driver/bson/value.go:64 +0x191
github.com/mongodb/mongo-go-driver/bson.(*Element).String(0xc42000e070, 0x4, …
```
=> panic: too small

bson/decode.go
Sorry about the lack of test, I tried, but I feel like the framework is too far away from where it needs to be to write efficient tests.
First fix is about deserializing to a slice of pointers. If the type of the elements of the slice is a pointer, then it adds the address of the new element to the slice instead of the element itself.
Second fix is about non-bson tags. The Lookup was returning an empty string when the bson tag wasn't found, so it never contained the `:`. A tag like `json:"xyz"` was not returning true for either condition, so it compared the full tag with the desired key.
=> Fix bugs in bson/decode

bson/constructor.go, bson/constructor_test.go
Also I would like to create constructor from time.Time, if you allow me. Like that:
```go
// Time creates a datetime element with the given key and value.
func (c ElementConstructor) Time(key string, time time.Time) *Element {
return c.DateTime(key, time.Unix() * 1000)
}
```
=> Add comment to DateTime constructor

bson/encode.go, bson/encode_test.go
When there is time.Time type in a struct, encoder encodes it into MongoDB DateTime format.
=> Adds support for go time struct.

bson/encode.go, bson/encode_test.go
The tag combination `bson:"inline,omitempty"` does not work properly.
If the struct field is zero value, all fields get included to the outer struct.
`if omitempty && e.isZero(field) {
continue
}`
has to be before the inline handling.
=> Check for 'omitempty' before inline handling

.gitignore, mongo/client.go, mongo/client_internal_test.go
Because client_internal_test assumes a ```readpref.Primary()``` I determined to use the same when creating a ```mongo.Client```
I considered and rejected two other options
-modifying connection string parsing to provide implicit default, but this was too much "special case"
-modifying database object creation, which initializes server selection functions, but it seemed that read-preference is more appropriately a property of the Client than a state-based mystery of server selection.
A new test-case has not been created, since this fixes an existing test that happens to be outside scope of Makefile & depends on a single local running MongoDB instance.
=> GODRIVER-407: allow readPreference to be implicit in connection string

bson/encode.go, bson/encode_test.go
As suggested in [GODRIVER-410](https://jira.mongodb.org/browse/GODRIVER-410)
=> GODRIVER-410: Check for omitempty and IsZero before encoding the field.

bson/decode.go, bson/decode_test.go
I understand this is not a bug as much as a feature, but I think it's the wrong behavior:
Right now if trying to deserialize a float to a float32, the decoder will return 0 if the float is too precise for 32 bits, without giving an error. I think the ideal solution would be to return an error, but that would require major changes. If we have to fail silently, the imprecise number seems better than 0.
=> Change "too precise" float32 behavior

bson/decode.go, bson/decode_test.go
Came across a problem with decoding pointers.
Example of code to reproduce common issue:
```
package main
import (
"github.com/mongodb/mongo-go-driver/bson"
"log"
)
type TestStruct struct {
TestValue *string `bson:"test_value,omitempty"`
}
func main() {
testString := "test value goes here"
t := TestStruct{
TestValue: &testString,
}
data, err := bson.Marshal(t)
log.Fatalf("Failed to marshal. Error: %v", err)
}
unt := TestStruct{}
err = bson.Unmarshal(data, &unt)
log.Fatalf("Failed to unmarshal. Error: %v", err)
}
log.Printf("Result: %+v")
if unt.TestValue == nil {
return
}
log.Printf("Contained string: %+v", *unt.TestValue)
}
```
Code like the one above gives error like:
```
reflect.Value.Addr of unaddressable value
```
=> fix pointers' decoding

bson/encode.go, bson/encode_test.go
Came across a problem with encoding *time.Time. It turned out that it is ignored during encoding process.
Code to reproduce:
```
package main
import (
"log"
"time"
"github.com/mongodb/mongo-go-driver/bson"
)
type testStruct struct {
FieldA time.Time  `bson:"field_a"`
FieldB *time.Time `bson:"field_b"`
}
func main() {
now := time.Now()
test := testStruct{
FieldA: now,
FieldB: &now,
}
data, err := bson.Marshal(test)
log.Fatalf("Failed to marshal. Error: %v", err)
}
unTest := testStruct{}
err = bson.Unmarshal(data, &unTest)
log.Fatalf("Failed to marshal. Error: %v", err)
}
log.Printf("Marshaled: %+v", test)
log.Printf("Unmarshaled:%+v", unTest)
}
```
Will give something like this:
```
2018/05/25 11:24:09 Marshaled: {FieldA:2018-05-25 11:24:09.703404724 +1000 …
```
=> Fix encoding of *time.Time

core/connection/connection.go
There are a bunch of unnecessary defers that incur
a speed cost as defers are slower by ~2X than a
plain function call. Noticed while instrumenting
this driver with OpenCensus.
For those that need numbers to motivate the change:
$ benchstat before.txt after.txt
```shell
name                              old time/op    new time/op    delta
ConnectionDeficientSize-4           1.15ms ±77%    1.02ms ±55%     ~           (p=0.280 n=10+10)
ConnectionDeficientMessageBody-4    2.23ms ±20%    1.94ms ±24%  -12.75%        (p=0.035 n=10+10)
ConnectionDeficientHeader-4         1.86ms ±41%    1.97ms ±27%     ~             (p=0.423 n=9+8)
ConnectionDeficientOpReply-4        2.06ms ±19%    2.11ms ±20%     ~             (p=0.931 n=9+9)
```
Given these benchmarks
```go
package main
import (
"context"
"net" …
```
=> core/connection: remove unnecessary defers

bson/encode.go, bson/encode_test.go
As the title says.
On lines 448 and 534 you get a panic when trying to dereference a nil pointer.
=> fix nil dereference panic when receiving nil *time.Time 

core/topology/server.go
This should fix a memory leak in topology.Server's update()
=> GODRIVER-508 - call Stop() on heartbeatTicker and rateLimitr

core/connection/connection.go, core/event/monitoring.go, mongo/causal_consistency_test.go, mongo/command_monitoring_test.go, mongo/sessions_test.go
For: https://jira.mongodb.org/browse/GODRIVER-515
This change passes the `context.Context` through to the events. In our case `Context` is used to pass IDs for tracing, but this could be useful for other things as well.
=> GODRIVER-515: add context.Context to events

core/readpref/options.go, core/readpref/readpref_test.go
GODRIVER-538
The readpref.WithTags function was entirely broken for any length of arguments n*2 where n > 1 or exactly 0 arguments.
0 arguments:
It only checked for length % 2 == 0 which a length of 0 obviously passes but that obviously isn't a legal tag.
Multiple of 2 arguments:
That for-loop was just completely wrong only accidentally being correct for exactly 2 tags.
It essentially made every key into a name and what should have been the next name into a key,
because it didn't skip any index but instead terminated at just half length, which also meant it would not include any actual later tags pairs.
Checking out just the altered tests in https://github.com/mongodb/mongo-go-driver/commit/c596cc5e83400d59c65b356a0f9d2090d97c8833 and running them clearly demonstrates that behavior.
I …
=> [GODRIVER-538] Fix readpref.WithTags function

bson/value.go
Add method to retrieve binary data without hazard of panicking.
=> GODRIVER-539: Add non panicking BinaryOK function to bson

bson/bsoncodec/bsoncodec_test.go
Hi, the value returned in case of null time is an empty time.Time struct, when teh time is not null, however, an int64 is returned, which makes no sense and prevents from decoding an ISODate into time.Time
There was no test for a non empty Time value, so I added it.
This is for teh JIRA ticket GODRIVER-567
=> GODRIVER-567 Returned time.Time instead of int64 when decoding an IsoDate

bson/constructor.go
I'm happy to add a test but it didn't seem like we have tests for internal consistency.
=> GODRIVER-564 Use same time.Time conversion in Encoder and ElementConstructor

bson/bsoncodec/struct_codec.go
If the value is nil then using `Interface` method on it causes panic. For example, write following struct
```go
type State struct {
Value struct {
Object interface{} `bson:",omitempty"`
}
}
```
with the following value:
```go
s := State{}
s.Value.Object = nil
```
case panic if there is not check for validity.
=> Check value validity before use value methods.

bson/objectid/objectid.go
If client sent data, which has format like: {"id": "5b4bcb0f85e47a1fabb82f3e"} then gets error
I added check for string.
=> Fix problem parsing string to ObjectID

bson/objectid/objectid.go
Currently, if we sent data to client, client gets data and type of id is array.
MarshalJSON encodes the ObjectID in to string.
=> Added MarshalJSON for ObjectID

bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/default_value_encoders_test.go
Came across a problem of encoding `bson.D` / `primitive.D`, decoded with `UnmarshalExtJSON`...
To be short: I've got a json file with a command to MongoDB, written in extended JSON format, I want to read that command from file and execute it with `db.RunCommand`. First of all, I came across a problem, that MongoDB is sensitive to order of elements in command, that is executed (`"insert": <coll-name>`, for example, has to be the first element in command), so it means that ordinary `map` is not usable. So, I started to use `bson.D` instead. Everything was pretty good, till recent, when some changes with `reflect` were merged.
The problem is, that I have `nil` value for some key in my json file. When I execute `db.RunCommand` it returns `error`, saying `cannot transform type primitive.D to a …
=> Error of nil conversion from bson.D decoded using UnmarshalExtJSON

mongo/gridfs/bucket.go, mongo/gridfs/upload_stream.go, mongo/options/gridfsoptions.go
[GODRIVER-833](https://jira.mongodb.com/browse/GODRIVER-833)
This PR updates the Go driver's GridFS constants to assume the KiB/MiB definition of MB/KB as other drivers do.
Note: I just set off the evergreen [patch](https://evergreen.mongodb.com/version/5c6608e60305b95db5c3b3ab) before leaving. If it is red, I'll look into it in the morning.
=> GODRIVER-833 Fix GridFS default chunk size is 255 kB, not 255 KiB

mongo/index_view.go, mongo/options/aggregateoptions.go, mongo/options/countoptions.go, mongo/options/deleteoptions.go, mongo/options/distinctoptions.go, mongo/options/estimatedcountoptions.go, mongo/options/findoptions.go, mongo/options/indexoptions.go, mongo/options/insertoptions.go, mongo/options/replaceoptions.go, mongo/options/updateoptions.go
* "creates" -> "created" - grammar typo
* Update options type main comments to consistent sentence format - i.e. "// DoStuffOptions represents all possible options to the DoStuff() function." 
* Fixed a few references to the wrong things - e.g. "DropIndexesOptions represents all possible options for the create() function."
=> Comment fixups

mongo/gridfs/bucket.go
[GODRIVER-886](https://jira.mongodb.org/browse/GODRIVER-886)
[evergreen](https://evergreen.mongodb.com/version/5c900963c9ec4457930c4f24)
=> GODRIVER-886 Fix panic when using non-ObjectID fileID in bucket.OpenDownloadStream

mongo/gridfs/bucket.go, mongo/options/gridfsoptions.go
[GODRIVER-887](https://jira.mongodb.org/browse/GODRIVER-887)
=> GODRIVER-887 Properly set default registry when using UploadOptions

README.md
If I follow the very first snippet in the Usage section, this is what I'll get:
```
$ go build
./main.go:12:36: undefined: options
```
This PR fixes the import statement to include the `options` module.
=> readme: fix missing import

Makefile, etc/check_env.sh, etc/check_fmt.sh
Hi, I was speaking with @divjotarora during GopherCon and decided that I would try fixing the Makefile on Linux, since I ran into this issue before and I know one other person did too (forgot his name).
This fixes the issue with `check_env.sh` using `bash`-specific syntax on `sh`. This only works on OS X because OS X does not actually _have_ `sh`, it has `bash` that is linked as `sh`. On Linux systems, `sh` exists and does not support the full `bash` language.
I've also fixed essentially the same problem in some in-line shell script in the Makefile, which by default on Linux will probably run via GNU Make, which runs `sh` by default.
Thank you!
P.S. A subset of the Evergreen tasks are [here](https://evergreen.mongodb.com/version/5d3d32b80ae6067c15bb6a22).
=> Fix Linux make

x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
GODRIVER-1302
The test for this seems slightly silly, but does reproduce the race with `go test -race`.
=> Lock `serversLock` in `Topology.String`.

x/mongo/driver/description/topology.go, x/mongo/driver/description/topology_test.go, x/mongo/driver/topology/polling_srv_records_test.go
GODRIVER-1301
One caveat is that this does not return added/removed servers in sorted ordered.  Neither of these functions were documented to do so, and afaict nothing in the driver actually requires that.  Similarly, since inputs are no longer sorted, I assume that topology servers will also not be sorted.
=> Don't mutate inputs in `DiffTopology` or `Topology.DiffHostlist`.

x/mongo/driver/topology/connection.go
I can't write a test for this because put only errors if it tries to put the connection in the wrong pool, which it can't.
=> GODRIVER-1323 cleanup connection close logic

mongo/bson_helpers_test.go, mongo/read_write_concern_spec_test.go, mongo/readconcern/readconcern.go
These are unit tests, not integration, so I kept them in the `mongo` package but I made the following changes:
1. The test file is parsed using our extended JSON library rather than `encoding/json` for consistency with other spec tests in `mongo/integration`.
2. Updated the assertion library.
3. Added new BSON comparison functions in a `bson_helpers_test.go` file. These are very similar to those in `mongo/integration` but they don't have special handling for 42/"42" and `$$type` placeholders because those aren't used in the read/write concern spec tests.
=> Use testing library for read/write concern spec tests.

.evergreen/config.yml
We already successfully compile with go1.9, so there's no code changes needed. This PR updates our Evergreen config to test compilation on go1.9 instead of go1.8.
=> Update evergreen config to test compilation with go1.9.

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
Previously, the error message for being unable to read a document was
confusing because it mentioned "decoding" when no such decoding was
occuring.  E.g.:
> unable to decode message length: read tcp 10.148.11.183:42418->63.35.244.142:27017: i/o timeout
This commit changes this and a related message to clarify that the
problem is an incomplete read, either of the message header or the full
message.  (These terms are also not quite accurate, but are likely to be
better-understood by end-users reading the message.)  After the change,
the message above would appear as follows:
> incomplete read of message header: read tcp 10.148.11.183:42418->63.35.244.142:27017: i/o timeout
=> Improve clarity of incomplete read error message

mongo/client.go, mongo/gridfs/gridfs_test.go, mongo/integration/client_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/sessions_test.go, mongo/with_transactions_test.go
=> Assert that tests close all opened sessions and connections.

bson/primitive/decimal.go, bson/primitive/decimal_test.go
Enhance Decimal128 with support parse from or to big.Int. Refactor ParseDecimal128 base on math/big to fix boundary bug like "-NaN","10384593717069655257060992658440191"
=> GODRIVER-1158 Enhance Decimal128 and fix bug

bson/primitive/decimal.go
The PR for GODRIVER-1158 used the `big.Int.CmpAbs` function, which compares the absolute value of 2 `big.Int` instances. This function is only available for go1.10, so this PR removes uses of that function to maintain go1.9 compatibility.
=> Remove usages of CmpAbs

mongo/integration/client_side_encryption_prose_test.go
One of the tests added for GODRIVER-1348 expects dialing a connection to a host that does not exist will return an error with the substring "connection refused". This is not true for Windows, which returns "No connection could be made because the target machine actively refused it."
=> GODRIVER-1348 Fix connection error substring for Windows

mongo/index_options_builder.go
If you don't mind undocumented public functions, I could also just delete all the method documentation.
=> GODRIVER-911 Deprecate IndexOptionBuilder

mongo/client_side_encryption_examples_test.go, mongo/doc.go
For reference, these examples are supposed to mimic the Java ones at https://mongodb.github.io/mongo-java-driver/3.11/driver/tutorials/client-side-encryption/ as per the DRIVERS-752.
=> GODRIVER-1368 Add GoDoc examples for client side encryption

data/retryable-reads/listIndexNames.json, data/retryable-reads/listIndexNames.yml
We don't run these tests as we don't have a `ListIndexNames` helper but I figured it's worth doing this ticket anyway so we're in sync with the specs repo.
=> GODRIVER-1369 Resync retryable reads tests for listIndexNames

README.md
`dep` will automatically fetch the latest released version so this PR removes the version number from our README instructions to avoid inconsistencies.
=> Remove version number from README instructions

mongo/crud_examples_test.go
I want to get an initial review of these before adding examples for the rest of the examples for `Database` and `Collection`. The general rules I've been following for these are:
1. Use a non-empty filter/update/replacement when applicable.
2. Specify an arbitrary option from the `options` package.
3. For methods that return an iterable or concrete result type (e.g. `[]string`, `InsertOneResult`), print out something to show the result.
4. For methods that return a `Cursor`, use the `All` method to capture all docs as `bson.Raw` and print out each document. Add a note to say that users should see the `Cursor` docs for more examples.
5. For methods that return a `ChangeStream`, print out each event in a loop. Add a note to say that users should see the `ChangeStream` docs for more …
=> GODRIVER-1379 CRUD GoDoc examples

mongo/client.go, mongo/crud_examples_test.go, mongo/session.go
This is kind of annoying because `Session` is an interface and the concrete type is private so methods like `WithTransaction` can only be documented on the top-level `Session` type itself. Also, we can't have standalone examples for `WithTransaction` because afaik Godoc doesn't support examples for interfaces. To get around this, I added a `WithTransaction` example inside the `Client.StartSession` example and made a note about this in the docs.
=> GODRIVER-1380 Document Session and provide GoDoc examples

mongo/options/clientoptions.go, x/mongo/driver/topology/server_options.go
Notes:
1. Filed https://jira.mongodb.org/browse/GODRIVER-1410 to add a `retryReads` URI option. If that ticket is done before this, we'll update this PR to include a note about that.
2. Each setter contains a note about the corresponding URI option(s). This was done because our connection string parser is in `x` and therefore not publicly documented.
=> GODRIVER-1401 ClientOptions documentation

x/bsonx/bsoncore/bsoncore.go, x/bsonx/document_test.go
Hello,
we were fuzzing one of our libraries that depend on bsonx and found following panics
```
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
go.mongodb.org/mongo-driver/x/bsonx/bsoncore.Document.Validate(0x4381000, 0x4, 0x4, 0x12dad00, 0xc0000102c0)
XXXX/mongo-driver/x/bsonx/bsoncore/document.go:373 +0x6e3
go.mongodb.org/mongo-driver/x/bsonx.(*Doc).UnmarshalBSON(0xc0000cbe08, 0x4381000, 0x4, 0x4, 0xc0000cbe08, 0x99c4e6fa)
XXXX/mongo-driver/x/bsonx/document.go:225 +0xb6
go.mongodb.org/mongo-driver/x/bsonx.ReadDoc(0x4381000, 0x4, 0x4, 0xc0000cbe70, 0x1076066, 0x5dcdd198, 0xdc8138, 0x133fa99c4e6fa)
XXXXXXXXXXXXXXXX
exit status 2
----------
panic: runtime error: slice bounds out of range [:-2147483643]
goroutine 1 [running]: …
```
=> Fix bsoncore overflow

bson/bsoncodec/struct_codec.go, bson/bsonoptions/string_codec_options.go, bson/bsonoptions/struct_codec_options.go, bson/mgocompat/bson_test.go, bson/mgocompat/registry.go
The lax decoding work was removed from the scope of this ticket, as it is impossible to add an option for mgobson's specific lax decoding behavior without backwards breaking changes.
=> GODRIVER-1349 implement mgocompat StructCodec options

mongo/integration/change_stream_spec_test.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/crud_helpers_test.go, mongo/integration/gridfs_spec_test.go
I realized on Friday that our semantic BSON equality functions don't offer much context when values don't match. This PR changes those functions to return errors rather than fail via an `assert` statement so the errors can be propagated upwards and context can be added.
To see an example of this, change the value of `_id` in https://github.com/mongodb/mongo-go-driver/blob/master/data/transactions/insert.json#L133 from 3 to 4. The error messages are:
old: `value mismatch for key _id; expected {"$numberInt":"4"}, got {"$numberInt":"3"}`
new: `expectation comparison error at index 1: value mismatch for key documents.1._id; expected {"$numberInt":"4"}, got {"$numberInt":"3"}`
=> Add context to document comparison errors for tests

.evergreen/config.yml
This PR includes changes to use the public instructions for building libmongocrypt in our tests. The build isn't green yet because we're blocked on some changes being made to libmongocrypt, but it should be ready for review.
=> Use Ubuntu/Mac instructions for libmongocrypt in tests

bson/bsoncodec/time_codec.go, bson/doc.go
A second attempt at some docs prework based on the meeting we had last week. The idea here is to enumerate the mappings from BSON to Go types for decoding into a D or M and list some information about struct behavior.
=> Document default encoding/decoding behavior for Go to BSON

.evergreen/config.yml
Updated the linked patch build to run a full build with the same variants that are run on the waterfall so we can make sure no weird errors are happening.
=> Fix PKG_CONFIG_PATH and LD_LIBRARY_PATH for Evergreen tests

bson/bson.go, bson/bson_1_8.go, bson/primitive/primitive.go
The docs for the D, M, and A types are copied in bson.go, bson_1_8.go, and primitive.go. If there are any suggestions, please only comment once and I'll apply the suggestions to all three places.
=> GODRIVER-1061 Remove references to RawArray and Array types in BSON docs

bson/bsoncodec/struct_codec.go, bson/mgocompat/bson_test.go
I realized I forgot to enable one of the mgocompat tests for structcodecs when I did that work.
=> GODRIVER-1349 fix omitEmpty for interface{}

bson/bsoncodec/byte_slice_codec.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/default_value_encoders_test.go, bson/bsoncodec/empty_interface_codec.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/slice_codec.go, bson/bsoncodec/string_codec.go, bson/bsoncodec/struct_codec.go, bson/bsoncodec/types.go, bson/bsonoptions/byte_slice_codec_options.go, bson/bsonoptions/empty_interface_codec_options.go, bson/bsonoptions/map_codec_options.go, bson/bsonoptions/slice_codec_options.go, bson/bsonrw/value_reader.go, bson/bsontype/bsontype.go, bson/mgocompat/bson_test.go, bson/mgocompat/registry.go
GODRIVER-1354
GODRIVER-1362
GODRIVER-1421
GODRIVER-1429
GODRIVER-1430
=> mgocompat ObjectID, interface{}, slice, []byte, and symbol changes

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/registry.go, bson/bsoncodec/registry_test.go, bson/mgocompat/registry.go, bson/primitive_codecs.go, mongo/integration/unified_spec_test.go, x/bsonx/primitive_codecs.go
- Deprecate RegisterEncoder and replace with RegisterTypeEncoder and RegisterHookEncoder
- Deprecate RegisterDecoder and replace with RegisterTypeDecoder and RegisterHookDecoder
=> GODRIVER-1438 Add separate RegistryBuilder methods for types and hooks

mongo/testatlas/main.go
I've seen these tests fail sometimes with because the inserted document isn't found, so I added write concern majority and read concern local (I tried read concern majority but I believe some of these are running against older servers that weren't started with `--enableMajorityReadConcern`).
Also, the current tests use `log.Fatalf` which calls `os.Exit` in a failure. This means that `defer` functions do not run, so the created client isn't closed in failure cases. I changed these to `panic` instead and added the URI index to the error messages so we can easily find the cluster URI if we have failures that aren't transient.
=> Make Atlas connectivity tests more robust

.evergreen/config.yml
Per a recent downstream changes email, latest versions of the server should be tested on Windows 10.
=> Upgrade Evergreen config to Windows 2017

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/empty_interface_codec.go, bson/bsoncodec/registry.go, bson/bsonoptions/empty_interface_codec_options.go, bson/mgocompat/registry.go
- Change empty interface decoding so that type map entries registered for bsontype.EmbeddedDocument are used for top level documents as well.
- Remove the DecodeAsMap option for EmptyInterfaceCodec and replace the functionality by registering a type map entry for bsontype.EmbeddedDocument to bson.M.
=> GODRIVER-1466 Respect type map entries for bsontype.EmbeddedDocument

mongo/single_result.go
Corrects a small typo that was reported in https://jira.mongodb.org/browse/DOCS-13384
=> (DOCS-13384): correct typo in Decode docs

data/read-write-concern/README.rst, data/read-write-concern/operation/default-write-concern-2.6.json, data/read-write-concern/operation/default-write-concern-2.6.yml, data/read-write-concern/operation/default-write-concern-3.2.json, data/read-write-concern/operation/default-write-concern-3.2.yml, data/read-write-concern/operation/default-write-concern-3.4.json, data/read-write-concern/operation/default-write-concern-3.4.yml, data/read-write-concern/operation/default-write-concern-4.2.json, data/read-write-concern/operation/default-write-concern-4.2.yml, mongo/integration/crud_helpers_test.go, mongo/integration/json_helpers_test.go, mongo/integration/unified_spec_test.go
No logic changes needed! The test format for the spec changes added a field called `other_collection_name` which from what I can tell is used to specify the name of the outcome collection. However, the CRUD v2 tests already have this functionality for operations like aggregate with `$merge` and do not have this field, so I'm going to ask tomorrow if the field can be removed in a follow-up PR or the CRUD tests can be updated to match.
=> GODRIVER-1398 Add tests to ensure default write concern is omitted.

mongo/integration/change_stream_spec_test.go
- The test is failing on the latest server variant because SERVER-45505 was merged.
- The test will be re-enabled or removed after SPEC-1505 is resolved.
=> Disable change stream test.

.evergreen/config.yml
The first commit for GODRIVER-1467 added tests for RSA certificates.
This commit adds the following sets of tests:
- RSA certificates + OCSP responses signed by delegates
- ECDSA certificates
- ECDSA certificates + OCSP responses signed by delegates
This commit also uses a buildvariant instead of a matrix for OCSP tests
in Evergreen and uses cron to set the variant to only run every 14 days
on the waterfall.
=> GODRIVER-1467 Add tests for all combinations

mongo/collection.go, mongo/integration/crud_prose_test.go
I added a test for now so this will continue to be tested on the release branch. The hope is to remove the test on master before 1.4.0 and replace it with spec tests when we do the work for $out/$merge to secondaries.
=> GODRIVER-1522 Ignore read preference for aggregations with output stages

data/change-streams/README.rst, data/change-streams/change-streams-errors.json, data/change-streams/change-streams-errors.yml, data/change-streams/change-streams-resume-errorLabels.json, data/change-streams/change-streams-resume-errorLabels.yml, data/change-streams/change-streams-resume-whitelist.json, data/change-streams/change-streams-resume-whitelist.yml, mongo/change_stream.go, mongo/integration/change_stream_spec_test.go, mongo/integration/change_stream_test.go, mongo/integration/mtest/mongotest.go, mongo/with_transactions_test.go
This includes some spec test changes that are in an open PR on the specs repo (https://github.com/mongodb/specifications/pull/757). The changes in that PR aren't strictly necessary, but they make error output a little nicer because we fail faster during command monitoring expectation comparisons if we do something incorrectly.
=> GODRIVER-1509 Whitelist errors for change streams

bson/bsonrw/extjson_parser.go, bson/bsonrw/extjson_parser_test.go
While doing this, I also made the relevant test functions in extjson_parser_test.go run table-driven tests as subtests so I could easily isolate the tests I wanted to run.
=> GODRIVER-1520 Fix panics for lone scope

bson/bsonrw/extjson_parser.go, bson/bsonrw/extjson_parser_test.go
This is based on top of the branch for GODRIVER-1520 because the test helpers I added in that commit are useful here. Please review that one first so I can rebase and push in the correct order.
=> GODRIVER-1502 Fix variable shadowing in parsing

bson/bsonrw/extjson_wrappers.go, bson/extjson_prose_test.go
We didn't have a great place to put prose tests before, so I added a new extjson_prose_test.go file.
=> GODRIVER-1506 Fix error checking for invalid extjson timestamp values

mongo/client.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/sessions_test.go, mongo/integration/unified_spec_test.go, mongo/session.go, x/mongo/driver/operation.go, x/mongo/driver/session/server_session.go, x/mongo/driver/session/session_pool.go, x/mongo/driver/session/session_pool_test.go
- Add an ID method to the mongo.Session interface
=> GODRIVER-672 Change session IDs to be stored as bson.Raw

.evergreen/config.yml
The previous cron syntax was incorrect (see EVG-7622). This patch re-structures the OCSP tests as a matrix and uses batchtime instead of cron.
=> GODRIVER-1467 Use batchtime for OCSP Evergreen tasks

mongo/integration/crud_prose_test.go, mongo/integration/mtest/mongotest.go
Relevant spec change: https://github.com/mongodb/specifications/commit/7745234f93039a83ae42589a6c0cdbefcffa32fa
We were already parsing the `errInfo` field for the `WriteConcernError.Details` document, so the only change here is adding a test.
=> GODRIVER-1536 Ensure errInfo is propagated

README.md
The `ecosystem` prefix was removed for driver doc pages. The old ecosystem links are 404 now. 
See new link https://docs.mongodb.com/drivers/go/
=> Update readme mongodb.com doc links

mongo/client.go, mongo/integration/client_test.go, x/mongo/driver/examples/server_monitoring/main.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/topology_options.go
This is a follow-up change for the bug fix in GODRIVER-1405. The topology.WithConnectionAppName ConnectionOption doesn't do anythhing because the app name for a connection is set through the handshaker, so it's safe to remove.
=> GODRIVER-1405 Remove topology.WithConnectionAppName

benchmark/harness.go, x/bsonx/bsoncore/document.go
Calling `elem.Key()` causes a string to be needlessly allocated for every key in the document (until the key is found).
```
Before:
BenchmarkMultiInsertSmallDocument-8       137404          7895 ns/op        4401 B/op         85 allocs/op
BenchmarkMultiInsertLargeDocument-8           28      40820770 ns/op    56993558 B/op     519048 allocs/op
BenchmarkSingleRunCommand-8                15486         77255 ns/op        8703 B/op        145 allocs/op
BenchmarkSingleFindOneByID-8               12741        108356 ns/op        6398 B/op         68 allocs/op
BenchmarkSingleInsertSmallDocument-8       11641        103208 ns/op        5769 B/op        129 allocs/op
BenchmarkSingleInsertLargeDocument-8          24      41890824 ns/op    49652546 B/op     519096 allocs/op
After: …
```
=> Improve perf and reduce allocs in `bsoncore.Document.LookupErr`.

data/auth/connection-string.json, data/auth/connection-string.yml, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/connstring/connstring.go
The previous set of changes in SPEC-1270 made it so the "default db" in the URI is only treated as the auth source if there are other auth-related parameters in the URI. Otherwise, it is ignored. This makes it so `mongodb://localhost:27017/db` does not represent a request for auth.
This PR expands that so an explicit auth source is only treated as a request for auth if there are other auth-related parameters in the URI and is ignored if there are not. This makes it so `mongodb://localhost:27017/?authSource=db` does not represent a request for auth.
Spec commit: https://github.com/mongodb/specifications/commit/af6b8b14606d43f1938a2a8da23801f05c6cf4ab
=> GODRIVER-1473 Allow authSource without credentials

bson/bsoncodec/cond_addr_codec.go, bson/bsoncodec/cond_addr_codec_test.go, bson/bsoncodec/registry.go, bson/bsoncodec/registry_test.go
Right now this doesn't store CondAddrEncoders in the typeEncoders map. Would it make sense to store half-filled CondAddrEncoders?
=> GODRIVER-1576 fix non-addr type with pointer implementation for bson

.evergreen/config.yml, mongo/client.go, mongo/integration/client_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/integration/mtest/setup.go, mongo/integration/sessions_test.go, x/mongo/driver/auth/auth.go, x/mongo/driver/auth/conversation.go, x/mongo/driver/auth/default.go, x/mongo/driver/auth/gssapi.go, x/mongo/driver/auth/gssapi_test.go, x/mongo/driver/auth/mongodbaws.go, x/mongo/driver/auth/mongodbcr.go, x/mongo/driver/auth/mongodbcr_test.go, x/mongo/driver/auth/plain.go, x/mongo/driver/auth/plain_test.go, x/mongo/driver/auth/sasl.go, x/mongo/driver/auth/scram.go, x/mongo/driver/auth/scram_test.go, x/mongo/driver/auth/x509.go, x/mongo/driver/drivertest/channel_conn.go
Testing this required adding a auth-nossl variant because the custom dialer can't handle SSL connections and I'm not sure there's any benefit in testing this with SSL, as that's a property of the networking layer and does not affect the wire messages we create/receieve.
=> GODRIVER-1584 Ensure cluster time is updated from handshakes

mongo/index_view.go, mongo/integration/index_view_test.go
The current code converts `IndexModel.Keys` into `bsoncore.Document` twice: once to generate the key specification document and another time in `getOrGenerateIndexName` to iterate the document and generarte the name. This PR cleans up that logic to first generate the key spec and pass that into `getOrGenerateIndexName` to avoid doubling the marshalling cost. I've also updated the documentation for `IndexModel.Keys` to say that it should be order-preserving.
=> GODRIVER-1565 Consolidate IndexView helpers and improve docs

x/mongo/driver/operation.go
This is a little bit of pre-work for streamable to make sure the part that reads the wire message updates all of the relevant info, as the `ExecuteExhaust` doesn't run through the part of `Execute` that does these updates.
=> GODRIVER-1634 Consolidate response processing code in roundTrip

.gitignore, x/mongo/driver/driver.go, x/mongo/driver/operation.go, x/mongo/driver/operation_exhaust.go, x/mongo/driver/operation_test.go, x/mongo/driver/topology/connection.go
This is the first part of streamable isMaster. I added a new `Streamer` interface that connections should implement if they support setting `exhaustAllowed` and receiving `moreToCome` messages. The other main addition is the `Operation.ExecuteExhaust` function, which takes a `Streamer` and streams the next message.
=> GODRIVER-1489 Add ability to stream wire messages

mongo/integration/crud_helpers_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/unified_spec_test.go
This is pre-work for the streamable isMaster test runner. I changed
the runner to use the default ClientOptions when starting a new test
and use that Client for test setup. After setup, the Client is reset
to use the ClientOptions specified in the test.
=> Simplify unified test runner

mongo/integration/crud_spec_test.go, mongo/integration/json_helpers_test.go, mongo/integration/unified_spec_test.go
This commit changes the runOperation function in the unified
test runner to return an error rather than failing the test
so that errors can be reported with more context at a higher
level.
Note that this still isn't perfect because functions like `executeCollectionOperation` will fail the test if the operation result doesn't match the expected result (e.g. the `UpsertedCount` field is different in an `Update*` test), but the errors we usually see on Evergreen are when a test gets an unexpected error, which is handled by this PR. Ideally, we should get to a point where any helpers called from `runSpecTestCase` return an error and never internally call `mt.Fatalf`.
=> Propagate errors in unified test runner rather than failing

bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/struct_codec.go
Talked to @craigwilson offline and we agreed that the struct field
information is never necessary because users have to specify a
struct tag if the struct field name doesn't match the BSON key
name, so I removed that from the error message completely.
With that change made, the only change needed to support the feature
request in the ticket is to export a `Keys` function from `DecodeError`.
=> GODRIVER-1627 Export keys slice from bsoncodec.DecodeError

x/mongo/driver/topology/pool_test.go
I think this is the same issue that we ran into when first implementing this ticket, but for a different test, so I moved the `assert.RunWithTimeout` logic into a helper.
Example failure in Evergreen: https://evergreen.mongodb.com/test_log/5ee118211e2d17189bc97d0a#L14607
=> GODRIVER-1613 Improve stability of flaky test

.evergreen/config.yml, mongo/integration/client_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/integration/mtest/proxy_dialer.go, mongo/integration/mtest/received_message.go, mongo/integration/mtest/sent_message.go, mongo/integration/mtest/wiremessage_helpers.go, mongo/integration/operation_legacy_test.go, mongo/integration/sessions_test.go, x/mongo/driver/wiremessage/wiremessage.go
This is a POC I've been working on and the changes for GODRIVER-1405 gave me a good reason for integrating it into our testing library. A summary of the changes made:
1. `received_message.go`, `sent_message.go`, and `wiremessage_helpers.go` contain types and helper functions for parsing sent and received wire messages. The messages are parsed into a view that unifies OP_QUERY and OP_MSG, but a raw copy of the entire message is also stored so we can check exact bits if we want.
2. `proxy_dialer.go` contains the `ContextDialer` and `net.Conn` interface implementations. The `proxyDialer` stores pairs of messages rather than separate slices for sent and received because it can access the wire message RequestID and match them up to make things easier for developers. It stores messages in two …
=> Implement a proxy dialer for integration tests

mongo/errors.go, mongo/integration/errors_test.go, x/mongo/driver/errors.go, x/mongo/driver/operation_legacy.go, x/mongo/driver/topology/connection.go
If a context is translated to a network read/write deadline and the
read/write call returns a timeout error, this commit will swallow
that error and replace it with context.DeadlineExceeded so the
resulting error will return true for
errors.Is(err, context.DeadlineExceeded).
=> GODRIVER-1581 Transform network errors into context.DeadlineExceeded

mongo/integration/mtest/mongotest.go, mongo/integration/sdam_error_handling_test.go, mongo/integration/sessions_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/server.go
The change itself is simple: we no longer update the topology for successful connection handshakes because doing so doesn't gain us much and could actually hurt because it can cause resource contention if the applcation has many concurrent operations making connections, which would all try to update the topology even during steady-state. This PR also moves the SDAM error handling for connection handshakes to be earlier. Instead of doing it when a connection is checked out, we now do it inside `connection.connect` itself. This prevents an error from sitting around for a long time in the pool before it's actually processed and/or becomes stale.
@iwysiu This will probably require changes to your code for GODRIVER-1572 as well.
=> GODRIVER-1658 Fix connection updates to topology

.evergreen/config.yml, mongo/ocsp_test.go
1. All OCSP tests are tagged with either `ocsp-rsa` or `ocsp-ecdsa` based on the certificate algorithm used.
2. All OCSP tests that require the server to staple a respones are tagged with `ocsp-staple`.
3. Matrices for macos and Windows were added to our Evergreen config. Both matrices only run tests that use RSA certificates and do not require stapling support.
=> GODRIVER-1650 Test OCSP on macos and Windows

x/mongo/driver/topology/server.go
Server descriptions used to set the server to Unknown after a network
error should not have TopologyVersion set because they always need to be
applied to the topology.
=> GODRIVER-1572 Fix server description creation for network errors

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
https://jira.mongodb.org/browse/GODRIVER-1663
=> GODRIVER-1663 setting cancelConext to nil to avoid context being pinned

x/mongo/driver/topology/server.go
The original code unwrapped `ConnectionError` to get the actual error which could have a `TopologyVersion` field, but I realized this is problematic because the error should be re-wrapped when actually creating the server description. This PR introduces a helper function to unwrap and get the TV without modifying the actual error, which is later used to set `description.Server.LastError`.
=> GODRIVER-1489 Correctly unwrap topology version for monitor check errors

README.md
This pull request updates the `README.md` with a reminder to the user to import the `"go.mongodb.org/mongo-driver/bson"` package when following the documentation.
=> Added bson to import statement

data/server-discovery-and-monitoring/single/too_old_then_upgraded.json, data/server-discovery-and-monitoring/single/too_old_then_upgraded.yml, x/mongo/driver/topology/sdam_spec_test.go
I added an assertion to the SDAM spec test runner to ensure that `fsm.compatibilityError` is nil if the test expects the topology to be compatible and non-nil if not. This assertion is important to ensure that we won't keep around a stale compatibility error if an incompatible server later becomes compatible.
=> GODRIVER-1534 Sync spec tests for incompatible server becoming compatible

data/server-discovery-and-monitoring/rs/repeated.json, data/server-discovery-and-monitoring/rs/repeated.yml
We were already running the SDAM flow for every new server description, regardless of equality, so the only changes here are spec test resyncs.
=> GODRIVER-1511 Test that SDAM flow is always run

bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/time_codec.go, bson/bsonrw/extjson_wrappers.go, bson/primitive/primitive.go, bson/primitive/primitive_test.go
I also went through and changed places that were directly converting `time.Time` to int64 to use `NewDateTimeFromTime` instead.
=> GODRIVER-1688 Remove UnixNano call from NewDateTimeFromTime

data/auth/connection-string.json, data/auth/connection-string.yml, x/mongo/driver/connstring/connstring.go
EDIT: This PR now also contains the spec tests and changes made in SPEC-1313.
GODRIVER-1479
GODRIVER-1577
=> Resync auth tests and error for empty authSource in a URI

x/mongo/driver/description/topology.go, x/mongo/driver/topology/fsm.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
https://jira.mongodb.org/browse/GODRIVER-1659
This pull request will ensure that if any server has an incompatible `WireVersion`, it will fail fast during server selection and return the appropriate error in order to be consistent with the spec.
=> GODRIVER-1659 fail fast during server selection if incompatible WireVersion

bson/bsoncodec/byte_slice_codec.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/string_codec.go, bson/bsoncodec/time_codec.go, bson/bsoncodec/uint_codec.go
This is branched off of the PR for GODRIVER-1680, so it includes all of those changes as well. Once that's merged, I can rebase and force-push.
EDIT: GODRIVER-1680 has been merged and rebased. This PR now only contains changes made for GODRIVER-1681.
=> GODRIVER-1681 Add typeDecoder implementations for non-recursive types

mongo/integration/json_helpers_test.go, x/mongo/driver/topology/server.go
We cancel the check when a network error happens during an operation after the
connection handshake, but not when one happens during a connection handshake.
This commit fixes that.
=> GODRIVER-1489 Ensure server check is cancelled for network errors during handshake

mongo/errors.go, mongo/integration/collection_test.go, mongo/integration/crud_prose_test.go
No changes were needed for `mongo.CommandError`. The `mongo.WriteConcernError` type had a `Name` field but it wasn't being filled in, so I fixed that and added tests for both error types.
=> GODRIVER-1706 Ensure codeName is propagated for errors

x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
Evergreen patch: https://spruce.mongodb.com/version/5f2dd0057742ae3bdd6b4d14/tasks
=> GODRIVER-1708 Set starting time for monitoring connection handshake

x/bsonx/bsoncore/bson_arraybuilder.go, x/bsonx/bsoncore/bson_arraybuilder_test.go, x/bsonx/bsoncore/bson_documentbuilder.go, x/bsonx/bsoncore/bson_documentbuilder_test.go
The DocumentBuilder and ArrayBuilder Build() functions return both a Document/Array and an error, so they can't be used inline when declaring a struct. They don't need to return errors, though, because we're building the BSON, so we know it is not malformed.
=> GODRIVER-613 Remove error return from bsoncore builders

internal/cancellation_listener.go, mongo/integration/sdam_error_handling_test.go, x/mongo/driver/topology/cancellation_listener.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
We could do this by adding a `connection.listenForCancellation` function and a channel to signal that the listening should stop, but this is difficult to test. Consider the case where `writeWireMessage` doesn't write to the channel to signal that the `listenForCancellation` function should stop. Everything still works, but we have a goroutine leak because `listenForCancellation` blocks waiting on the channel write, which doesn't happen. To make this easier to test, I added a `CancellationListener` abstraction, which can be mocked in tests to track the number of times `Listen` and `StopListening` are called.
=> GODRIVER-1662 Respect context.Cancellation for network operations

internal/background_context.go, internal/background_context_test.go, mongo/session.go, mongo/with_transactions_test.go
Main open question is whether this should apply to all `AbortTransaction` calls or only those done implicitly through `WithTransaction`. For the initial PR, I have it apply to all calls, but I'm open to changing it if anyone disagrees.
EDIT: After thinking about this more, I changed it to only use the special context for implicit `AbortTransaction` calls done via `WithTransaction`.
=> GODRIVER-1653 Use non-timeout context for AbortTransaction

mongo/collection.go, mongo/database.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/database_test.go, mongo/options/listcollectionsoptions.go, x/mongo/driver/operation/list_collections.go
1. `Collection.Insert*`, `Collection.Delete*`, and `Collection.Update*` helpers changed to `ordered: true` unconditionally.
2. `ListCollections` changed to accept a `BatchSize` option. The command generation now appends a `cursor` subdocument, similar to that for `aggregate`. There is a new test in `mongo/integration/database_test.go` for this option.
3. The expectation comparison code in our test runners changed to use `LookupErr` instead of `Lookup`. It now uses `assert.Nil`/`assert.NotNil` on that error to assert that a field is present/absent in a command.
=> GODRIVER-526 Unskip keys in command monitoring assertions

mongo/integration/sdam_error_handling_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
I took this ticket as an opportunity to add some integration tests for SDAM error handling. They now ensure that we correctly process NodeIsRecovering and NotMaster errors correctly when they're in an ok:0 or writeConcernError document. Unfortunately, each test takes ~0.5 seconds to run because of minHeartbeatFrequency, but I still think they're worth having. Also, we don't have SDAM monitoring, so we can't actually assert that the server was marked Unknown, but by testing on both 4.0 and 4.2, we can assert that the server's connection pool was cleared, which is at least enough to ensure that we're correctly entering the SDAM error handling code path.
=> GODRIVER-1726 Fix SDAM error handling for write concern errors

data/change-streams/README.rst, data/change-streams/change-streams-errors.json, data/change-streams/change-streams-errors.yml, data/change-streams/change-streams.json, data/change-streams/change-streams.yml, mongo/integration/change_stream_spec_test.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/command_monitoring_test.go, mongo/integration/unified_spec_test.go
This commit also modifies our checking of command monitoring events in tests:
- Skip monitoring assertions if the expectations field in the test JSON is null
- Assert that no events were published if the expectations field is a non-null empty array
=> GODRIVER-1725 Resync change stream spec tests

.evergreen/config.yml, bson/bson_test.go, bson/raw_value.go, mongo/mongo_test.go, x/bsonx/bsoncore/bsoncore.go, x/mongo/driver/wiremessage/wiremessage.go
I filed two separate tickets to use Go 1.15 in Evergreen and to fix vet/fmt errors for 1.15, but they're dependent on each other so I have them in one pull request. Once this is approved, we can figure out if we want to backport both or rebase/merge instead of squashing and just backport the vet/fmt fixes.
=> Use Go 1.15 in Evergreen

bson/bsoncodec/default_value_decoders_test.go
This change is needed because the stringification of the `url.Error` type changed between 1.13 and 1.15. To make the test more robust to these sorts of changes, we directly construct a `url.Error` and compare to that rather than using knowledge about the stringified value. This change is only needed on the release/1.4 branch because it was already done on the master branch as part of GODRIVER-1680.
=> GODRIVER-1729 Fix test error for 1.15

data/retryable-writes/insertOne-serverErrors.json, data/retryable-writes/insertOne-serverErrors.yml, mongo/integration/json_helpers_test.go
I resynced the retryable writes tests as part of this PR because the
changes for the spec tests and the test runner are related.
The test runner change is to correctly check error names and labels. Our
existing code only honors these expectations if the error is a
`mongo.CommandError` (i.e. an `ok: 0` error from the server). However,
these expectations can exist for `ok: 1` cases if there was a write
concern error. The test runner now extracts common details from
different error types and then makes the necessary assertions.
GODRIVER-1739
GODRIVER-1741
=> Fix checks for error names and labels in spec tests

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/registry.go, mongo/cursor.go, mongo/index_options_builder.go, mongo/options/clientoptions.go, mongo/options/findoptions.go, mongo/options/indexoptions.go, mongo/session.go
I found these deprecations via `git grep "deprecated"`. After fixing the notices, I ran the `staticcheck` linter against https://play.golang.org/p/3jPWZqPMt0H and ensured that all of the usages are marked as deprecated.
If anyone wants to reproduce the results, run `go get honnef.co/go/tools/cmd/staticcheck` to install the linter and copy/paste the the code from the playground link into a local script.
I couldn't test deprecation warnings for struct fields due to https://github.com/dominikh/go-tools/issues/607. This means that the `AuthenticateToAnything` and `Deployment` Client options can't be tested because they don't have corresponding setter functions. To work around this for `FindOptions`, `FindOneOptions`, and `IndexOptions`, I deprecated both the struct field and the setter …
=> GODRIVER-1736 Fix deprecation notice formats

internal/string_util.go, mongo/description/server.go, mongo/description/server_test.go, x/mongo/driver/auth/auth.go, x/mongo/driver/auth/default.go, x/mongo/driver/auth/speculative_scram_test.go, x/mongo/driver/auth/speculative_x509_test.go, x/mongo/driver/driver.go, x/mongo/driver/operation/ismaster.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
The main change here is to remove the `SpeculativeAuthenticate` and `SaslSupportedMechs` fields from `description.Server`. The idea is that these fields are only required for the connection handshake, so we don't need to track them once that's done. To do this, I changed the `driver.Handshaker` interface from
```
type Handshaker interface {
GetDescription(context.Context, address.Address, Connection) (description.Server, error)
}
```
to
```
type HandshakeInformation struct {
Description             description.Server
SpeculativeAuthenticate bsoncore.Document
SaslSupportedMechs      []string
}
type Handshaker interface {
GetHandshakeInformation(context.Context, address.Address, Connection) (HandshakeInformation, error)
}
```
The `IsMaster` operation changed to continue implementing this …
=> GODRIVER-1740 Remove auth-related fields from description.Server

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/default_value_encoders_test.go, bson/bsoncodec/pointer_codec.go, bson/bsoncodec/struct_codec.go, bson/marshal_test.go, bson/unmarshal_test.go
It was complicated to put these tests in the `bsoncodec` package because it required a lot of manual setup, so I put them in the `bson` package as a type of "integration" test for `bsoncodec` instead. This lets us push down all of the setup work to helpers that already exist in `bson`.
=> GODRIVER-1751 Ensure codecs that cache are not shared across registries

.evergreen/config.yml
I modified the linked patch build to run Windows tasks in addition to the existing Ubuntu ones. Do not LGTM if any of the Windows tasks have failed.
=> GODRIVER-1764 Use new mingw version in Evergreen tasks

mongo/integration/change_stream_spec_test.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/client_test.go, mongo/integration/command_monitoring_test.go, mongo/integration/crud_helpers_test.go, mongo/integration/data_lake_test.go, mongo/integration/database_test.go, mongo/integration/errors_test.go, mongo/integration/index_view_test.go, mongo/integration/mongos_pinning_test.go, mongo/integration/mtest/global_state.go, mongo/integration/mtest/mongotest.go, mongo/integration/primary_stepdown_test.go, mongo/integration/retryable_writes_spec_test.go, mongo/integration/sdam_error_handling_test.go, mongo/integration/sdam_prose_test.go, mongo/integration/sessions_test.go, mongo/integration/unified_spec_test.go
This is some clean up that's required for us to implement the unified test runner. The main change I made was moving some functions that had a `mtest.T` as their receiver to be standalone functions because they were just proxies to query global testing state. All of these functions moved from `mongotest.go` to `global_state.go`. The rest of the changes are in the callers.
=> GODRIVER-1394 Remove receiver from mongotest functions

x/mongo/driver/session/client_session.go, x/mongo/driver/session/client_session_test.go
This is required to implement the `assertSessionTransactionState` operation.
=> GODRIVER-1394 Export TransactionState from session.Client

x/mongo/driver/auth/internal/gssapi/sspi_wrapper.c
We currently call `LoadLibrary("secur32.dll")` in our SSPI code. This allows for DLL preloading attacks because an attacker can place a DLL with that name in the application directory and it would be favored over the system version.
The changes in this PR use `GetSystemDirectory` to find out where `secur32.dll` is located so we can construct the full path and ensure that `LoadLibrary` only looks for it there. The motivation for the solution is in the `LoadLibrary` documentation's [Parameters section](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya#parameters):
> If the string specifies a full path, the function searches only that path for the module.
> If the string specifies a relative path or a module name without a path, the function uses a …
=> GODRIVER-1757 Specify exact path for LoadLibrary call

Makefile, event/monitoring.go
I noticed the `event` package is missing from our Makefile. There were some `gofmt` issues in the SDAM monitoring event descriptions, so this PR fixes those and modifies the Makefile so these things are caught in CI.
=> Add event package to Makefile and fix gofmt errors

mongo/integration/unified/client_entity_test.go, mongo/integration/unified/entity_test.go
Our handling for the `useMultipleMongoses` option is incorrect because we're not verifying that there are multiple mongos servers if the option is explicitly set to true. See the `useMultipleMongoses` bullet in the `client` entity definition [here](https://github.com/mongodb/specifications/blob/61b8189193b8647b58ba18321aaf4a77933aa7b9/source/unified-test-format/unified-test-format.rst#entity) for a description of the correct behavior.
=> GODRIVER-1394 Require multiple hosts to exist if useMultipleMongoses=true

.evergreen/config.yml
FLE tests require the 1.1.0-beta download, which is uploaded to a different fixed URL than the latest stable release.
=> GODRIVER-1780 Use unstable URL for libmongocrypt Windows tests.

mongo/collection.go
In current version, `coll.InsertOne(ctx,doc,nil)` will trigger panic, because `opts` will be [nil] inside `InsertOne()`, then panic happens when call `opt.BypassDocumentValidation != nil`:
```
func (coll *Collection) InsertOne(ctx context.Context, document interface{},
opts ...*options.InsertOneOptions) (*InsertOneResult, error) {
imOpts := make([]*options.InsertManyOptions, len(opts))
for i, opt := range opts {
imo := options.InsertMany()
if opt.BypassDocumentValidation != nil && *opt.BypassDocumentValidation {
imo = imo.SetBypassDocumentValidation(*opt.BypassDocumentValidation)
}
imOpts[i] = imo
}
...
```
=> GODRIVER-1793 Avoid panic if opts is nil when call InsertOne 

README.md
In particular, this is to make the documentation for configuring authentication more discoverable.
=> GODRIVER-1789 link to Connect docs in README

mongo/index_view.go, mongo/integration/index_view_test.go
After reading through, I'm pretty sure that this is the only spot that isn't replacing errors correctly. Also fixed the CreateMany commitQuorum tests while i was there.
=> GODRIVER-1788 correctly replace errors in IndexView CreateMany

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go
Checks the length of the read message in `connection#readWireMessage()` to make sure it does not exceed the `MaxMessageSize` defined in the server description.
Adds a unit test to make sure error is raised.
=> GODRIVER-150 Raise error for read message length too large 

bson/unmarshal_test.go
[GODRIVER-1805](https://jira.mongodb.org/browse/GODRIVER-1805)
Adds tests for unmarshalling BSON with undefined fields. Faulty behavior was recently discovered when unmarshalling extended JSON with undefined fields; this behavior was fixed in [1235](https://jira.mongodb.org/browse/GODRIVER-1235), and test coverage was added. The same faulty behavior does not exist for BSON, but these tests should cover any theoretical `value_reader#Skip()` errors.
=> GODRIVER-1805 Add tests for unmarshalling BSON with undefined fields

mongo/doc.go, mongo/errors.go, mongo/integration/errors_test.go
Still not sure about add Unwrap to the interface when CommandError is the only one that actually uses it.
=> GODRIVER-1802 add ServerError interface

mongo/integration/index_view_test.go
This is just removing it so that tests pass while we wait for the drivers ticket. I can alter the code instead if this seems too hack-y.
=> GODRIVER-1794 remove SetBucketSize from TestIndexView/create_one/all_options

mongo/gridfs/download_stream.go, mongo/integration/gridfs_test.go
- Fix bug when skip lands on chunk boundary
=> GODRIVER-1806 Fix and test DownloadStream.Skip()

.evergreen/config.yml
[GODRIVER-1848](https://jira.mongodb.org/browse/GODRIVER-1848)
Fixes the currently broken versioned API tests `test-replicaset-versioned-api` (now `standalone`) and `test-standalone-versioned-api-test-commands`.
The new versioned API tests do not need to be run against replica sets. There is no way to enable `requireAPIVersion` on replica sets through mongo orchestration currently, so we can only test against standalone. And, only the `transaction-handling` spec test needs a replica set, but it will be run in other tasks anyway. 
The separate `test-standalone-versioned-api-test-commands` task does not need to be run with auth, either. Running with auth was causing an error because the [versioned-api-testing.json](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergree …
=> GODRIVER-1848 Only test versioned API tasks against standalone and use noauth

mongo/integration/collection_test.go, x/mongo/driver/batch_cursor.go
[GODRIVER-1831](https://jira.mongodb.org/browse/GODRIVER-1831)
Includes change [from this PR](https://github.com/mongodb/mongo-go-driver/pull/561) to legacy `batch_cursor#getMore()` to fix a bug found by an external user on MDB versioned 2.6.12: when `numReturned == limit` and `batchSize` is not set on a `batchCursor` an extra `getMore` is run when the cursor should have just been closed
Adds a test to make sure that when `batchSize` is not set on a `batchCursor`, a set limit will not be surpassed accidentally.
=> GODRIVER-1831 Avoid accidental extra getMore when using limit on Find

x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/errors.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_test.go
[GODRIVER-1849](https://jira.mongodb.org/browse/GODRIVER-1849)
Adds a new timeout error `WaitQueueTimeoutError` to wrap `ctx.Err()` so that users can detect a timeout error with `errors.Is(err, context.DeadlineExceeded)` or `mongo.IsTimeout()`.
=> GODRIVER-1849 Add new WaitQueueTimeoutError to wrap context error

event/doc.go, event/examples_test.go, event/monitoring.go
I didn't go into what the different monitor functions were for, since they have short descriptions in monitoring.go, but I can add it if it seems helpful.
=> GODRIVER-1817 add docs.go for event package

mongo/options/findoptions.go
[GODRIVER-1775](https://jira.mongodb.org/browse/GODRIVER-1775)
Deprecates `FindOneOptions` `BatchSize`, `CursorType`, `NoCursorTimeout` and their setter functions in `findoptions` since they refer to a cursor that is not actually created in a `findOne` operation.
=> GODRIVER-1775 Deprecate unnecessary FindOne options

mongo/integration/mtest/setup.go
[GODRIVER-1877](https://jira.mongodb.org/browse/GODRIVER-1877)
Fixes Atlas Data Lake integration test, which was failing because "getParameter" was being run against the data lake instance even though data lake does not support "getParameter".
Here's a small [patch](https://spruce.mongodb.com/version/602325dfe3c331145aae5e56/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) showing the fix, and that tests like versioned API that do use "getParameter" are unaffected.
=> GODRIVER-1877 Skip getParameter in ADL int test setup

bson/bson_test.go, bson/bsoncodec/array_codec.go, bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/default_value_encoders_test.go, bson/bsoncodec/types.go, bson/bsonrw/copier.go, bson/raw_test.go, bson/unmarshal_test.go, x/bsonx/bsoncore/array.go, x/bsonx/bsoncore/array_test.go, x/bsonx/bsoncore/document.go, x/bsonx/bsoncore/document_test.go
[GODRIVER-1846](https://jira.mongodb.org/browse/GODRIVER-1846)
Currently, `bsoncore.Array` is defined as `type Array = Document`, when it should really be a separate type that can be encoded as type 4 (array) in BSON instead of type 3 (embedded document). A new codec is required.
Adds a new `ArrayCodec`, a `tCoreArray` type, and adds `copier#CopyBytesToArrayWriter()`.
Adds a test to ensure that `[]bson.D` can be marshalled, unmarshalled to `bsoncore.Array`, and marshalled again without modifying the original BSON.
=> GODRIVER-1846 Add bsoncore.Array type with new codec

mongo/client_examples_test.go
[GODRIVER-1853](https://jira.mongodb.org/browse/GODRIVER-1853)
Adds documentation in `client_examples_test` under `Connect` for creating a mongo client with `ServerAPIOptions`.
=> GODRIVER-1853 Document versioned API usage

bson/doc.go
There was some confusion about the existing documentation for `omitempty` on the [MongoDB developer forums](https://developer.mongodb.com/community/forums/t/golang-mongo-driver-getting-omitempty-struct-tag-to-evaluate-golang-primitives/14354). This PR clarifies the documentation and explicitly outlines how empty-ness is determined for struct fields of different types. If there are no objections, I also plan on backporting this to the release/1.5 and release/1.4 branches when merging so the updated docs will show up in pkg.go.dev for releases on those branches.
=> Clarify omitempty documentation

mongo/integration/client_side_encryption_prose_test.go
[GODRIVER-1888](https://jira.mongodb.org/browse/GODRIVER-1888)
Appends the latest server API version in the recently edited CSE prose tests using `testutil.AddTestServerAPIVersion()`.
This fixes some failing versioned API tasks on Ubuntu and Windows. It also fixes some on MacOS, but there are remaining failures due to a server bug ([SERVER-54508](https://jira.mongodb.org/browse/SERVER-54508)). Here is a [patch](https://spruce.mongodb.com/version/602c4155850e610b329f0a5c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) showing success on all versioned API tasks except for failures due to the aforementioned server bug on latest MacOS.
To avoid missing server API version appends in the future, we should probably be running the versioned API tasks as part of regular PR CI. Will reach out …
=> GODRIVER-1888 Append test server API version in CSE prose test

mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/integration/mtest/opmsg_deployment.go, x/mongo/driver/topology/fsm.go, x/mongo/driver/topology/server_test.go, x/mongo/driver/topology/topology_test.go
Based on local logging, it seems like most of the time was spent deleting documents server-side. Switching to the mock deployment speeds up the test from ~57s to 0.25s. 
In addition to using the mock deployment for a specific test, this PR also modifies the mock deployment code to export a server description. This allows us to programatically determine the required batch size for a test without having to assume it's 100K. I also chose to export the `SupportedWireVersions` variable in the `topology` package so the mock deployment could access the max supported wire version rather than hardcoding it, which avoids the risk of it getting outdated.
=> GODRIVER-1858 Use mock deployment for slow BulkWrite test

README.md
Port number of 2nd replica must be 27019 instead of 27018.
=> Fix README replica set test example

mongo/errors.go, mongo/session.go, mongo/with_transactions_test.go
[GODRIVER-1852](https://jira.mongodb.org/browse/GODRIVER-1852)
Adds a check for network timeout after executing the operation within a commitTransaction. Avoids incorrectly updating transaction state to "Committed" in the case of a timeout. 
Adds test to make sure a transaction can still be aborted after a timed-out commitTransaction.
=> GODRIVER-1852 Add commitTransaction error check for timeout

x/mongo/driver/operation.go
[GODRIVER-1890](https://jira.mongodb.org/browse/GODRIVER-1890)
Adds extra, missing checks for a `nil` `Client` value on an `Operation` to avoid an accidental panic when `Client` is not set on an `Operation`.
=> GODRIVER-1890 Add nil Client checks

.evergreen/config.yml
[GODRIVER-1882](https://jira.mongodb.org/browse/GODRIVER-1882)
Uses new drivers tools `activate_venv.sh` [script](https://github.com/mongodb-labs/drivers-evergreen-tools/pull/138/files) in place of manual calls to "activate" scripts. This new script also installs the latest version of boto3, the AWS SDK for python.
This change fixes failing AWS Auth tests on Ubuntu (I've added these tests to the linked evg patch). The failure was due to an outdated version of the boto3 dependency.
=> GODRIVER-1882 Use new AWS setup script in Evergreen

bson/primitive/objectid.go, bson/primitive/objectid_test.go
For https://jira.mongodb.org/browse/GODRIVER-1893
Copy the description from above
>Description
bson-ruby has validation method for ObjectID format as `BSON::ObjectId.legal?(string)` ref: https://github.com/mongodb/bson-ruby/blob/13c42e1ca47f47abdb15485ef5615a9189549a97/lib/bson/object_id.rb#L307-L308
I'd like to use similar feature in golang.
=> GODRIVER-1893 Implement predicator for BSON ObjectID

internal/uri_validation_errors.go, mongo/client.go, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/dns/dns.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/topology/server_options.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_options.go, x/mongo/driver/topology/topology_options_test.go
The full design doc is linked in the main [epic ticket](https://jira.mongodb.org/browse/GODRIVER-1856). Summary of changes:
1. Add a `loadBalanced` URI option and an equivalent `ClientOptions#SetLoadBalanced` function.
2. Allow `loadBalanced` to be specified via TXT records.
3. Validate combinations of options when `loadBalanced=true`.
4. Do not start the SRV polling goroutine if `loadBalanced=true`.
Additional notes for reviewers:
1. Use of TXT records and validation of `loadBalanced=true` with SRV records that resolve to multiple hostnames is untested. I expect upstream spec tests to be added for these as the project progresses.
2. The validation code is duplicated in `ClientOptions#Validate` and `Connstring#Validate`. Ideally, it would only happen in `ClientOptions#Validate`, but it's …
=> GODRIVER-1894 Add support for loadBalanced URI option

.evergreen/config.yml, data/client-side-encryption/README.rst, data/client-side-encryption/awsTemporary.json, data/client-side-encryption/awsTemporary.yml, mongo/integration/client_side_encryption_spec_test.go, mongo/integration/json_helpers_test.go
[GODRIVER-1855](https://jira.mongodb.org/browse/GODRIVER-1855)
Adds support for temporary AWS credentials in spec test helpers.
Adds new `awsTemporary` spec tests. Updates client-side-encryption test README.
=> GODRIVER-1855 Support AWS authentication with temporary credentials in CSFLE

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/tls_connection_source.go
This PR modifies the connection code to apply the `connectTimeoutMS` option to both socket establishment and the TLS handshake. Previously, it was only applied to the former. To aid in testing, I also modified the existing `tlsConnectionSource` interface to return a new `tlsConn` interface rather than directly returning a concrete `tls.Conn`. This allows us to provide a custom implementation for TLS handshaking in our tests.
The alternate approach considered was to use [tls.Dialer](https://golang.org/pkg/crypto/tls/#Dialer) or [tls.DialWithDialer](https://golang.org/pkg/crypto/tls/#DialWithDialer). These aren't flexible enough because they require us to specify a [net.Dialer](https://golang.org/pkg/net/#Dialer) as the dialer for the underlying network socket, but we actually accept a …
=> GODRIVER-1879 Apply connectTimeoutMS to TLS handshake

mongo/client.go, mongo/description/server.go, mongo/description/server_kind.go, mongo/description/server_selector.go, mongo/description/topology_kind.go, x/mongo/driver/auth/auth.go, x/mongo/driver/operation/ismaster.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/topology.go
1. Send `loadBalanced: true` in application connection handshakes.
2. Record the new `serverId` field when parsing `isMaster` responses.
3. Add a new `LoadBalanced` TopologyKind type and `LoadBalancer` ServerKind.
4. Ensure the LB is always selected during server selection.
5. Do not start a monitoring connection in LB mode and instead publish a pre-determined set of SDAM events at configuration time.
Additional notes:
1. For server selection, I modified each exported server selector implementation (e.g. `ReadPrefSelector`, `WriteSelector`, etc) as well as the top-level `Topology#SelectServer` function. We need to modify each selector individually because server selection spec tests will use these selectors directly.
2. I changed `description.Server#String` to only …
=> GODRIVER-1895 SDAM, server selection, and handshake changes for LB mode

internal/testutil/ops.go, mongo/integration/initial_dns_seedlist_discovery_test.go, x/mongo/driver/integration/aggregate_test.go, x/mongo/driver/integration/scram_test.go, x/mongo/driver/topology/topology.go
[GODRIVER-1197](https://jira.mongodb.org/browse/GODRIVER-1197)
Removes the `topology.SelectServerLegacy()` function and replaces all occurrences with `topology.SelectServer()`.
Updates `testutil.RunCommand()` (a helper used alongside `topology.SelectServerLegacy()`) to use a `driver.Server`, the return type of `topology.SelectServer()`
=> GODRIVER-1197 Remove selectServerLegacy function

event/monitoring.go, x/mongo/driver/operation.go
Only change is to add `ServerID` to `CommandStartedEvent` and `CommandFinishedEvent`.
=> GODRIVER-1896 Add ServerID to command monitoring events

x/mongo/driver/batch_cursor.go, x/mongo/driver/operation.go, x/mongo/driver/operation/abort_transaction.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/command.go, x/mongo/driver/operation/commit_transaction.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation/create.go, x/mongo/driver/operation/createIndexes.go, x/mongo/driver/operation/delete.go, x/mongo/driver/operation/distinct.go, x/mongo/driver/operation/drop_collection.go, x/mongo/driver/operation/drop_database.go, x/mongo/driver/operation/drop_indexes.go, x/mongo/driver/operation/end_sessions.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/insert.go, x/mongo/driver/operation/ismaster.go, x/mongo/driver/operation/listDatabases.go, x/mongo/driver/operation/list_collections.go, x/mongo/driver/operation/list_indexes.go, x/mongo/driver/operation/update.go, x/mongo/driver/operation_exhaust.go, x/mongo/driver/operation_legacy.go
To support load balanced clusters, we need to sometimes pin resources like connections and transactions to a single connection. We can do this by modifying the [response processing function](https://github.com/mongodb/mongo-go-driver/blob/9f796d93bf13a28aa074b573df1dac4e41bd47d5/x/mongo/driver/operation.go#L116) that gets called when an operation is executed to take a new `driver.Connection` argument. However, that function already takes four arguments, so this PR introduces a new `ResponseInfo` type to hold all of these arguments along with a new `Connection` field. In my opinion, this makes the API much cleaner.
Note that this PR doesn't change individual operations to actually pin connections to resources. That will come in a later PR for the same ticket.
=> GODRIVER-1897 Add a ResponseInfo type for processing server responses

mongo/database.go, mongo/description/server.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/driver.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/command.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/list_collections.go, x/mongo/driver/operation/list_indexes.go, x/mongo/driver/topology/connection.go
1. Introduce a `driver.PinnedConnection` interface to represent the fact that connections can be pinned by cursors and transactions. Currently, only the cursor functionality is used. A future PR will utilize the transaction functions as well. Note that this interface has separate `PinToCursor` and `PinToTransaction` methods rather than a generic `Pin` method because this project requires us to track the reason for which a connection is pinned. This PR only sets us up to do that; a future PR will plumb these statistics down to the connection pool and use them in error messages (GODRIVER-1901).
2. `BatchCursor` holds on to a connection if it detects that the server is behind an LB. It uses this connection to execute `getMore` and `killCursors` commands. The connection is …
=> GODRIVER-1897 Pin cursors to a connection in LB mode

x/mongo/driver/driver.go, x/mongo/driver/operation.go, x/mongo/driver/session/client_session.go
This PR adds functionality to pin transactions to a connection for load-balanced deployments. It is the last of the connection pinning PRs for load balancer support.
1. A new `session.LoadBalancedTransactionConnection` interface has been added. This interface is a copy of `driver.PinnedConnection`. It exists only because using `driver.Connection` directly creates an import cycle (`driver.Operation` depends on `session.Client`, so `session.Client` can't also depend on `driver.PinnedConnection`). Ideally, we'd put the `PinnedConnection` interface in another package along with the related `Connection` and `Expirable` interfaces, but this is a bigger refactoring than I'd like to take on for this project and would be a breaking change for low-level driver users like BIC.
2. …
=> GODRIVER-1897 Pin transactions to a connection in LB mode

data/versioned-api/crud-api-version-1-strict.json, data/versioned-api/crud-api-version-1-strict.yml, data/versioned-api/crud-api-version-1.json, data/versioned-api/crud-api-version-1.yml, data/versioned-api/runcommand-helper-no-api-version-declared.json, data/versioned-api/runcommand-helper-no-api-version-declared.yml, data/versioned-api/test-commands-deprecation-errors.json, data/versioned-api/test-commands-deprecation-errors.yml, data/versioned-api/test-commands-strict-mode.json, data/versioned-api/test-commands-strict-mode.yml, data/versioned-api/transaction-handling.json, data/versioned-api/transaction-handling.yml
[GODRIVER-1907](https://jira.mongodb.org/browse/GODRIVER-1907)
[GODRIVER-1908](https://jira.mongodb.org/browse/GODRIVER-1908)
Syncs versioned API tests. Adds a new test to ensure abortTransaction does not send API version and updates all versioned API tests to run on only 4.9+.
=> Update Versioned API Spec Tests

bson/bsoncodec/default_value_decoders.go, bson/bsoncodec/default_value_decoders_test.go
Try to run this code
```
type Entity struct {
ID primitive.ObjectID `bson:"_id"`
}
func main() {
var e Entity
err := bson.UnmarshalExtJSON([]byte(`{"_id":"5ef7fdd91c19e3222b41b839"}`), true, &e)
log.Fatal(err)
}
}
```
You'll get an `ObjectID string must be exactly 12 bytes long`. Obvious bug
=> GODRIVER-1919 Add object id decoder awareness of string hex

event/monitoring.go, x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_generation_counter.go, x/mongo/driver/topology/pool_test.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
1. Instead of tracking a pool's generation number as a single `uint64`, use a map from `serverID` (which is an ObjectID) to a tuple of `(generation number, connection count)`. In this new map type, `primitive.NilObjectID` is used to store the generation and connection count for servers that do not return a `serverId` field in `ismaster` responses (i.e. servers in non-load balanced deployments).
2. When clearing the pool, only clear connections for a specific server ID.
3. Add a `ServerID` field to `PoolCleared` events.
4. Ignore connection establishment errors that occur before the server ID is known for connections to LBs.
=> GODRIVER-1898 SDAM error handling changes for LB mode

x/bsonx/bsoncore/bsoncore.go, x/bsonx/bsoncore/value_test.go
[GODRIVER-1918](https://jira.mongodb.org/browse/GODRIVER-1918)
Adds a check for zero length strings in readstring to ensure that a malformed string such as `{0x0, 0x0, 0x0, 0x0}` will not panic with `StringValue()` and `StringValueOk()`.
Adds two new tests to verify no panic in the case of zero-length strings.
=> GODRIVER-1918 Check for zero length in readstring

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/errors.go, x/mongo/driver/topology/pool.go
This PR modifies the `pool` type to track the number of connections that are checked out for cursors and transactions. The `Connection` type increments these statistics when a `Pin*` function is called and decrements when the connection is expired or returned to the pool. Per the spec, I've also updated the `WaitQueueTimeoutError` type to include these statistics. They're accessible in code via exported fields on the error type and in the error message generated by the type's `Error` function.
=> GODRIVER-1901 Add details to wait queue timeout errors

bson/bsonrw/value_writer.go, bson/extjson_prose_test.go, bson/marshal_test.go, x/bsonx/bsoncore/bsoncore.go, x/bsonx/bsoncore/bsoncore_test.go
Per bsonspec.org, cstrings are only used for BSON key names and for the pattern/options fields in a BSON regex value so this PR applies validation to those types. This validation does not apply to regular BSON strings, which can have null bytes because they're prefixed with a 4-byte length. It also does not apply to extended JSON because the JSON specification allows null bytes and other unicode code points as long as they are properly escaped (e.g. in JSON, this would look like `{"foo\u0000": "bar"}`.
=> GODRIVER-1923 Error if BSON cstrings contain null bytes

README.md
Hi, I found the case of error handling in the README was inaccurate. We need to handle the case that error is `ErrNoDocuments` separately. [go-redis](https://github.com/go-redis/redis#quickstart) has a similar design. So I changed `README` to point out this case.
=> feat(README.md): more accurate error handling for using FindOne

mongo/change_stream.go, mongo/client.go, mongo/collection.go, mongo/database.go, mongo/index_view.go, mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/integration/database_test.go, mongo/integration/index_view_test.go, x/mongo/driver/operation/command.go
This PR adds a new `mongo.createBaseCursorOptions` function to ensure that options that apply to all cursor-related commands are set before being passed down to the operations layer. I've also re-introduced a `CursorOptions` paramter to the `operation.Command` type. This was removed when doing the LB support work because it was always empty, but the empty options was actually a bug.
=> GODRIVER-1934 Ensure correct CursorOptions are used

event/monitoring.go, mongo/description/server.go, x/mongo/driver/operation.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_generation_counter.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
This change is to keep us in sync with a recent change in the LB spec.
=> GODRIVER-1958 Rename ServerID to ServiceID

x/bsonx/bsoncore/array_test.go, x/bsonx/bsoncore/bsoncore.go, x/bsonx/bsoncore/bsoncore_test.go, x/bsonx/bsoncore/document.go, x/bsonx/bsoncore/value.go, x/bsonx/bsoncore/value_test.go, x/mongo/driver/errors.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation_legacy.go
[GODRIVER-1930](https://jira.mongodb.org/browse/GODRIVER-1930)
Changes `bsoncore#ReadArray()` to return the `bsoncore#Array` type instead of the `bsoncore#Document` type, a change that should have been handled in [GODRIVER-1846](https://jira.mongodb.org/browse/GODRIVER-1846).
This change modifies the return type of `bsoncore#Array()` and `bsoncore#ArrayOK()`, which in turn requires some changes to testing and `x` level code; all small changes 😄 .
=> GODRIVER-1930 bsoncore Array functions should return Array

mongo/change_stream.go, mongo/client.go, mongo/collection.go, mongo/database.go, mongo/index_view.go, mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/integration/database_test.go, mongo/integration/index_view_test.go
This is a PR for the backport of GODRIVER-1934 because there were merge conflicts when backporting because the `RunCommandCursor` code has changed when implementing LB support.
=> GODRIVER-1934 Ensure correct CursorOptions are used (#625)

.evergreen/config.yml, Makefile, mongo/integration/client_side_encryption_prose_test.go
[GODRIVER-1916](https://jira.mongodb.org/browse/GODRIVER-1916)
Adds two new CSFLE prose tests to test that TLS connections to KMS servers actually verify peer certificates.
Updates Evergreen config to launch KMS mock servers for testing.
=> GODRIVER-1916 Test that KMS TLS connections verify peer certificates

.evergreen/config.yml
[GODRIVER-1941](https://jira.mongodb.org/browse/GODRIVER-1941)
Uses Ubuntu 18.04 instead of Ubuntu 16.04 in Evergreen tasks.
=> GODRIVER-1941 Run Evg tasks on Ubuntu 18.04

data/versioned-api/crud-api-version-1-strict.json, data/versioned-api/crud-api-version-1-strict.yml
[GODRIVER-1924](https://jira.mongodb.org/browse/GODRIVER-1924)
The now un-skipped test won't pass until the "latest" server version compiles on this [commit](https://evergreen.mongodb.com/version/mongodb_mongo_master_075e51fefecc54e219c56e75c3ba08c993b5c187#%230), so I won't merge until the test passes in CI.
=> GODRIVER-1924 Remove skipReason from estimatedDocumentCount test for versioned API

x/mongo/driver/topology/sdam_spec_test.go
GODRIVER-1979
Removes a few lingering usages of `bsoncore.Array#Elements()` and replaces them with `bsoncore.Array#Values()`.
=> GODRIVER-1979 Use array.Values instead of array.Elements

data/versioned-api/README.rst, data/versioned-api/test-commands-deprecation-errors.json, data/versioned-api/test-commands-deprecation-errors.yml
GODRIVER-1960
Replaces all instances of `acceptAPIVersion2` with `acceptApiVersion2` in spec test code. (The server recently changed the parameter to comply with acronym style guidelines).
This should stop us from skipping the versioned api `test-commands-deprecation-errors` spec test unintentionally.
=> GODRIVER-1960 Replace acceptAPIVersion2 with acceptApiVersion2

data/retryable-reads/aggregate-merge.json, data/retryable-reads/aggregate-merge.yml, data/retryable-reads/changeStreams-client.watch-serverErrors.json, data/retryable-reads/changeStreams-client.watch-serverErrors.yml, data/retryable-reads/changeStreams-client.watch.json, data/retryable-reads/changeStreams-client.watch.yml, data/retryable-reads/changeStreams-db.coll.watch-serverErrors.json, data/retryable-reads/changeStreams-db.coll.watch-serverErrors.yml, data/retryable-reads/changeStreams-db.coll.watch.json, data/retryable-reads/changeStreams-db.coll.watch.yml, data/retryable-reads/changeStreams-db.watch-serverErrors.json, data/retryable-reads/changeStreams-db.watch-serverErrors.yml, data/retryable-reads/changeStreams-db.watch.json, data/retryable-reads/changeStreams-db.watch.yml, data/retryable-reads/estimatedDocumentCount-4.9.json, data/retryable-reads/estimatedDocumentCount-serverErrors-4.9.json
As part of LB testing, we'll need to run some of the existing spec tests against LB clusters. These spec tests will require some modifications to ensure they can run (e.g. the `topology` arrays will need to include `load-balanced`). Those changes are described in https://github.com/mongodb/specifications/pull/961. This PR syncs the retryable reads spec tests with the ones present in the `master` branch of the specs repo to ensure that we can easily pull in the new changes from the linked spec PR when it is merged.
=> GODRIVER-1931 Sync retryable reads spec tests

.evergreen/config.yml, Makefile, internal/const.go, mongo/description/server.go, mongo/integration/load_balancer_prose_test.go, mongo/integration/main_test.go, mongo/integration/mtest/global_state.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/setup.go, mongo/integration/unified/client_entity.go, mongo/integration/unified/collection_operation_execution.go, mongo/integration/unified/database_operation_execution.go, mongo/integration/unified/main_test.go, mongo/integration/unified/operation.go, mongo/integration/unified/unified_spec_runner.go, mongo/integration/unified/unified_spec_test.go
This PR contains the changes needed to run load balancers in Evergreen and some updates to the mtest packakge to handle load balancer URIs. I also added a `load_balancer_prose_test.go` file to fill in some missing test coverage. There were a couple of missing/untested operations in the unified test runner so there are some changes required for that as well.
I called out some notable changes in PR comments, but there are additional changes that span multiple files:
1. There is currently no upstream service (e.g. mongos) that supports running behind an LB. To test against a sharded cluster without waiting for upstream support, this PR introduces a `SetServiceID` flag in `internal/const.go`. This flag is used in `description/server.go` when parsing `hello` command responses and enables a …
=> GODRIVER-1931 Run tests against LBs in Evergreen

data/transactions/unified/mongos-unpin.json, data/transactions/unified/mongos-unpin.yml
This ticket requires syncing the new tests added in https://github.com/mongodb/specifications/commit/ec326862be443d11f0233cee2de32a95751144df. I tried syncing the whole test file, but it has been changed to require version 1.4 of the unified test format in the `master` branch of the specs repo due to https://github.com/mongodb/specifications/commit/3586db8b1ed90d835737f6226bb3ff9012cfc5de. We don't support this version of the format yet as that will be done in GODRIVER-1861, so I manually synced over the new `unpin after non-transient error on abort` test.
=> GODRIVER-1981 Sync new transactions tests

mongo/errors.go, mongo/integration/sdam_error_handling_test.go
I could technically make labeledError a public interface, but I don't think users get much benefit from it.
=> GODRIVER-1955 create labeledError interface

mongo/gridfs/download_stream.go, mongo/integration/gridfs_test.go
GODRIVER-1925
Checks for a possible cursor error in `DownloadStream#FillBuffer` instead of always returning `errNoMoreChunks` when `ds.cursor.Next` returns false. If there is a cursor error, closes the cursor and returns the underlying error.
Adds a test to simulate a timeout during `DownloadStream#Read` and assert that `context deadline exceeded` is returned instead of `io.EOF`.
=> GODRIVER-1925 Surface cursor errors in DownloadStream fillBuffer

README.md
Original example goes log.Fatal if your query return something different than "ErrNoDocuments" but, we want to go Fatal if you have an error which is unhandled.
Otherwise, we can never process query result after error check.
=> fix README error handling of FindOne

mongo/integration/database_test.go, x/mongo/driver/operation_legacy.go
Support the `BatchSize` option for the `ListCollections` call for server version 2.6
Changes:
- Use the `cursor.batchSize` field to set the `NumberToReturn` in the legacy list collections command for server version 2.6
- Re-enable getMore/killCursors command tests for server version 2.6
=> GODRIVER-1937 Update legacy ListCollections to support the BatchSize option for server version 2.6

mongo/bulk_write.go, mongo/collection.go, mongo/database.go, mongo/mongo.go, mongo/mongo_test.go
[GODRIVER-1180](https://jira.mongodb.org/browse/GODRIVER-1180)
Removes the no longer used `transformAndEnsureID`, `ensureDollarKey`, and `transformAggregatePipeline` functions and renames their v2 variants to the now available names.
Updates `mongo_test#TestMongoHelpers` to account for changes.
=> GODRIVER-1180 Remove legacy transform functions from mongo

.evergreen/config.yml
GODRIVER-1961
Runs OCSP linux tests against RHEL 7.0 with go1.16 instead of Ubuntu 16.04 with go1.15.
=> GODRIVER-1961 Run OCSP tests against RHEL 7.0

examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go
GODRIVER-2004
Adds examples of configuring server API options for the docs team.
=> GODRIVER-2004 Add Versioned API connection examples for docs

.evergreen/run-mongodb-aws-test.sh
Since updating Evergreen to run with Go 1.16, the AWS auth tests have been failing with errors like
```
go.mongodb.org/mongo-driver/mongo/testaws/main.go:14:2: no required module provides package go.mongodb.org/mongo-driver/bson: go.mod file not found in current directory or any parent directory
```
Resolve that error by running `go run` from the project directory root, which contains a `go.mod` file.
https://jira.mongodb.org/browse/GODRIVER-2012
=> GODRIVER-2012 Fix AWS auth Evergreen test failures with Go 1.16+

.evergreen/config.yml, bson/bsoncodec/registry_examples_test.go, etc/check_fmt.sh, mongo/client_examples_test.go, mongo/client_side_encryption_examples_test.go, mongo/crud_examples_test.go, mongo/gridfs/gridfs_examples_test.go
Wrap all lines in `*_examples_test.go` files at 80 characters to make them easier to read when rendered in [pkg.go.dev](https://pkg.go.dev/).
Add a format check using the `github.com/walle/lll` line-length linter to assert all lines in `*_examples_test.go` files are wrapped at 80 characters.
https://jira.mongodb.org/browse/GODRIVER-2015
=> GODRIVER-2015 Wrap all lines in example test files at 80 characters.

bson/benchmark_test.go
Add benchmarks that use the test data in `./data/extended_bson/` to test marshalling and unmarshalling performance using the BSON, extJSON, and `encoding/json` libraries.
E.g. benchmark output:
```
❯ go test ./bson/... -run=X -bench='Marshal|Unmarshal' -benchmem
goos: darwin
goarch: amd64
pkg: go.mongodb.org/mongo-driver/bson
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkMarshal/simple_struct/BSON-12            816336              1466 ns/op             792 B/op          3 allocs/op
BenchmarkMarshal/simple_struct/extJSON-12         185301              6385 ns/op            3476 B/op         88 allocs/op
BenchmarkMarshal/simple_struct/JSON-12           1358628               881.6 ns/op           240 B/op          1 allocs/op
BenchmarkMarshal/nested_struct/BSON-12            384160 …
```
=> GODRIVER-1946 Add BSON, extJSON, and JSON benchmarks.

data/server-discovery-and-monitoring/integration/connectTimeoutMS.json, data/server-discovery-and-monitoring/integration/connectTimeoutMS.yml, data/server-discovery-and-monitoring/integration/isMaster-command-error.json, data/server-discovery-and-monitoring/integration/isMaster-command-error.yml, data/server-discovery-and-monitoring/integration/isMaster-network-error.json, data/server-discovery-and-monitoring/integration/isMaster-network-error.yml, data/server-discovery-and-monitoring/integration/isMaster-timeout.json, data/server-discovery-and-monitoring/integration/isMaster-timeout.yml, mongo/description/server.go, mongo/integration/client_test.go, mongo/integration/sdam_prose_test.go, x/mongo/driver/operation/ismaster.go
GODRIVER-1944
Uses "hello" instead of "isMaster" when an API version is declared.
This is a temporary fix to avoid erroring on API strict since `isMaster` is no longer a part of API version 1. We will remove occurrences of `isMaster` in the Go driver as part of GODRIVER-1862.
=> GODRIVER-1944 Use "hello" command when API version is declared

mongo/errors.go, mongo/session.go, mongo/with_transactions_test.go
GODRIVER-2001
Checks for a context deadline exceeded or canceled error during transactions (before `commitTransaction`) in `WithTransaction` and returns early in either case.
Adds two new tests to ensure expired and canceled contexts will return early in `WithTransaction`.
If the context for `WithTransaction` has expired or been canceled, the commands within the transaction have no chance of succeeding, so we should simply simply return instead of waiting for the `withTransactionTimeout` `timer` to `Stop` (120 seconds).
=> GODRIVER-2001 Do not retry transaction after expired or canceled context

data/versioned-api/crud-api-version-1-strict.json, data/versioned-api/crud-api-version-1-strict.yml, data/versioned-api/crud-api-version-1.json, data/versioned-api/crud-api-version-1.yml, data/versioned-api/transaction-handling.json, data/versioned-api/transaction-handling.yml, mongo/session.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/operation.go, x/mongo/driver/operation/abort_transaction.go, x/mongo/driver/operation/commit_transaction.go
GODRIVER-1987
Appends API version to `getMore` and transaction-continuing commands.
Previously, the server required no API version on `getMore` and transaction-continuing commands as the API version was inferred from the original `find` or `startTransaction` respectively. For the sake of simplicity and consistency, the server now expects API version on all commands.
=> GODRIVER-1987 Pass API version to getMore and transaction commands

bson/benchmark_test.go
Fix erroneous `error` nil check in recently added `bson.BenchmarkMarshal` benchmark.
https://jira.mongodb.org/browse/GODRIVER-1946
=> GODRIVER-1946 Fix bson.BenchmarkMarshal error nil check.

bson/bsonrw/extjson_reader.go, bson/unmarshal_test.go
GODRIVER-2017
Adds a case for empty objects in `extJSONValueReader#skipObject()`. Adds tests for empty objects in undefined fields for `UnmarshalExtJSON`.
Empty objects in extended JSON were being skipped without setting `ejvr.p.emptyObject` back to `false`. So, a regular object following an empty object, as in
```
{
"skip": {},
"a": {"b", "c"}
}
```
was being unmarshaled to an empty object even though it wasn't empty (i.e. `a` unmarshaled to `bson.D{}`).
=> GODRIVER-2017 Skip empty extJSON objects correctly in Unmarshal

bson/bsonrw/value_writer.go, bson/marshal_test.go, mongo/mongo_test.go, x/bsonx/bsoncore/bsoncore.go, x/bsonx/bsoncore/bsoncore_test.go
Because I had to make a few changes to backport it: https://github.com/mongodb/mongo-go-driver/commit/2aca31d5986a9e1c65a92264736de9fdc3b9b4ca
=> GODRIVER-1923 Error if BSON cstrings contain null bytes (#622)

bson/bsonrw/value_writer.go, bson/marshal.go
Currently, a `bsonrw.valueWriter` will use a new byte slice as the write buffer for each document written if one is passed in as the writer (if it is a `SliceWriter`). The result is that the write buffer capacity must be grown many times, each resulting in an allocate-then-copy operation. Instead, reuse the write buffer for every document written, only allocating a new byte slice when flushing the full document from the buffer (or when the write buffer needs to grow).
Before and after benchmark results:
```
❯ benchstat old.txt new.txt                         
name                                 old time/op    new time/op    delta
Marshal/simple_struct/BSON-12          1.50µs ± 1%    1.44µs ± 0%   -4.34%  (p=0.016 n=5+4)
Marshal/nested_struct/BSON-12          3.16µs ± 1%    3.06µs ± 0% …
```
=> GODRIVER-2025 Stop replacing the bsonrw.valueWriter buffer when given a SliceWriter destination.

data/command-monitoring/unified/redacted-commands.json, data/command-monitoring/unified/redacted-commands.yml, mongo/integration/unified/client_entity.go, mongo/integration/unified/entity.go, mongo/integration/unified/event_verification.go, mongo/integration/unified/matches.go, mongo/integration/unified/schema_version.go, mongo/integration/unified/unified_spec_test.go, x/mongo/driver/operation.go
GODRIVER-2013
Adds tests to ensure that we are redacting security sensitive commands from command monitoring. Updates `redactCommand` to also redact `hello` when `speculativeAuthenticate` is present.
=> GODRIVER-2013 Security-sensitive command-monitoring redactions

mongo/options/clientoptions.go, mongo/options/clientoptions_test.go
It seems that SRV polling is not spawned when using `opts.ApplyURI()` without (deprecated) deployment options.
That's because options.MergeClientOptions doesn't copy "uri" field. Then topology.New gets options with empty uri value, and polling is disabled.
```go
if t.cfg.uri != "" {
t.pollingRequired = strings.HasPrefix(t.cfg.uri, "mongodb+srv://")
}
```
https://jira.mongodb.org/browse/GODRIVER-2057
=> GODRIVER-2056 Fix uri merging on options.ClientOptions

mongo/integration/primary_stepdown_test.go, mongo/integration/sdam_error_handling_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go
Update `topology.Server#ProcessHandshakeError` to not clear the server connection pool on client-side timeout errors that occur while creating a connection in-line with an operation. This is intended as a patch to prevent clearing the connection pool on specific identified conditions that currently cause the driver to clear the server connection pool unnecessarily and is not intended to handle a comprehensive set of errors that could occur during handshake.
Note that the changes here are likely irrelevant once all connections are established in the background with the `connectTimeoutMS` deadline ([GODRIVER-2038](https://jira.mongodb.org/browse/GODRIVER-2038)).
Possible cases:
1. `server.Connection(context.Background())`
Get a connection to `server` using `connectTimeoutMS`. The `server` …
=> GODRIVER-2037 Don't clear the connection pool on client-side connect timeout errors.

data/crud/unified/insertMany-dots_and_dollars.json, data/crud/unified/insertMany-dots_and_dollars.yml, data/crud/unified/insertOne-dots_and_dollars.json, data/crud/unified/insertOne-dots_and_dollars.yml, data/unified-test-format/valid-pass/poc-crud.json, data/unified-test-format/valid-pass/poc-crud.yml, data/unified-test-format/valid-pass/poc-retryable-writes.json, data/unified-test-format/valid-pass/poc-retryable-writes.yml, mongo/integration/unified/collection_operation_execution.go
GODRIVER-1870
Assertions for `insertedCount` were recently removed from `insertOne-dots_and_dollars`, as "insertedCount" is not part of the specification for `insertOne`. Remove assertions from spec test and remove workaround for hardcoding `insertedCount` of 1 into `executeInsertOne` result.
Also remove assertions of `insertedCount` for `insertMany` since it's not a documented field in the CRUD spec and improve usages of `$$unsetOrMatches` (spec changes added in [DRIVERS-1828](https://jira.mongodb.org/browse/DRIVERS-1828)).
=> GODRIVER-1870 Remove insertedCount assertions on insertOne

mongo/collection.go, mongo/errors.go, mongo/errors_test.go, mongo/integration/crud_prose_test.go, mongo/integration/errors_test.go, mongo/integration/mtest/mongotest.go, x/mongo/driver/errors.go
Add the new `Details` field to the `WriteError` type and set it from the `"errInfo"` property on the server error response. Test that it is populated when there is a JSON Schema validation error.
[GODRIVER-1867](https://jira.mongodb.org/browse/GODRIVER-1867)
=> GODRIVER-1867 Add new Details field on WriteError for server v5.0

data/command-monitoring/unified/redacted-commands.json, data/command-monitoring/unified/redacted-commands.yml, mongo/integration/unified/event_verification.go
GODRIVER-2061
Syncs the redacted commands spec tests. These tests have been updated to make a best effort at asserting that replies to security sensitive commands are redacted. The Go driver already has the correct behavior (reply redaction happens [here](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/operation.go#L1485-L1489)), so no code changes are necessary. 
Adds workaround for empty `Reply` fields in `verifyCommandEvents`; it is almost identical to the existing workaround for empty `Command` fields [here](https://github.com/mongodb/mongo-go-driver/blob/master/mongo/integration/unified/event_verification.go#L171-L178).
=> GODRIVER-2061 Test redaction of replies of security sensitive commands

data/server-selection/server_selection/Sharded/read/Nearest.json, data/server-selection/server_selection/Sharded/read/Nearest.yml, data/server-selection/server_selection/Sharded/read/Primary.json, data/server-selection/server_selection/Sharded/read/Primary.yml, data/server-selection/server_selection/Sharded/read/PrimaryPreferred.json, data/server-selection/server_selection/Sharded/read/PrimaryPreferred.yml, data/server-selection/server_selection/Sharded/read/Secondary.json, data/server-selection/server_selection/Sharded/read/Secondary.yml, data/server-selection/server_selection/Sharded/write/Nearest.json, data/server-selection/server_selection/Sharded/write/Nearest.yml, data/server-selection/server_selection/Sharded/write/Primary.json, data/server-selection/server_selection/Sharded/write/Primary.yml, data/server-selection/server_selection/Sharded/write/PrimaryPreferred.json, data/server-selection/server_selection/Sharded/write/PrimaryPreferred.yml, data/server-selection/server_selection/Sharded/write/Secondary.json, data/server-selection/server_selection/Sharded/write/Secondary.yml, data/server-selection/server_selection/Sharded/write/SecondaryPreferred.json, data/server-selection/server_selection/Sharded/write/SecondaryPreferred.yml
GODRIVER-227
We were missing a number of spec tests from [`server_selection/Sharded`](https://github.com/mongodb/specifications/tree/master/source/server-selection/tests/server_selection/Sharded). All new and modified tests seem to pass.
=> GODRIVER-227 Sync Sharded server selection spec tests

mongo/options/createcollectionoptions.go
GODRIVER-2076
Updates documentation for `CreateCollectionOptions#ExpireAfterSeconds` and `CreateCollectionOptions#TimeSeriesOptions`. Includes link to [new server documentation](https://docs.mongodb.com/manual/core/timeseries-collections/), and specifies that options can only be used on 5.0+.
=> GODRIVER-2076 Update documentation for time-series collections

mongo/client.go
GODRIVER-2080
Users may expect that `client.StartSession` will always error when `client` is disconnected from the server (e.g. `client.Disconnect` has been called). `StartSession` will only return `ErrClientDisconnected` if `sessionPool` is empty. Documents this behavior.
=> GODRIVER-2080 Document that StartSession does not error on disconnected client

.evergreen/config.yml, mongo/integration/client_side_encryption_prose_test.go
Uses the new `kms_http_server.py` instead of the now-removed, trivial `mock_kms.js`.
=> GODRIVER-2114 Fix failing KMS TLS tests

mongo/gridfs/download_stream.go
GODRIVER-2058
`UploadDate` is not configurable, and if a user wishes to store a custom date on a GridFS `File`, they'll have to use the `Metadata` field instead. Documents these facts.
=> GODRIVER-2058 Document that File UploadDate is not configurable

examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go
GODRIVER-2088
Adds an example of migrating a command not available in strict API version 1 (`count`) to one that is (`CountDocuments`). 
This is an odd set of examples for Go, since we don't have an actual `count` helper. See [DRIVERS-1846](https://jira.mongodb.org/browse/DRIVERS-1846) for more information, but in short:
Example 5: Show inserting some documents to `db.sales`.
Example 6: Show the error returned in the Go driver from using our equivalent of `db.sales.count()`.
Example 7: Show an alternative to `db.sales.count()` that works with strict API version 1.
Example 8: Show the result of that alternative.
=> GODRIVER-2088 Versioned API strict migration example

x/mongo/driver/auth/mongodbcr.go
GODRIVER-209.
Fixes documentation relating to MONGODB-CR authentication mechanism deprecation.
This ticket was closed as "done" a couple years ago, but the documentation is slightly incorrect. We do want to mark the `MONGODB-CR` authentication mechanism as deprecated, but it was deprecated in 3.6 not 4.0. It was _removed_ in 4.0. See server documentation [here](https://docs.mongodb.com/manual/release-notes/3.6/#security).
=> GODRIVER-209 Fix documentation for deprecating MONGODB-CR

bson/primitive/objectid.go, bson/primitive/objectid_test.go
[GODRIVER-2119](https://jira.mongodb.org/browse/GODRIVER-2119)
Implements the [TextMarshaler](https://cs.opensource.google/go/go/+/go1.16.7:src/encoding/encoding.go;l=36) and [TextUnmarshaler](https://cs.opensource.google/go/go/+/go1.16.7:src/encoding/encoding.go;l=46) methods on `primitive.ObjectID` to allow it to be used as a map key.
=> GODRIVER-2119 implement methods required to use  as a map key

mongo/change_stream.go
GODRIVER-2136
Modifies the `selector` for new `ChangeStream` instances in `newChangeStream` to be a `CompositeSelector` of a `ReadPrefSelector` and a `LatencySelector`. This should make it so change stream server selection (both in creation and resumption) will respect the `Client`'s `LocalThreshold` value.
=> GODRIVER-2136 Include LatencySelector in change stream server selector

.evergreen/config.yml
GODRIVER-2064
The Evergreen team is now using YAML v3 which no longer supports duplicate key mappings (YAML v2 was last-definition-honored for duplicate keys). Removes the single duplicate key mapping of `matrix_spec` from our Evergreen config.
=> GODRIVER-2064 Remove duplicate key mappings from Evg config

mongo/mongo.go, mongo/mongo_test.go
GODRIVER-2133
Modifies `transformAggregatePipeline` to error if the provided `pipeline` is a non-empty semantically a single document (`bson.D`, `bson.Raw`, `bsoncore.Document`) but is implemented as a slice. This will stop users from passing something like `bson.D{{"x", 1}}` as a pipeline since it is not strictly speaking an array of documents and give them an informative error message.
=> GODRIVER-2133 Error on semantic single documents as aggregate pipelines

mongo/integration/client_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/pool.go
[GODRIVER-2109](https://jira.mongodb.org/browse/GODRIVER-2109)
There is currently a data race on the field `connection.desc` between setting it at [connection.go#L231](https://github.com/mongodb/mongo-go-driver/blob/e142bb3bb6c3c05f3feedefc6c5e87ee096c7422/x/mongo/driver/topology/connection.go#L231) and reading it at [pool.go#L199](https://github.com/mongodb/mongo-go-driver/blob/e142bb3bb6c3c05f3feedefc6c5e87ee096c7422/x/mongo/driver/topology/pool.go#L199) and [pool.go#L535](https://github.com/mongodb/mongo-go-driver/blob/e142bb3bb6c3c05f3feedefc6c5e87ee096c7422/x/mongo/driver/topology/pool.go#L535). The data race occurs when the `resourcePool.Maintain()` function adds connections to satisfy `minPoolSize` (only when `minPoolSize > 0`). The unconnected connections are added to the …
=> GODRIVER-2109 Prevent a data race between connecting and checking out a connection from the resourcePool.

bson/bsonrw/value_reader_test.go, bson/primitive/objectid.go, bson/primitive/primitive.go, x/mongo/driver/topology/fsm.go, x/mongo/driver/uuid/uuid.go
ObjectID is an array typed `[12]byte`, so it can be compared with another one directly.
I don't know why we convert two ObjectID to slices and compare them with `bytes.Equal`, I believe it is unnecessary.
=> fix: compare object id directly

data/command-monitoring/unified/pre-42-server-connection-id.json, data/command-monitoring/unified/pre-42-server-connection-id.yml, data/command-monitoring/unified/server-connection-id.json, data/command-monitoring/unified/server-connection-id.yml, event/monitoring.go, mongo/description/server.go, mongo/integration/mtest/opmsg_deployment.go, mongo/integration/unified/event_verification.go, mongo/integration/unified/schema_version.go, x/mongo/driver/driver.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/operation.go, x/mongo/driver/operation/hello.go, x/mongo/driver/operation_test.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/connection.go
GODRIVER-2085
Adds a `ServerConnectionID` field to `CommandStartedEvent`, `CommandSucceededEvent` and `CommandFailedEvent` to track the `serverConnectionId` returned in the server's `hello` or legacy hello response (on 4.2+). Syncs command monitoring spec tests. Bumps supported schema version of the unified test runner to 1.6.
=> GODRIVER-2085 Add serverConnectionId to command monitoring events

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_generation_counter.go, x/mongo/driver/topology/pool_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_errors_test.go, x/mongo/driver/topology/topology_test.go
When I tried to use my program on ARM I got panic:
```
(...)
panic: unaligned 64-bit atomic operation [recovered]
panic: unaligned 64-bit atomic operation
goroutine 1 [running]:
github.com/alecthomas/kong.catch(0x2cb1f58)
/home/sr/go/pkg/mod/github.com/alecthomas/kong@v0.2.18-0.20210713035501-d1a818b5a1a8/kong.go:407 +0xa8
panic(0x6b9540, 0x8b0528)
/usr/lib/go/src/runtime/panic.go:965 +0x174
runtime/internal/atomic.panicUnaligned()
/usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x2c77b14, 0x1, 0x0, 0x7, 0xc)
/usr/lib/go/src/runtime/internal/atomic/asm_arm.s:233 +0x14
go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*pool).makeNewConnection(0x2c77ae0, 0x2d62c01, 0x0, 0x1, 0x0, 0x0)
/home/sr/go/pkg/mod/go.mongodb.org/mongo-driver@v1.7.1/x/mong …
```
=> Fix panic on ARM, 386, and 32-bit MIPS by aligne fileds used by atomic package

README.md
I noticed the link referenced in the README https://docs.mongodb.com/drivers/go/ leads to a 404 page, so I updated it with the working one https://docs.mongodb.com/drivers/go/current/.
=> fixed driver broken link

data/initial-dns-seedlist-discovery/replica-set/srv-service-name.json, data/initial-dns-seedlist-discovery/replica-set/srv-service-name.yml, data/uri-options/srv-service-name-option.json, data/uri-options/srv-service-name-option.yml, internal/testutil/helpers/helpers.go, mongo/client.go, mongo/integration/initial_dns_seedlist_discovery_test.go, mongo/options/clientoptions.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/dns/dns.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_options.go
GODRIVER-2086
Introduces a new URI option, `srvServiceName`, that can be used to specify a custom SRV service name for SRV discovery and polling. Adds new field to `ConnString`, updates test runners, and syncs spec tests.
=> GODRIVER-2086 Allow custom SRV service names with URI option srvServiceName

x/mongo/driver/topology/fsm.go
GODRIVER-2159
Bumps supported max wire version to 14 to support running against the upcoming MongoDB 5.1.
=> GODRIVER-2159 Bump maxWireVersion to 14

data/crud/unified/aggregate-write-readPreference.json, data/crud/unified/aggregate-write-readPreference.yml, data/crud/unified/db-aggregate-write-readPreference.json, data/crud/unified/db-aggregate-write-readPreference.yml, mongo/collection.go, mongo/description/server_selector.go, mongo/integration/crud_prose_test.go, x/mongo/driver/operation.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation_legacy.go, x/mongo/driver/operation_test.go
GODRIVER-1868
Allows non-primary read preferences (either inherited or explicit) for aggregates with `$out` and `$merge` stages on wire versions >= 13. Modifies server selection to remove secondaries with wire versions < 13 from the list of candidates when executing an aggregate with an output stage but fall back to primary in the case of no usable secondaries. Modifies `createReadPref` in `operation.go` to _not_ append read preference when executing an aggregate with an output stage against a server with wire version < 13.
=> GODRIVER-1868 Support $out and $merge executing on secondaries

mongo/integration/unified_runner_events_helper_test.go, mongo/integration/unified_spec_test.go
GODRIVER-1749
Removes `ServerMarkedUnknownEvent` skips for SDAM integration tests. Actually handles, waits for, and asserts the count of [`ServerMarkedUnknownEvent`s](https://github.com/mongodb/specifications/blob/57d31cc6ccec53b31657d0807b6b24c51d3cb1af/source/server-discovery-and-monitoring/tests/README.rst#servermarkedunknownevent).
=> GODRIVER-1749 Check for ServerMarkedUnknownEvent in SDAM integration tests

data/unified-test-format/valid-pass/observeSensitiveCommands.json, data/unified-test-format/valid-pass/observeSensitiveCommands.yml, mongo/integration/unified/client_entity.go
GODRIVER-2107
Syncs spec tests for new [`observeSensitiveCommands`](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst) flag in the unified test format. Corrects logic in unified test runner event verification to ignore `hello`s and legacy hellos that had `speculativeAuthenticate` but have already been redacted. 
The previous behavior tried to check if `speculativeAuthenticate` was present in the `Command` or `Reply`, but if it were, `Command` or `Reply` would have been set to an empty `bson.Raw{}` [here](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/operation.go#L1476) in `operation.go`. See this [recent clarification](https://github.com/mongodb/specifications/commit/6847048c551431c8a328b9c1f0deeec158160d20#diff …
=> GODRIVER-2107 Correctly ignore sensitive commands in unified test runner

data/crud/unified/aggregate-write-readPreference.json, data/crud/unified/aggregate-write-readPreference.yml, data/crud/unified/db-aggregate-write-readPreference.json, data/crud/unified/db-aggregate-write-readPreference.yml
GODRIVER-2195
Syncs spec tests for `aggregate`s with write stages (e.g. `$out` and `$merge`) to avoid testing against pre-4.2 servers when read concern is specified. MongoDB 4.2 introduced support for read concern and write stages, so we should not run the modified tests on servers above that version.
=> GODRIVER-2195 Do not expect readConcern with write stage on pre 4.2

x/mongo/driver/mongocrypt/mongocrypt_test.go
PR https://github.com/mongodb/libmongocrypt/pull/208 adds a default port to the AWS KMS hostname (see [MONGOCRYPT-354](https://jira.mongodb.org/browse/MONGOCRYPT-354)). Update `TestMongoCrypt` to expect the updated hostname with port.
=> MONGOCRYPT-352 Update TestMongoCrypt to expect AWS KMS hostname with port.

internal/testutil/assert/assert.go, mongo/change_stream_deployment.go, mongo/integration/client_test.go, mongo/integration/mtest/opmsg_deployment.go, mongo/integration/mtest/proxy_dialer.go, mongo/integration/sessions_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/driver.go, x/mongo/driver/drivertest/channel_netconn.go, x/mongo/driver/operation.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/rtt_monitor_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_rtt_test.go, x/mongo/driver/topology/server_test.go
[GODRIVER-2065](https://jira.mongodb.org/browse/GODRIVER-2065)
If an operation times out during the network round trip, the driver closes the in-use connection. Minimize the number of closed connections by trying to predict which operations are likely to time out during the network round trip using the minimum measured RTT value for the last 5 minutes.
Changes:
* Add `rttMonitor.getMinRTT()` that returns the minimum RTT measured for the last window (default 5 minutes). If there are fewer than the minimum number of samples (default 5), return 0 to prevent calculating minimum on too few values.
* Refactor `rttMonitor.start()` to manage creating and closing its own connection to avoid synchronization logic around a shared `*connection`.
* Add `MinRTT() time.Duration` to the `driver.Server` …
=> GODRIVER-2065 Don't send the operation if the Context deadline is before (now + minimum RTT).

.evergreen/config.yml
GODRIVER-2215
Changes our call of `git clone` for the `drivers-evergreen-tools` repo to use `https://` instead of `git://` as the URL scheme. See new [GitHub changes](https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective:).
=> GODRIVER-2215 Use git clone https:// instead of git://

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server.go
[GODRIVER-2138](https://jira.mongodb.org/browse/GODRIVER-2138)
Now that [GODRIVER-2038](https://jira.mongodb.org/browse/GODRIVER-2038) is merged, we no longer need the `opCtx` param that was added to `Server.ProcessHandshakeError()` with [GODRIVER-2037](https://jira.mongodb.org/browse/GODRIVER-2037). Remove it from `Server.ProcessHandshakeError()` and all related function signatures and calling functions.
=> GODRIVER-2138 Remove unused opCtx param from Server.ProcessHandshakeError

mongo/integration/index_view_test.go, mongo/results.go
Adding `Unique`, `ExpireAfterSeconds`, and `Sparse` to the `IndexSpecification` type returned from `collection.ListSpecifications()`.
I've been working on some tooling that relies on fetching the current state of the indexes in a collection. It seems like just a pure oversight to not include these values in the returned `IndexSpecification` object, seeing as they are available just fine from `mongosh` and the like.
Just added the fields so that they will be appropriately unmarshalled from the bson response, and amended the existing "list specifications" unit test to verify that they are working.
=> GODRIVER-2221 add unique, expires, and sparse to index options

x/mongo/driver/connstring/connstring.go, x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/uuid/uuid.go, x/mongo/driver/uuid/uuid_test.go
[GODRIVER-2223](https://jira.mongodb.org/browse/GODRIVER-2223)
Changes:
* Use a `"math/rand"` pseudo-random number source for the `x/mongo/driver/uuid` package instead of `"crypto/rand"`; aligns with the [spec for generating session IDs](https://github.com/mongodb/specifications/blob/70c26f323619573fba1e39a97cd5f2fa17dbaf3b/source/sessions/driver-sessions.rst#generating-a-session-id-locally), which is currently the only use of the `uuid` package.
* Document that the `x/mongo/driver/uuid` package should not be used to generate cryptographically-secure random UUIDs.
* Use a separate pseudo-random number source for the `connstring`, `topology` and `uuid` packages.
* Seed all pseudo-random number sources with the package initialization time.
=> GODRIVER-2223 Use separate, seeded pseudo-random sources for each package.

mongo/description/server_selector.go, x/mongo/driver/operation.go
GODRIVER-2220
Simplifies the logic for read preference application in server selection when the underlying operation is an `aggregate` with an output stage (`$out` or `$merge`). Previously, we attempted to use the read preference and only fell back to a primary if a pre-5.0 secondary was going to be selected. Now, we always disregard the read preference if there is any evidence of a pre-5.0 server in `candidates`. If there are either no candidates or all servers are 5.0+ (or load balanced, where we assume 5.0+), we utilize the read preference.
=> GODRIVER-2220 Ignore readpref for output aggs if any servers are pre-5.0

.golangci.yml, bson/bsoncodec/default_value_encoders.go, bson/bsoncodec/map_codec.go, bson/bsoncodec/registry.go, bson/bsoncodec/registry_test.go, bson/bsoncodec/struct_codec.go, bson/mgocompat/bson_test.go, bson/primitive/decimal.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/mtest/sent_message.go, mongo/integration/mtest/setup.go, mongo/integration/unified/unified_spec_runner.go, x/bsonx/bsoncore/bson_arraybuilder_test.go, x/bsonx/bsoncore/bson_documentbuilder_test.go, x/bsonx/bsoncore/bsoncore_test.go, x/bsonx/document.go, x/bsonx/mdocument.go, x/bsonx/value.go, x/mongo/driver/errors.go, x/mongo/driver/operation.go, x/mongo/driver/session/client_session.go, x/mongo/driver/topology/topology_options.go
Enable the `gosimple` linter and make suggested simplifications.
=> GODRIVER-2156 Enable gosimple linter.

.golangci.yml, bson/primitive/decimal.go
Enable the `nakedret` linter and remove suggested naked returns.
=> GODRIVER-2156 Enable nakedret linter.

.golangci.yml, bson/bsoncodec/struct_codec.go, bson/mgocompat/bson_test.go
Enable the `structcheck` and `varcheck` linters and remove suggested unused code.
=> GODRIVER-2156 Enable structcheck and varcheck linters.

.golangci.yml, mongo/collection.go, x/mongo/driver/topology/server.go
Enable the `makezero` linter and make suggested simplifications.
=> GODRIVER-2156 Enable makezero linter.

internal/randutil/randutil.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/topology/topology.go, x/mongo/driver/uuid/uuid.go
The changes in https://github.com/mongodb/mongo-go-driver/pull/803 introduced a data race because `rand.Rand` is not goroutine safe. Add a new type `LockedRand` that synchronizes access to an underlying `rand.Rand` for frequently used pRNG functions and use `LockedRand` in place of a `rand.Rand` wherever it needs to be goroutine safe.
=> GODRIVER-2223 Fix data races caused by unsynchronized access to rand.Rand instances.

examples/documentation_examples/examples_test.go
[GODRIVER-2238](https://jira.mongodb.org/browse/GODRIVER-2238)
Currently, `TestCausalConsistencyExamples` fails on most runs with MongoDB v4.0 sharded clusters. Skip the `TestCausalConsistencyExamples` test on MongoDB v4.0 CI variants for now until we can root cause the failures.
=> GODRIVER-2238 Skip TestCausalConsistencyExamples on MongoDB v4.0 for now.

Makefile, mongo/integration/mtest/mongotest.go, x/mongo/driver/topology/server.go
[GODRIVER-2236](https://jira.mongodb.org/browse/GODRIVER-2236)
Fix atomic operation struct field alignment panic noted in https://github.com/mongodb/mongo-go-driver/pull/723#issuecomment-971411194. Also run the linters on the Go distributions officially supported by the driver to prevent recurrence:
```
linux/amd64
linux/386
linux/arm64
linux/arm
linux/s390x
```
=> GODRIVER-2236 Fix atomic op alignment and run linters on multiple architectures.

.evergreen/config.yml, Makefile, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/client_side_encryption_spec_test.go
[GODRIVER-2237](https://jira.mongodb.org/browse/GODRIVER-2237)
Configures an Evergreen build variant to test the KMS KMIP spec and prose tests. Passes according to [this patch](https://spruce.mongodb.com/version/6196d83161837d799a22ece1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
=> GODRIVER-2237: Run KMS KMIP spec and prose tests in Evergreen

x/mongo/driver/connstring/connstring.go, x/mongo/driver/topology/polling_srv_records_test.go, x/mongo/driver/topology/topology.go
[GODRIVER-2222](https://jira.mongodb.org/browse/GODRIVER-2222)
Currently, the driver may remove valid servers from a topology when updating the topology based on the SRV host records if `len(SRV hosts) > srvMaxHosts`. Instead, when updating topology servers from SRV host records, wait until we've determined the added and removed hosts to limit the topology servers list to `srvMaxHosts`.
Also use `rand.Rand.Shuffle` instead of a custom shuffle implementation and re-enable the "SRVMaxHosts is less than number of hosts" test.
=> GODRIVER-2222 Prevent removing valid servers when updating SRV hosts.

bson/marshal.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation/create.go, x/mongo/driver/operation/createIndexes.go, x/mongo/driver/operation/delete.go, x/mongo/driver/operation/distinct.go, x/mongo/driver/operation/drop_collection.go, x/mongo/driver/operation/drop_indexes.go, x/mongo/driver/operation/end_sessions.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/insert.go, x/mongo/driver/operation/listDatabases.go
GODRIVER-2247
Adds missing (and fixes malformed) comments of exported functions/types across the repo. `golint` was complaining on older branches.
=> GODRIVER-2247 Add missing comments to exported functions/types

data/atlas-data-lake-testing/estimatedDocumentCount.json, data/atlas-data-lake-testing/estimatedDocumentCount.yml
GODRIVER-2242
Updates the `estimatedDocumentCount` test in `atlas-data-lake-testing` to expect an `aggregate` with `$collStats` instead of a `count` command, as ADL just bumped their max wire version to 13 (which has the new format for `estimatedDocumentCount`).
=> GODRIVER-2242 Update estimatedDocumentCount test for ADL

mongo/index_view.go, mongo/integration/index_view_test.go
This was returning driver.ErrUnacknowledgedWrite when creating indexes with an unacknowledged WriteConcern.
Wrap the error using processWriteError so we can return mongo.ErrUnacknowledgedWrite.
=> GODRIVER-2243 Wrap write errors in IndexView.CreateMany

.golangci.yml, internal/testutil/config.go
`golangci-lint` disables all warnings about missing comments on exported variables/functions/types by default (see https://github.com/golangci/golangci-lint/issues/456 for a discussion about that behavior). We want those warnings for most of the packages in the Go driver, so re-enable them.
=> GODRIVER-2247 Re-enable missing comment lint warnings.

mongo/client.go, mongo/options/clientoptions.go, mongo/options/clientoptions_test.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/connstring/connstring_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_options.go
[GODRIVER-2219](https://jira.mongodb.org/browse/GODRIVER-2219)
Add `ClientOptions.SetMaxConnecting` and support the `maxConnecting=<val>` URI option.
=> GODRIVER-2219 Make maxConnecting configurable via ClientOptions or URI options.

mongo/cursor.go, mongo/cursor_test.go, mongo/integration/mock_find_test.go, mongo/single_result.go, mongo/single_result_test.go, x/mongo/driver/batch_cursor.go
GODRIVER-2161
Adds a new `SingleResult` constructor `NewSingleResultFromDocument` that makes a `SingleResult` with an underlying `Cursor` pre-loaded with a singleton slice of documents (`[]interface{}{document}`) as the first batch. Adds a new `Cursor` construct `NewCursorFromDocuments` that makes a `Cursor` pre-loaded with a slice of documents (`[]interface{}`) as the first batch. These new functions can be used to mock server responses to read operations (e.g. `Find`, `FindOne`, `Aggregate`). Adds associated unit and integration tests.
=> GODRIVER-2161 Add NewSingleResultFromDocument and NewCursorFromDocuments functions

mongo/integration/collection_test.go
GODRIVER-2248
`TestCollection/bulk_write/update_with_batches` was causing timeouts on most of our MacOS variants. This was because of the large (100050) amount of documents that needed to be deleted server-side after the test. As in GODRIVER-1858, I've used the mock deployment built into `mtest` to lower testing times (from about 1m to about .3s).
=> GODRIVER-2248 Use mock deployment for slow BulkWrite update test

mongo/database.go, mongo/integration/database_test.go, mongo/options/listcollectionsoptions.go, x/mongo/driver/operation/list_collections.go
GODRIVER-2190
Adds support for the `authorizedCollections` option in `ListCollectionsOptions`. Adds a small unit test to ensure `authorizedCollections` is passed correctly in a `listCollections` command.
=> GODRIVER-2190 Support authorizedCollections option for ListCollections

bson/bsoncodec/default_value_decoders.go, bson/decoder_test.go, bson/unmarshal_test.go, bson/unmarshaling_cases_test.go
[GODRIVER-2252](https://jira.mongodb.org/browse/GODRIVER-2252)
When unmarshaling BSON, If the target Go value is a pointer, has a custom `UnmarshalBSON` function, and the BSON field value is empty, set the Go value to the zero value of the pointer (`nil`) and don't call `UnmarshalBSON`. `UnmarshalBSON` has no way to change the pointer value from within the function (only the value at the pointer address), so it can't set the pointer to `nil` itself. Since the most common Go value for an empty BSON field value is `nil`, we set the Go value to `nil` and don't call `UnmarshalBSON`. This behavior matches the behavior of the Go `"encoding/json"` unmarshaler when the target Go value is a pointer, has a custom `UnmarshalJSON` function, and the JSON field value is `null`.
See this [StackOverflow …
=> GODRIVER-2252 Don't call UnmarshalBSON for pointer values if the BSON field value is empty.

mongo/integration/sdam_prose_test.go
[GODRIVER-2265](https://jira.mongodb.org/browse/GODRIVER-2265)
The test `TestSDAMProse/heartbeats_processed_more_frequently` fails intermittently on the Evergreen waterfall. Some assertions made in that test are only accidentally working:
* The previous assertion that server version <4.4 processes a different number of operations for all heartbeat intervals is not correct. The discrepancy between the number of operations processed between server versions <4.4 and >=4.4 comes from the "minimum heartbeat interval" of 500ms that only applies to non-streaming heartbeats.
* The previous assertion that a `Client` should send a heartbeat exactly every interval is not correct. A `Client` waits _at least_ the specified interval between heartbeats, and does not guarantee exactly when the next …
=> GODRIVER-2265 Make more correct assertions in SDAM heartbeat test.

mongo/integration/sdam_prose_test.go
GODRIVER-1824
Implement the prose test described in [DRIVERS-1251](https://jira.mongodb.org/browse/DRIVERS-1251). This test verifies that the driver waits approximately 500ms between failing hellos and legacy hellos.
=> GODRIVER-1824 Test that Client waits 500ms between failed Hellos

x/mongo/driver/topology/fsm.go
GODRIVER-2270
Bumps the max supported wire version to 15, which correlates with MongoDB server version 5.2.
=> GODRIVER-2270 Bump maxWireVersion for MongoDB 5.2

mongo/change_stream.go, mongo/collection.go, mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/options/aggregateoptions.go, mongo/options/changestreamoptions.go, x/mongo/driver/operation/aggregate.go
GODRIVER-2278
Adds `SetCustomOptions` on both `ChangeStreamOptions` and `AggregateOptions`. Also adds integration tests for the new functions to make sure extra options are actually sent across the wire. 
`CustomOptions` is a `map[string]interface{}` representing extra options to pass in the underlying "aggregate" command for change stream initiation and regular aggregates. The `map[string]interface{}` should be a map of names of options (`string`s) to Marshalable values (`interface{}`s).
=> GODRIVER-2278 Support CustomOptions on ChangeStreamOptions and AggregateOptions

mongo/integration/client_test.go, mongo/integration/mtest/sent_message.go, x/mongo/driver/operation.go
GODRIVER-2120
GODRIVER-2192
Tests that `OP_MSG` is used as an `OpCode` for authentication-related commands when wire version is >= 6 (MDB server 3.6+). Tests that `OP_MSG` is used as an `OpCode` for `hello` commands when an API version is declared (we were sending `OP_QUERY` before this PR's changes to `operation.go`). Exposes the `OpCode` used in the wire message in `mtest`'s `SentMessage` type.
=> GODRIVER-2120 GODRIVER-2192 Ensure OP_QUERY is only used when necessary

mongo/errors.go, mongo/integration/errors_test.go
GODRIVER-2281
Implements the `ServerError` interface for `WriteError` so that the helpers like `IsDuplicateKeyError` can be used on individual `WriteError`s. Adds unit tests to `errors_test.go`.
=> GODRIVER-2281 Implement ServerError for WriteError

examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go, mongo/client_examples_test.go
GODRIVER-2301
- Replaces occurrences of "versioned" with "stable" in documentation when referring to the Stable API feature available in MongoDB 5.0+.
The docs team has rebranded the versioned API feature to "stable" API. We should update our documentation accordingly.
- The example annotations (`// Start/End Versioned API Example #`) should not be altered, as the docs team still expects that annotation format.
=> GODRIVER-2301 Rename 'Versioned API' to 'Stable API' in docs

README.md
Add missing `import context` in README.
=> Add missing context import

x/mongo/driver/connstring/connstring.go, x/mongo/driver/connstring/connstring_test.go
GODRIVER-2305
GODRIVER-1078 previously "fixed" behavior for empty tag sets provided in the URI (`readPreferenceTags=`) to simply skip instead of error. In reality, `readPreferenceTags=` in the URI represents a wild-card that should match any server with any tags (see docs [here](https://docs.mongodb.com/manual/reference/connection-string/#mongodb-urioption-urioption.readPreferenceTags)).
Appends `map[string]string{}` to tag sets if `readPreferenceTags=` is encountered. Fixes associated tests in `connstring_test.go`.
=> GODRIVER-2305 Correctly append empty TagSet

.evergreen/config.yml, internal/const.go, mongo/description/server.go, mongo/integration/initial_dns_seedlist_discovery_test.go, mongo/integration/main_test.go, mongo/integration/unified/main_test.go
[GODRIVER-2292](https://jira.mongodb.org/browse/GODRIVER-2292)
[DRIVERS-1983](https://jira.mongodb.org/browse/DRIVERS-1983) updated the load balancer mongo-orchestration config to support the new "loadBalancerPort" server option which allows the server to act more correctly in load balancer tests, including returning a "serviceID" in "hello" responses. Update the test runner to pass the new `LOAD_BALANCER="true"` option to mongo-orchestration and remove support for mocking "serviceID".
Changes:
* Set `LOAD_BALANCER="true"` and pass `LOAD_BALANCER` value to mongo-orchestration.
* Remove "serviceID" mocking.
* Skip some load-balanced initial DNS seedlist discovery tests until [GODRIVER-2312](https://jira.mongodb.org/browse/GODRIVER-2312) is done.
=> GODRIVER-2292 Support dedicated load balancer port in tests.

mongo/integration/client_test.go, x/mongo/driver/operation.go, x/mongo/driver/operation/hello.go
GODRIVER-2276
Always use the `OP_MSG` `OpCode` and a `hello` command for wire messages when the topology is load balanced.
=> GODRIVER-2276 Use OP_MSG and hello with loadBalanced

mongo/integration/collection_test.go
GODRIVER-2315
[SERVER-63201](https://jira.mongodb.org/browse/SERVER-63201) recently allowed deletes on capped collections in the latest server versions (5.3). Some of our tests in `integration/collection_test.go` expect server-side write errors when running a delete operation against a capped collection. Updates these tests to only run against 5.2-.
=> GODRIVER-2315 Update tests that expect errors with capped collection deletes

.evergreen/config.yml
Currently we install the Go linters in any task that calls the `prepare-resources` function (most tasks). Those linters (specifically the `golangci-lint` linter) download a bunch of Go modules and generally slow down the CI build. Only install those linters in the `sa-lint` task, which actually uses them.
=> Only install Go linters in sa-lint task.

x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/hanging_tls_conn_1_17.go
Changes:
* Honor the context passed in to `hangingTLSConn.HandshakeContext()` (i.e. exit when either the sleep time is reached or the context times out, whichever comes first).
* Add a `ServerName` to the `tls.Config` in one of the `TestConnection` test cases to resolve error "tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config".
=> Honor context in Go 1.17+ version of hangingTLSConn.

.evergreen/config.yml
Cleans up the `fetch-source` task in the Evergreen config. The function was oddly organized and not well commented.
=> Clean up fetch-source Evergreen function

x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_errors_test.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/rtt_monitor_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go, x/mongo/driver/topology/topology_options_test.go
Type `ConnectionOption` is currently a `func(*connectionConfig) error`. However, no `ConnectionOption` functions return an error. Remove the error returned by the `ConnectionOption` type (now `func(*connectionConfig)`) and remove all of the now-unnecessary error handling logic.
=> Remove unused ConnectionOption error.

mongo/integration/primary_stepdown_test.go, mongo/integration/retryable_reads_prose_test.go, mongo/integration/retryable_writes_prose_test.go
GODRIVER-1910
Tests that `PoolClearedError`s are retryable for both reads and writes. Implements the prose tests described in [DRIVERS-1483](https://jira.mongodb.org/browse/DRIVERS-1483).
=> GODRIVER-1910 Test that PoolClearedErrors are retryable

data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.json, data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.yml, data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.json, data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.yml, data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.json, data/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.yml, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.yml, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.json, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.yml, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.json, data/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.yml, mongo/integration/initial_dns_seedlist_discovery_test.go, x/mongo/driver/topology/topology_options.go
[GODRIVER-2312](https://jira.mongodb.org/browse/GODRIVER-2312)
Now that https://github.com/mongodb/specifications/pull/1148 is merged, we can update and re-enable the initial DNS seedlist discovery spec tests for load balancers. Also fixes a bug in `topology.WithConnString` that doesn't set the `LoadBalanced` option correctly on the connection handshakers.
=> GODRIVER-2312 Update and unskip initial DNS seedlist discovery spec tests

mongo/session.go
GODRIVER-2283
Removes comment stating that `AdvanceClusterTime` and `AdvanceOperationTime` are for internal use only. Explains the functions of the methods in documentation instead.
`AdvanceClusterTime` and `AdvanceOperationTime` are part of the drivers specifications for [sessions](https://github.com/mongodb/specifications/blob/b995503e975af1ea661fdd1fb83cc4f4ac2254a9/source/sessions/driver-sessions.rst#advanceclustertime) and [causal consistency](https://github.com/mongodb/specifications/blob/b995503e975af1ea661fdd1fb83cc4f4ac2254a9/source/causal-consistency/causal-consistency.rst#advanceoperationtime) respectively. They are expected to be used by applications wishing to manually plumb/persist a causal token for use across different logical sessions.
=> GODRIVER-2283 Remove innacurate comment about AdvanceCluster/OperationTime

examples/documentation_examples/examples_test.go
GODRIVER-2336
Skips the `StableAPIStrictCountExample` test when running against server version 6.0+. [DRIVERS-2228](https://jira.mongodb.org/browse/DRIVERS-2228) recently added the `count` command to API version 1, so enabling strict no longer results in the expected `count` error against the latest server versions.
=> GODRIVER-2336 Skip strict stable API count example

x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_errors_test.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_generation_counter.go, x/mongo/driver/topology/pool_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_errors_test.go, x/mongo/driver/topology/topology_test.go
[GODRIVER-2181](https://jira.mongodb.org/browse/GODRIVER-2181)
Use dedicated constants for each of the `connection`, `pool`, `poolGenerationMap`, `Server`, and `Topology` types.
* Add new state constants for the `connection`, `poolGenerationMap`, `Server`, and `Topology` types following the existing naming pattern of the `pool` state constants.
* Remove any unused states for each type.
* Rename the "state" field in each of the above types to `state`.
=> GODRIVER-2181 Use dedicated state constants for each topology type.

x/mongo/driver/topology/cmap_prose_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/pool_test.go
[GODRIVER-2218](https://jira.mongodb.org/browse/GODRIVER-2218)
Currently a connection's "idle deadline" is increased in the Go driver only when [reading](https://github.com/mongodb/mongo-go-driver/blob/223854caf2932b7d9aa42d3255eea2cb13acf8f3/x/mongo/driver/topology/connection.go#L432) [writing](https://github.com/mongodb/mongo-go-driver/blob/223854caf2932b7d9aa42d3255eea2cb13acf8f3/x/mongo/driver/topology/connection.go#L367) to the connection. However, the [CMAP spec](https://github.com/mongodb/specifications/blob/5964c134a85707dcfa3c54b7f9f88d3451f4a175/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#connection-1) defines "idle" as:
> Idle: The Connection is currently "available" (as defined below) and has been for longer than maxIdleTimeMS.
"Available" is …
=> GODRIVER-2218 Bump connection idle deadline on pool checkIn.

data/server-selection/in_window/equilibrium.json, data/server-selection/in_window/equilibrium.yml, data/server-selection/in_window/many-choices.json, data/server-selection/in_window/many-choices.yml, data/server-selection/in_window/one-least-two-tied.json, data/server-selection/in_window/one-least-two-tied.yml, data/server-selection/in_window/rs-equilibrium.json, data/server-selection/in_window/rs-equilibrium.yml, data/server-selection/in_window/rs-three-choices.json, data/server-selection/in_window/rs-three-choices.yml, data/server-selection/in_window/three-choices.json, data/server-selection/in_window/three-choices.yml, data/server-selection/in_window/two-choices.json, data/server-selection/in_window/two-choices.yml, data/server-selection/in_window/two-least.json, data/server-selection/in_window/two-least.yml, mongo/integration/server_selection_prose_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/pool.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_test.go
[GODRIVER-1825](https://jira.mongodb.org/browse/GODRIVER-1825)
Update `Topology.SelectServer()` to pick 2 random servers from the list of selectable servers, and return the one with fewer  in-progress operations to more evenly balance load across the selectable servers.
Changes:
* Add an `operationCount` counter in `Server` that keeps track of the number of requests for connections. Note that `operationCount` is not decremented while a connection is pinned to a transaction until the transaction is committed or aborted.
* Pick 2 random servers from the list of selectable servers in `Topology.SelectServer()` and return the one with fewer in-progress operations.
* Add a prose test for the one described in [operationCount-based Selection Within Latency …
=> GODRIVER-1825 Select the server with fewer in-progress operations.

mongo/change_stream.go, mongo/collection.go, mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/options/aggregateoptions.go, mongo/options/changestreamoptions.go
GODRIVER-2337
Renames `ChangeStreamOptions.CustomOptions` (a `bson.M` with marshalable values to be passed to the initial aggregate) to `ChangeStreamOptions.Custom`. Adds a `ChangeStreamOptions.CustomPipeline` (also a bson.M) to be passed to `$changeStream` stage within the initial aggregate pipeline. Adds an integration test for `CustomPipeline`.
=> GODRIVER-2337 Add CustomPipeline to ChangeStreamOptions

data/crud/unified/bulkWrite-deleteMany-let.json, data/crud/unified/bulkWrite-deleteMany-let.yml, data/crud/unified/bulkWrite-deleteOne-let.json, data/crud/unified/bulkWrite-deleteOne-let.yml, data/crud/unified/bulkWrite-replaceOne-let.json, data/crud/unified/bulkWrite-replaceOne-let.yml, data/crud/unified/bulkWrite-updateMany-let.json, data/crud/unified/bulkWrite-updateMany-let.yml, data/crud/unified/bulkWrite-updateOne-let.json, data/crud/unified/bulkWrite-updateOne-let.yml, mongo/bulk_write.go, mongo/collection.go, mongo/integration/unified/collection_operation_execution.go, mongo/options/bulkwriteoptions.go
GODRIVER-2314
GODRIVER-2327
GODRIVER-2313
Syncs CRUD bulkWrite spec tests. (first commit). Adds a new `let` option to `BulkWriteOptions` to be passed down to any `update` or `delete` commands within the `BulkWrite` (second commit).
=> Support 'let' option in BulkWriteOptions

mongo/change_stream.go, mongo/collection.go, mongo/integration/change_stream_test.go, mongo/integration/collection_test.go, mongo/options/aggregateoptions.go, mongo/options/changestreamoptions.go
GODRIVER-2337
Renames `ChangeStreamOptions.CustomOptions` (a `bson.M` with marshalable values to be passed to the initial aggregate) to `ChangeStreamOptions.Custom`. Adds a `ChangeStreamOptions.CustomPipeline` (also a bson.M) to be passed to `$changeStream` stage within the initial aggregate pipeline. Adds an integration test for `CustomPipeline`. 
#880 Was originally opened for this change but was accidentally merged. #881 Reverted those changes, and I've reopened this new PR (#882) to continue review. Apologies for the confusion.
=> GODRIVER-2337 Add CustomPipeline to ChangeStreamOptions (edited)

mongo/errors.go, mongo/integration/errors_test.go, x/mongo/driver/errors.go, x/mongo/driver/operation.go
GODRIVER-2325
Adds `Raw` fields to various `mongo` and `driver` errors. Adds integration tests to ensure the raw server reply can be accessed through these fields.
=> GODRIVER-2325 Expose raw server response in relevant errors

mongo/collection.go, mongo/options/indexoptions.go, mongo/options/listdatabasesoptions.go, mongo/readpref/readpref.go, x/mongo/driver/topology/connection_options.go, x/mongo/driver/topology/server_options.go, x/mongo/driver/topology/topology_options.go
GODRIVER-2351
Adds missing `opt == nil { continue }` guards to option loops. When using patterns like `for _, opt := range opts`, we need to check that `opt != nil` before accessing its fields. Failure to do so can result in panics when users pass a single `nil` option to the potential slice of options in the variadic parameter.
=> GODRIVER-2351 Add missing nil option checks

x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_options.go, x/mongo/driver/topology/server_test.go, x/mongo/driver/topology/topology.go, x/mongo/driver/topology/topology_options_test.go, x/mongo/driver/topology/topology_test.go
Type `ServerOption` is currently a `func(*serverConfig) error`. However, no `ServerOption` functions return an error. Remove the error returned by the `ServerOption` type (now `func(*serverConfig)`) and remove all of the now-unnecessary error handling logic.
Follow up to previous similar PR https://github.com/mongodb/mongo-go-driver/pull/859
=> Remove unused ServerOption error.

internal/randutil/randutil.go, internal/randutil/randutil_test.go, x/mongo/driver/connstring/connstring.go, x/mongo/driver/topology/topology.go, x/mongo/driver/uuid/uuid.go, x/mongo/driver/uuid/uuid_test.go
[GODRIVER-2349](https://jira.mongodb.org/browse/GODRIVER-2349)
On some versions of Go and on some operating systems, `time.Now()` returns a time with lower-than-expected resolution (updates every 500μs to 15ms). The Go driver uses `time.Now().UnixNano()` to seed some pseudo-random number generators, including the one for generating session IDs [here](https://github.com/mongodb/mongo-go-driver/blob/630ff7cbfd2363b49bfa48968b80ce287e70ae85/x/mongo/driver/uuid/uuid.go#L21). Due to that, it's possible, under the right conditions, to start two processes that reproduce the same sequence of session IDs if they are started at almost the same time.
To remove that possibility, read an `int64` value from the `"crypto/rand".Reader` and use it to seed all pseudo-random number generators in the driver.
=> GODRIVER-2349 Seed all pseudorandom number generators with a crypto-secure random number.

bson/bsonrw/value_reader.go
[GODRIVER-2311](https://jira.mongodb.org/browse/GODRIVER-2311)
As of the fix in https://github.com/mongodb/mongo-go-driver/pull/874, we no longer return values that point to the same underlying byte array as the input from `bson.Unmarshal`. However, the fix copies byte slices that are returned to the caller _and_ byte slices that are copied to byte arrays or converted to other values by the caller. Improve the previous fix to reduce the unnecessary additional copy while maintaining the correct behavior.
=> GODRIVER-2311 Improve the BSON unmarshal buffer reuse fix to reduce memory allocations.

internal/testutil/config.go, internal/testutil/monitor/monitor.go, internal/testutil/ops.go, mongo/integration/change_stream_test.go, mongo/integration/client_test.go, mongo/integration/primary_stepdown_test.go, mongo/integration/retryable_reads_prose_test.go, mongo/integration/retryable_writes_prose_test.go, mongo/integration/sdam_error_handling_test.go, mongo/integration/server_selection_prose_test.go, x/mongo/driver/topology/server_test.go
[GODRIVER-2068](https://jira.mongodb.org/browse/GODRIVER-2068)
There are various test types that are used as an `*event.PoolMonitor` and all work slightly differently with different levels of isolation between tests. The existing `testPoolMonitor` in the `mongo/integration` package tests can satisfy the use cases of all pool monitors used in tests and is intended to be instantiated per-test to prevent interaction between tests. Move the existing `testPoolMonitor` into a new test utility package `internal/testutil/monitor` and use it in most tests that require a connection pool monitor.
Making the new test pool monitor available to all tests also allows us to improve the flaky `TestServerConnectionTimeout` test by replacing the test-specific pool monitor with a `monitor.TestPoolMonitor`. …
=> GODRIVER-2068 Use monitor.TestPoolMonitor to replace most connection pool monitors in tests.

mongo/client_side_encryption_examples_test.go
GODRIVER-2360
Replace "admin.datakeys" with "encryption.__keyVault" as a value as a `KeyVaultNamespace` option.
=> GODRIVER-2360 replace admin db in CSFLE examples

x/mongo/driver/topology/pool_test.go
If a connection initialization error occurs during `checkOut`, removing and closing the failed connection happen asynchronously with the `checkOut`. Update the intermittently failing "return error when attempting to create new connection" test to wait for up to 10s for the failed connection to be removed.
=> Fix race condition in pool checkOut test.

examples/documentation_examples/examples_test.go, mongo/client_options_test.go, mongo/database.go, mongo/gridfs/bucket.go, mongo/gridfs/upload_stream.go, mongo/main_test.go, mongo/mongo.go, mongo/mongo_test.go
[GODRIVER-1953](https://jira.mongodb.org/browse/GODRIVER-1953)
Stop using types and functions from the `bsonx` package in "production" code paths. Leave references in (most) tests and non-production code (e.g. benchmarks) to make reviewing easier and ensure backward compatibility of the changes. We can remove those additional `bsonx` references (and maybe the `bsonx` package) in a later change.
Based on https://github.com/mongodb/mongo-go-driver/pull/692 by [RammasEchor](https://github.com/RammasEchor)
=> GODRIVER-1953 Remove bsonx from production code paths.

mongo/integration/client_side_encryption_prose_test.go
[GODRIVER-2370](https://jira.mongodb.org/browse/GODRIVER-2370)
Can't cherry-pick https://github.com/mongodb/mongo-go-driver/commit/f48a833c0e8fc25447ce8a2b156ca25684c10560 because the case structure is different, so made the change directly.
=> Godriver 2370.update err msg csfle

mongo/bulk_write.go, mongo/collection.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation/delete.go, x/mongo/driver/operation/insert.go, x/mongo/driver/operation/update.go
[GODRIVER-2323](https://jira.mongodb.org/browse/GODRIVER-2323)
Add support for int32 and int64 types in the `"n"` and `"nModified"` fields in various server CRUD responses.
=> GODRIVER-2323 Support int64 for 'n' field in insert, update, and delete ops.

internal/testutil/monitor/monitor.go, x/mongo/driver/topology/rtt_monitor_test.go
Running various `topology` package tests with the data race detector reveals two data races in the test code:
```
❯ go test -timeout 120s -run 'TestCMAP|TestPool|TestServer|TestConnection' go.mongodb.org/mongo-driver/x/mongo/driver/topology -count=1 -race
==================
WARNING: DATA RACE
Read at 0x00c00000f4e0 by goroutine 17:
go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*mockSlowConn).Read()
./mongo-go-driver/x/mongo/driver/topology/rtt_monitor_test.go:51 +0x6e
...
Previous write at 0x00c00000f4e0 by goroutine 24:
go.mongodb.org/mongo-driver/x/mongo/driver/topology.(*mockSlowConn).Close()
./mongo-go-driver/x/mongo/driver/topology/rtt_monitor_test.go:68 +0x34
...
==================
WARNING: DATA RACE
Read at 0x00c0004c4088 by goroutine 25: …
```
=> Fix two data races in test code.

data/crud/unified/aggregate-write-readPreference.yml, data/crud/unified/bulkWrite-replaceOne-let.json, data/crud/unified/bulkWrite-replaceOne-let.yml, data/crud/unified/bulkWrite-update-hint-serverError.yml, data/crud/unified/bulkWrite-updateMany-let.yml, data/crud/unified/replaceOne-hint.yml, data/crud/unified/replaceOne-let.json, data/crud/unified/replaceOne-let.yml, data/crud/unified/updateMany-hint-serverError.yml, data/crud/unified/updateMany-hint.yml, data/crud/unified/updateMany-let.json, data/crud/unified/updateMany-let.yml, data/crud/unified/updateOne-hint-serverError.yml, data/crud/unified/updateOne-hint.yml, data/crud/unified/updateOne-let.json, data/crud/unified/updateOne-let.yml, data/crud/unified/updateWithPipelines.yml
GODRIVER-2376
Partially syncs the CRUD unified spec tests (we still can't sync fully until we add `comment` support for CRUD operations in GODRIVER-2318). Mostly adds `$$unsetOrMatches` for `multi` and `upsert` for `update` operations. Some drivers besides the Go driver explicitly send `multi: false` or `upsert: false` and were failing spec tests as those fields were not specified in the expected events.
=> GODRIVER-2376 Partially sync CRUD unified spec tests

data/crud/unified/aggregate-allowdiskuse.json, data/crud/unified/aggregate-allowdiskuse.yml, data/crud/unified/find-allowdiskuse.yml
GODRIVER-2380
Adds tests to ensure that `allowDiskUse` is sent correctly in `aggregate` and `find` operations when it is unset, false and true (we already have the correct behavior).
=> GODRIVER-2380 Sync CRUD spec tests for allowDiskUse

data/client-side-operations-timeout/README.rst, data/client-side-operations-timeout/global-timeoutMS.json, data/client-side-operations-timeout/global-timeoutMS.yml, data/client-side-operations-timeout/override-collection-timeoutMS.json, data/client-side-operations-timeout/override-collection-timeoutMS.yml, data/client-side-operations-timeout/override-database-timeoutMS.json, data/client-side-operations-timeout/override-database-timeoutMS.yml, data/client-side-operations-timeout/override-operation-timeoutMS.json, data/client-side-operations-timeout/override-operation-timeoutMS.yml
GODRIVER-2341
[This PR](https://github.com/mongodb/specifications/pull/960) is still under review to add spec and prose tests for CSOT. There are a large number of new tests in that PR. GODRIVER-2341 will add `Timeout` to basic CRUD operations. I'd like to sync a subset of the spec tests written in the aformentioned spec PR in _this_ PR so I can just have code changes that get these tests to pass in subsequent PRs for GODRIVER-2341.
=> GODRIVER-2341 Sync basic CSOT spec tests

examples/documentation_examples/README, examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go
GODRIVER-2010
Adds a README to `examples/documentation_examples` explaining the purpose of `examples.go` and `examples_test.go`. Replaces `context.Background()` with `context.TODO()` is actual example code. Actually runs `WithTransactionExample`. Uses `mtest.ClusterURI()` instead of hard-coding URIs. Reorganizes `examples_test.go` to use `mtest` for server version/topology logic. Adds links to examples pointing to where they appear/will appear on www.mongodb.com/docs.
=> GODRIVER-2010 Further clean up documentation examples

data/unified-test-format/valid-pass/entity-cursor-iterateOnce.json, data/unified-test-format/valid-pass/entity-cursor-iterateOnce.yml, data/unified-test-format/valid-pass/initialCollectionData-collectionOptions.json, data/unified-test-format/valid-pass/initialCollectionData-collectionOptions.yml, data/unified-test-format/valid-pass/matches-lte-operator.json, data/unified-test-format/valid-pass/matches-lte-operator.yml, mongo/integration/unified/collection_data.go, mongo/integration/unified/cursor_operation_execution.go, mongo/integration/unified/matches.go, mongo/integration/unified/operation.go, mongo/integration/unified/testrunner_operation.go
GODRIVER-2384
Updates the unified test runner to support functionality that will be introduced with the merging of [this PR](https://github.com/mongodb/specifications/pull/959). These test runner updates should allow me to start running the CSOT spec tests in subsequent PRs. 
Syncs valid-pass tests (POC tests that should pass in the unified test runner). Adds support for specifying `collectionOptions` in `initialData`, using the `iterateOnce` operation on cursor entities, using `$$lte` as a special matching operator, and using the `createEntities` operation on the test runner.
I did not sync the `invalid` tests, as we don't currently have a way of running those in the Go driver. I also did not add the new [`isTimeoutError`](https://github.com/mongodb/specifications/pull/959/files#diff-f718 …
=> GODRIVER-2384 Unified test runner changes for CSOT.

data/change-streams/unified/change-streams-pre_and_post_images.json, data/change-streams/unified/change-streams-pre_and_post_images.yml, mongo/change_stream.go, mongo/integration/unified/client_operation_execution.go, mongo/options/changestreamoptions.go, mongo/options/mongooptions.go
GODRIVER-2294
GODRIVER-2329
Syncs change stream unified spec tests to add tests for the new `fullDocument` values and `fullDocumentBeforeChange` (first commit). Adds `FullDocumentBeforeChange` to `ChangeStreamOptions`. Adds new `FullDocument` values: `Required`, `WhenAvailable` and `Off`.
=> GODRIVER-2294 Support PIT pre- and post-images for change streams

data/crud/unified/bulkWrite-comment.json, data/crud/unified/bulkWrite-comment.yml, data/crud/unified/deleteMany-comment.json, data/crud/unified/deleteMany-comment.yml, data/crud/unified/deleteOne-comment.json, data/crud/unified/deleteOne-comment.yml, data/crud/unified/insertMany-comment.json, data/crud/unified/insertMany-comment.yml, data/crud/unified/insertOne-comment.json, data/crud/unified/insertOne-comment.yml, data/crud/unified/replaceOne-comment.json, data/crud/unified/replaceOne-comment.yml, data/crud/unified/updateMany-comment.json, data/crud/unified/updateMany-comment.yml, data/crud/unified/updateOne-comment.json, data/crud/unified/updateOne-comment.yml
[GODRIVER-2394](https://jira.mongodb.org/browse/GODRIVER-2394)
Sync the unified CRUD tests with https://github.com/mongodb/specifications/commit/b8371eac99679f072672fa9c7c3ecafb279e13f1 .  Merging this into GODRIVER-2330, which is the branch that needs it directly.  It will eventually be merged into master through GODRIVER-2199 branch.
The path here is 
[GODRIVER-2199](https://github.com/mongodb/mongo-go-driver/pull/922) <- [GODRIVER-2330](https://github.com/mongodb/mongo-go-driver/pull/923) <- GODRIVER-2394
=> GODRIVER-2394 No error raised for bulkWrite with comment on <= 3.2

data/change-streams/unified/change-streams.json, data/change-streams/unified/change-streams.yml, data/crud/unified/aggregate.json, data/crud/unified/aggregate.yml, data/crud/unified/find-comment.json, data/crud/unified/find-comment.yml
GODRIVER-2321
Sync `change-streams`, `aggregate`, and `find-comment` unified spec tests from [mongodb/specifications@ad1ee9b](https://github.com/mongodb/specifications/commit/ad1ee9b764f7d9ff193fe485d31feca536e6a2d7).  
Include [missing test](https://github.com/mongodb/specifications/blob/ad1ee9b764f7d9ff193fe485d31feca536e6a2d7/source/crud/tests/unified/find-comment.yml#L91) to `find-comment.yml`.
=> GODRIVER-2321 Fix getMore with comment specs

mongo/integration/collection_test.go
GODRIVER-2315
[SERVER-63201](https://jira.mongodb.org/browse/SERVER-63201)  recently allowed deletes on capped collections in the latest server versions. That ticket was backported to server version 5.0.7. Some of our tests in `integration/collection_test.go` expect server-side write errors when running a delete operation against a capped collection. Updates these tests to only run against 5.0.6- (previously ran on 5.2.99-).
=> GODRIVER-2315 Further restrict tests that expect errors with capped collection deletes.

x/mongo/driver/ocsp/ocsp.go, x/mongo/driver/ocsp/ocsp_test.go
[GODRIVER-2395](https://jira.mongodb.org/browse/GODRIVER-2395)
Currently, the OCSP certificate status fetching code in the Go Driver (run when the certificate status is not stapled to the certificate) will return an error if the passed-in Context is cancelled or passes its deadline (see [here](https://github.com/mongodb/mongo-go-driver/blob/f195b4e891d34ef0c680c19a2d0f36a2a0c4794c/x/mongo/driver/ocsp/ocsp.go#L277)). However, the [OCSP spec](https://github.com/mongodb/specifications/blob/223df1f58beb0d3aed1e6ef7f1ee74a707a01a43/source/ocsp-support/ocsp-support.rst) describes that drivers should "soft fail" (i.e. fail to return a conclusive status but also not return any errors) anytime the OCSP responders are unreachable for any reason.
Update the OCSP certificate status fetching code to …
=> GODRIVER-2395 Never return errors when attempting to contact OCSP responders.

x/mongo/driver/batch_cursor.go
The `legacy` field in the `BatchCursor` type is unused, remove it.
=> Remove unused 'legacy' field from BatchCursor.

.gitignore, CONTRIBUTING.md, vendor/github.com/xdg-go/pbkdf2/README.md, vendor/github.com/xdg-go/scram/CHANGELOG.md, vendor/github.com/xdg-go/scram/README.md, vendor/github.com/xdg-go/stringprep/CHANGELOG.md, vendor/github.com/xdg-go/stringprep/README.md, vendor/github.com/youmark/pkcs8/README.md, vendor/gopkg.in/yaml.v3/README.md
Some information in CONTRIBUTING.md is out-of-date and some Markdown files are missing from the vendor directory.
Changes:
* Update CONTRIBUTING.md with current information on contributing to the Go Driver.
* Remove `**.md` from .gitignore so git picks up all changes to Markdown files.
* Commit all previously ignored *.md files from the vendor directory.
=> Update CONTRIBUTING with current information and stop ignoring *.md files.

data/unified-test-format/valid-fail/operation-unsupported.json, data/unified-test-format/valid-fail/operation-unsupported.yml
GODRIVER-2409
Syncs a simple spec tests that ensures that the unified test runner fails when it encounters an unsupported operation `unsupportedOperation`.
=> GODRIVER-2409 Add spec test for unsupported operation.

.evergreen/config.yml, data/change-streams/unified/change-streams-pre_and_post_images.json, data/change-streams/unified/change-streams-pre_and_post_images.yml, data/change-streams/unified/change-streams.json, data/change-streams/unified/change-streams.yml, data/unified-test-format/valid-pass/poc-change-streams.json, data/unified-test-format/valid-pass/poc-change-streams.yml, mongo/integration/mtest/global_state.go, mongo/integration/mtest/setup.go, mongo/integration/unified/client_entity.go
GODRIVER-2389
GODRIVER-2214
Syncs unified change streams tests to not run against serverless topologies (they are not supported). Updates serverless testing to use the new `SERVERLESS_URI` as a testing URI.
I've linked the serverless task to this PR manually to show it passing and will also add the serverless task to the set of tasks run on every GH Evergreen patch.
=> Fix serverless task

.evergreen/config.yml
Currently Go builds fail or use the wrong version of Go on Windows Evergreen tasks. The issue is that the `PATH` environment variable contains a mixture of Windows-style paths (e.g. `C:/...`) and Bash-style Cygwin paths (e.g. `/cygdrive/c/...`), but is being interpreted by the Bash shell in Cygwin, which doesn't support Windows-style paths (the `PATH` separator and the Windows drive separator are both a colon ":"). To fix it, convert all Windows-style paths to Bash-style Cygwin paths when building the `PATH` environment variable. Note that other scripts and binaries expect Windows-style paths, so keep the Windows-style paths for all other exported environment variables (e.g. `GOROOT`).
=> GODRIVER-2264 Fix PATH on Windows Evergreen tasks to work with Cygwin/Bash shell.

data/unified-test-format/valid-fail/clientEncryptionOpts-missing-kms-credentials.json, data/unified-test-format/valid-fail/clientEncryptionOpts-missing-kms-credentials.yml, data/unified-test-format/valid-fail/clientEncryptionOpts-no-kms.json, data/unified-test-format/valid-fail/clientEncryptionOpts-no-kms.yml, data/unified-test-format/valid-fail/kmsProviders-missing_aws_kms_credentials.json, data/unified-test-format/valid-fail/kmsProviders-missing_aws_kms_credentials.yml, data/unified-test-format/valid-fail/kmsProviders-missing_azure_kms_credentials.json, data/unified-test-format/valid-fail/kmsProviders-missing_azure_kms_credentials.yml, data/unified-test-format/valid-fail/kmsProviders-missing_gcp_kms_credentials.json, data/unified-test-format/valid-fail/kmsProviders-missing_gcp_kms_credentials.yml, data/unified-test-format/valid-fail/kmsProviders-no_kms.json, data/unified-test-format/valid-fail/kmsProviders-no_kms.yml, data/unified-test-format/valid-pass/kmsProviders-explicit_kms_credentials.json, data/unified-test-format/valid-pass/kmsProviders-explicit_kms_credentials.yml, data/unified-test-format/valid-pass/kmsProviders-mixed_kms_credential_fields.json, data/unified-test-format/valid-pass/kmsProviders-mixed_kms_credential_fields.yml, data/unified-test-format/valid-pass/kmsProviders-placeholder_kms_credentials.json, data/unified-test-format/valid-pass/kmsProviders-placeholder_kms_credentials.yml, data/unified-test-format/valid-pass/kmsProviders-unconfigured_kms.json, data/unified-test-format/valid-pass/kmsProviders-unconfigured_kms.yml, mongo/integration/mtest/csfle_enabled.go, mongo/integration/mtest/csfle_not_enabled.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/integration/unified/entity.go, mongo/integration/unified/schema_version.go
GODRIVER-2352
Add Unified Test Format support for 1.8. This is a prerequisite for the Go implementation of the CSFLE Key Management API.
See https://github.com/mongodb/specifications/commit/e91f0ec558d8d6c3213126fd63aa3d111771f49d and https://github.com/mongodb/specifications/commit/0f65908778188a8d6eeb22571c7791a2b1674234 for the Unified Test Format changes.
`ClientEncryption.Close()` calls `Disconnect` on the keyVaultClient. [Client entities used as keyVaultClients are tracked](https://github.com/mongodb/mongo-go-driver/pull/920/commits/9b1b9c2e5093d8303727bb80de402fa3d6ed4622) to prevent the test runner from calling `Disconnect` twice.
=> GODRIVER-2352 Add clientEncryption entity to unified test format

Makefile, data/collection-management/README.rst, data/collection-management/createCollection-pre_and_post_images.json, data/collection-management/createCollection-pre_and_post_images.yml, data/collection-management/modifyCollection-pre_and_post_images.json, data/collection-management/modifyCollection-pre_and_post_images.yml, data/unified-test-format/valid-pass/initialCollectionData-collectionOptions.json, data/unified-test-format/valid-pass/initialCollectionData-collectionOptions.yml, mongo/integration/retryable_reads_prose_test.go
GODRIVER-2421
GODRIVER-2396
Runs all tests specified [in the spec](https://github.com/mongodb/specifications/blob/master/source/serverless-testing/README.rst#existing-spec-tests) against serverless instances (we were missing a number of them). Forbids `serverless` on some collection management tests, the `initialCollectionData` UTF test and the retryable reads prose test that asserts `PoolClearedError` retryability (pool clearing logic differs when running against serverless).
=> Run all appropriate tests against serverless

mongo/integration/client_side_encryption_prose_test.go, mongo/integration/collection_test.go, mongo/integration/crud_prose_test.go, mongo/integration/cursor_test.go, mongo/integration/database_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/mtest/options.go, mongo/integration/unified_spec_test.go
GODRIVER-2398
This is a test refactor with no functional changes.
- Use `CreateCollection()` and `CreateView()`, not `RunCommand()` to create test collections in mtest.
This is motivated by upcoming CSFLE specification tests of GODRIVER-2398. The `EncryptedFields` option is handled in the `Database.CreateCollection()` helper.
=> GODRIVER-2398 use CreateCollection() and CreateView() in mtest

x/mongo/driver/topology/fsm.go
=> GODRIVER-2408 Bump maxWireVersion for MongoDB 6.0

data/change-streams/change-streams.json, data/change-streams/change-streams.yml
[GODRIVER-2393](https://jira.mongodb.org/browse/GODRIVER-2393)
Sync unified test for `wallTime` field in the change stream event output.
=> GODRIVER-2393 Sync unified tests

bson/bsoncodec/bsoncodec.go, bson/bsoncodec/empty_interface_codec.go, bson/bsoncodec/map_codec.go, bson/decoder.go, bson/decoder_test.go
GODRIVER-2407 
This PR creates a way for a user/client to write a document-type override to the `DecodeContext` per [this JIRA comment](https://jira.mongodb.org/browse/GODRIVER-2407?focusedCommentId=4551812&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4551812).
```go
dec, err := NewDecoder(bsonrw.NewBSONDocumentReader(bytes))
t.Fatal(err)
}
// This will default empty interfaces into primitive.D.
dec.DefaultDocumentD()
```
My understanding is that we would like the encoder/decoder map to be [bijective](https://en.wikipedia.org/wiki/Bijection).
```
encoder                decoder
go type ───────► bsontype.Type ───────► driver type
```
I believe that the canonical argument for this is that the purpose of a BSON decoder should be to decode …
=> GODRIVER-2407 Add DocumentDecodeType to DecodeContext

mongo/options/clientoptions.go, mongo/options/clientoptions_test.go
Currently it's possible for `ClientOptions.Validate()` validation errors to be overwritten because `validateAndSetError()` does not always return when setting an error, specifically the errors set [here](https://github.com/mongodb/mongo-go-driver/blob/7c228ce9ad08e276108e8e01ac1a63222e7447a3/mongo/options/clientoptions.go#L186) and [here](https://github.com/mongodb/mongo-go-driver/blob/7c228ce9ad08e276108e8e01ac1a63222e7447a3/mongo/options/clientoptions.go#L208). Simplify the `validateAndSetError()` API to return instead of store validation errors and always return immediately on errors.
=> Improve ClientOptions.Validate to prevent overwriting validation errors.

data/client-side-encryption-prose/encrypted-fields.json, data/client-side-encryption-prose/key1-document.json, mongo/client_encryption.go, mongo/doc.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/mtest/mongotest.go, mongo/options/encryptoptions.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/options/mongocrypt_context_options.go
GODRIVER-2400
- Support new encryption algorithms "Indexed" and "Unindexed".
- Support the new explicit encryption API: `queryType` and `contentionFactor`.
- Document requirement of libmongocrypt 1.5.0 in Go driver 1.10.0.
Please see the "Upstream Changes Summary" links to the specification changes implemented.
=> GODRIVER-2400 Add FLE 2 API to explicit encryption

.evergreen/config.yml, data/client-side-encryption/fle2-CreateCollection.json, data/client-side-encryption/fle2-CreateCollection.yml
- Use libmongocrypt 1.5.0-alpha2 in tests.
- Update the fle2-CreateCollection test from https://github.com/mongodb/specifications/pull/1230.
- Update Windows download to use 1.5.0-alpha2 rather than the latest unstable release.
Updating fle2-CreateCollection resolves test failures. MONGOCRYPT-429 requires additional `listCollections` commands in the expectations in the fle2-CreateCollection test.
libmongocrypt 1.5.0-alpha2 includes [this fix](https://jira.mongodb.org/browse/MONGOCRYPT-427) to explain with the csfle shared library.
=> pin to libmongocrypt 1.5.0-alpha2

bson/bson_test.go, bson/bsoncodec/default_value_decoders.go, bson/mgocompat/setter_getter.go, bson/unmarshaling_cases_test.go
GODRIVER-2427
Reporter is getting an error when defining an unmarshaler for unaddressable data.  Using `(Value).CanSet()` to determine if we should use the zero value setter resolves this problem.  `(Value).CanSet()` determines for a value if 
> [it is addressable and was not obtained by the use of unexported struct fields](https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/reflect/value.go;l=324)
The behavior of the `json/encoding` package is to allow the unmarshaler to run in such cases, [for example](https://go.dev/play/p/ZrfEEGeus9O).  Given that, I would expect the BSON unmarshaler to call `UnmarshalBSON` for unadressable values as well.
=> Godriver 2427 Unmarshaler for Unaddressable Data

internal/testutil/assert/assert.go, mongo/client.go, mongo/integration/client_test.go, mongo/integration/sdam_prose_test.go, mongo/integration/unified_runner_events_helper_test.go, mongo/with_transactions_test.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/rtt_monitor_test.go, x/mongo/driver/topology/topology_errors_test.go
GODRIVER-2405
Tests that the 90th percentile observed round-trip time is monitored and used to prevent sending messages to the server when `Timeout` is specified. Tests the functionality of the new `percentile` function and the `getRTT90()` method of `rttMonitor`. Bumps the `minSamples` of the `rttMonitor` to 10 instead of 5.
Opening PRs with csot-implementation as the base branch messes with the GH Evergreen CI: so [here](https://spruce.mongodb.com/version/629768842fbabe16459b62db/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) is a patch I'll keep updated with every commit.
=> GODRIVER-2405 Test RTT90 monitoring.

Makefile, examples/documentation_examples/examples_test.go, mongo/client_test.go, mongo/gridfs/gridfs_test.go, mongo/integration/client_options_test.go, mongo/integration/client_test.go, mongo/integration/main_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/unified/main_test.go, mongo/with_transactions_test.go, x/mongo/driver/integration/aggregate_test.go, x/mongo/driver/topology/polling_srv_records_test.go
[GODRIVER-2184](https://jira.mongodb.org/browse/GODRIVER-2184)
We want to be able to run tests with the `-short` flag and expect the tests to run reasonably quickly with minimal dependencies. For example, we want to be able to run the following command to easily run all non-integration-tests:
```
go test -short ./...
```
=> GODRIVER-2184 Skip all integration tests when the -short flag is included.

.evergreen/config.yml, data/client-side-encryption/fle2-Delete.json, data/client-side-encryption/fle2-Delete.yml, data/client-side-encryption/fle2-EncryptedFields-vs-jsonSchema.json, data/client-side-encryption/fle2-EncryptedFields-vs-jsonSchema.yml, data/client-side-encryption/fle2-FindOneAndUpdate.json, data/client-side-encryption/fle2-FindOneAndUpdate.yml, data/client-side-encryption/fle2-InsertFind-Indexed.json, data/client-side-encryption/fle2-InsertFind-Indexed.yml, data/client-side-encryption/fle2-Update.json, data/client-side-encryption/fle2-Update.yml
GODRIVER-2439
- Update libmongocrypt dependency to 1.5.0-rc0.
- Resync FLE 2 tests.
Please see the "Downstream Changes Summary" of DRIVERS-2343.
=> GODRIVER-2439 Update expected FLE 2 find payloads

mongo/collection.go
small typo in `aggregate` doc.
=> ~ `aggreate` -> `aggregate`

.golangci.yml, bson/primitive/decimal_test.go, mongo/client.go, mongo/options/clientoptions.go, x/mongo/driver/connstring/connstring.go
Appending to a slice and assigning the result to a different or new variable than the one being appended to is a common source of intermittent bugs.
Consider the following example:
```go
a := make([]int, 0, 4)
a = append(a, 1, 2, 3)
b := append(a, 4)
a = append(a, 5)
```
After running that, we expect that `a` contains `[1 2 3 5]` and `b` contains `[1 2 3 4]`. However, the last append to `a` actually overwrites the last element of `b` as well because they both share the same underlying array. Check out an example in the Go Playground [here](https://go.dev/play/p/F21yGAitcOl). To make the situation more confusing, if we change the initial capacity of `a` from 4 to 3, we get the behavior we originally expected!
We should avoid appending and assigning to a different variable. Enable the …
=> Check for and fix suspicious append result assignments.

.evergreen/config.yml, data/client-side-encryption/fle2-Delete.json, data/client-side-encryption/fle2-Delete.yml, data/client-side-encryption/fle2-EncryptedFields-vs-jsonSchema.json, data/client-side-encryption/fle2-EncryptedFields-vs-jsonSchema.yml, data/client-side-encryption/fle2-FindOneAndUpdate.json, data/client-side-encryption/fle2-FindOneAndUpdate.yml, data/client-side-encryption/fle2-InsertFind-Indexed.json, data/client-side-encryption/fle2-InsertFind-Indexed.yml, data/client-side-encryption/fle2-Update.json, data/client-side-encryption/fle2-Update.yml
- Revert GODRIVER-2439.
- Use libmongocrypt 1.5.0-rc1.
MONGOCRYPT-433 was reverted in libmongocrypt 1.5.0-rc1. This reverted changes to the FLE 2 find payload and required updating FLE 2 tests.
Attempting to pin Windows builds to a specific release resulted in a ["Host key verification failed" error](https://evergreen.mongodb.com/lobster/evergreen/task/mongo_go_driver_tests_legacy_noauth_nossl__version~2.6_os_ssl_32~windows_64_go_1_17_test_standalone_noauth_nossl_11b70760d4c38b59b9ddfef1a891f1e6ea1afa28_22_06_03_02_04_12/0/task#bookmarks=0%2C388&l=1&shareLine=86) when building libmongocrypt. Filed [BUILD-15101](https://jira.mongodb.org/browse/BUILD-15101) to investigate.
=> Revert GODRIVER-2439 and use libmongocrypt 1.5.0-rc1

.evergreen/config.yml, .evergreen/run-tests.sh, .golangci.yml, mongo/client.go, mongo/client_encryption.go, mongo/client_test.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/client_side_encryption_test.go, mongo/integration/mtest/mongotest.go, mongo/integration/unified_spec_test.go, mongo/mongocryptd.go, mongo/options/autoencryptionoptions.go, x/mongo/driver/crypt.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/mongocrypt_not_enabled.go, x/mongo/driver/mongocrypt/options/mongocrypt_options.go
Allow loading the new crypt_shared library in the Go driver.
Changes related to crypt_shared:
* Support loading the new crypt_shared library.
* Add new AutoEncryption extra options "cryptSharedLibRequired" and "cryptSharedLibPath" and document how to use the options on `AutoEncryptionOptions.SetExtraOptions`.
* Separate creation of a `mongocrypt.MongoCrypt` from creation of a `driver.crypt` to prevent having to pass options that are only relevant to `mongocrypt.NewMongoCrypt` through `driver.NewCrypt`.
* Don't spawn mongocryptd when the crypt_shared library is loaded.
* Test that when the crypt_shared library is loaded, mongocryptd is not spawned.
* Download the crypt_shared library in Evergreen CI tasks for supported platforms and set the `CRYPT_SHARED_LIB_PATH` environment variable to …
=> GODRIVER-2411 Allow loading the new crypt_shared library.

.evergreen/config.yml
GODRIVER-2417
Runs the load balancer tests against 6.0 and 5.0. Previously we were only running against `latest` and `rapid`.
=> GODRIVER-2417 Run load balancer tests against 6.0 and 5.0.

data/client-side-operations-timeout/bulkWrite.json, data/client-side-operations-timeout/bulkWrite.yml
GODRIVER-2341
Syncs the `bulkWrite` CSOT spec tests.
I forgot to sync these with the original GODRIVER-2341 PR, but no code changes are required.
=> GODRIVER-2341 Sync CSOT bulkWrite spec tests.

x/mongo/driver/compression.go, x/mongo/driver/compression_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_test.go, x/mongo/driver/wiremessage/wiremessage.go
[GODRIVER-2259](https://jira.mongodb.org/browse/GODRIVER-2259)
[GODRIVER-2023](https://jira.mongodb.org/browse/GODRIVER-2023)
- Tune the Zstd compression.
- Use src slice directly when using no compression.
=> Godriver2259 Reduce memory consumption in Connection.CompressWireMessage().

.evergreen/config.yml, mongo/client_encryption.go, mongo/integration/client_side_encryption_prose_test.go, mongo/integration/cmd_monitoring_helpers_test.go, mongo/integration/mtest/mongotest.go, mongo/options/encryptoptions.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/options/mongocrypt_context_options.go
=> GODRIVER-2454 use string for QueryType

mongo/client.go, mongo/session.go
[GODRIVER-2453](https://jira.mongodb.org/browse/GODRIVER-2453)
Add phrasing to match the [session spec](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#clientsession): 
> `ClientSession` instances are not thread safe or fork safe
- [Client.StartSession](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Client.StartSession)
- [Client.UseSession](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Client.UseSession)
- [Client.UseSessionWithOptions](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Client.UseSessionWithOptions)
- [mongo.Session](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#Session)
- [mongo.WithSession](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo#WithSession)
=> GODRIVER-2453 extend session function comments with thread/fork warnings

mongo/integration/csot_prose_test.go, x/mongo/driver/topology/topology.go
GODRIVER-2343
Adds the CSOT [prose tests](https://github.com/mongodb/specifications/blob/master/source/client-side-operations-timeout/tests/README.rst#server-selection) for server selection.
These new tests ensure that `ServerSelectionTimeout` and `Timeout` have the correct interaction when set on the `Client`.
=> GODRIVER-2343 Add CSOT prose tests for server selection.

.evergreen/config.yml
[GODRIVER-2472](https://jira.mongodb.org/browse/GODRIVER-2472)
Add a task that runs all of the regular tests for each server version with `SKIP_CRYPT_SHARED_LIB_DOWNLOAD="true"` to force all tests to use `mongocryptd` instead of the `crypt_shared` library. Pick a task with TLS and authentication enabled using a replicaset, which we expect to be a reasonably representative configuration for customers using CSFLE.
Server versions that run on Ubuntu 14.04 have no dedicated `mongocryptd` test because there is no `crypt_shared` library for those platforms, so all tasks use `mongocryptd`.
=> GODRIVER-2472 Run at least one CI task for every server version using mongocryptd.

.evergreen/config.yml, data/client-side-encryption/legacy/fle2-Delete.json, data/client-side-encryption/legacy/fle2-Delete.yml, data/client-side-encryption/legacy/fle2-EncryptedFields-vs-jsonSchema.json, data/client-side-encryption/legacy/fle2-EncryptedFields-vs-jsonSchema.yml, data/client-side-encryption/legacy/fle2-FindOneAndUpdate.json, data/client-side-encryption/legacy/fle2-FindOneAndUpdate.yml, data/client-side-encryption/legacy/fle2-InsertFind-Indexed.json, data/client-side-encryption/legacy/fle2-InsertFind-Indexed.yml, data/client-side-encryption/legacy/fle2-Update.json, data/client-side-encryption/legacy/fle2-Update.yml, mongo/integration/client_side_encryption_prose_test.go
- GODRIVER-2436 bump libmongocrypt test dependency to 1.5.0
- GODRIVER-2474 set contentionFactor in explicit encryption tests
- GODRIVER-2439 resync fle2 tests
=> Update to libmongocrypt 1.5.0

examples/documentation_examples/examples.go, examples/documentation_examples/examples_test.go
The example `StableAPIStrictCountExample` no longer works because "count" was added to Stable API v1. Skip the test for all server versions for now. See [GODRIVER-2482](https://jira.mongodb.org/browse/GODRIVER-2482) for more details and the plant to eventually update the example.
=> Skip Stable API count example test.

.evergreen/config.yml, Makefile
Confirm that PRs always have "tidy" and correctly vendored modules by running `go mod tidy` and `go mod vendor` during Evergreen CI runs. If `go mod tidy` or `go mod vendor` make any changes, return an error code.
=> Confirm that modules are always tidy and vendored.

data/connection-string/valid-auth.json, data/connection-string/valid-auth.yml, x/mongo/driver/connstring/connstring.go
[GODRIVER-449](https://jira.mongodb.org/browse/GODRIVER-449)
Use [url.PathUnescape](https://pkg.go.dev/net/url#PathUnescape) instead of [url.QueryUnescape](https://pkg.go.dev/net/url#QueryUnescape) to more correctly unescape usernames and passwords in connection strings. Specifically, [url.QueryUnescape](https://pkg.go.dev/net/url#QueryUnescape) unescapes "+" to " ", which does not match the behavior required by the [Connection String Spec](https://github.com/mongodb/specifications/blob/0e1d31ec088a4da9380cba95eb987db97bc435ed/source/connection-string/connection-string-spec.rst). [url.PathUnescape](https://pkg.go.dev/net/url#PathUnescape) does not unescape "+" to " ":
> PathUnescape is identical to QueryUnescape except that it does not unescape '+' to ' ' (space). 
Also sync connection …
=> GODRIVER-449 Correctly unescape usernames and passwords in connection strings

data/server-discovery-and-monitoring/integration/hello-command-error.json, data/server-discovery-and-monitoring/integration/hello-command-error.yml, data/server-discovery-and-monitoring/integration/hello-network-error.json, data/server-discovery-and-monitoring/integration/hello-network-error.yml, data/server-discovery-and-monitoring/integration/hello-timeout.json, data/server-discovery-and-monitoring/integration/hello-timeout.yml, x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/rtt_monitor_test.go
[GODRIVER-2464](https://jira.mongodb.org/browse/GODRIVER-2464)
Currently the RTT monitor uses a context without timeout to run the "hello" operation (see [here](https://github.com/mongodb/mongo-go-driver/blob/95de0fb36ca077bbe9a92b3fbf66ef0d28c6eeae/x/mongo/driver/topology/rtt_monitor.go#L128)). As a result, it's possible for RTT monitor "hello" operations to get stuck indefinitely if there is a network problem, preventing the monitor from recording more RTT samples. The motivation for this ticket comes from troubleshooting [GODRIVER-2438](https://jira.mongodb.org/browse/GODRIVER-2438).
Add a timeout to the RTT monitor "hello" operation to prevent network issues from causing the RTT monitor to get stuck. Add a test that confirms that the RTT monitor can recover from a stuck operation. …
=> GODRIVER-2464 Add timeout for RTT monitor hello operations.

.evergreen/config.yml
Currently the OS specs in the `os-aws-auth` axis define the `PYTHON3` variable that contains a path to the Python 3 binary for that OS. However, all of the other Evergreen configuration and scripts use the `PYTHON3_BINARY` variable name, leading to CI setup failures like [this](https://evergreen.mongodb.com/task/mongo_go_driver_aws_auth_test__version~4.4_os_aws_auth~windows_64_vsMulti_small_go_1_17_aws_auth_test_6f2489ef35dae2e7b2cfdc2e13b4dbc02b3f40e6_22_07_07_21_43_02). Use the correct variable name and update the Python 3 path to point to a Python 3 binary.
Changes:
* Define `PYTHON3_BINARY` variable instead of `PYTHON3` variable for `os-aws-auth` OS specs.
* Use correct path for `PYTHON3_BINARY` variable copied from the `os-ssl-40` OS specs.
=> Use correct variable name for Python path in AWS auth tests.

x/mongo/driver/topology/rtt_monitor_test.go
The new `TestRTTMonitor/stuck_operations_time_out` test added in https://github.com/mongodb/mongo-go-driver/pull/994 fails frequently on Windows tasks because Go running on some versions of Windows can't measure very short periods of time (<1ms) reliably (see test failure example [here](https://spruce.mongodb.com/task/mongo_go_driver_tests_42_plus_zlib_zstd_support__version~5.0_os_ssl_40~windows_64_go_1_17_test_replicaset_auth_nossl_03207bb751fa9b9b34c71c22830a265df7f98a83_22_07_13_15_25_04/tests?execution=0&sortBy=STATUS&sortDir=ASC) and related Go issue [here](https://github.com/golang/go/issues/8687)).
Add a 10ms delay in the `TestRTTMonitor/stuck_operations_time_out` test "hello" responder so that Windows can successfully measure a non-zero round-trip latency.
=> GODRIVER-2464 Add delay in RTT monitor test so Windows can measure a non-zero latency.

mongo/integration/client_test.go
GODRIVER-2483
Reduces expectation of 90th percentile round-trip-time to 275ms in a network environment where connections block for 300ms. This makes the test much more reliable on Windows distributions (that can have poor time granularity in Go).
=> GODRIVER-2483 Make RTT90 client integration test more reliable

.evergreen/config.yml, .evergreen/run-tests.sh
- Download the same version of crypt_shared as the server version.
This PR validates changes proposed in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/213.
Queryable Encryption is in Technical Preview and is subject to backwards breaking changes. If backwards breaking changes are made, using different version of the server and crypt_shared may complicate diagnosing driver test failures.
=> GODRIVER-2492 use consistent versions of crypt_shared and server

data/change-streams/change-streams-resume-errorLabels.json, data/change-streams/change-streams-resume-errorLabels.yml
GODRIVER-2494
Skips the `StaleShardVersion` change stream resumability test on 6.1+, as `StaleShardVersion` was removed in server version 6.1.0 and is no longer considered resumable.
This should fix the "latest" test failures for now.
=> GODRIVER-2494 Skip StaleShardVersion resume test on 6.1+.

data/client-side-operations-timeout/error-transformations.json, data/client-side-operations-timeout/error-transformations.yml, internal/csot_util.go, mongo/change_stream_deployment.go, mongo/errors.go, mongo/integration/client_test.go, mongo/integration/mtest/opmsg_deployment.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/driver.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/topology/rtt_monitor.go, x/mongo/driver/topology/rtt_monitor_test.go, x/mongo/driver/topology/server.go, x/mongo/driver/topology/server_rtt_test.go
GODRIVER-2339
Syncs CSOT spec tests for error transformations. Extends the `IsTimeout()` helper to recognize the `MaxTimeMSExpired` error. Modifies the `Server` interface to contain a new `RTTMonitor` interface. Adds `Stats()` method to `rttMonitor`. Returns RTT monitor stats with `ErrDeadlineWouldBeExceeded` errors.
=> GODRIVER-2339 Use interface for RTTMonitor and add Stats method.

.evergreen/config.yml, data/client-side-encryption/legacy/fle2-InsertFind-Unindexed.json, data/client-side-encryption/legacy/fle2-InsertFind-Unindexed.yml, data/client-side-encryption/unified/createDataKey-kms_providers-invalid.json, data/client-side-encryption/unified/createDataKey-kms_providers-invalid.yml, data/client-side-encryption/unified/rewrapManyDataKey.json, data/client-side-encryption/unified/rewrapManyDataKey.yml, go.mod, mongo/client_encryption.go, mongo/doc.go, mongo/integration/client_side_encryption_prose_test.go, x/mongo/driver/mongocrypt/mongocrypt.go, x/mongo/driver/mongocrypt/mongocrypt_not_enabled.go
Resolve GODRIVER-2511:
- Add CSFLE prose test 16.
- Update tests to use libmongocrypt 1.5.2.
Resolve GODRIVER-2513:
- Return error if libmongocrypt < 1.5.2 is detected in RewrapManyDataKey.
- Retract Go 1.10.0.
Resolve GODRIVER-2509:
- Resync RewrapManyDataKey specification tests to https://github.com/mongodb/specifications/commit/10b4a41f8d282cebc5d3681adba27de18539d9f4.
Resolve GODRIVER-2512:
- Resync fle2-InsertFind-Unindexed.json file to https://github.com/mongodb/specifications/pull/1286.
libmongocrypt 1.5.2 includes a fix to a severe bug introduced in libmongocrypt 1.5.0: MONGOCRYPT-464.
=> update for libmongocrypt 1.5.2

mongo/change_stream.go
GODRIVER-2489
Update `createPipelineOptionsDoc` to return `error` to shore up non-idomatic error handling in the the change stream operations.
=> GODRIVER-2489 createPipelineOptionsDoc: return err

mongo/collection.go, mongo/index_view.go, mongo/integration/operation_legacy_test.go, mongo/options/clientoptions.go, mongo/session.go, x/mongo/driver/errors.go, x/mongo/driver/operation.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/commit_transaction.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation/createIndexes.go, x/mongo/driver/operation/distinct.go, x/mongo/driver/operation/drop_indexes.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/list_indexes.go, x/mongo/driver/operation_legacy.go, x/mongo/driver/operation_test.go
GODRIVER-2496
Changes `MaxTimeMS` `*int64` values to `MaxTime` `*time.Duration` values. Passes `MaxTime` fields to `operation.go` where a new `calculateMaxTimeMS` method calculates the correct `maxTimeMS` field to append based on setting of `Timeout` (instead of appending `maxTimeMS` in operation `command` methods). Adds tests for `calculateMaxTimeMS`.
=> GODRIVER-2496 Simplify maxTimeMS appension.

.evergreen/config.yml
The "latest" version of golangci-lint currently requires Go 1.19. We can pin back to "latest" when we complete [GODRIVER-2519](https://jira.mongodb.org/browse/GODRIVER-2519).
=> Pin golangci-lint to a version that supports Go 1.17

.evergreen/config.yml, cmd/testgcpkms/main.go
- Use MongoDB managed GCP account for GCP tests.
The integration tests added in DRIVERS-2377 were relying on a personal account.
[BUILD-15386](https://jira.mongodb.org/browse/BUILD-15386) provided a service account with necessary permissions.
Here is a patch build with the [testgcpkms tasks](https://spruce.mongodb.com/version/62f13d6f9ccd4e4612bed0eb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
=> GODRIVER-2514 Use MongoDB managed GCP account for GCP tests.

data/client-side-encryption/unified/addKeyAltName.json, data/client-side-encryption/unified/addKeyAltName.yml, data/client-side-encryption/unified/getKey.json, data/client-side-encryption/unified/getKey.yml, data/client-side-encryption/unified/getKeyByAltName.json, data/client-side-encryption/unified/getKeyByAltName.yml, data/client-side-encryption/unified/removeKeyAltName.json, data/client-side-encryption/unified/removeKeyAltName.yml
- Resync key management unified tests with https://github.com/mongodb/specifications/commit/79f682a4a7e62fcce18099b4552d48d1f679e096
=> GODRIVER-2485 update unified CSE tests

data/transactions/unified/do-not-retry-read-in-transaction.json, data/transactions/unified/do-not-retry-read-in-transaction.yml
GODRIVER-2502
Adds a test to ensure that a read type operation will not be retried when a transaction is active.
=> GODRIVER-2502 Add test that reads are not retried in a transaction.

.evergreen/config.yml, README.md, docs/CONTRIBUTING.md
=> GODRIVER-2518 Use Go 1.18 for Evergreen CI.

.evergreen/config.yml
- Remove unnecessary download of crypt_shared library
https://github.com/mongodb-labs/drivers-evergreen-tools/commit/5af4bfe0f18ece58d8492436b115c24a4167f1a3 simplified obtaining the crypt_shared library.
Running the `run-orchestration.sh` script will now generate the `CRYPT_SHARED_LIB_PATH` expansion.
=> GODRIVER-2492 remove command to download crypt_shared

mongo/session.go, x/mongo/driver/operation.go, x/mongo/driver/operation_test.go, x/mongo/driver/topology/connection.go, x/mongo/driver/topology/connection_errors_test.go, x/mongo/driver/topology/connection_test.go
GODRIVER-2468
GODRIVER-1965
Stops returning a network error when minimum RTT exceeds time remaining until deadline. Stops checking for context expiration in `writeWireMessage` and `readWireMessage`; removes associated tests. Stops checking for context expiration in `WithTransaction`. Starts checking for _any_ context error before running `roundTrip` in `Execute` (including cancelation). Adds tests to ensure that `Execute` does not mark done contexts with the `TransientTransactionError` label.
Network errors can be marked with the `TransientTransactionError` label [here](https://github.com/mongodb/mongo-go-driver/blob/master/x/mongo/driver/operation.go#L848), and can therefore be retryable. Context errors do not represent retryable scenarios, so we should stop calling `networkError()` on …
=> Stop treating context errors as network errors where possible.

.golangci.yml, bson/bsonoptions/doc.go, bson/bsonrw/bsonrwtest/bsonrwtest.go, mongo/address/addr.go, mongo/description/description.go, mongo/options/doc.go, mongo/readconcern/readconcern.go, mongo/readpref/readpref.go, mongo/writeconcern/writeconcern.go, tag/tag.go, version/version.go
The "revive" linter now requires package comments on all packages. Add package comments to all packages commonly used by external users. Ignore package comment warnings on all other packages.
As of `golangci-lint` v1.49.0, the "deadcode", "structcheck", and "varcheck" linters are deprecated (replaced by "unused"), so remove them from the configuration.
=> Fix new lint failures and drop deprecated linters.

internal/testutil/helpers/helpers.go, mongo/description/max_staleness_spec_test.go, mongo/description/selector_spec_test.go, mongo/integration/crud_helpers_test.go, mongo/integration/crud_spec_test.go, mongo/integration/json_helpers_test.go, mongo/integration/unified/bulkwrite_helpers.go, mongo/integration/unified/client_operation_execution.go, mongo/integration/unified/collection_data.go, mongo/integration/unified/collection_operation_execution.go, mongo/integration/unified/crud_helpers.go, mongo/integration/unified/database_operation_execution.go, mongo/integration/unified/unified_spec_runner.go, mongo/integration/unified_spec_test.go, x/mongo/driver/auth/auth_spec_test.go, x/mongo/driver/connstring/connstring_spec_test.go, x/mongo/driver/session/client_session_test.go, x/mongo/driver/topology/CMAP_spec_test.go, x/mongo/driver/topology/sdam_spec_test.go, x/mongo/driver/topology/server_rtt_test.go, x/mongo/driver/topology/topology_test.go
Improvements:
* Update package name at `internal/testutil/helpers` to align with import path (i.e. rename package to `helpers`).
* Move all single-use functions in `helpers` package to where they are used and un-export them.
* Remove duplicate test assertion functions from `helpers` package.
* Add `t.Helper()` to the one remaining test helper function.
=> Clean up internal/testutil/helpers package.

benchmark/operation_test.go, x/mongo/driver/batch_cursor.go, x/mongo/driver/drivertest/channel_conn.go, x/mongo/driver/operation.go, x/mongo/driver/operation/abort_transaction.go, x/mongo/driver/operation/aggregate.go, x/mongo/driver/operation/command.go, x/mongo/driver/operation/commit_transaction.go, x/mongo/driver/operation/count.go, x/mongo/driver/operation/create.go, x/mongo/driver/operation/createIndexes.go, x/mongo/driver/operation/delete.go, x/mongo/driver/operation/distinct.go, x/mongo/driver/operation/drop_collection.go, x/mongo/driver/operation/drop_database.go, x/mongo/driver/operation/drop_indexes.go, x/mongo/driver/operation/end_sessions.go, x/mongo/driver/operation/find.go, x/mongo/driver/operation/find_and_modify.go, x/mongo/driver/operation/hello.go, x/mongo/driver/operation/insert.go, x/mongo/driver/operation/listDatabases.go, x/mongo/driver/operation/list_collections.go, x/mongo/driver/operation/list_indexes.go, x/mongo/driver/operation/update.go, x/mongo/driver/operation_exhaust.go, x/mongo/driver/operation_test.go, x/mongo/driver/topology/connection.go
[GODRIVER-2021](https://jira.mongodb.org/browse/GODRIVER-2021)
[GODRIVER-1670](https://jira.mongodb.org/browse/GODRIVER-1670)
Use pooling to reduce memory allocation.
The benchstat from benchmark/operation_test.go shows:
```
name                          old time/op    new time/op    delta
ClientWrite/not_compressed-4     153µs ± 2%     154µs ± 2%     ~     (p=0.079 n=9+10)
ClientWrite/snappy-4             183µs ± 2%     187µs ±12%     ~     (p=0.878 n=8+8)
ClientWrite/zlib-4              1.35ms ±36%    1.39ms ±27%     ~     (p=0.842 n=10+9)
ClientWrite/zstd-4               286µs ±13%     286µs ±16%     ~     (p=0.666 n=9+9)
name                          old alloc/op   new alloc/op   delta
ClientWrite/not_compressed-4    34.3kB ± 0%    23.9kB ± 0%  -30.32%  (p=0.000 n=10+9) …
```
=> GODRIVER-2021 Use pooling to reduce memory allocation.

mongo/description/selector_test.go, mongo/description/server_selector.go
[GODRIVER-2526](https://jira.mongodb.org/browse/GODRIVER-2526)
The reporter has hundreds of mongos instances, so appending `Server` causes high memory usage. This PR pre-allocates slice to reduce allocations.
The benchmark show:
```
name                old time/op    new time/op    delta
Selector_Sharded-4    28.4µs ±37%     9.7µs ± 3%  -65.66%  (p=0.000 n=9+8)
name                old alloc/op   new alloc/op   delta
Selector_Sharded-4     111kB ± 0%      42kB ± 0%  -62.28%  (p=0.000 n=10+10)
name                old allocs/op  new allocs/op  delta
Selector_Sharded-4      9.00 ± 0%      3.00 ± 0%  -66.67%  (p=0.000 n=10+10)
```
=> GODRIVER-2526 Optimize description.selectByKind.

bson/bson.go, bson/bsoncodec/doc.go, bson/bsoncodec/registry.go, bson/bsoncodec/struct_tag_parser.go, bson/doc.go, bson/mgocompat/doc.go, bson/mgocompat/setter_getter.go, bson/primitive/decimal.go, bson/primitive/primitive.go, event/doc.go, internal/error.go, mongo/database.go, mongo/doc.go, mongo/errors.go, mongo/gridfs/doc.go, mongo/mongo.go, mongo/options/autoencryptionoptions.go, mongo/options/clientencryptionoptions.go, mongo/options/datakeyoptions.go, x/bsonx/bsoncore/document_sequence.go, x/mongo/driver/operation/drop_indexes.go, x/mongo/driver/operation/find_and_modify.go
We recommend that users run `make fmt` before contributing, so we should probably run it ourselves and make the necessary updates. Some of these changes are a little strange to me, so let me know what you think.
=> GODRIVER-2453 Run `make fmt` with the latest Go version.

.golangci.yml
[GODRIVER-2517](https://jira.mongodb.org/browse/GODRIVER-2517)
Now that https://github.com/mongodb/mongo-go-driver/pull/1056 is merged, we can remove the moved paths from the linter ignore paths.
=> GODRIVER-2517 Remove no longer relevant linter ignore paths.

.evergreen/config.yml
GODRIVER-2544
Bumps the MacOS distro version used for Evergreen testing from 10.15 to 11.0. This allows tests to actually run (the `go` binary was not working properly on 10.15) and reduces the number of spec test timeouts on MacOS.
=> GODRIVER-2544 Bump MacOS distro version to 11.0.

x/mongo/driver/operation.go
GODRIVER-2516
Change `Labelled` to `Labeled`; we generally stick to American spellings. This also fixes a lint error I was getting as the export comment already said `LabeledError`.
=> GODRIVER-2516 Fix labeled typo.

mongo/integration/sdam_error_handling_test.go
The `pool cleared on network timeout` test sets `SocketTimeout` and a blocking fail point on `saslContinue` higher than the set `SocketTimeout` and expects a timeout from `InsertOne`. The comment in the test says the timeout is caused by `connectTimeoutMS`, but I believe the timeout is due to `socketTimeoutMS`.
=> Fix typo in SDAM error handling test.

mongo/errors.go
GODRIVER-2536
Returns `nil` in `replaceErrors` when `err == nil` to avoid costly reflection logic below. 
[Here's a benchmark](https://gist.github.com/benjirewis/8b088d422788a4beceeb5076652db256) I used to measure the difference in operations per second. The output from `benchstat` was:
```
name             old time/op    new time/op    delta
ReplaceErrors-8    12.2ns ± 1%     2.7ns ± 0%  -78.19%  (p=0.008 n=5+5)
```
=> GODRIVER-2536 Return early in replaceErrors.

bson/primitive/objectid.go, bson/primitive/objectid_test.go
EncodeToString internally creates slice not array and thus makes unnecessary allocation AFAIU, since we know exactly the size of result hex. I wrote the following benchmark to prove the benefit:
```
import (
"encoding/hex"
"testing"
"go.mongodb.org/mongo-driver/bson/primitive"
)
var Blackhole string
func BenchmarkHex(b *testing.B) {
id := primitive.NewObjectID()
b.Run("BufEncode", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
var buf [24]byte
hex.Encode(buf[:], id[:])
Blackhole = string(buf[:])
}
})
b.Run("EncodeToString", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
Blackhole = hex.EncodeToString(id[:])
}
})
}
```
It produces the following results:
```
BenchmarkHex/BufEncode
BenchmarkHex/BufEncode-10         	54523264	        22.25 ns/op	      24 …
```
=> GODRIVER-2542 optimize objectid hex func

mongo/integration/csot_cse_prose_test.go
GODRIVER-2458
Fixes race condition in CSOT CSE prose test 1 where `ping` would be sent to `mongocryptd` process before it had a chance to start through auto-encryption. Runs a `find` through the encrypted client to ensure the `mongocryptd` process has been started before `ping`ing.
Failures due to this race condition were only happening on Windows due to its relative slowness in spawning `mongocryptd` processes.
=> GODRIVER-2458 Fix race condition in CSE maxTimeMS prose test.

.evergreen/config.yml, .evergreen/run-mongodb-aws-test.sh
Resolves GODRIVER-2534
Overwrite `prepare_mongodb_aws.sh` before running EC2 auth test to avoid zombie credentials from preventing the driver from fetching the credentials using the AWS end point.
=> Ensure zombie credentials are not used in EC2 auth tests

mongo/client.go, mongo/integration/sessions_test.go, x/mongo/driver/session/session_pool.go
GODRIVER-2533
Fixes data race in `session.Pool` by switching `checkedOut` from an `int` to an atomically-accessed `int64`. Adds a regression test for the data race.
=> GODRIVER-2533 Fix data race from NumberSessionsInProgress.

.golangci.yml
[GODRIVER-2569](https://jira.mongodb.org/browse/GODRIVER-2569)
Use the [paralleltest](https://github.com/kunwardeep/paralleltest) linter to report when tests use `t.Parallel()` incorrectly (e.g. without capturing the test case for loop variable).
=> GODRIVER-2569 Use the paralleltest linter.

x/mongo/driver/topology/topology_options.go, x/mongo/driver/topology/topology_options_test.go
GODRIVER-2573
Default values `ServerSelectionTimeout` and `SeedList` were removed from the now-deprecated `newConfig` function in PR #1044 for GODRIVER-1530 . There was no basis for this removal and this PR adds it back to the `topology.Config` constructor.
=> GODRIVER-2573 re-apply default serverSelectionTimeout

examples/example_customdns_test.go
[GODRIVER-2045](https://jira.mongodb.org/browse/GODRIVER-2045)
This is an example of implementing a custom dialer with cache support.
The main purpose of this PR is for review. Merging is still TBD.
Error handling in `resolve()` is under discussion offline depending on the degree of support for the DNS cache we will provide.
=> GODRIVER-2045 Propose an example of custom dialer with DNS cache.

mongo/integration/csot_cse_prose_test.go, mongo/integration/csot_prose_test.go
GODRIVER-2458
Implements [this prose test](https://github.com/mongodb/specifications/tree/master/source/client-side-operations-timeout/tests#multi-batch-writes). Uses numbers for existing CSOT prose tests.
Note that I bumped some of the timeouts beyond the test description, since the `InsertMany` call of 50 1MB documents takes a while on my machine.
Aside: I worry about tests like this on Windows and Mac; I'm thinking about solutions for timing tests on those OSes (maybe we just skip timing-related tests?)
=> GODRIVER-2458 Multi-batch writes CSOT test.

examples/_example_aws_lambda_handler.go
[GODRIVER-2368](https://jira.mongodb.org/browse/GODRIVER-2368)
This is an example of AWS Lambda handler.
Tesed on Lambda.
Prefixed the filename with a `_` to prevent it from being compiled.
=> GODRIVER-2368 Add example for AWS Lambda handler.

.evergreen/config.yml
[GODRIVER-2522](https://jira.mongodb.org/browse/GODRIVER-2522)
Use `batchtime: 1440` to run macOS builds for batches of commits, at most once per 24 hours.
=> GODRIVER-2522 Run macOS tasks at most once per 24 hours.

mongo/integration/sdam_error_handling_test.go
The SDAM [error before handshake completes](https://github.com/mongodb/mongo-go-driver/blob/25122e12942e5d1fa1dff4df03d8110515df3037/mongo/integration/sdam_error_handling_test.go#L91) tests fail intermittently because returning errors to operation calls and handling connection errors are not guaranteed to run in a particular order. For example, if a connection establishment error occurs, it's possible for the operation caller to get an error returned before the SDAM error handler is called. Note that the race condition is only applicable to handshake errors; application errors are handled synchronously and always before returning the error to the user.
Resolve that problem by waiting for up to 2 seconds for the connection pool to be cleared after a connection establishment error happens …
=> Improve reliability of SDAM error 'before handshake completes' tests.

.evergreen/run-fuzz.sh
GODRIVER-2564
Evergreen notification events are triggered on "Finished" or "Failed" Builds/Versions. To avoid gratuitous notifications, this PR adds an `exit 1` for if generate corpus data is uploaded to the S3 bucket, [here](https://evergreen.mongodb.com/task/mongo_go_driver_fuzz_test__version~5.0_os_ssl_40~ubuntu1804_64_go_1_18_test_fuzz_patch_cb7150a53b0a1318b5fcc8da0ea0bd8601862835_634729649ccd4e5b4bb181ef_22_10_12_20_54_05) is an example of such a failure. If a failure occurs, then notify the #dbx-go slack channel.
[periodic build configuration](https://spruce.mongodb.com/project/mongo-go-driver/settings/periodic-builds), [notification configuration](https://spruce.mongodb.com/project/mongo-go-driver/settings/notifications)
=> GODRIVER-2564 exit 1 on gen corpus

mongo/integration/unified/error.go, mongo/integration/unified/schema_version.go, testdata/crud/unified/aggregate-merge-errorResponse.json, testdata/crud/unified/aggregate-merge-errorResponse.yml, testdata/crud/unified/bulkWrite-errorResponse.json, testdata/crud/unified/bulkWrite-errorResponse.yml, testdata/crud/unified/deleteOne-errorResponse.json, testdata/crud/unified/deleteOne-errorResponse.yml, testdata/crud/unified/findOneAndUpdate-errorResponse.json, testdata/crud/unified/findOneAndUpdate-errorResponse.yml, testdata/crud/unified/insertOne-errorResponse.json, testdata/crud/unified/insertOne-errorResponse.yml, testdata/crud/unified/updateOne-errorResponse.json, testdata/crud/unified/updateOne-errorResponse.yml
GODRIVER-2487
Adds spec tests for the new `errorResponse` field. Adds support for the `errorResponse` field in the unified test runner.
GODRIVER-2325 recently exposed the raw server reply in all errors returned from the server; this PR just accesses those `Raw` fields from the unified test runner.
=> GODRIVER-2487 Add spec tests for `errorResponse`.

.evergreen/config.yml
GODRIVER-2515
- test with libmongocrypt 1.6.1
1.6.1 is the latest stable release of libmongocrypt.
=> GODRIVER-2515 test with libmongocrypt 1.6.1

mongo/errors.go, mongo/integration/errors_test.go
GODRIVER-2604 
Adds more timeout errors to the `mongo.IsTimeout` error helper and updates the according test.
`mongo.IsTimeout` is our way of grouping timeout errors; there are some lower level errors that were not included in that helper that would be good to include.
=> GODRIVER-2604 Add `ErrServerSelectionTimeout` and `WaitQueueTimeoutError` to `IsTimeout`.
