mongodb/mongo-go-driver

core/command/command.go
core/command/read.go
core/command/write.go
core/session/client_session.go
core/session/client_session_test.go
core/session/options.go
mongo/causal_consistency_test.go
mongo/client.go
mongo/client_internal_test.go
mongo/sessionopt/sessionopt.go
mongo/sessionopt/sessionopt_test.go
mongo/sessions_test.go

GODRIVER-56
Change-Id: I075a519c3dfb12001c3c55cd9374c511420892c0

Implement causal consistency

---

mongo/clientopt/clientopt.go

Fix for https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-491?filter=allopenissues

GODRIVER-491: fix local certificate

---

bson/element_test.go
bson/value.go

Additionally adds a Time() method that returns a time.Time instance.

GODRIVER-513 Make Value.DateTime() return int64

---

mongo/client.go
mongo/client_internal_test.go

It wasn't clear to me how to test with multiple read preferences if you have any tips I'm happy to write those tests.

GODRIVER-372 Add Ping method to mongo.Client

---

mongo/index_view_internal_test.go
x/mongo/driver/list_indexes.go
x/network/integration/list_indexes_test.go

GODRIVER-279
Change-Id: I2409ecc61ce82099881c505c19cf979f7af69fe0

Implement legacy index enumeration

---

mongo/client_internal_test.go
mongo/database.go
mongo/database_internal_test.go
x/mongo/driver/list_collections.go
x/mongo/driver/list_collections_test.go
x/mongo/driver/topology/list_collections_cursor.go
x/network/integration/list_collections_test.go

GODRIVER-492
Change-Id: Iafd2527267b470a582925cc52fdd93bd7f7d7a9e

Implement legacy collection enumeration.

---

bson/bsonrw/extjson_parser.go
bson/bsonrw/extjson_parser_test.go

[GODRIVER-775](https://jira.mongodb.org/browse/GODRIVER-775)

GODRIVER-775: Add support for legacy $binary format

---

README.md

Just a small pr to update the readme to reflect the latest breaking changes when initializing a new client connection.

update readme to reflect latest breaking changes

---

bson/primitive/primitive.go

fix datetime marshal json format. refer to rfc3339

fix datetime marshal json

---

x/mongo/driver/topology/server.go

GODRIVER-900 Fix typo in server description

---

mongo/gridfs/bucket.go

Fix for: https://jira.mongodb.org/browse/GODRIVER-809

GODRIVER-809 Fix panic while calling existing GridFS data

---

mongo/client.go
mongo/options/clientoptions.go
mongo/options/clientoptions_test.go

Fix for https://jira.mongodb.org/browse/GODRIVER-908

GODRIVER-908 Fix err merging on options.ClientOptions

---

bson/primitive/objectid.go
bson/primitive/objectid_test.go
bson/primitive/primitive.go

I am starting to use this library and would like a couple of extra helper functions around creating an using the object IDs

Add helper functions to object ID

---

mongo/database.go

GODRIVER-1292
Change-Id: I02c8765de132c1e8a8267c473a24fb9784d3e8fd

Close cursor in Database.ListCollectionNames.

---

mongo/database.go
mongo/database_test.go
mongo/main_test.go

GODRIVER-1325
Change-Id: I6e63baf092a796c1e9ca01e4c84c8cac6f6af4ca

Use registry passed in from DatabaseOptions in newDatabase.

---

mongo/integration/index_view_test.go

Remove checks for ns field in index view tests

---

bson/bsonrw/extjson_parser_test.go
bson/bsonrw/extjson_wrappers.go

Support looser extended JSON datetime format.

---

mongo/client.go

First pass at documentation. I've read it over a bunch of times so I think I'm getting a bit tunnel-visioned and would love some more eyes on this.

GODRIVER-1376 Improve documentation for Client and its methods

---

mongo/client.go
mongo/collection.go
mongo/database.go

Should've mentioned this earlier but the docs are easier to read if you run a local GoDoc server:
1. run `godoc -http localhost:8000`
2. visit `http://localhost:8000/pkg/go.mongodb.org/mongo-driver/mongo/`).

GODRIVER-1378 Collection documentation

---

.evergreen/config.yml
mongo/client_encryption.go
mongo/doc.go
mongo/options/autoencryptionoptions.go

- Remove "beta" annotations from docs
- Update the instructions to install libmongocrypt

GODRIVER-1406 FLE GA docs changes

---

bson/bsoncodec/default_value_decoders.go
bson/bsoncodec/default_value_decoders_test.go
bson/bsoncodec/string_codec.go
bson/mgocompat/bson_test.go
bson/mgocompat/registry.go

port mgobson tests for mgocompat testing

---

x/mongo/driver/topology/resource_pool_test.go

While I was working in this file, I changed the comparisons to use the new assertion library too.

GODRIVER-1386 Use atomic.LoadInt32 in resource pool tests

---

mongo/integration/mtest/setup.go

On master, if a mongod isn't running when running tests in `mongo/integration`, the test execution will hang for 30 seconds (server selection timeout). This PR changes it so the initial `Ping` to check connectivity is run with a short context and a more helpful error message is printed along with the URI that's being used to connect.

Ping deployment with a short context during test setup.

---

bson/bsoncodec/default_value_decoders.go
bson/bsoncodec/default_value_encoders.go
bson/bsoncodec/map_codec.go
bson/bsoncodec/struct_codec.go
bson/bsonoptions/map_codec_options.go
bson/bsonoptions/string_codec_options.go
bson/bsonoptions/struct_codec_options.go
bson/decoder.go
bson/mgocompat/bson_test.go
bson/mgocompat/registry.go

I realized when I did this that I missed a structcodec option

GODRIVER-1407 add MapCodec for mgocompat

---

bson/bsoncodec/default_value_decoders.go
bson/mgocompat/bson_test.go

GODRIVER-1357
GODRIVER-1358
GODRIVER-1359
GODRIVER-1360

Change codecs to convert between numbers and bools

---

mongo/options/bulkwriteoptions.go
mongo/options/deleteoptions.go
mongo/options/findoptions.go
mongo/options/gridfsoptions.go
mongo/options/indexoptions.go
mongo/options/insertoptions.go
mongo/options/replaceoptions.go
mongo/options/updateoptions.go

I left some TODO comments for options that I don't know. If there are any comments on options that are used in multiple operations, only comment once and I'll apply the suggestion to all of the relevant operations.

GODRIVER-1449 Improve documentation for write options

---

bson/bsoncodec/default_value_decoders.go
bson/bsoncodec/default_value_decoders_test.go
bson/bsoncodec/default_value_encoders.go
bson/bsoncodec/default_value_encoders_test.go
bson/bsoncodec/uint_codec.go
bson/bsonoptions/uint_codec_options.go
bson/mgocompat/bson_test.go
bson/mgocompat/registry.go

I forgot to add this with the other int/uint stuff.
Also,  I'm not very happy with EncodeToMinSize as a name and will accept other suggestions.

GODRIVER-1358 add UIntCodec for mgocompat

---

bson/bsoncodec/doc.go
bson/bsoncodec/registry_examples_test.go
bson/doc.go

I'm unsure if this is enough documentation to cover all of the essentials, but I'm putting it up for review so we can all talk about it and figure out what the holes are.

GODRIVER-904 Improve documentation for registering custom codecs

---

mongo/integration/collection_test.go

- Addresses test failures that started after by SERVER-45920

Change w value for unsatisfiable write concern in tests

---

data/crud/v2/bulkWrite-update-hint.json
data/crud/v2/bulkWrite-update-hint.yml
data/crud/v2/replaceOne-hint.json
data/crud/v2/replaceOne-hint.yml
data/crud/v2/updateMany-hint.json
data/crud/v2/updateMany-hint.yml
data/crud/v2/updateOne-hint.json
data/crud/v2/updateOne-hint.yml
mongo/bulk_write.go
mongo/bulk_write_models.go
mongo/collection.go
mongo/integration/crud_helpers_test.go
mongo/integration/crud_prose_test.go
mongo/options/replaceoptions.go
mongo/options/updateoptions.go
x/mongo/driver/operation/update.go
x/mongo/driver/operation/update.toml

This includes changes to bulkwrite-update-hint that are in code review on the spec repo

GODRIVER-1366 add Hint option for update commands

---

internal/testutil/helpers/helpers.go
mongo/options/clientoptions.go
mongo/options/clientoptions_test.go
x/mongo/driver/connstring/connstring.go

- Change field name in connstring.Connstring
- Add tests

GODRIVER-1491 Fixup OCSP URI option

---

x/mongo/driver/auth/auth.go
x/mongo/driver/auth/conversation.go
x/mongo/driver/auth/default.go
x/mongo/driver/auth/sasl.go
x/mongo/driver/auth/scram.go
x/mongo/driver/auth/speculative_scram_test.go
x/mongo/driver/auth/speculative_x509_test.go
x/mongo/driver/auth/x509.go
x/mongo/driver/command_monitoring_test.go
x/mongo/driver/description/server.go
x/mongo/driver/operation.go
x/mongo/driver/operation/ismaster.go

Relevant spec links:
1. https://github.com/mongodb/specifications/blob/master/source/mongodb-handshake/handshake.rst#speculative-authentication

GODRIVER-1526 Support speculative authentication

---

data/uri-options/tls-options.json
data/uri-options/tls-options.yml
x/mongo/driver/connstring/connstring_spec_test.go

- Pull in test changes for SPEC-1595

GODRIVER-1491 Resync URI options tests

---

mongo/integration/mtest/setup.go

Some pre-work for GODRIVER-1558. It's possible that this is related to the $merge test failures, but may also just be a red herring. Either way, good to fix.

GODRIVER-1558 Ensure topology kind is always discovered for tests

---

examples/documentation_examples/examples.go

- Also addresses GODRIVER-1541

GODRIVER-1259 Add WithTransaction example for docs site

---

x/mongo/driver/topology/connection.go

I don't think we can really test this and it's more for consistency than anything else. I read through the connection pool code and we handle the error from `connect` every time we call it, so there should never be a case where we try to close a connection that failed to connect.

GODRIVER-1556 Ensure underlying net.Conn is not set in error cases

---

mongo/errors.go
mongo/mongo.go
mongo/mongo_test.go

This is blocking the work for adding the commitQuorum helper.

GODRIVER-1590 Use MarshalValue in transformValue helper

---

x/mongo/driver/topology/pool.go
x/mongo/driver/topology/resource_pool_test.go
x/mongo/driver/topology/server.go
x/mongo/driver/topology/server_test.go

There were some points where we were calling drain when we shouldn't.

GODRIVER-1589 consolidate pool.drain and pool.clear

---

internal/testutil/assert/assert.go
x/mongo/driver/topology/connection.go
x/mongo/driver/topology/pool.go
x/mongo/driver/topology/pool_test.go
x/mongo/driver/topology/resource_pool.go
x/mongo/driver/topology/resource_pool_test.go
x/mongo/driver/topology/server.go

If you have any ideas for other tests I am open to adding them.

GODRIVER-1613 fix how pool handles MaxPoolSize

---

mongo/options/clientoptions_test.go
x/mongo/driver/connstring/connstring.go

- Allow single character passwords
- Ensure that single character usernames are validated for unescaped
slashes

GODRIVER-1625 Allow and validate single character credentials

---

mongo/cursor.go
mongo/cursor_test.go

https://jira.mongodb.org/browse/GODRIVER-1657

Godriver 1657 pass interface to cursor.all

---

mongo/change_stream_deployment.go
mongo/client_test.go
mongo/integration/mtest/opmsg_deployment.go
x/mongo/driver/description/server.go
x/mongo/driver/driver.go
x/mongo/driver/operation.go
x/mongo/driver/operation_test.go
x/mongo/driver/topology/topology.go

https://jira.mongodb.org/browse/GODRIVER-1632

GODRIVER-1632 fixing function for retryable writes

---

README.md

JIRA:
https://jira.mongodb.org/browse/DOCS-13739

DOCS-13739: add defers to the code snippets in the README

---

go.mod
go.sum

I also ran `go mod tidy` to ensure our go.mod and go.sum files don't have extraneous entries.

GODRIVER-1675 Update x/text version to v0.3.3

---

data/change-streams/README.rst
data/change-streams/change-streams-errors.json
data/change-streams/change-streams-errors.yml
data/change-streams/change-streams-resume-whitelist.json
data/change-streams/change-streams-resume-whitelist.yml
data/change-streams/change-streams.json
data/change-streams/change-streams.yml
mongo/change_stream.go

This commit also resyncs all change stream spec tests to pull in changes
from GODRIVER-1671.

GODRIVER-1678 Consider CursorNotFound a resumable change stream error

---

bson/bsoncodec/bsoncodec.go
bson/bsoncodec/default_value_decoders.go
bson/bsoncodec/default_value_decoders_test.go
bson/bsoncodec/empty_interface_codec.go

This commit also changes EmptyInterfaceCodec to implement typeDecoder.

GODRIVER-1680 Add typeDecoder and dedicated bson.D decoder

---

x/mongo/driver/topology/topology_errors_test.go

I see this test timeout a couple of times per waterfall run on macos. The `assert.Soon` call fails because the 100ms timeout elapses before the provided callback returns. I refactored a bit to move the topology construction out of the callback and also increased the `assert.Soon` timeout.

GODRIVER-559 Increase test timeout

---

mongo/results.go

Fix typo in CollectionSpecification documentation

---

x/mongo/driver/topology/connection.go
x/mongo/driver/topology/connection_options.go
x/mongo/driver/topology/pool_test.go

I don't really have a good way to test this so I'm open to ideas if anyone thinks it's necessary.

GODRIVER-1742 Remove connection life timeout

---

mongo/database.go
mongo/integration/collection_test.go
mongo/integration/database_test.go
x/mongo/driver/batch_cursor.go
x/mongo/driver/operation.go
x/mongo/driver/operation/abort_transaction.go
x/mongo/driver/operation/aggregate.go
x/mongo/driver/operation/command.go
x/mongo/driver/operation/commit_transaction.go
x/mongo/driver/operation/count.go
x/mongo/driver/operation/create.go
x/mongo/driver/operation/createIndexes.go
x/mongo/driver/operation/delete.go
x/mongo/driver/operation/distinct.go
x/mongo/driver/operation/drop_collection.go
x/mongo/driver/operation/drop_database.go
x/mongo/driver/operation/drop_indexes.go
x/mongo/driver/operation/end_sessions.go
x/mongo/driver/operation/find.go
x/mongo/driver/operation/find_and_modify.go
x/mongo/driver/operation/insert.go
x/mongo/driver/operation/ismaster.go
x/mongo/driver/operation/listDatabases.go
x/mongo/driver/operation/list_collections.go
x/mongo/driver/operation/list_indexes.go
x/mongo/driver/operation/update.go
x/mongo/driver/operation_exhaust.go
x/mongo/driver/operation_legacy.go

GODRIVER-1715 sum up results from batches

---

bson/primitive/decimal.go

Fixes https://jira.mongodb.org/browse/GODRIVER-1783

GODRIVER-1783 make primitive.Decimal128 implement Zeroer

---

mongo/doc.go
mongo/errors.go
mongo/integration/errors_test.go
mongo/integration/sdam_error_handling_test.go

If anyone has better phrasing for adding it to mongo/doc.go, I'm open to it.

GODRIVER-1803 add error helpers

---

bson/primitive/primitive.go

Small grammatical/spelling typos and punctuation consistency.
I noticed on these docs pages:
https://pkg.go.dev/go.mongodb.org/mongo-driver/bson/primitive
https://godoc.org/go.mongodb.org/mongo-driver/bson/primitive

Comment fixups

---

bson/doc.go
mongo/client.go
mongo/collection.go
mongo/options/clientoptions.go

Signed-off-by: Ben Wells <b.v.wells@gmail.com>

Fix various typos in code documentation

---

README.md

Fix broken link to feedback section in README.

Fix broken link to feedback section in README

---

mongo/integration/unified/client_entity.go

This was a request from Oleg on my workload executor pull review.

GODRIVER-1844 finer precision for getSecondsSinceEpoch

---

bson/bsoncodec/default_value_decoders.go

Fix typo in default_value_decoders.go

---

x/mongo/driver/topology/server.go

Currently a `topology.Server`'s `connectionOpts` can be modified by calling `createConnection()` (used to create connections for the heartbeat and RTT monitor goroutines). The result is that connections used for operations may have some of the configurations applied to the heartbeat/RTT connections.
Additionally, an error handling callback may be unintentionally added to the `topology.Server`'s `connectionOpts` when calling `NewServer`.

GODRIVER-2105 Fix Server config connection options being modified by createConnection.

---

x/mongo/driver/mongocrypt/mongocrypt_test.go

GODRIVER-2216 Change testKmsCtx expectedHost to be port-agnostic

---

.golangci.yml
benchmark/harness_main.go
internal/randutil/randutil.go
mongo/mongocryptd.go
x/mongo/driver/auth/auth_spec_test.go
x/mongo/driver/auth/mongodbcr.go
x/mongo/driver/auth/util.go
x/mongo/driver/connstring/connstring_spec_test.go
x/mongo/driver/crypt.go

Enable the `gosec` linter and fix or clarify identified security issues.

GODRIVER-2156 Enable gosec linter.

---

.evergreen/config.yml
mongo/doc.go

https://jira.mongodb.org/browse/GODRIVER-2210

GODRIVER-2210: Update libmongocrypt dependency to 1.3.0

---

.golangci.yml
internal/string_util.go
internal/testutil/ops.go
mongo/integration/gridfs_spec_test.go
mongo/integration/mtest/mongotest.go
x/mongo/driver/auth/internal/awsv4/signer.go
x/mongo/driver/dns/dns.go

Enable the `prealloc` linter and pre-allocate the suggested slices.

GODRIVER-2156 Enable prealloc linter.

---

bson/doc.go
bson/extjson_prose_test.go
bson/mgocompat/registry.go
bson/registry.go
x/bsonx/registry.go
x/mongo/driver/operation/abort_transaction.go
x/mongo/driver/operation/aggregate.go
x/mongo/driver/operation/command.go
x/mongo/driver/operation/commit_transaction.go
x/mongo/driver/operation/count.go
x/mongo/driver/operation/create.go
x/mongo/driver/operation/createIndexes.go
x/mongo/driver/operation/delete.go
x/mongo/driver/operation/distinct.go
x/mongo/driver/operation/drop_collection.go
x/mongo/driver/operation/drop_database.go
x/mongo/driver/operation/drop_indexes.go
x/mongo/driver/operation/end_sessions.go
x/mongo/driver/operation/find.go
x/mongo/driver/operation/find_and_modify.go
x/mongo/driver/operation/insert.go
x/mongo/driver/operation/listDatabases.go
x/mongo/driver/operation/list_collections.go
x/mongo/driver/operation/list_indexes.go
x/mongo/driver/operation/update.go

Found and fixed a few typos in code comments and tests.

Fix typos in driver comments

---

mongo/change_stream.go
mongo/collection.go
mongo/integration/change_stream_test.go
mongo/integration/collection_test.go
mongo/options/aggregateoptions.go
mongo/options/changestreamoptions.go

Reverts mongodb/mongo-go-driver#880

Revert "GODRIVER-2337 Add CustomPipeline to ChangeStreamOptions"

---

data/change-streams/unified/change-streams.json
data/change-streams/unified/change-streams.yml
data/crud/unified/aggregate.json
data/crud/unified/aggregate.yml
data/crud/unified/find-comment.json
data/crud/unified/find-comment.yml

GODRIVER-2358
Remove the specific topologies from the `getMore` tests.

GODRIVER-2358 Test getMore with comment on all topologies

---

.evergreen/config.yml

GORIVER-2399 add 6.0 to testing evergreen testing matrices

---

data/client-side-encryption/fle2-Compact.json
data/client-side-encryption/fle2-Compact.yml

GODRIVER-2402
Sync the fle2-Compact test. There are no functional changes.

GODRIVER-2402 sync fle2-Compact test

---

mongo/integration/client_side_encryption_test.go

Tests the following:
- Create an encryptedFieldsMap with an indexed and unindexed field.
- Create an FLE 2 collection.
- Auto encrypt an insert and find.

GODRIVER-2406 add FLE 2 doc examples

---

.evergreen/config.yml
data/client-side-encryption/create-and-createIndexes.json
data/client-side-encryption/create-and-createIndexes.yml
data/client-side-encryption/fle2-validatorAndPartialFieldExpression.json
data/client-side-encryption/fle2-validatorAndPartialFieldExpression.yml
data/client-side-encryption/validatorAndPartialFieldExpression.json
data/client-side-encryption/validatorAndPartialFieldExpression.yml
mongo/integration/crud_helpers_test.go

Syncs the tests added in DRIVERS-2309. No driver changes needed.

GODRIVER-2420 sync validatorAndPartialFieldExpression + create-and-createIndexes tests

---

version/version.go

Bump version to `v1.11.0-prerelease`

Update version to v1.11.0-prerelease

---

data/server-discovery-and-monitoring/integration/hello-command-error.yml
data/server-discovery-and-monitoring/integration/hello-network-error.yml
data/server-discovery-and-monitoring/integration/hello-timeout.yml

[GODRIVER-2490](https://jira.mongodb.org/browse/GODRIVER-2490)
Sync [SDAM integration spec tests](https://github.com/mongodb/specifications/tree/98e20daa7e1bdf8f4acf391376531c477990bd3c/source/server-discovery-and-monitoring/tests/integration) at revision [98e20daa](https://github.com/mongodb/specifications/commit/98e20daa7e1bdf8f4acf391376531c477990bd3c).

GODRIVER-2490 Sync SDAM integration spec tests.

---

data/change-streams/change-streams-disambiguatedPaths.json
data/change-streams/change-streams-disambiguatedPaths.yml

GODRIVER-2506 expose rich field information in the updateDescription

---

data/change-streams/change-streams-showExpandedEvents.json
data/change-streams/change-streams-showExpandedEvents.yml

GODRIVER-2535 Exclude create events from showExpandedEvents tests.

---

testdata/client-side-encryption/legacy/maxWireVersion.json
testdata/client-side-encryption/legacy/maxWireVersion.yml

Resyncs to https://github.com/mongodb/specifications/commit/e761591616849d9b507287811e77f7a359fb9587.

GODRIVER-2546 update maxWireVersion test

---

mongo/doc.go

Make the use of the cse build tag more prominent to readers.

Emphasize use of required build tag.

---

mongo/doc.go

Standardizing language around enabling autoencryption

Clarify autoencrypt mongocryptd/shared library feature

---

testdata/server-discovery-and-monitoring/rs/electionId_precedence_setVersion.json
testdata/server-discovery-and-monitoring/rs/electionId_precedence_setVersion.yml
testdata/server-discovery-and-monitoring/rs/null_election_id-pre-6.0.json
testdata/server-discovery-and-monitoring/rs/null_election_id-pre-6.0.yml
testdata/server-discovery-and-monitoring/rs/null_election_id.json
testdata/server-discovery-and-monitoring/rs/secondary_ignore_ok_0-pre-6.0.json
testdata/server-discovery-and-monitoring/rs/secondary_ignore_ok_0-pre-6.0.yml
testdata/server-discovery-and-monitoring/rs/set_version_can_rollback.json
testdata/server-discovery-and-monitoring/rs/set_version_can_rollback.yml
testdata/server-discovery-and-monitoring/rs/setversion_equal_max_without_electionid.json
testdata/server-discovery-and-monitoring/rs/setversion_equal_max_without_electionid.yml
testdata/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
testdata/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.yml
testdata/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json
testdata/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.yml
testdata/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json
testdata/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.yml
x/mongo/driver/topology/fsm.go
x/mongo/driver/topology/sdam_spec_test.go

GODRIVER-2524
Implement the specification updates from [37c32cf](https://github.com/mongodb/specifications/commit/37c32cf5200cd8da6652c75ac65279c43628fe7a)

GODRIVER-2524 SDAM should prioritize electionId over setVersion only on >=6.0 servers

---

internal/http.go
mongo/client.go

GODRIVER-2631 - Always close internal.DefaultHTTPClient on Client.Disconnect

---

bson/fuzz_test.go
mongo/integration/unified/client_encryption_operation_execution.go

NA
Run `make add-license`
Two files were missing the Go Driver license, this PR adds those licenses.

Add missing licesnse to the Go Driver

---

x/mongo/driver/topology/pool.go

[GODRIVER-1996](https://jira.mongodb.org/browse/GODRIVER-1996)
Guarantee that `ConnectionPoolReady` is always sent before any connections are created by the `maintain()` goroutine.
[DRIVERS-1726](https://jira.mongodb.org/browse/DRIVERS-1726) changes the recommended order for the "ready" operation from
> mark pool as "ready"
> resume background thread
> emit PoolReadyEvent
to
> mark pool as "ready"
> emit PoolReadyEvent
> resume background thread
That resolves a race condition in the CMAP `pool-clear-min-size.yml` spec test.

GODRIVER-1996 Send ConnectionPoolReady before resuming the maintain goroutine.

---

internal/logger/io_sink.go

Fix typo in log sink comment

---

x/bsonx/bsoncore/value.go

GODRIVER-2826
Clean up TODOs in comments to prevent them from being rendered in the pkg.go.dev documentation.

GODRIVER-2826 Clean up TODOs in comments.

---

bson/marshal_value_cases_test.go

Commit 4d8c927dc0a0cf3f0a0a0b1fdfaa6673c39ef6ed added logic that causes the linter to fail in CI.

Fix linting errors in bson package

---

go.mod

GODRIVER-2831
Retract v1.11.5 in go.mod.

GODRIVER-2831 Retract v1.11.5

---

bson/marshal_value_cases_test.go
testdata/connection-monitoring-and-pooling/logging/connection-pool-options.json
testdata/connection-monitoring-and-pooling/logging/connection-pool-options.yml

GODRIVER-2815
The linting CI failures are fixed in PR #1246

GODRIVER-2815 Fix duplicate CMAP logging test description

---

bson/primitive/decimal.go
bson/primitive/decimal_test.go

[GODRIVER-1519](https://jira.mongodb.org/browse/GODRIVER-1519)
* If the significand is zero, bound the exponent range to the maximum supported by decimal128
* If the exponent is too large and positive, use the maximum positive value. If the exponent is too large and negative, use the maximum negative value.
* Add test cases for numbers with a zero significand and large exponent (e.g. `"0e2000000000000"`) and for "-0".
* Improve test assertion failure message to make debugging tests easier.
Some `ParseDecimal128` inputs can take an extremely long time to parse. For example:
```
"0e2000000000000"
```
or the similar value in an Extended JSON document:
```
{"":{"$numberDecimal":"0e2000000000000"}}
```
That's caused by the "normalization" loops that attempt to bring out-of-bounds significand …

GODRIVER-1519 Fix parsing decimal128 zero values with large exponents.

---

README.md

Include Renee French in the repository's README acknowledgements.
From the [documentation](https://go.dev/blog/gopher) on the Go Gopher: 
> The [gopher images](https://go.dev/doc/gopher/) are Creative Commons Attribution 4.0 licensed. That means you can play with the images but you must give credit to their creator (Renee French) wherever they are used.

Update README.md acknowledgements to include Renee French

---

.evergreen/config.yml

[GODRIVER-2825](https://jira.mongodb.org/browse/GODRIVER-2825)
Test against MongoDB 7.0
Explicitly test against MongoDB 7.0 in CI.

GODRIVER-2825 Test against MongoDB 7.0

---

testdata/client-side-encryption/legacy/explain.json
testdata/client-side-encryption/legacy/explain.yml

GODRIVER-2873
Updating for spec change in CSFLE.
Spec compliance.

GODRIVER-2873 Bump minServerVersion for CSFLE deterministic encryption spec test for explain command

---

testdata/server-discovery-and-monitoring/errors/prefer-error-code.json
testdata/server-discovery-and-monitoring/errors/prefer-error-code.yml

GODRIVER-2246
Sync spec test for prefer-error-code.

GODRIVER-2246 Sync spec test for prefer-error-code.

---

go.mod

Add 1.11.8 retract directive to the go.mode file.

Add 1.11.8 retract directive

---

.github/workflows/comment.yml
.gitignore
Makefile
cmd/parse-api-report/main.go
etc/api_report.sh
test.sh

GODRIVER-2923
Add a GitHub Action that creates an API Changes Summary Report.
Note that for now, the action only runs on my fork, until we merge.
Help us to identify API changes introduced in PRs.

GODRIVER-2923 Report Go Driver API changes in PRs

---

.github/workflows/comment.yml

GODRIVER-2923
Run the api report workflow in an environment.
Ensure manual interaction from the Go Driver team to run the workflow.

GODRIVER-2923 Run workflow in an environment

---

.github/workflows/comment.yml

Cherry-pick of #1393 from v1 to master

GODRIVER-2981 [master] API comment doesn't work when job approver isn't PR author

---

x/mongo/driver/topology/server.go
x/mongo/driver/topology/server_test.go

Cherry-pick of #1378 from v1 to master

GODRIVER-2966 [master] Remove the heartbeat events after a connection is closed / a check is canceled.

---

.evergreen/config.yml

Cherry-pick of #1408 from v1 to master

GODRIVER-3002 [master] Azure KMS Clean up

---

mongo/session.go

Cherry-pick of #1416 from v1 to master

GODRIVER-2997 [master] Prevent cancelable context in txn commit loop

---

.evergreen/config.yml

Cherry-pick of #1422 from v1 to master

GODRIVER-3010 [master] Update ECS Test to use Ubuntu 20.04

---

README.md

Cherry-pick of #1426 from v1 to master

[master] Updated README.md for highlighting Go syntax (#1426)

---

mongo/integration/unified/logger.go

Cherry-pick of #1425 from v1 to master

GODRIVER-3013 [master] Resolve race test failures

---

.evergreen/config.yml
.evergreen/run-mongodb-aws-test.sh

Cherry-pick of #1429 from v1 to master

GODRIVER-2607 [master] Remove legacy shell from test scripts

---

.evergreen/config.yml
Dockerfile
docs/CONTRIBUTING.md

Cherry-pick of #1430 from v1 to master

GODRIVER-2989 [master] Fix golang installation in Dockerfile

---

internal/driverutil/hello.go
internal/test/faas/awslambda/mongodb/main.go
mongo/integration/unified/testrunner_operation.go
x/mongo/driver/topology/rtt_monitor.go

Fix spelling issues identified by codespell.

Fix spelling issues

---

examples/documentation_examples/examples.go
examples/documentation_examples/examples_test.go

Cherry-pick of #1438 from v1 to master

GODRIVER-2005 [master] - Replace "require" library with "assert" in documentation examples

---

mongo/database.go
x/mongo/driver/operation/command.go

Cherry-pick of #1450 from v1 to master

GODRIVER-2649 [master] Remove RW Concern Logic from RunCommand

---

.evergreen/config.yml
.evergreen/run-tests.sh

GODRIVER-3401 
Use the new scripts to run mongohoused from a Docker image
Easier to stay in sync with upstream config changes.

GODRIVER-3401 Pull mongohouse image from ADL ECR repo

---

mongo/integration/unified_spec_test.go

Cherry-pick of #1457 from v1 to master

GODRIVER-2117 [master] - Check clientSession is not nil inside executeTestRunnerOperation

---

.evergreen/config.yml

Cherry-pick of #1458 from v1 to master

GODRIVER-3401 [master] Pull mongohouse image from ADL ECR repo

---

mongo/gridfs/download_stream.go

GODRIVER-2695
Rename ErrWrongIndex to the more clear ErrMissingChunk

GODRIVER-2695 Rename ErrWrongIndex to ErrMissingChunk

---

.evergreen/config.yml
.evergreen/run-mongodb-aws-test.sh
Makefile
etc/run-atlas-test.sh

Cherry-pick of #1472 from v1 to master

GODRIVER-2960 [master] Improve Evergreen Runtime and Usability

---

bson/bsoncodec/registry.go
bson/bsoncodec/registry_test.go
bson/marshal_test.go
bson/unmarshal_test.go

GODRIVER-3009
Cherry-pick 868e9c0

GODRIVER-3009 Fix concurrent panic in struct codec. (#1477)

---

x/mongo/driver/topology/connection.go
x/mongo/driver/topology/connection_test.go
x/mongo/driver/topology/server.go

GODRIVER-2952
cherry-pick of 9ca46ea

GODRIVER-2952 Update context.Canceled equality comparisons

---

bson/primitive/objectid_test.go
mongo/bulk_write.go
mongo/collection.go
mongo/mongo.go
mongo/mongo_test.go

Cherry-pick of #1479 from v1 to master

Generate new ObjectID only when required (#1479) [master] Generate new ObjectID only when required (#1479)

---

.evergreen/config.yml
.evergreen/run-tests.sh
Dockerfile
docs/CONTRIBUTING.md
etc/docker_entry.sh
etc/run_docker.sh
internal/integration/mtest/opmsg_deployment.go
mongo/client_test.go
mongo/with_transactions_test.go
x/mongo/driver/operation/hello_test.go
x/mongo/driver/topology/server_test.go

Cherry-pick of #1494 from v1 to master

GODRIVER-3061 [master] Support Load Balancing in Docker Container

---

x/mongo/driver/auth/scram.go

GODRIVER-3062
Remove password string from error message.

GODRIVER-3062 Remove password string from error message.

---

internal/integration/unified/unified_spec_runner.go
testdata/index-management/createSearchIndex.json
testdata/index-management/createSearchIndex.yml
testdata/index-management/createSearchIndexes.json
testdata/index-management/createSearchIndexes.yml
testdata/index-management/dropSearchIndex.json
testdata/index-management/dropSearchIndex.yml
testdata/index-management/listSearchIndexes.json
testdata/index-management/listSearchIndexes.yml
testdata/index-management/searchIndexIgnoresReadWriteConcern.json
testdata/index-management/searchIndexIgnoresReadWriteConcern.yml
testdata/index-management/updateSearchIndex.json
testdata/index-management/updateSearchIndex.yml

Cherry-pick of #1510 from v1 to master

GODRIVER-3074 [master] Sync index management tests

---

.evergreen/config.yml

Cherry-pick of #1512 from v1 to master

GODRIVER-3088 [master] Fix serverless binary handling

---

bson/doc.go
bson/encoder_example_test.go

Cherry-pick of #1500 from v1 to master

GODRIVER-3071 [master] Correct uint Encoding BSON Documentation

---

.evergreen/config.yml

GODRIVER-3087
Only test stable versions of the server in PR builds.
Helps disambiguate code errors vs errors in the dev version of the server.

GODRIVER-3087 Do not test latest server as part of PR build

---

.pre-commit-config.yaml
docs/CONTRIBUTING.md

Cherry-pick of #1517 from v1 to master

GODRIVER-3089 [master] Add link checkers for repository

---

.evergreen/config.yml

Cherry-pick of #1519 from v1 to master

GODRIVER-3087 [master] Do not test latest server as part of PR build

---

mongo/description/selector_test.go
mongo/description/server_selector.go

Cherry-pick of #1509 from v1 to master

GODRIVER-3108 [master] Optimize writeServerSelector

---

internal/integration/client_side_encryption_prose_test.go

Cherry-pick of #1535 from v1 to master

GDORIVER-2934 [master] Add list of possible OS and Go dep errors to case 6

---

version/version.go

Update driver version string to "v1.14.0-prerelease"

Update version to v1.14.0-prerelease

---

.evergreen/config.yml
.evergreen/run-tests.sh
Makefile
docs/CONTRIBUTING.md
etc/setup-encryption.sh
internal/integration/client_side_encryption_prose_test.go
internal/integration/json_helpers_test.go
internal/integration/unified/entity.go

Cherry-pick of #1520 from v1 to master

GODRIVER-3100 [master] Use AWS Secrets Manager for CSFLE Tests

---

bson/primitive/decimal.go

Cherry-pick of #1531 from v1 to master

GODRIVER-3111 [master] Combine the identical if-else branches in bson/primitive/decimal.go

---

bson/bsoncodec/struct_codec.go
bson/bsoncodec/struct_codec_test.go
bson/doc.go
bson/primitive_codecs_test.go

Cherry-pick of https://github.com/mongodb/mongo-go-driver/pull/1514 to v1.

GODRIVER-3081 Fix zero value detection for empty slices and maps.

---

testdata/initial-dns-seedlist-discovery/replica-set/uri-with-uppercase-hostname.json
testdata/initial-dns-seedlist-discovery/replica-set/uri-with-uppercase-hostname.yml
x/mongo/driver/dns/dns.go

Cherry-pick of https://github.com/mongodb/mongo-go-driver/pull/1493 to v1.

GODRIVER-2897 Add SRV test with capital letters in hostnames.

---

testdata/transactions/unified/mongos-unpin.json
testdata/transactions/unified/mongos-unpin.yml

Cherry-pick of #1552 from v1 to master

GODRIVER-3113 [master] Skip unpin_after_TransientTransactionError_error_on_commit on latest

---

.evergreen/config.yml
.github/labeler.yml

GODRIVER-3139
Applies a set of labels based on labeler config using a function from https://github.com/mongodb-labs/drivers-evergreen-tools/pull/411.
Allow us to auto-apply labels without the need for a `pull_request_target`.

GODRIVER-3139 Automatically Add Labels to PRs

---

etc/run-atlas-test.sh

GODRIVER-3147
Write to file instead of using tee.
Ensure that the return code is honored.

GODRIVER-3147 Fix Atlas Test Runner Return Value Handling

---

etc/run-atlas-test.sh

Cherry-pick of #1573 from v1 to master

GODRIVER-3147 [master] Fix Atlas Test Runner Return Value Handling

---

.evergreen/config.yml
.github/reviewers.txt
docs/CODEOWNERS

Cherry-pick of #1572 from v1 to master

GODRIVER-3148 [master] Use GitHub App to Auto Assign Reviewer

---

Dockerfile

Cherry-pick of #1576 from v1 to master

GODRIVER-3150 [master] Make Docker Test More Robust

---

.evergreen/config.yml

Cherry-pick of #1580 from v1 to master

GODRIVER-3158 [master] Invoke all Drivers Evergreen Tools Scripts with Bash

---

internal/integration/unified/unified_spec_runner.go

GODRIVER-3137
GODRIVER-3034
Skip failing tests until we are able to implement the changes.
N/A

GODRIVER-3137 [master] Skip failing transaction tests

---

version/version.go

Update version to "v1.15.0-prerelease".

Fix version to prepare for the v1.15.0 release.

---

internal/cmd/faas/awslambda/mongodb/bootstrap.go
internal/integration/unified_runner_events_helper_test.go
mongo/database.go
x/mongo/driver/operation.go

Cherry-pick of #1596 from v1 to master

[master] chore: fix function names in comment (#1596)

---

event/monitoring.go
testdata/connection-monitoring-and-pooling/logging/connection-logging.json
testdata/connection-monitoring-and-pooling/logging/connection-logging.yml
testdata/connection-monitoring-and-pooling/logging/connection-pool-options.json
testdata/connection-monitoring-and-pooling/logging/connection-pool-options.yml
x/mongo/driver/topology/pool.go
x/mongo/driver/topology/pool_test.go

Cherry-pick of #1590 from v1 to master

GODRIVER-2910 [master] Add durations to connection pool events.

---

internal/integration/client_test.go
x/mongo/driver/operation.go

Cherry-pick of #1598 from v1 to master

GODRIVER-3145 [master] Don't retry on context timeout or cancellation.

---

mongo/writeconcern/writeconcern.go

Cherry-pick of #1579 from v1 to master

[master] Fix typo within WriteConcern docs (#1579)

---

Makefile
internal/integration/search_index_prose_test.go
mongo/collection.go
mongo/search_index_view.go
testdata/index-management/searchIndexIgnoresReadWriteConcern.json
testdata/index-management/searchIndexIgnoresReadWriteConcern.yml
x/mongo/driver/operation/create_search_indexes.go
x/mongo/driver/operation/drop_search_index.go
x/mongo/driver/operation/update_search_index.go

Cherry-pick of #1563 from v1 to master

GODRIVER-3043 [master] Use default write/read concerns in the index search commands.

---

x/mongo/driver/topology/rtt_monitor.go
x/mongo/driver/topology/server.go

Cherry-pick of #1587 from v1 to master

GODRIVER-3107 [master] Fix leaking rttMonitor.runHellos() routine.

---

etc/compile_check.sh
mongo/options/mongooptions.go
mongo/writeconcern/writeconcern.go
x/mongo/driver/auth/speculative_x509_test.go
x/mongo/driver/operation.go
x/mongo/driver/operation_test.go
x/mongo/driver/topology/polling_srv_records_test.go
x/mongo/driver/wiremessage/wiremessage.go

Cherry-pick of #1623 from v1 to master

[master] chore: fix some comments and typos (#1623)

---

.evergreen/config.yml

GODRIVER-3209
Test against 8.0 builds
8.0.0-rc4 is available for testing and latest is tracking 8.1 alpha.

GODRIVER-3209 Test against 8.0 builds

---

.evergreen/config.yml

Cherry-pick of #1628 from v1 to master

GODRIVER-3209 [master] Test against 8.0 builds

---

x/mongo/driver/topology/connection.go

Cherry-pick of #1625 from v1 to master

GODRIVER-3163 [master] Preserve original cancellation/timeout errors.

---

.evergreen/config.yml
etc/run-serverless-test.sh
internal/integration/unified/unified_spec_runner.go
testdata/load-balancers/sdam-error-handling.json
testdata/load-balancers/sdam-error-handling.yml

Cherry-pick of #1640 from v1 to master

GODRIVER-3157 [master] Skip Serverless Proxy test that requires failpoint on hello.

---

.evergreen/config.yml

Cherry-pick of #1634 from v1 to master

GODRIVER-3216 [master] Run go mod tidy before lambda test

---

testdata/crud/unified/aggregate-write-readPreference.json
testdata/crud/unified/aggregate-write-readPreference.yml
testdata/crud/unified/db-aggregate-write-readPreference.json
testdata/crud/unified/db-aggregate-write-readPreference.yml

Cherry-pick of #1642 from v1 to master

GODRIVER-3218 [master] Skip Aggregation with Crud Tests on 8.0+

---

internal/integration/client_side_encryption_prose_test.go

Cherry-pick of #1637 from v1 to master

GODRIVER-3120 [master] Add list of possible OS errors to case 11

---

internal/integration/search_index_prose_test.go
internal/integration/unified/collection_operation_execution.go
mongo/options/searchindexoptions.go
mongo/search_index_view.go
testdata/index-management/createSearchIndex.json
testdata/index-management/createSearchIndex.yml
testdata/index-management/createSearchIndexes.json
testdata/index-management/createSearchIndexes.yml

Cherry-pick of #1649 from v1 to master

GODRIVER-3125 [master] Allow to set search index type

---

sbom.json

GODRIVER-3229 
Add SBOM-lite file.
Part of SSDLC compliance.

GODRIVER-3229 [cloud-1.12.0] Add SBOM-lite file

---

sbom.json

GODRIVER-3187
Add SBOM lite file.
Part of SSDLC compliance.

GODRIVER-3187 [master] Add SBOM lite file

---

bson/primitive.go

GODRIVER-2977
Remove "import comment" from "primitive.go".

GODRIVER-2977 Remove "import comment" from "primitive.go".

---

sbom.json

GODRIVER-3187
Update sbom-lite file.  Remove unused field and add `components` field.
Part of SSDLC compliance.

GODRIVER-3187 [cloud-1.12.0] Update sbom-lite file

---

sbom.json

GODRIVER-3187
Update sbom-lite file.  Remove unused field and add `components` field.
Part of SSDLC compliance.

GODRIVER-3187 [master] Update sbom-lite file

---

mongo/client.go

GODRIVER-3257
Redundant error handling removed.

GODRIVER-3257 Update client.go

---

mongo/client.go

Cherry-pick of #1681 from v1 to master

GODRIVER-3257 [master] Update client.go

---

.github/workflows/release.yml

GODRIVER-3052
Update the environment variables used in the release workflow.
SSDLC compliance.

GODRIVER-3052 Update release environment variables

---

.evergreen/config.yml

Cherry-pick of #1675 from v1 to master

GODRIVER-3248 [master] Update windows CI build

---

.evergreen/config.yml

Cherry-pick of #1696 from v1 to master

Remove 8.0 from windows waterfall build (#1696) [master] Remove 8.0 from windows waterfall build (#1696)

---

.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test.yml

GODRIVER-3261
Adds a release workflow for Go Driver v2.
SSDLC compliance.

GODRIVER-3261 Add release workflow

---

internal/integration/csot_prose_test.go

GODRIVER-3266
Add TODO comment to investigate why parallelizing CSOT Prose test 8 causes CI failures.

GODRIVER-3266 Add TODO comment to investigate CSOT test failure

---

.evergreen/config.yml
etc/run-serverless-test.sh
internal/integration/unified/unified_spec_runner.go

Cherry-pick of #1710 from v1 to master

GODRIVER-3272 [master] Remove Serverless Proxy Incremental Rollout Tests

---

internal/integration/mtest/mongotest.go

Cherry-pick of #1721 from v1 to master

GODRIVER-3292 [master] Pass context to custom mtest monitor

---

.evergreen/config.yml
etc/run-oidc-test.sh
internal/cmd/testoidcauth/main.go
x/mongo/driver/auth/oidc.go

GODRIVER-2728
Implement automatic Azure token acquisition callback
required by OIDC epic

GODRIVER-2728 [master] Implement automatic Azure token acquisition callback 

---

mongo/integration/sdam_prose_test.go
x/mongo/driver/topology/server.go

Cherry-pick of #1720 from v1 to release/1.16

GODRIVER-3255 [release/1.16] Await heartbeat checks upto freq when polling

---

bson/doc.go

Cherry-pick of #1739 from v1 to master

GODRIVER-3138 [master] Improve omitempty tag documentation.

---

x/mongo/driver/auth/internal/gssapi/sspi.go

GODRIVER-3299
Fix build failure in gssapi tests.

GODRIVER-3299 Address gssapi build failure

---

x/mongo/driver/auth/internal/gssapi/sspi.go

GODRIVER-3299 [v1] Address gssapi build failure

---

cmd/testoidcauth/main.go

chore: fix some comments

---

x/mongo/driver/wiremessage/wiremessage.go

Cherry-pick of #1735 from v1 to master

GODRIVER-3303 [master] Prevent out of bounds panic with length value

---

docs/CONTRIBUTING.md
etc/cherry-picker.sh

Cherry-pick of #1744 from v1 to master

GODRIVER-3300 [master] Add cherry-picker script

---

.evergreen/config.yml

Cherry-pick of #1746 from v1 to master

GODRIVER-3301 [master] Fix Atlas Data Lake Startup Failure

---

.evergreen/config.yml

GODRIVER-3314
Fix invocation of backport script.

GODRIVER-3314 Fix backport script invocation

---

.evergreen/config.yml
internal/cmd/testoidcauth/main.go
mongo/options/clientoptions.go
mongo/options/clientoptions_test.go
x/mongo/driver/auth/oidc.go

GODRIVER-3149
This cleans up a few things that changed in the spec during implementation and adds the 3 tests that were missing from previous tickets
OIDC epic

GODRIVER-3149 [master] OIDC Spec Cleanup

---

README.md

GODRIVER-3290
Add a notice in the REAMDE for that 1.17 is the final 1.x release.

GODRIVER-3290 Mention the final 1.x release in the release notes

---

.evergreen/config.yml
docs/CONTRIBUTING.md

GODRIVER-3314 
Add PR CherryPicker Task to Master.

GODRIVER-3314 Add PR Cherrypicker Task [master]

---

bson/raw_array_test.go

Remove print statements from test code.

Remove print statements from raw array test

---

.evergreen/config.yml

Co-authored-by: Preston Vasquez <prestonvasquez@icloud.com>
(cherry picked from commit e1994e4f9ff2e742cee8c49d4257a574eecd7f61)

DEVPROD-10453 Use assume_role for s3 uploads [release/1.17] (#1824)

---

x/mongo/driver/connstring/connstring.go

Cherry-pick of #1830 to release/1.17

GODRIVER-3358 [release/1.17] Do not override authSource from TXT record

---

x/mongo/driver/topology/connection.go
x/mongo/driver/topology/connection_test.go
x/mongo/driver/topology/pool.go
x/mongo/driver/topology/pool_test.go
x/mongo/driver/topology/server_test.go
x/mongo/driver/topology/topology_errors_test.go
x/mongo/driver/topology/topology_test.go

GODRIVER-3363 Detect and discard closed idle connections. (#1815) [master]

---

.evergreen/config.yml

Enable benchmarks on Github PR builds.

Enable benchmarks on Github PR builds.

---

.github/reviewers.txt

Update reviewers.txt (#1855) [v1]

---

sbom.json

- fixes invalid JSON in the SBOM

Fix invalid JSON in SBOM

---

mongo/options/clientoptions.go
mongo/options/clientoptions_test.go

Cherry-pick of ab61be419a2e70a91cbae91567762847bef7bd52 to release/2.0

 GODRIVER-3452 MergeClientOptions returns object when given nil arguments (#1917) [release/2.0]

---

testdata/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.json
testdata/server-discovery-and-monitoring/unified/loadbalanced-emit-topology-changed-before-close.yml
testdata/server-discovery-and-monitoring/unified/logging-loadbalanced.json
testdata/server-discovery-and-monitoring/unified/logging-loadbalanced.yml
testdata/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.json
testdata/server-discovery-and-monitoring/unified/replicaset-emit-topology-changed-before-close.yml
testdata/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.json
testdata/server-discovery-and-monitoring/unified/sharded-emit-topology-changed-before-close.yml
testdata/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.json
testdata/server-discovery-and-monitoring/unified/standalone-emit-topology-changed-before-close.yml

GODRIVER-3035
Sync up with https://github.com/mongodb/specifications/commit/1448ba6eedfa2f16584222e683b427bea07bb085

GODRIVER-3035 Publish TopologyDescriptionChangedEvent on topology close.

---

bson/marshal.go
bson/unmarshal.go
bson/value_reader.go
bson/value_writer.go

Cherry pick of 8c453d2d66dd3004779575664e51b5402001bbcd

GODRIVER-3533 Optimize value reader and writer (#2022)

---

examples/_logger/logrus/go.mod
examples/_logger/zap/go.mod
examples/_logger/zerolog/go.mod
internal/cmd/benchmark/go.mod
internal/cmd/compilecheck/go.mod
internal/cmd/faas/awslambda/mongodb/go.mod
internal/test/compilecheck/go.mod
internal/test/goleak/go.mod

Update test modules to use the v2 path.

Convert test modules to v2

---

.github/workflows/codeql.yml

This updates the CodeQL workflow to run for feature branches and pull requests to feature branches.

Run CodeQL workflow for feature branches
